// Generated by CIRCT firtool-1.133.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module ICacheValidRam_Verification_Assert();
  `ifndef SYNTHESIS
    always @(posedge ICacheValidRam.clock) begin
      if (ICacheValidRam.io_p0_wr & ICacheValidRam.io_p1_wr & ~ICacheValidRam.reset
          & ICacheValidRam.io_p0_addr == ICacheValidRam.io_p1_addr) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: ValidRam: dual write same address\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

