#!/usr/bin/env python
"""Tests for static RTL review report generation."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from fecompiler.data.step import StateEnum
from fecompiler.data.workspace import CreateWorkspaceData, create_workspace, load_workspace
from fecompiler.engine.flow import EngineFlow
from fecompiler.tools.review.structural_probe import run_structural_probe


def test_rtl_review_step_generates_structured_report(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "demo.v"
    rtl.write_text(
        """
module demo(input clk, input rst_n, input [3:0] a, output y);
  wire gated_clk;
  assign gated_clk = clk & a[0];
  always @* begin
    if (a[0]) begin
      y = a[1] ? a[2] : a[3];
    end
  end
endmodule
""",
        encoding="utf-8",
    )
    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws"),
        parameters={"Design": "demo", "Top module": "demo", "Frequency max [MHz]": 250},
        origin_verilog=str(rtl),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()
    _mock_successful_yosys_precheck(monkeypatch)

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws" / "review_fe" / "report" / "rtl_review.json"
    assert report.exists()
    data = json.loads(report.read_text(encoding="utf-8"))
    assert "profiles" not in data
    assert "profile_counts" not in data["summary"]
    assert data["summary"]["total_issues"] > 0
    assert any(issue["title"] == "Clock generated by RTL logic" for issue in data["issues"])


def test_rtl_review_uses_cpu_filelist_and_ignores_soc_filelist(tmp_path: Path, monkeypatch):
    cpu_rtl = tmp_path / "cpu.v"
    soc_rtl = tmp_path / "soc.v"
    cpu_filelist = tmp_path / "filelist.cpu.f"
    soc_filelist = tmp_path / "filelist.soc.f"
    cpu_rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    soc_rtl.write_text(
        """
module soc(input clk, input en, output y);
  wire gated_clk;
  assign gated_clk = clk & en;
  assign y = gated_clk;
endmodule
""",
        encoding="utf-8",
    )
    cpu_filelist.write_text(f"{cpu_rtl}\n", encoding="utf-8")
    soc_filelist.write_text(f"{soc_rtl}\n", encoding="utf-8")

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_cpu_only"),
        parameters={"Design": "demo", "Top module": "demo"},
        cpu_filelist=str(cpu_filelist),
        soc_filelist=str(soc_filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_cpu_only"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()
    _mock_successful_yosys_precheck(monkeypatch)

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_cpu_only" / "review_fe" / "report" / "rtl_review.json"
    content = report.read_text(encoding="utf-8")
    assert '"scope": "cpu"' in content
    assert str(cpu_rtl) in content
    assert str(soc_rtl) not in content
    assert "Clock generated by RTL logic" not in content


def test_rtl_review_continues_when_yosys_is_unavailable(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "")

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_probe_optional"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_probe_optional"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_probe_optional" / "review_fe" / "report" / "rtl_review.json"
    content = report.read_text(encoding="utf-8")
    assert '"structural_probe"' in content
    assert '"status": "unavailable"' in content
    summary = json.loads((tmp_path / "ws_probe_optional" / "review_fe" / "report" / "review.rpt").read_text(encoding="utf-8"))
    assert summary["review"] == "pass"


def test_rtl_review_tracks_delta_confidence_and_exact_waivers(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    rtl.write_text(
        "module cpu(input clk, input en, output y); wire gated_clk; "
        "assign gated_clk = clk & en; assign y = gated_clk; endmodule\n",
        encoding="utf-8",
    )
    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_review_delta"),
        parameters={"Design": "cpu", "Top module": "cpu"},
        origin_verilog=str(rtl),
    )
    create_workspace(spec)
    workspace = load_workspace(str(tmp_path / "ws_review_delta"))
    engine = EngineFlow(workspace=workspace)
    engine.create_step_workspaces()
    _mock_successful_yosys_precheck(monkeypatch)

    assert engine.run_step("review", rerun=True) == StateEnum.Success
    report_path = Path(workspace["directory"]) / "review_fe" / "report" / "rtl_review.json"
    first = json.loads(report_path.read_text(encoding="utf-8"))
    issue = next(item for item in first["issues"] if item["title"] == "Clock generated by RTL logic")
    assert issue["status"] == "new"
    assert issue["confidence"] == "medium"
    assert issue["origin"] == "source_heuristic"
    assert issue["ownership"] == "cpu"
    assert len(issue["fingerprint"]) == 64

    workspace["review_waivers"] = [{
        "fingerprint": issue["fingerprint"],
        "reason": "Reviewed clock-gating experiment",
    }]
    assert engine.run_step("review", rerun=True) == StateEnum.Success
    second = json.loads(report_path.read_text(encoding="utf-8"))
    waived = next(item for item in second["issues"] if item["fingerprint"] == issue["fingerprint"])
    assert waived["status"] == "existing"
    assert waived["waived"] is True
    assert waived["waiver"]["reason"] == "Reviewed clock-gating experiment"
    assert second["delta"]["existing"] >= 1

    Path(workspace["origin_verilog"]).write_text(
        "module cpu(input clk, output y); assign y = clk; endmodule\n",
        encoding="utf-8",
    )
    assert engine.run_step("review", rerun=True) == StateEnum.Success
    third = json.loads(report_path.read_text(encoding="utf-8"))
    assert issue["fingerprint"] in {item["fingerprint"] for item in third["resolved_issues"]}
    assert third["delta"]["resolved"] >= 1


def test_yosys_precheck_inferrs_cpu_top_when_wrapper_is_outside_cpu_filelist(tmp_path: Path, monkeypatch):
    leaf = tmp_path / "leaf.v"
    cpu_top = tmp_path / "CpuTop.v"
    soc_wrapper = tmp_path / "SocWrapper.v"
    cpu_filelist = tmp_path / "filelist.cpu.f"
    soc_filelist = tmp_path / "filelist.soc.f"
    leaf.write_text("module Leaf(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    cpu_top.write_text("module CpuTop(input clk, output y); Leaf u_leaf(.clk(clk), .y(y)); endmodule\n", encoding="utf-8")
    soc_wrapper.write_text("module SocWrapper(input clk, output y); CpuTop u_cpu(.clk(clk), .y(y)); endmodule\n", encoding="utf-8")
    cpu_filelist.write_text(f"{leaf}\n{cpu_top}\n", encoding="utf-8")
    soc_filelist.write_text(f"{soc_wrapper}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: False)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        assert "hierarchy -top CpuTop -check" in script_text
        assert "hierarchy -top SocWrapper -check" not in script_text
        assert str(cpu_top) in script_text
        assert str(soc_wrapper) not in script_text
        stat_path = _stat_path_from_script(script_text)
        netlist_path = _netlist_path_from_script(script_text)
        stat_path.write_text(json.dumps({"modules": {"\\CpuTop": {"num_cells": 1}}, "design": {"num_cells": 1}}), encoding="utf-8")
        netlist_path.write_text(json.dumps({"modules": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_cpu_wrapper_outside_filelist"),
        parameters={"Design": "demo", "Top module": "ecos_sim_top"},
        cpu_filelist=str(cpu_filelist),
        soc_filelist=str(soc_filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_cpu_wrapper_outside_filelist"))
    assert loaded is not None
    loaded["cpu_wrapper_top"] = "SocWrapper"
    loaded["top_module"] = "ecos_sim_top"
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_cpu_wrapper_outside_filelist" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    assert data["structural_probe"]["top_module"] == "CpuTop"


def test_yosys_precheck_autodiscovers_same_name_local_helper_sources(tmp_path: Path, monkeypatch):
    cpu_top = tmp_path / "CpuTop.sv"
    helper = tmp_path / "difftest_wrapper.sv"
    cpu_filelist = tmp_path / "filelist.cpu.f"
    cpu_top.write_text(
        "module CpuTop(input logic clk, output logic y); difftest_wrapper difftest(.clk(clk), .y(y)); endmodule\n",
        encoding="utf-8",
    )
    helper.write_text("module difftest_wrapper(input logic clk, output logic y); assign y = clk; endmodule\n", encoding="utf-8")
    cpu_filelist.write_text(f"{cpu_top}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: True)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        assert str(cpu_top) in script_text
        assert str(helper) in script_text
        assert "--top CpuTop" in script_text
        stat_path = _stat_path_from_script(script_text)
        netlist_path = _netlist_path_from_script(script_text)
        stat_path.write_text(json.dumps({"modules": {"\\CpuTop": {"num_cells": 1}}, "design": {"num_cells": 1}}), encoding="utf-8")
        netlist_path.write_text(json.dumps({"modules": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_autodiscover_helper"),
        parameters={"Design": "demo", "Top module": "CpuTop"},
        cpu_filelist=str(cpu_filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_autodiscover_helper"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_autodiscover_helper" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    assert str(helper) in data["structural_probe"]["inputs"]["auto_discovered_rtl_files"]


def test_yosys_precheck_collects_stat_metrics(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: False)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        assert cmd[0] == "/usr/bin/yosys"
        assert "-s" in cmd
        assert isinstance(env, dict)
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        assert "read_verilog -sv -defer" in script_text
        assert "-DSYNTHESIS" in script_text
        assert "-DYOSYS" in script_text
        assert "hierarchy -top cpu -check" in script_text
        assert "stat -json" in script_text
        assert "write_json" in script_text
        stat_path = _stat_path_from_script(script_text)
        netlist_path = _netlist_path_from_script(script_text)
        stat_path.write_text(json.dumps({
            "modules": {
                "\\cpu": {
                    "num_cells": 3,
                    "num_wires": 5,
                    "num_port_bits": 2,
                    "num_cells_by_type": {
                        "$mux": 2,
                        "$add": 1,
                    },
                },
                "\\decode": {
                    "num_cells": 250,
                    "num_wires": 500,
                    "num_port_bits": 60,
                    "num_cells_by_type": {
                        "$mux": 210,
                        "$add": 45,
                        "$memrd": 1,
                    },
                },
            },
            "design": {
                "num_cells": 253,
                "num_wires": 505,
                "num_port_bits": 62,
            },
        }), encoding="utf-8")
        netlist_path.write_text(json.dumps({
            "modules": {
                "\\decode": {
                    "ports": {
                        "\\in": {"direction": "input", "bits": list(range(1, 34))},
                        "\\out": {"direction": "output", "bits": [900]},
                    },
                    "netnames": {
                        "\\wide_ctrl": {"bits": [1]},
                        "\\deep_out": {"bits": [900]},
                    },
                    "cells": {
                        "\\wide_mux": {
                            "type": "$mux",
                            "attributes": {"src": f"{rtl}:2.5-2.20"},
                            "port_directions": {"A": "input", "B": "input", "S": "input", "Y": "output"},
                            "connections": {
                                "A": list(range(1, 18)),
                                "B": list(range(18, 34)),
                                "S": [1],
                                "Y": [100],
                            },
                        },
                        **{
                            f"\\stage_{idx}": {
                                "type": "$and",
                                "attributes": {"src": f"{rtl}:{idx + 2}.3-{idx + 2}.18"},
                                "port_directions": {"A": "input", "B": "input", "Y": "output"},
                                "connections": {
                                    "A": [100 + idx - 1],
                                    "B": [2],
                                    "Y": [100 + idx],
                                },
                            }
                            for idx in range(1, 17)
                        },
                        **{
                            f"\\fanout_{idx}": {
                                "type": "$not",
                                "attributes": {"src": f"{rtl}:30.{idx + 1}-30.{idx + 2}"},
                                "port_directions": {"A": "input", "Y": "output"},
                                "connections": {
                                    "A": [1],
                                    "Y": [300 + idx],
                                },
                            }
                            for idx in range(70)
                        },
                    },
                },
            },
        }), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout=f"Warning: {rtl}:12:7: demo warning\n", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_yosys_precheck"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_yosys_precheck"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_yosys_precheck" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    probe = data["structural_probe"]
    assert probe["status"] == "success"
    assert probe["mode"] == "cpu_only_yosys_precheck"
    assert probe["frontend"] == "read_verilog"
    assert probe["metrics"]["cells"] == 253
    assert probe["metrics"]["mux_cells"] == 212
    assert probe["quality"]["gate"] == "warnings"
    assert probe["diagnostics"][0]["severity"] == "warning"
    assert probe["diagnostics"][0]["source"] == str(rtl)
    assert probe["diagnostics"][0]["line"] == 12
    assert probe["diagnostics"][0]["column"] == 7
    assert probe["module_risks"][0]["module"] == "decode"
    assert probe["module_risks"][0]["risk"] in {"medium", "high"}
    assert "mux-heavy control/data selection" in probe["module_risks"][0]["reasons"]
    assert probe["metrics"]["max_fanout"] >= 64
    assert probe["metrics"]["max_fanin"] >= 32
    assert probe["metrics"]["max_comb_depth"] >= 16
    assert probe["metrics"]["high_fanout_nets"][0]["net"] == "wide_ctrl"
    fanout_issue = next(issue for issue in data["issues"] if issue["title"] == "High fanout net candidate")
    depth_issue = next(issue for issue in data["issues"] if issue["title"] == "Deep combinational path candidate")
    assert fanout_issue["source"] == str(rtl)
    assert fanout_issue["line"] > 0
    assert depth_issue["source"] == str(rtl)
    assert depth_issue["line"] > 0


def test_yosys_precheck_error_blocks_review_step(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: False)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        stat_path = _stat_path_from_script(script.read_text(encoding="utf-8"))
        stat_path.write_text(json.dumps({"modules": {}, "design": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(
            cmd,
            1,
            stdout=f"ERROR: Parser error in line {rtl}:9:3: syntax error\n",
            stderr="",
        )

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_yosys_error"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_yosys_error"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Incomplete

    report = tmp_path / "ws_yosys_error" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    probe = data["yosys_precheck"]
    assert probe["status"] == "failed"
    assert "syntax error" in probe["reason"]
    assert probe["quality"]["gate"] == "failed"
    assert probe["diagnostics"][0]["severity"] == "error"
    assert any(issue["category"] == "syntax" for issue in data["issues"])


def test_yosys_precheck_tool_limit_does_not_block_review_step(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.sv"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input logic clk, output logic y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: True)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        stat_path = _stat_path_from_script(script_text)
        netlist_path = _netlist_path_from_script(script_text)
        stat_path.write_text(json.dumps({"modules": {}, "design": {}}), encoding="utf-8")
        netlist_path.write_text(json.dumps({"modules": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(
            cmd,
            1,
            stdout='ERROR: Feature unimplemented at slang_frontend.cc:1306 (failed condition "ret.size()")\n',
            stderr="",
        )

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_yosys_tool_limit"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_yosys_tool_limit"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_yosys_tool_limit" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    probe = data["yosys_precheck"]
    assert probe["status"] == "failed"
    assert probe["quality"]["gate"] == "warnings"
    assert probe["diagnostics"][0]["category"] == "tool-limit"
    tooling_issue = next(issue for issue in data["issues"] if issue["category"] == "tooling")
    assert tooling_issue["ownership"] == "tool"
    assert tooling_issue["origin"] == "yosys_structural"
    assert data["summary"]["actionable_errors"] == 0
    assert data["summary"]["status"] == "tool_limited"


def test_yosys_precheck_script_stays_frontend_only(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: False)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        stat_path = _stat_path_from_script(script.read_text(encoding="utf-8"))
        stat_path.write_text(json.dumps({"modules": {}, "design": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_probe_script"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_probe_script"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()
    step = engine.get_workspace_step("review")
    assert step is not None

    run_structural_probe(loaded, step)
    script = Path(step.script["dir"]) / "yosys_precheck.ys"
    text = script.read_text(encoding="utf-8") if script.exists() else ""

    forbidden = ("techmap", "abc", "synth", "write_verilog")
    assert not any(word in text for word in forbidden)


def test_yosys_precheck_prefers_slang_frontend_when_available(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.sv"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input logic clk, output logic y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: True)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        assert "plugin -i slang" in script_text
        assert "read_slang" in script_text
        assert "--compat-mode" in script_text
        assert "--ignore-assertions" in script_text
        assert "--top cpu" in script_text
        assert "+define+SYNTHESIS" in script_text
        assert "+define+YOSYS" in script_text
        assert "read_verilog -sv -defer" not in script_text
        stat_path = _stat_path_from_script(script_text)
        netlist_path = _netlist_path_from_script(script_text)
        stat_path.write_text(json.dumps({"modules": {}, "design": {}}), encoding="utf-8")
        netlist_path.write_text(json.dumps({"modules": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_yosys_slang"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_yosys_slang"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success
    report = tmp_path / "ws_yosys_slang" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    assert data["structural_probe"]["frontend"] == "read_slang"


def _stat_path_from_script(script_text: str) -> Path:
    marker = "tee -o "
    line = next(line for line in script_text.splitlines() if line.startswith(marker))
    raw = line.removeprefix(marker).split(" stat -json", maxsplit=1)[0].strip()
    return Path(raw.strip('"')).resolve()


def _netlist_path_from_script(script_text: str) -> Path:
    marker = "write_json "
    line = next(line for line in script_text.splitlines() if line.startswith(marker))
    raw = line.removeprefix(marker).strip()
    return Path(raw.strip('"')).resolve()


def _mock_successful_yosys_precheck(monkeypatch):
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._yosys_supports_slang", lambda yosys: False)

    def fake_run(cmd, cwd, capture_output, text, env, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        _stat_path_from_script(script_text).write_text(
            json.dumps({"modules": {}, "design": {"num_cells": 0, "num_wires": 0}}),
            encoding="utf-8",
        )
        _netlist_path_from_script(script_text).write_text(json.dumps({"modules": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)
