#!/usr/bin/env python
"""Tests for static RTL review report generation."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from fecompiler.data.step import StateEnum
from fecompiler.data.workspace import CreateWorkspaceData, create_workspace, load_workspace
from fecompiler.engine.flow import EngineFlow
from fecompiler.tools.review.structural_probe import run_structural_probe


def test_rtl_review_step_generates_structured_report(tmp_path: Path):
    rtl = tmp_path / "demo.v"
    rtl.write_text(
        """
module demo(input clk, input rst_n, input [3:0] a, output y);
  wire gated_clk;
  assign gated_clk = clk & a[0];
  always @* begin
    if (a[0]) begin
      y = a[1] ? a[2] : a[3];
    end
  end
endmodule
""",
        encoding="utf-8",
    )
    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws"),
        parameters={"Design": "demo", "Top module": "demo", "Frequency max [MHz]": 250},
        origin_verilog=str(rtl),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws" / "review_fe" / "report" / "rtl_review.json"
    assert report.exists()
    content = report.read_text(encoding="utf-8")
    assert '"profiles"' in content
    assert '"IC"' in content
    assert '"FPGA"' in content
    assert '"Clock generated by RTL logic"' in content


def test_rtl_review_uses_cpu_filelist_and_ignores_soc_filelist(tmp_path: Path):
    cpu_rtl = tmp_path / "cpu.v"
    soc_rtl = tmp_path / "soc.v"
    cpu_filelist = tmp_path / "filelist.cpu.f"
    soc_filelist = tmp_path / "filelist.soc.f"
    cpu_rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    soc_rtl.write_text(
        """
module soc(input clk, input en, output y);
  wire gated_clk;
  assign gated_clk = clk & en;
  assign y = gated_clk;
endmodule
""",
        encoding="utf-8",
    )
    cpu_filelist.write_text(f"{cpu_rtl}\n", encoding="utf-8")
    soc_filelist.write_text(f"{soc_rtl}\n", encoding="utf-8")

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_cpu_only"),
        parameters={"Design": "demo", "Top module": "demo"},
        cpu_filelist=str(cpu_filelist),
        soc_filelist=str(soc_filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_cpu_only"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_cpu_only" / "review_fe" / "report" / "rtl_review.json"
    content = report.read_text(encoding="utf-8")
    assert '"scope": "cpu"' in content
    assert str(cpu_rtl) in content
    assert str(soc_rtl) not in content
    assert "Clock generated by RTL logic" not in content


def test_rtl_review_structural_probe_is_optional(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "")

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_probe_optional"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_probe_optional"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_probe_optional" / "review_fe" / "report" / "rtl_review.json"
    content = report.read_text(encoding="utf-8")
    assert '"structural_probe"' in content
    assert '"status": "unavailable"' in content


def test_yosys_precheck_collects_stat_metrics(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")

    def fake_run(cmd, cwd, capture_output, text, timeout):
        assert cmd[0] == "/usr/bin/yosys"
        assert "-s" in cmd
        script = Path(cmd[cmd.index("-s") + 1])
        script_text = script.read_text(encoding="utf-8")
        assert "read_verilog -sv -defer" in script_text
        assert "hierarchy -top \"cpu\" -check" in script_text
        assert "stat -json" in script_text
        stat_path = _stat_path_from_script(script_text)
        stat_path.write_text(json.dumps({
            "modules": {
                "\\cpu": {
                    "num_cells": 3,
                    "num_wires": 5,
                    "num_port_bits": 2,
                    "num_cells_by_type": {
                        "$mux": 2,
                        "$add": 1,
                    },
                },
                "\\decode": {
                    "num_cells": 250,
                    "num_wires": 500,
                    "num_port_bits": 60,
                    "num_cells_by_type": {
                        "$mux": 210,
                        "$add": 45,
                        "$memrd": 1,
                    },
                },
            },
            "design": {
                "num_cells": 253,
                "num_wires": 505,
                "num_port_bits": 62,
            },
        }), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout=f"Warning: {rtl}:12:7: demo warning\n", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_yosys_precheck"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_yosys_precheck"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_yosys_precheck" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    probe = data["structural_probe"]
    assert probe["status"] == "success"
    assert probe["mode"] == "cpu_only_yosys_precheck"
    assert probe["metrics"]["cells"] == 253
    assert probe["metrics"]["mux_cells"] == 212
    assert probe["quality"]["gate"] == "warnings"
    assert probe["diagnostics"][0]["severity"] == "warning"
    assert probe["diagnostics"][0]["source"] == str(rtl)
    assert probe["diagnostics"][0]["line"] == 12
    assert probe["diagnostics"][0]["column"] == 7
    assert probe["module_risks"][0]["module"] == "decode"
    assert probe["module_risks"][0]["risk"] in {"medium", "high"}
    assert "mux-heavy control/data selection" in probe["module_risks"][0]["reasons"]


def test_yosys_precheck_error_blocks_review_step(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")

    def fake_run(cmd, cwd, capture_output, text, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        stat_path = _stat_path_from_script(script.read_text(encoding="utf-8"))
        stat_path.write_text(json.dumps({"modules": {}, "design": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(
            cmd,
            1,
            stdout=f"ERROR: Parser error in line {rtl}:9:3: syntax error\n",
            stderr="",
        )

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_yosys_error"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_yosys_error"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Incomplete

    report = tmp_path / "ws_yosys_error" / "review_fe" / "report" / "rtl_review.json"
    data = json.loads(report.read_text(encoding="utf-8"))
    probe = data["yosys_precheck"]
    assert probe["status"] == "failed"
    assert probe["quality"]["gate"] == "failed"
    assert probe["diagnostics"][0]["severity"] == "error"
    assert any(issue["category"] == "syntax" for issue in data["issues"])


def test_yosys_precheck_script_stays_frontend_only(tmp_path: Path, monkeypatch):
    rtl = tmp_path / "cpu.v"
    filelist = tmp_path / "filelist.cpu.f"
    rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    filelist.write_text(f"{rtl}\n", encoding="utf-8")
    monkeypatch.setattr("fecompiler.tools.review.structural_probe._resolve_yosys", lambda: "/usr/bin/yosys")

    def fake_run(cmd, cwd, capture_output, text, timeout):
        script = Path(cmd[cmd.index("-s") + 1])
        stat_path = _stat_path_from_script(script.read_text(encoding="utf-8"))
        stat_path.write_text(json.dumps({"modules": {}, "design": {}}), encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr("fecompiler.tools.review.structural_probe.subprocess.run", fake_run)

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_probe_script"),
        parameters={"Design": "demo", "Top module": "cpu"},
        cpu_filelist=str(filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_probe_script"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()
    step = engine.get_workspace_step("review")
    assert step is not None

    run_structural_probe(loaded, step)
    script = Path(step.script["dir"]) / "yosys_precheck.ys"
    text = script.read_text(encoding="utf-8") if script.exists() else ""

    forbidden = ("techmap", "abc", "synth", "write_verilog")
    assert not any(word in text for word in forbidden)


def _stat_path_from_script(script_text: str) -> Path:
    marker = "tee -o "
    line = next(line for line in script_text.splitlines() if line.startswith(marker))
    raw = line.removeprefix(marker).split(" stat -json", maxsplit=1)[0].strip()
    return Path(raw.strip('"')).resolve()
