#!/usr/bin/env python
"""Tests for static RTL review report generation."""

from __future__ import annotations

from pathlib import Path

from fecompiler.data.step import StateEnum
from fecompiler.data.workspace import CreateWorkspaceData, create_workspace, load_workspace
from fecompiler.engine.flow import EngineFlow


def test_rtl_review_step_generates_structured_report(tmp_path: Path):
    rtl = tmp_path / "demo.v"
    rtl.write_text(
        """
module demo(input clk, input rst_n, input [3:0] a, output y);
  wire gated_clk;
  assign gated_clk = clk & a[0];
  always @* begin
    if (a[0]) begin
      y = a[1] ? a[2] : a[3];
    end
  end
endmodule
""",
        encoding="utf-8",
    )
    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws"),
        parameters={"Design": "demo", "Top module": "demo", "Frequency max [MHz]": 250},
        origin_verilog=str(rtl),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws" / "review_fe" / "report" / "rtl_review.json"
    assert report.exists()
    content = report.read_text(encoding="utf-8")
    assert '"profiles"' in content
    assert '"IC"' in content
    assert '"FPGA"' in content
    assert '"Clock generated by RTL logic"' in content


def test_rtl_review_uses_cpu_filelist_and_ignores_soc_filelist(tmp_path: Path):
    cpu_rtl = tmp_path / "cpu.v"
    soc_rtl = tmp_path / "soc.v"
    cpu_filelist = tmp_path / "filelist.cpu.f"
    soc_filelist = tmp_path / "filelist.soc.f"
    cpu_rtl.write_text("module cpu(input clk, output y); assign y = clk; endmodule\n", encoding="utf-8")
    soc_rtl.write_text(
        """
module soc(input clk, input en, output y);
  wire gated_clk;
  assign gated_clk = clk & en;
  assign y = gated_clk;
endmodule
""",
        encoding="utf-8",
    )
    cpu_filelist.write_text(f"{cpu_rtl}\n", encoding="utf-8")
    soc_filelist.write_text(f"{soc_rtl}\n", encoding="utf-8")

    spec = CreateWorkspaceData(
        directory=str(tmp_path / "ws_cpu_only"),
        parameters={"Design": "demo", "Top module": "demo"},
        cpu_filelist=str(cpu_filelist),
        soc_filelist=str(soc_filelist),
    )
    workspace = create_workspace(spec)
    assert workspace is not None

    loaded = load_workspace(str(tmp_path / "ws_cpu_only"))
    assert loaded is not None
    engine = EngineFlow(workspace=loaded)
    engine.create_step_workspaces()

    assert engine.run_step("review", rerun=True) == StateEnum.Success

    report = tmp_path / "ws_cpu_only" / "review_fe" / "report" / "rtl_review.json"
    content = report.read_text(encoding="utf-8")
    assert '"scope": "cpu"' in content
    assert str(cpu_rtl) in content
    assert str(soc_rtl) not in content
    assert "Clock generated by RTL logic" not in content
