+incdir+../../thirdparty/scr1/src/includes
+incdir+.
+define+SCR1_ARCH_CUSTOM
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_hdu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_tdu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_ipic.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_csr.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_exu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_ialu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_idu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_ifu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_lsu.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_mprf.sv
../../thirdparty/scr1/src/core/pipeline/scr1_pipe_top.sv
../../thirdparty/scr1/src/core/primitives/scr1_reset_cells.sv
../../thirdparty/scr1/src/core/primitives/scr1_cg.sv
../../thirdparty/scr1/src/core/scr1_clk_ctrl.sv
../../thirdparty/scr1/src/core/scr1_tapc_shift_reg.sv
../../thirdparty/scr1/src/core/scr1_tapc.sv
../../thirdparty/scr1/src/core/scr1_tapc_synchronizer.sv
../../thirdparty/scr1/src/core/scr1_core_top.sv
../../thirdparty/scr1/src/core/scr1_dm.sv
../../thirdparty/scr1/src/core/scr1_dmi.sv
../../thirdparty/scr1/src/core/scr1_scu.sv
ecos_scr1_cpu_wrapper.sv
