// Generated by CIRCT firtool-1.133.0
module AxiArbiter(
  input         clock,
                reset,
  output        io_icache_axi_ar_ready,
  input         io_icache_axi_ar_valid,
  input  [31:0] io_icache_axi_ar_bits_addr,
  output        io_icache_axi_r_valid,
  output [31:0] io_icache_axi_r_bits_data,
  output [1:0]  io_icache_axi_r_bits_resp,
  output        io_icache_axi_r_bits_last,
                io_dcache_axi_aw_ready,
  input         io_dcache_axi_aw_valid,
  input  [31:0] io_dcache_axi_aw_bits_addr,
  input  [7:0]  io_dcache_axi_aw_bits_len,
  output        io_dcache_axi_w_ready,
  input         io_dcache_axi_w_valid,
  input  [31:0] io_dcache_axi_w_bits_data,
  input  [3:0]  io_dcache_axi_w_bits_strb,
  input         io_dcache_axi_w_bits_last,
  output        io_dcache_axi_b_valid,
  output [1:0]  io_dcache_axi_b_bits_resp,
  output        io_dcache_axi_ar_ready,
  input         io_dcache_axi_ar_valid,
  input  [31:0] io_dcache_axi_ar_bits_addr,
  input  [7:0]  io_dcache_axi_ar_bits_len,
  output        io_dcache_axi_r_valid,
  output [31:0] io_dcache_axi_r_bits_data,
  output [1:0]  io_dcache_axi_r_bits_resp,
  output        io_dcache_axi_r_bits_last,
  input         io_mem_axi_aw_ready,
  output        io_mem_axi_aw_valid,
  output [31:0] io_mem_axi_aw_bits_addr,
  output [7:0]  io_mem_axi_aw_bits_len,
  input         io_mem_axi_w_ready,
  output        io_mem_axi_w_valid,
  output [31:0] io_mem_axi_w_bits_data,
  output [3:0]  io_mem_axi_w_bits_strb,
  output        io_mem_axi_w_bits_last,
  input         io_mem_axi_b_valid,
  input  [1:0]  io_mem_axi_b_bits_resp,
  input         io_mem_axi_ar_ready,
  output        io_mem_axi_ar_valid,
  output [31:0] io_mem_axi_ar_bits_addr,
  output [7:0]  io_mem_axi_ar_bits_len,
  output [1:0]  io_mem_axi_ar_bits_burst,
  output [2:0]  io_mem_axi_ar_bits_size,
  output [3:0]  io_mem_axi_ar_bits_cache,
  input         io_mem_axi_r_valid,
  input  [31:0] io_mem_axi_r_bits_data,
  input  [1:0]  io_mem_axi_r_bits_resp,
  input         io_mem_axi_r_bits_last
);

  reg  axiReadBusy;
  reg  lastServedD;
  reg  dcacheGrantReg;
  wire _GEN = io_icache_axi_ar_valid & io_dcache_axi_ar_valid;
  wire _GEN_0 =
    _GEN
      ? ~lastServedD
      : ~io_icache_axi_ar_valid & (io_dcache_axi_ar_valid | dcacheGrantReg);
  wire dcacheGranted = axiReadBusy ? dcacheGrantReg : _GEN_0;
  always @(posedge clock) begin
    if (reset) begin
      axiReadBusy <= 1'h0;
      lastServedD <= 1'h0;
      dcacheGrantReg <= 1'h0;
    end
    else begin
      axiReadBusy <=
        ~(io_mem_axi_r_valid & io_mem_axi_r_bits_last)
        & (axiReadBusy ? axiReadBusy : io_icache_axi_ar_valid | io_dcache_axi_ar_valid);
      lastServedD <= ~axiReadBusy & _GEN ^ lastServedD;
      if (axiReadBusy) begin
      end
      else
        dcacheGrantReg <= _GEN_0;
    end
  end // always @(posedge)
  assign io_icache_axi_ar_ready = ~dcacheGranted & io_mem_axi_ar_ready;
  assign io_icache_axi_r_valid = ~dcacheGrantReg & io_mem_axi_r_valid;
  assign io_icache_axi_r_bits_data = io_mem_axi_r_bits_data;
  assign io_icache_axi_r_bits_resp = io_mem_axi_r_bits_resp;
  assign io_icache_axi_r_bits_last = ~dcacheGrantReg & io_mem_axi_r_bits_last;
  assign io_dcache_axi_aw_ready = io_mem_axi_aw_ready;
  assign io_dcache_axi_w_ready = io_mem_axi_w_ready;
  assign io_dcache_axi_b_valid = io_mem_axi_b_valid;
  assign io_dcache_axi_b_bits_resp = io_mem_axi_b_bits_resp;
  assign io_dcache_axi_ar_ready = dcacheGranted & io_mem_axi_ar_ready;
  assign io_dcache_axi_r_valid = dcacheGrantReg & io_mem_axi_r_valid;
  assign io_dcache_axi_r_bits_data = io_mem_axi_r_bits_data;
  assign io_dcache_axi_r_bits_resp = io_mem_axi_r_bits_resp;
  assign io_dcache_axi_r_bits_last = dcacheGrantReg & io_mem_axi_r_bits_last;
  assign io_mem_axi_aw_valid = io_dcache_axi_aw_valid;
  assign io_mem_axi_aw_bits_addr = io_dcache_axi_aw_bits_addr;
  assign io_mem_axi_aw_bits_len = io_dcache_axi_aw_bits_len;
  assign io_mem_axi_w_valid = io_dcache_axi_w_valid;
  assign io_mem_axi_w_bits_data = io_dcache_axi_w_bits_data;
  assign io_mem_axi_w_bits_strb = io_dcache_axi_w_bits_strb;
  assign io_mem_axi_w_bits_last = io_dcache_axi_w_bits_last;
  assign io_mem_axi_ar_valid =
    dcacheGranted & io_dcache_axi_ar_valid | ~dcacheGranted & io_icache_axi_ar_valid;
  assign io_mem_axi_ar_bits_addr =
    (dcacheGranted ? io_dcache_axi_ar_bits_addr : 32'h0)
    | (dcacheGranted ? 32'h0 : io_icache_axi_ar_bits_addr);
  assign io_mem_axi_ar_bits_len =
    (dcacheGranted ? io_dcache_axi_ar_bits_len : 8'h0) | (dcacheGranted ? 8'h0 : 8'h7);
  assign io_mem_axi_ar_bits_burst = {1'h0, dcacheGranted} | {1'h0, ~dcacheGranted};
  assign io_mem_axi_ar_bits_size =
    {1'h0, dcacheGranted, 1'h0} | {1'h0, ~dcacheGranted, 1'h0};
  assign io_mem_axi_ar_bits_cache =
    (dcacheGranted ? 4'h6 : 4'h0) | (dcacheGranted ? 4'h0 : 4'h6);
endmodule

