// Generated by CIRCT firtool-1.133.0
module CL3Issue(
  input         clock,
                reset,
  output        io_in_fetch_0_ready,
  input         io_in_fetch_0_valid,
  input  [31:0] io_in_fetch_0_bits_inst,
                io_in_fetch_0_bits_pc,
  input         io_in_fetch_0_bits_wen,
                io_in_fetch_0_bits_isLSU,
                io_in_fetch_0_bits_isMUL,
                io_in_fetch_0_bits_isDIV,
                io_in_fetch_0_bits_isCSR,
                io_in_fetch_0_bits_isEXU,
                io_in_fetch_0_bits_isBr,
  input  [3:0]  io_in_fetch_0_bits_uop_op0,
  input  [2:0]  io_in_fetch_0_bits_uop_op1,
                io_in_fetch_0_bits_uop_op2,
  input         io_in_fetch_0_bits_illegal,
                io_in_fetch_0_bits_fault_fetch,
                io_in_fetch_0_bits_fault_page,
  output        io_in_fetch_1_ready,
  input         io_in_fetch_1_valid,
  input  [31:0] io_in_fetch_1_bits_inst,
                io_in_fetch_1_bits_pc,
  input         io_in_fetch_1_bits_wen,
                io_in_fetch_1_bits_isLSU,
                io_in_fetch_1_bits_isMUL,
                io_in_fetch_1_bits_isDIV,
                io_in_fetch_1_bits_isCSR,
                io_in_fetch_1_bits_isEXU,
                io_in_fetch_1_bits_isBr,
  input  [3:0]  io_in_fetch_1_bits_uop_op0,
  input  [2:0]  io_in_fetch_1_bits_uop_op1,
                io_in_fetch_1_bits_uop_op2,
  input         io_in_fetch_1_bits_illegal,
                io_in_fetch_1_bits_fault_fetch,
                io_in_fetch_1_bits_fault_page,
                io_in_csr_br_valid,
  input  [31:0] io_in_csr_br_pc,
  input         io_in_csr_wen,
  input  [31:0] io_in_csr_rdata,
                io_in_csr_wdata,
  input  [5:0]  io_in_csr_except_code,
  input  [31:0] io_in_csr_except_pc,
                io_in_csr_except_tval,
  input         io_in_exec_0_br_valid,
  input  [31:0] io_in_exec_0_br_pc,
  input         io_in_exec_0_bp_valid,
  input  [31:0] io_in_exec_0_bp_target,
  input         io_in_exec_0_bp_isTaken,
                io_in_exec_0_bp_isNotTaken,
  input  [31:0] io_in_exec_0_bp_source,
  input         io_in_exec_0_bp_isCall,
                io_in_exec_0_bp_isRet,
                io_in_exec_0_bp_isJmp,
  input  [31:0] io_in_exec_0_result,
  input         io_in_exec_1_br_valid,
  input  [31:0] io_in_exec_1_br_pc,
  input         io_in_exec_1_bp_valid,
  input  [31:0] io_in_exec_1_bp_target,
  input         io_in_exec_1_bp_isTaken,
                io_in_exec_1_bp_isNotTaken,
  input  [31:0] io_in_exec_1_bp_source,
  input         io_in_exec_1_bp_isCall,
                io_in_exec_1_bp_isRet,
                io_in_exec_1_bp_isJmp,
  input  [31:0] io_in_exec_1_result,
                io_in_exec_2_result,
                io_in_exec_3_result,
                io_in_mul_result,
  input         io_in_div_valid,
  input  [31:0] io_in_div_result,
  input         io_in_lsu_valid,
  input  [31:0] io_in_lsu_rdata,
  input  [5:0]  io_in_lsu_except_code,
  input  [31:0] io_in_lsu_except_pc,
                io_in_lsu_except_tval,
  input         io_in_lsu_stall,
                io_in_lsu_cacheable,
                io_in_irq,
  input  [31:0] io_in_tvec,
                io_in_epc,
  output        io_out_br_valid,
  output [31:0] io_out_br_pc,
  output        io_out_bp_valid,
  output [31:0] io_out_bp_target,
  output        io_out_bp_isTaken,
                io_out_bp_isNotTaken,
  output [31:0] io_out_bp_source,
  output        io_out_bp_isCall,
                io_out_bp_isRet,
                io_out_bp_isJmp,
                io_out_op_0_valid,
  output [31:0] io_out_op_0_inst,
                io_out_op_0_pc,
  output [3:0]  io_out_op_0_uop_op0,
  output [2:0]  io_out_op_0_uop_op1,
                io_out_op_0_uop_op2,
  output [31:0] io_out_op_0_rs1,
                io_out_op_0_rs2,
  output        io_out_op_1_valid,
  output [31:0] io_out_op_1_inst,
                io_out_op_1_pc,
  output [3:0]  io_out_op_1_uop_op0,
  output [2:0]  io_out_op_1_uop_op1,
                io_out_op_1_uop_op2,
  output [31:0] io_out_op_1_rs1,
                io_out_op_1_rs2,
  output        io_out_op_2_valid,
  output [31:0] io_out_op_2_inst,
                io_out_op_2_pc,
                io_out_op_2_rs1,
                io_out_op_2_rs2,
  output        io_out_op_3_valid,
  output [31:0] io_out_op_3_inst,
                io_out_op_3_pc,
  output        io_out_op_3_wen,
  output [3:0]  io_out_op_3_uop_op0,
  output [2:0]  io_out_op_3_uop_op1,
                io_out_op_3_uop_op2,
  output [31:0] io_out_op_3_rs1,
                io_out_op_3_rs2,
  output        io_out_op_4_valid,
  output [31:0] io_out_op_4_inst,
                io_out_op_4_rs1,
                io_out_op_4_rs2,
  output        io_out_op_5_valid,
  output [31:0] io_out_op_5_inst,
                io_out_op_5_pc,
  output [2:0]  io_out_op_5_uop_op1,
  output [31:0] io_out_op_5_rs1,
  output        io_out_op_6_valid,
  output [31:0] io_out_op_6_inst,
                io_out_op_6_pc,
  output [3:0]  io_out_op_6_uop_op0,
  output [2:0]  io_out_op_6_uop_op1,
                io_out_op_6_uop_op2,
  output [31:0] io_out_op_6_rs1,
                io_out_op_6_rs2,
  output        io_out_op_7_valid,
  output [31:0] io_out_op_7_inst,
                io_out_op_7_pc,
  output [3:0]  io_out_op_7_uop_op0,
  output [2:0]  io_out_op_7_uop_op1,
                io_out_op_7_uop_op2,
  output [31:0] io_out_op_7_rs1,
                io_out_op_7_rs2,
  output        io_out_csr_wen,
  output [11:0] io_out_csr_waddr,
  output [31:0] io_out_csr_wdata,
  output [5:0]  io_out_csr_except_code,
  output [31:0] io_out_csr_except_pc,
                io_out_csr_except_tval,
  output        io_out_hold,
                io_out_lsu_flush,
                io_out_debug_fetch0_ok,
                io_out_debug_fetch1_ok,
                io_out_debug_slot0_data_check,
                io_out_debug_slot1_data_check,
                io_out_debug_slot0_struct_check,
                io_out_debug_slot1_struct_check,
                io_out_debug_slot0_order_check,
                io_out_debug_slot1_order_check,
                io_out_debug_slot1_type_check,
                io_out_debug_slot1_data_check_internal,
  output [1:0]  io_out_debug_delay0,
  output [2:0]  io_out_debug_id0,
  output [1:0]  io_out_debug_inst_delay0,
                io_out_debug_delay1,
  output [2:0]  io_out_debug_id1,
  output [1:0]  io_out_debug_inst_delay1,
  output [4:0]  io_out_debug_slot0_rdIdx,
                io_out_debug_slot1_rs1Idx,
                io_out_debug_slot1_rs2Idx,
  output        io_out_debug_mismatch0,
                io_out_debug_mismatch1,
                io_out_debug_dual_issue,
                io_out_debug_single_issue,
                io_out_debug_pipe1mem,
                io_out_debug_rdystage,
  output [31:0] io_out_debug_mispred,
                io_out_debug_brj_num
);

  wire        io_out_br_valid_0;
  wire        slot0_is_trap;
  wire        slot1_mismatch;
  reg         csr_pending_q;
  reg         div_pending_q;
  wire [1:0]  pipes_0_io_in_issue_rdy_stage;
  wire [31:0] _bypass_io_out_issue_0_a_data;
  wire [2:0]  _bypass_io_out_issue_0_a_id;
  wire [1:0]  _bypass_io_out_issue_0_a_delay;
  wire [31:0] _bypass_io_out_issue_0_b_data;
  wire [2:0]  _bypass_io_out_issue_0_b_id;
  wire [1:0]  _bypass_io_out_issue_0_b_delay;
  wire [31:0] _bypass_io_out_issue_1_a_data;
  wire [2:0]  _bypass_io_out_issue_1_a_id;
  wire [1:0]  _bypass_io_out_issue_1_a_delay;
  wire [31:0] _bypass_io_out_issue_1_b_data;
  wire [2:0]  _bypass_io_out_issue_1_b_id;
  wire [1:0]  _bypass_io_out_issue_1_b_delay;
  wire [31:0] _rf_io_rd_0_rdata;
  wire [31:0] _rf_io_rd_1_rdata;
  wire [31:0] _rf_io_rd_2_rdata;
  wire [31:0] _rf_io_rd_3_rdata;
  wire        _pipes_1_io_out_e1_valid;
  wire [31:0] _pipes_1_io_out_e1_info_inst;
  wire [31:0] _pipes_1_io_out_e1_info_pc;
  wire        _pipes_1_io_out_e1_info_wen;
  wire        _pipes_1_io_out_e1_info_isLSU;
  wire        _pipes_1_io_out_e1_info_isMUL;
  wire        _pipes_1_io_out_e1_info_isEXU;
  wire        _pipes_1_io_out_e1_info_isBr;
  wire [3:0]  _pipes_1_io_out_e1_info_uop_op0;
  wire [2:0]  _pipes_1_io_out_e1_info_uop_op1;
  wire [2:0]  _pipes_1_io_out_e1_info_uop_op2;
  wire [31:0] _pipes_1_io_out_e1_rs1;
  wire [31:0] _pipes_1_io_out_e1_rs2;
  wire [31:0] _pipes_1_io_out_e1_result;
  wire [1:0]  _pipes_1_io_out_e1_rdy_stage;
  wire        _pipes_1_io_out_e1_commit;
  wire        _pipes_1_io_out_e1_stall;
  wire [5:0]  _pipes_1_io_out_e1_except_code;
  wire        _pipes_1_io_out_e2_valid;
  wire [31:0] _pipes_1_io_out_e2_info_inst;
  wire        _pipes_1_io_out_e2_info_wen;
  wire [31:0] _pipes_1_io_out_e2_result;
  wire [1:0]  _pipes_1_io_out_e2_rdy_stage;
  wire        _pipes_1_io_out_e2_stall;
  wire [5:0]  _pipes_1_io_out_e2_except_code;
  wire        _pipes_1_io_out_wb_valid;
  wire [31:0] _pipes_1_io_out_wb_info_inst;
  wire [31:0] _pipes_1_io_out_wb_info_pc;
  wire        _pipes_1_io_out_wb_info_wen;
  wire [31:0] _pipes_1_io_out_wb_npc;
  wire [31:0] _pipes_1_io_out_wb_result;
  wire [1:0]  _pipes_1_io_out_wb_rdy_stage;
  wire        _pipes_1_io_out_wb_commit;
  wire        _pipes_1_io_out_wb_stall;
  wire [11:0] _pipes_1_io_out_wb_csr_waddr;
  wire [31:0] _pipes_1_io_out_wb_csr_wdata;
  wire        _pipes_1_io_out_wb_csr_wen;
  wire [5:0]  _pipes_1_io_out_wb_except_code;
  wire [31:0] _pipes_1_io_out_wb_except_pc;
  wire [31:0] _pipes_1_io_out_wb_except_tval;
  wire        _pipes_1_io_out_wb_mem_cacheable;
  wire        _pipes_0_io_out_e1_valid;
  wire [31:0] _pipes_0_io_out_e1_info_inst;
  wire [31:0] _pipes_0_io_out_e1_info_pc;
  wire        _pipes_0_io_out_e1_info_wen;
  wire        _pipes_0_io_out_e1_info_isLSU;
  wire        _pipes_0_io_out_e1_info_isMUL;
  wire        _pipes_0_io_out_e1_info_isEXU;
  wire        _pipes_0_io_out_e1_info_isBr;
  wire [3:0]  _pipes_0_io_out_e1_info_uop_op0;
  wire [2:0]  _pipes_0_io_out_e1_info_uop_op1;
  wire [2:0]  _pipes_0_io_out_e1_info_uop_op2;
  wire [31:0] _pipes_0_io_out_e1_rs1;
  wire [31:0] _pipes_0_io_out_e1_rs2;
  wire [31:0] _pipes_0_io_out_e1_result;
  wire [1:0]  _pipes_0_io_out_e1_rdy_stage;
  wire        _pipes_0_io_out_e1_commit;
  wire        _pipes_0_io_out_e1_stall;
  wire [5:0]  _pipes_0_io_out_e1_except_code;
  wire        _pipes_0_io_out_e2_valid;
  wire [31:0] _pipes_0_io_out_e2_info_inst;
  wire        _pipes_0_io_out_e2_info_wen;
  wire [31:0] _pipes_0_io_out_e2_result;
  wire [1:0]  _pipes_0_io_out_e2_rdy_stage;
  wire        _pipes_0_io_out_e2_stall;
  wire [5:0]  _pipes_0_io_out_e2_except_code;
  wire        _pipes_0_io_out_wb_valid;
  wire [31:0] _pipes_0_io_out_wb_info_inst;
  wire [31:0] _pipes_0_io_out_wb_info_pc;
  wire        _pipes_0_io_out_wb_info_wen;
  wire [31:0] _pipes_0_io_out_wb_npc;
  wire [31:0] _pipes_0_io_out_wb_result;
  wire [1:0]  _pipes_0_io_out_wb_rdy_stage;
  wire        _pipes_0_io_out_wb_commit;
  wire        _pipes_0_io_out_wb_stall;
  wire [11:0] _pipes_0_io_out_wb_csr_waddr;
  wire [31:0] _pipes_0_io_out_wb_csr_wdata;
  wire        _pipes_0_io_out_wb_csr_wen;
  wire [5:0]  _pipes_0_io_out_wb_except_code;
  wire [31:0] _pipes_0_io_out_wb_except_pc;
  wire [31:0] _pipes_0_io_out_wb_except_tval;
  wire        _pipes_0_io_out_wb_mem_cacheable;
  reg  [31:0] pc_q;
  wire        fetch0_ok = io_in_fetch_0_valid & ~io_out_br_valid_0;
  wire        fetch1_ok = io_in_fetch_1_valid & fetch0_ok;
  wire        stall = _pipes_0_io_out_e1_stall | _pipes_1_io_out_e1_stall;
  wire        e2_trap =
    _pipes_0_io_out_e2_valid & (|_pipes_0_io_out_e2_except_code)
    | _pipes_1_io_out_e2_valid & (|_pipes_1_io_out_e2_except_code);
  wire        wb_trap =
    _pipes_0_io_out_wb_valid & (|_pipes_0_io_out_wb_except_code)
    | _pipes_1_io_out_wb_valid & (|_pipes_1_io_out_wb_except_code);
  wire [5:0]  issue0_fault_w =
    io_in_fetch_0_bits_fault_fetch
      ? 6'h11
      : io_in_fetch_0_bits_fault_page ? 6'h1C : io_in_fetch_0_bits_illegal ? 6'h12 : 6'h0;
  wire [5:0]  issue1_fault_w =
    io_in_fetch_1_bits_fault_fetch
      ? 6'h11
      : io_in_fetch_1_bits_fault_page ? 6'h1C : io_in_fetch_1_bits_illegal ? 6'h12 : 6'h0;
  wire        _rf_io_rd_0_raddr_T = io_in_fetch_0_bits_uop_op1 == 3'h0;
  wire        _rf_io_rd_0_raddr_T_1 = io_in_fetch_0_bits_uop_op1 == 3'h2;
  wire        _rf_io_rd_1_raddr_T = io_in_fetch_0_bits_uop_op2 == 3'h1;
  wire        _rf_io_rd_2_raddr_T_1 = io_in_fetch_1_bits_uop_op1 == 3'h2;
  wire        _rf_io_rd_3_raddr_T = io_in_fetch_1_bits_uop_op2 == 3'h1;
  wire        _io_out_lsu_flush_T = slot1_mismatch | slot0_is_trap;
  wire        pipes_1_io_in_e1_flush = _io_out_lsu_flush_T | io_in_csr_br_valid;
  wire        _io_out_debug_slot1_rs1Idx_T_1 = io_in_fetch_1_bits_uop_op1 == 3'h2;
  wire        rs1_dep_internal =
    io_in_fetch_0_bits_inst[11:7] == (~(|io_in_fetch_1_bits_uop_op1)
                                      | _io_out_debug_slot1_rs1Idx_T_1
                                        ? 5'h0
                                        : io_in_fetch_1_bits_inst[19:15])
    & io_in_fetch_0_bits_wen & (|(io_in_fetch_0_bits_inst[11:7]));
  wire        _io_out_debug_slot1_rs2Idx_T = io_in_fetch_1_bits_uop_op2 == 3'h1;
  wire        rs2_dep_internal =
    io_in_fetch_0_bits_inst[11:7] == (_io_out_debug_slot1_rs2Idx_T
                                        ? io_in_fetch_1_bits_inst[24:20]
                                        : 5'h0) & io_in_fetch_0_bits_wen
    & (|(io_in_fetch_0_bits_inst[11:7]));
  wire        data_dep_internal = rs1_dep_internal | rs2_dep_internal;
  wire        _e1_slot0_lsu_T_2 =
    _pipes_0_io_out_e1_valid & _pipes_0_io_out_e1_info_isLSU;
  wire        _io_out_debug_pipe1mem_T_2 =
    _pipes_1_io_out_e1_valid & _pipes_1_io_out_e1_info_isLSU;
  wire        lsu_delay =
    (_e1_slot0_lsu_T_2 & _pipes_0_io_out_e1_info_wen | _e1_slot0_lsu_T_2
     & ~_pipes_0_io_out_e1_info_wen) & _pipes_0_io_out_e1_rdy_stage[1]
    | (_io_out_debug_pipe1mem_T_2 & _pipes_1_io_out_e1_info_wen
       | _io_out_debug_pipe1mem_T_2 & ~_pipes_1_io_out_e1_info_wen)
    & _pipes_1_io_out_e1_rdy_stage[1];
  wire        _e1_slot0_mul_T = _pipes_0_io_out_e1_valid & _pipes_0_io_out_e1_info_isMUL;
  wire        _e1_slot1_mul_T = _pipes_1_io_out_e1_valid & _pipes_1_io_out_e1_info_isMUL;
  wire        mul_delay =
    _e1_slot0_mul_T & _pipes_0_io_out_e1_rdy_stage[1] | _e1_slot1_mul_T
    & _pipes_1_io_out_e1_rdy_stage[1];
  wire        _io_out_debug_id0_T =
    _bypass_io_out_issue_0_a_delay > _bypass_io_out_issue_0_b_delay;
  wire        slot0_data_check =
    io_in_fetch_0_bits_isBr
    & (|(_io_out_debug_id0_T
           ? _bypass_io_out_issue_0_a_delay
           : _bypass_io_out_issue_0_b_delay)) | io_in_fetch_0_bits_isEXU
    & (_io_out_debug_id0_T
         ? _bypass_io_out_issue_0_a_delay[1]
         : _bypass_io_out_issue_0_b_delay[1]) | io_in_fetch_0_bits_isCSR
    & (|(_io_out_debug_id0_T
           ? _bypass_io_out_issue_0_a_delay
           : _bypass_io_out_issue_0_b_delay)) | io_in_fetch_0_bits_isDIV
    & (|(_io_out_debug_id0_T
           ? _bypass_io_out_issue_0_a_delay
           : _bypass_io_out_issue_0_b_delay)) | io_in_fetch_0_bits_isMUL
    & (_io_out_debug_id0_T
         ? _bypass_io_out_issue_0_a_delay[1]
         : _bypass_io_out_issue_0_b_delay[1]) | io_in_fetch_0_bits_isLSU
    & (_io_out_debug_id0_T
         ? _bypass_io_out_issue_0_a_delay[1]
         : _bypass_io_out_issue_0_b_delay[1]);
  wire        _slot1_struct_check_T = io_in_lsu_stall | div_pending_q;
  wire        slot0_struct_check = _slot1_struct_check_T | csr_pending_q | stall;
  wire        slot0_order_check =
    (_e1_slot0_lsu_T_2 & _pipes_0_io_out_e1_info_wen | _e1_slot0_lsu_T_2
     & ~_pipes_0_io_out_e1_info_wen | _io_out_debug_pipe1mem_T_2
     & _pipes_1_io_out_e1_info_wen | _io_out_debug_pipe1mem_T_2
     & ~_pipes_1_io_out_e1_info_wen)
    & (io_in_fetch_0_bits_isDIV | io_in_fetch_0_bits_isMUL | io_in_fetch_0_bits_isCSR);
  wire        slot0_fire =
    ~(slot0_data_check | slot0_struct_check | slot0_order_check) & fetch0_ok;
  wire        _io_out_debug_id1_T =
    _bypass_io_out_issue_1_a_delay > _bypass_io_out_issue_1_b_delay;
  wire        slot1_data_check =
    io_in_fetch_1_bits_isBr
    & (|(_io_out_debug_id1_T
           ? _bypass_io_out_issue_1_a_delay
           : _bypass_io_out_issue_1_b_delay)) | io_in_fetch_1_bits_isEXU
    & (_io_out_debug_id1_T
         ? _bypass_io_out_issue_1_a_delay[1]
         : _bypass_io_out_issue_1_b_delay[1]) | io_in_fetch_1_bits_isCSR
    & (|(_io_out_debug_id1_T
           ? _bypass_io_out_issue_1_a_delay
           : _bypass_io_out_issue_1_b_delay)) | io_in_fetch_1_bits_isDIV
    & (|(_io_out_debug_id1_T
           ? _bypass_io_out_issue_1_a_delay
           : _bypass_io_out_issue_1_b_delay)) | io_in_fetch_1_bits_isMUL
    & (_io_out_debug_id1_T
         ? _bypass_io_out_issue_1_a_delay[1]
         : _bypass_io_out_issue_1_b_delay[1]) | io_in_fetch_1_bits_isLSU
    & (_io_out_debug_id1_T
         ? _bypass_io_out_issue_1_a_delay[1]
         : _bypass_io_out_issue_1_b_delay[1]);
  wire        slot1_data_check_internal =
    data_dep_internal & ((|pipes_0_io_in_issue_rdy_stage) | io_in_fetch_1_bits_isBr);
  wire        slot1_struct_check =
    _slot1_struct_check_T | stall | ~slot0_fire | csr_pending_q;
  wire        slot1_order_check =
    fetch1_ok
    & (_e1_slot0_lsu_T_2 & _pipes_0_io_out_e1_info_wen | _e1_slot0_lsu_T_2
       & ~_pipes_0_io_out_e1_info_wen | _io_out_debug_pipe1mem_T_2
       & _pipes_1_io_out_e1_info_wen | _io_out_debug_pipe1mem_T_2
       & ~_pipes_1_io_out_e1_info_wen)
    & (io_in_fetch_1_bits_isDIV | io_in_fetch_1_bits_isMUL | io_in_fetch_1_bits_isCSR);
  wire        _slot1_type_check_T_12 =
    io_in_fetch_0_bits_isEXU | io_in_fetch_0_bits_isLSU;
  wire        slot1_type_check =
    fetch1_ok
    & ~(io_in_fetch_1_bits_isEXU
        & (_slot1_type_check_T_12 | io_in_fetch_0_bits_isMUL | io_in_fetch_0_bits_isBr)
        | io_in_fetch_1_bits_isBr & (_slot1_type_check_T_12 | io_in_fetch_0_bits_isMUL)
        | io_in_fetch_1_bits_isLSU
        & (io_in_fetch_0_bits_isEXU | io_in_fetch_0_bits_isMUL | io_in_fetch_0_bits_isBr)
        | io_in_fetch_1_bits_isMUL & (_slot1_type_check_T_12 | io_in_fetch_0_bits_isBr)
        | ~fetch0_ok);
  wire        slot1_fire =
    fetch1_ok
    & ~(slot1_data_check_internal | slot1_data_check | slot1_struct_check
        | slot1_type_check | slot1_order_check);
  wire [1:0]  _io_out_debug_inst_delay0_T = {1'h0, io_in_fetch_0_bits_isLSU};
  wire [1:0]  _io_out_debug_inst_delay0_T_1 = {1'h0, io_in_fetch_0_bits_isMUL};
  wire [1:0]  _io_out_debug_inst_delay0_T_2 = {io_in_fetch_0_bits_isDIV, 1'h0};
  wire [1:0]  _io_out_debug_inst_delay0_T_3 = {io_in_fetch_0_bits_isCSR, 1'h0};
  assign pipes_0_io_in_issue_rdy_stage =
    lsu_delay & io_in_fetch_0_bits_isLSU | mul_delay & io_in_fetch_0_bits_isMUL
      ? 2'h2
      : (_io_out_debug_id0_T
           ? _bypass_io_out_issue_0_a_delay
           : _bypass_io_out_issue_0_b_delay)
        + (_io_out_debug_inst_delay0_T | _io_out_debug_inst_delay0_T_1
           | _io_out_debug_inst_delay0_T_2 | _io_out_debug_inst_delay0_T_3);
  wire [1:0]  _io_out_debug_inst_delay1_T = {1'h0, io_in_fetch_1_bits_isLSU};
  wire [1:0]  _io_out_debug_inst_delay1_T_1 = {1'h0, io_in_fetch_1_bits_isMUL};
  wire [1:0]  _io_out_debug_inst_delay1_T_2 = {io_in_fetch_1_bits_isDIV, 1'h0};
  wire [1:0]  _io_out_debug_inst_delay1_T_3 = {io_in_fetch_1_bits_isCSR, 1'h0};
  wire [1:0]  pipes_1_io_in_issue_rdy_stage =
    data_dep_internal
      ? (_io_out_debug_inst_delay1_T | _io_out_debug_inst_delay1_T_1
         | _io_out_debug_inst_delay1_T_2 | _io_out_debug_inst_delay1_T_3) + 2'h1
      : lsu_delay & io_in_fetch_1_bits_isLSU | mul_delay & io_in_fetch_1_bits_isMUL
          ? 2'h2
          : (_io_out_debug_id1_T
               ? _bypass_io_out_issue_1_a_delay
               : _bypass_io_out_issue_1_b_delay)
            + (_io_out_debug_inst_delay1_T | _io_out_debug_inst_delay1_T_1
               | _io_out_debug_inst_delay1_T_2 | _io_out_debug_inst_delay1_T_3);
  wire        issue_slot0_lsu =
    io_in_fetch_0_bits_isLSU & slot0_fire & pipes_0_io_in_issue_rdy_stage[0]
    & ~(|(issue0_fault_w[4:0]));
  wire        e1_slot1_lsu =
    (_io_out_debug_pipe1mem_T_2 & _pipes_1_io_out_e1_info_wen | _io_out_debug_pipe1mem_T_2
     & ~_pipes_1_io_out_e1_info_wen) & _pipes_1_io_out_e1_rdy_stage[1]
    & _pipes_1_io_out_e1_commit & ~(|_pipes_1_io_out_e1_except_code) & ~slot1_mismatch;
  wire        e1_lsu_op_valid =
    ((_e1_slot0_lsu_T_2 & _pipes_0_io_out_e1_info_wen | _e1_slot0_lsu_T_2
      & ~_pipes_0_io_out_e1_info_wen) & _pipes_0_io_out_e1_rdy_stage[1]
     & _pipes_0_io_out_e1_commit & ~(|_pipes_0_io_out_e1_except_code) | e1_slot1_lsu)
    & ~e2_trap & ~wb_trap;
  wire        issue_slot0_mul =
    io_in_fetch_0_bits_isMUL & slot0_fire & pipes_0_io_in_issue_rdy_stage[0]
    & ~(|(issue0_fault_w[4:0]));
  wire        e1_slot1_mul =
    _e1_slot1_mul_T & _pipes_1_io_out_e1_rdy_stage[1] & _pipes_1_io_out_e1_commit
    & ~(|_pipes_1_io_out_e1_except_code) & ~slot1_mismatch;
  wire        e1_mul_op_valid =
    _e1_slot0_mul_T & _pipes_0_io_out_e1_rdy_stage[1] & _pipes_0_io_out_e1_commit
    & ~(|_pipes_0_io_out_e1_except_code) | e1_slot1_mul;
  wire        io_out_op_4_valid_0 =
    slot0_fire & io_in_fetch_0_bits_isDIV & ~(|(issue0_fault_w[4:0]));
  wire        io_out_op_5_valid_0 =
    slot0_fire & ~io_in_irq & io_in_fetch_0_bits_isCSR & ~(|(issue0_fault_w[4:0]));
  wire        dual_issue = slot1_fire & ~io_in_irq;
  wire        single_issue = slot0_fire & ~dual_issue & ~io_in_irq;
  reg         dual_issue_q;
  reg  [31:0] slot1_pc_q;
  wire [31:0] slot1_pc_actual =
    io_in_exec_0_bp_valid & io_in_exec_0_bp_isTaken
      ? io_in_exec_0_bp_target
      : io_in_exec_0_bp_source + 32'h4;
  wire        slot0_mismatch = pc_q != io_in_fetch_0_bits_pc & io_in_fetch_0_valid;
  assign slot1_mismatch = slot1_pc_q != slot1_pc_actual & dual_issue_q;
  assign slot0_is_trap = _pipes_0_io_out_e1_valid & (|_pipes_0_io_out_e1_except_code);
  wire        mispred = slot1_mismatch | slot0_mismatch;
  assign io_out_br_valid_0 = mispred | io_in_csr_br_valid;
  wire        _io_out_bp_T_3 = _pipes_1_io_out_e1_valid & _pipes_1_io_out_e1_info_isBr;
  wire        _io_out_bp_T_5 =
    _io_out_bp_T_3 & ~_pipes_1_io_out_e1_info_wen | _io_out_bp_T_3
    & _pipes_1_io_out_e1_info_wen;
  wire        io_out_bp_valid_0 =
    _io_out_bp_T_5 ? io_in_exec_1_bp_valid : io_in_exec_0_bp_valid;
  reg  [31:0] mispred_q;
  reg  [31:0] brj_num_q;
  always @(posedge clock) begin
    if (reset) begin
      pc_q <= 32'h0;
      div_pending_q <= 1'h0;
      csr_pending_q <= 1'h0;
      dual_issue_q <= 1'h0;
      slot1_pc_q <= 32'h0;
      mispred_q <= 32'h0;
      brj_num_q <= 32'h0;
    end
    else begin
      if (io_in_csr_br_valid)
        pc_q <= io_in_csr_br_pc;
      else if (io_out_br_valid_0) begin
        if (io_in_csr_br_valid)
          pc_q <= io_in_csr_br_pc;
        else if (slot1_mismatch)
          pc_q <= slot1_pc_actual;
      end
      else if (io_in_exec_0_br_valid & dual_issue)
        pc_q <= io_in_fetch_1_bits_pc + 32'h4;
      else if (io_in_exec_0_br_valid & single_issue)
        pc_q <= io_in_exec_0_br_pc;
      else if (io_in_exec_1_br_valid)
        pc_q <= io_in_exec_1_br_pc;
      else if (dual_issue)
        pc_q <= pc_q + 32'h8;
      else if (single_issue)
        pc_q <= pc_q + 32'h4;
      div_pending_q <=
        ~pipes_1_io_in_e1_flush
        & (io_out_op_4_valid_0 | ~io_in_div_valid & div_pending_q);
      csr_pending_q <=
        ~io_in_csr_br_valid
        & (io_out_op_5_valid_0 | ~_pipes_0_io_out_wb_commit & csr_pending_q);
      dual_issue_q <= dual_issue;
      if (dual_issue)
        slot1_pc_q <= io_in_fetch_1_bits_pc;
      if (mispred)
        mispred_q <= mispred_q + 32'h1;
      if (io_out_bp_valid_0)
        brj_num_q <= brj_num_q + 32'h1;
    end
  end // always @(posedge)
  CL3Pipe pipes_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_issue_fire         (slot0_fire),
    .io_in_issue_info_inst    (io_in_fetch_0_bits_inst),
    .io_in_issue_info_pc      (io_in_fetch_0_bits_pc),
    .io_in_issue_info_wen     (io_in_fetch_0_bits_wen),
    .io_in_issue_info_isLSU   (io_in_fetch_0_bits_isLSU),
    .io_in_issue_info_isMUL   (io_in_fetch_0_bits_isMUL),
    .io_in_issue_info_isDIV   (io_in_fetch_0_bits_isDIV),
    .io_in_issue_info_isCSR   (io_in_fetch_0_bits_isCSR),
    .io_in_issue_info_isEXU   (io_in_fetch_0_bits_isEXU),
    .io_in_issue_info_isBr    (io_in_fetch_0_bits_isBr),
    .io_in_issue_info_uop_op0 (io_in_fetch_0_bits_uop_op0),
    .io_in_issue_info_uop_op1 (io_in_fetch_0_bits_uop_op1),
    .io_in_issue_info_uop_op2 (io_in_fetch_0_bits_uop_op2),
    .io_in_issue_rs1          (_bypass_io_out_issue_0_a_data),
    .io_in_issue_rs2          (_bypass_io_out_issue_0_b_data),
    .io_in_issue_rs1_id
      ((|_bypass_io_out_issue_0_a_delay)
         ? {_bypass_io_out_issue_0_a_delay, 1'h0} + _bypass_io_out_issue_0_a_id
         : 3'h0),
    .io_in_issue_rs2_id
      ((|_bypass_io_out_issue_0_b_delay)
         ? {_bypass_io_out_issue_0_b_delay, 1'h0} + _bypass_io_out_issue_0_b_id
         : 3'h0),
    .io_in_issue_except_code  (issue0_fault_w),
    .io_in_issue_except_pc    (io_in_fetch_0_bits_pc),
    .io_in_issue_except_tval
      (io_in_fetch_0_bits_fault_fetch | io_in_fetch_0_bits_fault_page
         ? io_in_fetch_0_bits_pc
         : io_in_fetch_0_bits_inst),
    .io_in_issue_rdy_stage    (pipes_0_io_in_issue_rdy_stage),
    .io_in_lsu_valid          (io_in_lsu_valid),
    .io_in_lsu_rdata          (io_in_lsu_rdata),
    .io_in_lsu_except_code    (io_in_lsu_except_code),
    .io_in_lsu_except_pc      (io_in_lsu_except_pc),
    .io_in_lsu_except_tval    (io_in_lsu_except_tval),
    .io_in_lsu_stall          (io_in_lsu_stall),
    .io_in_lsu_cacheable      (io_in_lsu_cacheable),
    .io_in_exu_0_result       (io_in_exec_0_result),
    .io_in_exu_0_br_valid     (io_in_exec_0_br_valid),
    .io_in_exu_0_br_pc        (io_in_exec_0_br_pc),
    .io_in_exu_1_result       (io_in_exec_2_result),
    .io_in_div_valid          (io_in_div_valid),
    .io_in_div_result         (io_in_div_result),
    .io_in_mul_result         (io_in_mul_result),
    .io_in_csr_wen            (io_in_csr_wen),
    .io_in_csr_rdata          (io_in_csr_rdata),
    .io_in_csr_wdata          (io_in_csr_wdata),
    .io_in_csr_except_code    (io_in_csr_except_code),
    .io_in_csr_except_pc      (io_in_csr_except_pc),
    .io_in_csr_except_tval    (io_in_csr_except_tval),
    .io_in_pipe_e1_stall      (_pipes_1_io_out_e1_stall),
    .io_in_pipe_e2_result     (_pipes_1_io_out_e2_result),
    .io_in_pipe_e2_stall      (_pipes_1_io_out_e2_stall),
    .io_in_pipe_wb_result     (_pipes_1_io_out_wb_result),
    .io_in_pipe_wb_stall      (_pipes_1_io_out_wb_stall),
    .io_in_irq                (io_in_irq),
    .io_in_e1_flush           (io_in_csr_br_valid),
    .io_in_e2_flush           (io_in_csr_br_valid),
    .io_in_wb_flush           (io_in_csr_br_valid),
    .io_in_tvec               (io_in_tvec),
    .io_in_epc                (io_in_epc),
    .io_out_e1_valid          (_pipes_0_io_out_e1_valid),
    .io_out_e1_info_inst      (_pipes_0_io_out_e1_info_inst),
    .io_out_e1_info_pc        (_pipes_0_io_out_e1_info_pc),
    .io_out_e1_info_wen       (_pipes_0_io_out_e1_info_wen),
    .io_out_e1_info_isLSU     (_pipes_0_io_out_e1_info_isLSU),
    .io_out_e1_info_isMUL     (_pipes_0_io_out_e1_info_isMUL),
    .io_out_e1_info_isEXU     (_pipes_0_io_out_e1_info_isEXU),
    .io_out_e1_info_isBr      (_pipes_0_io_out_e1_info_isBr),
    .io_out_e1_info_uop_op0   (_pipes_0_io_out_e1_info_uop_op0),
    .io_out_e1_info_uop_op1   (_pipes_0_io_out_e1_info_uop_op1),
    .io_out_e1_info_uop_op2   (_pipes_0_io_out_e1_info_uop_op2),
    .io_out_e1_rs1            (_pipes_0_io_out_e1_rs1),
    .io_out_e1_rs2            (_pipes_0_io_out_e1_rs2),
    .io_out_e1_result         (_pipes_0_io_out_e1_result),
    .io_out_e1_rdy_stage      (_pipes_0_io_out_e1_rdy_stage),
    .io_out_e1_commit         (_pipes_0_io_out_e1_commit),
    .io_out_e1_stall          (_pipes_0_io_out_e1_stall),
    .io_out_e1_except_code    (_pipes_0_io_out_e1_except_code),
    .io_out_e2_valid          (_pipes_0_io_out_e2_valid),
    .io_out_e2_info_inst      (_pipes_0_io_out_e2_info_inst),
    .io_out_e2_info_wen       (_pipes_0_io_out_e2_info_wen),
    .io_out_e2_result         (_pipes_0_io_out_e2_result),
    .io_out_e2_rdy_stage      (_pipes_0_io_out_e2_rdy_stage),
    .io_out_e2_stall          (_pipes_0_io_out_e2_stall),
    .io_out_e2_except_code    (_pipes_0_io_out_e2_except_code),
    .io_out_wb_valid          (_pipes_0_io_out_wb_valid),
    .io_out_wb_info_inst      (_pipes_0_io_out_wb_info_inst),
    .io_out_wb_info_pc        (_pipes_0_io_out_wb_info_pc),
    .io_out_wb_info_wen       (_pipes_0_io_out_wb_info_wen),
    .io_out_wb_npc            (_pipes_0_io_out_wb_npc),
    .io_out_wb_result         (_pipes_0_io_out_wb_result),
    .io_out_wb_rdy_stage      (_pipes_0_io_out_wb_rdy_stage),
    .io_out_wb_commit         (_pipes_0_io_out_wb_commit),
    .io_out_wb_stall          (_pipes_0_io_out_wb_stall),
    .io_out_wb_csr_waddr      (_pipes_0_io_out_wb_csr_waddr),
    .io_out_wb_csr_wdata      (_pipes_0_io_out_wb_csr_wdata),
    .io_out_wb_csr_wen        (_pipes_0_io_out_wb_csr_wen),
    .io_out_wb_except_code    (_pipes_0_io_out_wb_except_code),
    .io_out_wb_except_pc      (_pipes_0_io_out_wb_except_pc),
    .io_out_wb_except_tval    (_pipes_0_io_out_wb_except_tval),
    .io_out_wb_mem_cacheable  (_pipes_0_io_out_wb_mem_cacheable)
  );
  CL3Pipe_1 pipes_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_issue_fire         (slot1_fire),
    .io_in_issue_info_inst    (io_in_fetch_1_bits_inst),
    .io_in_issue_info_pc      (io_in_fetch_1_bits_pc),
    .io_in_issue_info_wen     (io_in_fetch_1_bits_wen),
    .io_in_issue_info_isLSU   (io_in_fetch_1_bits_isLSU),
    .io_in_issue_info_isMUL   (io_in_fetch_1_bits_isMUL),
    .io_in_issue_info_isDIV   (io_in_fetch_1_bits_isDIV),
    .io_in_issue_info_isCSR   (io_in_fetch_1_bits_isCSR),
    .io_in_issue_info_isEXU   (io_in_fetch_1_bits_isEXU),
    .io_in_issue_info_isBr    (io_in_fetch_1_bits_isBr),
    .io_in_issue_info_uop_op0 (io_in_fetch_1_bits_uop_op0),
    .io_in_issue_info_uop_op1 (io_in_fetch_1_bits_uop_op1),
    .io_in_issue_info_uop_op2 (io_in_fetch_1_bits_uop_op2),
    .io_in_issue_rs1          (_bypass_io_out_issue_1_a_data),
    .io_in_issue_rs2          (_bypass_io_out_issue_1_b_data),
    .io_in_issue_rs1_id
      (rs1_dep_internal
         ? 3'h1
         : (|_bypass_io_out_issue_1_a_delay)
             ? {_bypass_io_out_issue_1_a_delay, 1'h0} + _bypass_io_out_issue_1_a_id
             : 3'h0),
    .io_in_issue_rs2_id
      (rs2_dep_internal
         ? 3'h1
         : (|_bypass_io_out_issue_1_b_delay)
             ? {_bypass_io_out_issue_1_b_delay, 1'h0} + _bypass_io_out_issue_1_b_id
             : 3'h0),
    .io_in_issue_except_code  (issue1_fault_w),
    .io_in_issue_except_pc    (io_in_fetch_1_bits_pc),
    .io_in_issue_except_tval
      (io_in_fetch_1_bits_fault_fetch | io_in_fetch_1_bits_fault_page
         ? io_in_fetch_1_bits_pc
         : io_in_fetch_1_bits_inst),
    .io_in_issue_rdy_stage    (pipes_1_io_in_issue_rdy_stage),
    .io_in_lsu_valid          (io_in_lsu_valid),
    .io_in_lsu_rdata          (io_in_lsu_rdata),
    .io_in_lsu_except_code    (io_in_lsu_except_code),
    .io_in_lsu_except_pc      (io_in_lsu_except_pc),
    .io_in_lsu_except_tval    (io_in_lsu_except_tval),
    .io_in_lsu_stall          (io_in_lsu_stall),
    .io_in_lsu_cacheable      (io_in_lsu_cacheable),
    .io_in_exu_0_result       (io_in_exec_1_result),
    .io_in_exu_0_br_valid     (io_in_exec_1_br_valid),
    .io_in_exu_0_br_pc        (io_in_exec_1_br_pc),
    .io_in_exu_1_result       (io_in_exec_3_result),
    .io_in_div_valid          (io_in_div_valid),
    .io_in_div_result         (io_in_div_result),
    .io_in_mul_result         (io_in_mul_result),
    .io_in_csr_wen            (io_in_csr_wen),
    .io_in_csr_rdata          (io_in_csr_rdata),
    .io_in_csr_wdata          (io_in_csr_wdata),
    .io_in_csr_except_code    (io_in_csr_except_code),
    .io_in_csr_except_pc      (io_in_csr_except_pc),
    .io_in_csr_except_tval    (io_in_csr_except_tval),
    .io_in_pipe_e1_result     (_pipes_0_io_out_e1_result),
    .io_in_pipe_e1_stall      (_pipes_0_io_out_e1_stall),
    .io_in_pipe_e2_result     (_pipes_0_io_out_e2_result),
    .io_in_pipe_e2_stall      (_pipes_0_io_out_e2_stall),
    .io_in_pipe_wb_result     (_pipes_0_io_out_wb_result),
    .io_in_pipe_wb_stall      (_pipes_0_io_out_wb_stall),
    .io_in_irq                (io_in_irq),
    .io_in_e1_flush           (pipes_1_io_in_e1_flush),
    .io_in_e2_flush           (io_in_csr_br_valid),
    .io_in_wb_flush           (|{io_in_csr_br_valid, _pipes_0_io_out_wb_except_code}),
    .io_in_tvec               (io_in_tvec),
    .io_in_epc                (io_in_epc),
    .io_out_e1_valid          (_pipes_1_io_out_e1_valid),
    .io_out_e1_info_inst      (_pipes_1_io_out_e1_info_inst),
    .io_out_e1_info_pc        (_pipes_1_io_out_e1_info_pc),
    .io_out_e1_info_wen       (_pipes_1_io_out_e1_info_wen),
    .io_out_e1_info_isLSU     (_pipes_1_io_out_e1_info_isLSU),
    .io_out_e1_info_isMUL     (_pipes_1_io_out_e1_info_isMUL),
    .io_out_e1_info_isEXU     (_pipes_1_io_out_e1_info_isEXU),
    .io_out_e1_info_isBr      (_pipes_1_io_out_e1_info_isBr),
    .io_out_e1_info_uop_op0   (_pipes_1_io_out_e1_info_uop_op0),
    .io_out_e1_info_uop_op1   (_pipes_1_io_out_e1_info_uop_op1),
    .io_out_e1_info_uop_op2   (_pipes_1_io_out_e1_info_uop_op2),
    .io_out_e1_rs1            (_pipes_1_io_out_e1_rs1),
    .io_out_e1_rs2            (_pipes_1_io_out_e1_rs2),
    .io_out_e1_result         (_pipes_1_io_out_e1_result),
    .io_out_e1_rdy_stage      (_pipes_1_io_out_e1_rdy_stage),
    .io_out_e1_commit         (_pipes_1_io_out_e1_commit),
    .io_out_e1_stall          (_pipes_1_io_out_e1_stall),
    .io_out_e1_except_code    (_pipes_1_io_out_e1_except_code),
    .io_out_e2_valid          (_pipes_1_io_out_e2_valid),
    .io_out_e2_info_inst      (_pipes_1_io_out_e2_info_inst),
    .io_out_e2_info_wen       (_pipes_1_io_out_e2_info_wen),
    .io_out_e2_result         (_pipes_1_io_out_e2_result),
    .io_out_e2_rdy_stage      (_pipes_1_io_out_e2_rdy_stage),
    .io_out_e2_stall          (_pipes_1_io_out_e2_stall),
    .io_out_e2_except_code    (_pipes_1_io_out_e2_except_code),
    .io_out_wb_valid          (_pipes_1_io_out_wb_valid),
    .io_out_wb_info_inst      (_pipes_1_io_out_wb_info_inst),
    .io_out_wb_info_pc        (_pipes_1_io_out_wb_info_pc),
    .io_out_wb_info_wen       (_pipes_1_io_out_wb_info_wen),
    .io_out_wb_npc            (_pipes_1_io_out_wb_npc),
    .io_out_wb_result         (_pipes_1_io_out_wb_result),
    .io_out_wb_rdy_stage      (_pipes_1_io_out_wb_rdy_stage),
    .io_out_wb_commit         (_pipes_1_io_out_wb_commit),
    .io_out_wb_stall          (_pipes_1_io_out_wb_stall),
    .io_out_wb_csr_waddr      (_pipes_1_io_out_wb_csr_waddr),
    .io_out_wb_csr_wdata      (_pipes_1_io_out_wb_csr_wdata),
    .io_out_wb_csr_wen        (_pipes_1_io_out_wb_csr_wen),
    .io_out_wb_except_code    (_pipes_1_io_out_wb_except_code),
    .io_out_wb_except_pc      (_pipes_1_io_out_wb_except_pc),
    .io_out_wb_except_tval    (_pipes_1_io_out_wb_except_tval),
    .io_out_wb_mem_cacheable  (_pipes_1_io_out_wb_mem_cacheable)
  );
  CL3RF rf (
    .clock         (clock),
    .reset         (reset),
    .io_rd_0_raddr
      (_rf_io_rd_0_raddr_T | _rf_io_rd_0_raddr_T_1
         ? 5'h0
         : io_in_fetch_0_bits_inst[19:15]),
    .io_rd_0_rdata (_rf_io_rd_0_rdata),
    .io_rd_1_raddr (_rf_io_rd_1_raddr_T ? io_in_fetch_0_bits_inst[24:20] : 5'h0),
    .io_rd_1_rdata (_rf_io_rd_1_rdata),
    .io_rd_2_raddr
      (~(|io_in_fetch_1_bits_uop_op1) | _rf_io_rd_2_raddr_T_1
         ? 5'h0
         : io_in_fetch_1_bits_inst[19:15]),
    .io_rd_2_rdata (_rf_io_rd_2_rdata),
    .io_rd_3_raddr (_rf_io_rd_3_raddr_T ? io_in_fetch_1_bits_inst[24:20] : 5'h0),
    .io_rd_3_rdata (_rf_io_rd_3_rdata),
    .io_wr_0_wen   (_pipes_0_io_out_wb_info_wen & _pipes_0_io_out_wb_commit),
    .io_wr_0_wdata (_pipes_0_io_out_wb_result),
    .io_wr_0_waddr (_pipes_0_io_out_wb_info_inst[11:7]),
    .io_wr_1_wen   (_pipes_1_io_out_wb_info_wen & _pipes_1_io_out_wb_commit),
    .io_wr_1_wdata (_pipes_1_io_out_wb_result),
    .io_wr_1_waddr (_pipes_1_io_out_wb_info_inst[11:7])
  );
  BypassNetwork bypass (
    .io_in_issue_0_rs1Idx
      (_rf_io_rd_0_raddr_T | _rf_io_rd_0_raddr_T_1
         ? 5'h0
         : io_in_fetch_0_bits_inst[19:15]),
    .io_in_issue_0_rs2Idx
      (_rf_io_rd_1_raddr_T ? io_in_fetch_0_bits_inst[24:20] : 5'h0),
    .io_in_issue_0_rs1         (_rf_io_rd_0_rdata),
    .io_in_issue_0_rs2         (_rf_io_rd_1_rdata),
    .io_in_issue_1_rs1Idx
      (~(|io_in_fetch_1_bits_uop_op1) | _rf_io_rd_2_raddr_T_1
         ? 5'h0
         : io_in_fetch_1_bits_inst[19:15]),
    .io_in_issue_1_rs2Idx
      (_rf_io_rd_3_raddr_T ? io_in_fetch_1_bits_inst[24:20] : 5'h0),
    .io_in_issue_1_rs1         (_rf_io_rd_2_rdata),
    .io_in_issue_1_rs2         (_rf_io_rd_3_rdata),
    .io_in_pipe_0_e1_valid     (_pipes_0_io_out_e1_valid),
    .io_in_pipe_0_e1_info_inst (_pipes_0_io_out_e1_info_inst),
    .io_in_pipe_0_e1_info_wen  (_pipes_0_io_out_e1_info_wen),
    .io_in_pipe_0_e1_result    (_pipes_0_io_out_e1_result),
    .io_in_pipe_0_e1_rdy_stage (_pipes_0_io_out_e1_rdy_stage),
    .io_in_pipe_0_e2_valid     (_pipes_0_io_out_e2_valid),
    .io_in_pipe_0_e2_info_inst (_pipes_0_io_out_e2_info_inst),
    .io_in_pipe_0_e2_info_wen  (_pipes_0_io_out_e2_info_wen),
    .io_in_pipe_0_e2_result    (_pipes_0_io_out_e2_result),
    .io_in_pipe_0_e2_rdy_stage (_pipes_0_io_out_e2_rdy_stage),
    .io_in_pipe_0_wb_valid     (_pipes_0_io_out_wb_valid),
    .io_in_pipe_0_wb_info_inst (_pipes_0_io_out_wb_info_inst),
    .io_in_pipe_0_wb_info_wen  (_pipes_0_io_out_wb_info_wen),
    .io_in_pipe_0_wb_result    (_pipes_0_io_out_wb_result),
    .io_in_pipe_0_wb_rdy_stage (_pipes_0_io_out_wb_rdy_stage),
    .io_in_pipe_1_e1_valid     (_pipes_1_io_out_e1_valid),
    .io_in_pipe_1_e1_info_inst (_pipes_1_io_out_e1_info_inst),
    .io_in_pipe_1_e1_info_wen  (_pipes_1_io_out_e1_info_wen),
    .io_in_pipe_1_e1_result    (_pipes_1_io_out_e1_result),
    .io_in_pipe_1_e1_rdy_stage (_pipes_1_io_out_e1_rdy_stage),
    .io_in_pipe_1_e2_valid     (_pipes_1_io_out_e2_valid),
    .io_in_pipe_1_e2_info_inst (_pipes_1_io_out_e2_info_inst),
    .io_in_pipe_1_e2_info_wen  (_pipes_1_io_out_e2_info_wen),
    .io_in_pipe_1_e2_result    (_pipes_1_io_out_e2_result),
    .io_in_pipe_1_e2_rdy_stage (_pipes_1_io_out_e2_rdy_stage),
    .io_in_pipe_1_wb_valid     (_pipes_1_io_out_wb_valid),
    .io_in_pipe_1_wb_info_inst (_pipes_1_io_out_wb_info_inst),
    .io_in_pipe_1_wb_info_wen  (_pipes_1_io_out_wb_info_wen),
    .io_in_pipe_1_wb_result    (_pipes_1_io_out_wb_result),
    .io_in_pipe_1_wb_rdy_stage (_pipes_1_io_out_wb_rdy_stage),
    .io_out_issue_0_a_data     (_bypass_io_out_issue_0_a_data),
    .io_out_issue_0_a_id       (_bypass_io_out_issue_0_a_id),
    .io_out_issue_0_a_delay    (_bypass_io_out_issue_0_a_delay),
    .io_out_issue_0_b_data     (_bypass_io_out_issue_0_b_data),
    .io_out_issue_0_b_id       (_bypass_io_out_issue_0_b_id),
    .io_out_issue_0_b_delay    (_bypass_io_out_issue_0_b_delay),
    .io_out_issue_1_a_data     (_bypass_io_out_issue_1_a_data),
    .io_out_issue_1_a_id       (_bypass_io_out_issue_1_a_id),
    .io_out_issue_1_a_delay    (_bypass_io_out_issue_1_a_delay),
    .io_out_issue_1_b_data     (_bypass_io_out_issue_1_b_data),
    .io_out_issue_1_b_id       (_bypass_io_out_issue_1_b_id),
    .io_out_issue_1_b_delay    (_bypass_io_out_issue_1_b_delay)
  );
  difftest_wrapper difftest (
    .clock                 (clock),
    .reset                 (reset),
    .diff_info_0_pc        (_pipes_0_io_out_wb_info_pc),
    .diff_info_0_npc       (_pipes_0_io_out_wb_npc),
    .diff_info_0_inst      (_pipes_0_io_out_wb_info_inst),
    .diff_info_0_rdIdx     (_pipes_0_io_out_wb_info_inst[11:7]),
    .diff_info_0_wen       (_pipes_0_io_out_wb_info_wen),
    .diff_info_0_wdata     (_pipes_0_io_out_wb_result),
    .diff_info_0_commit    (_pipes_0_io_out_wb_commit),
    .diff_info_0_skip      (~_pipes_0_io_out_wb_mem_cacheable),
    .diff_info_0_csr_wen   (_pipes_0_io_out_wb_csr_wen),
    .diff_info_0_csr_wdata (_pipes_0_io_out_wb_csr_wdata),
    .diff_info_0_csr_waddr (_pipes_0_io_out_wb_csr_waddr),
    .diff_info_0_irq_en
      (_pipes_0_io_out_wb_valid & _pipes_0_io_out_wb_except_code[5:4] == 2'h2
       & (|_pipes_0_io_out_wb_except_code)),
    .diff_info_1_pc        (_pipes_1_io_out_wb_info_pc),
    .diff_info_1_npc       (_pipes_1_io_out_wb_npc),
    .diff_info_1_inst      (_pipes_1_io_out_wb_info_inst),
    .diff_info_1_rdIdx     (_pipes_1_io_out_wb_info_inst[11:7]),
    .diff_info_1_wen       (_pipes_1_io_out_wb_info_wen),
    .diff_info_1_wdata     (_pipes_1_io_out_wb_result),
    .diff_info_1_commit    (_pipes_1_io_out_wb_commit),
    .diff_info_1_skip      (~_pipes_1_io_out_wb_mem_cacheable),
    .diff_info_1_csr_wen   (_pipes_1_io_out_wb_csr_wen),
    .diff_info_1_csr_wdata (_pipes_1_io_out_wb_csr_wdata),
    .diff_info_1_csr_waddr (_pipes_1_io_out_wb_csr_waddr),
    .diff_info_1_irq_en
      (_pipes_1_io_out_wb_valid & _pipes_1_io_out_wb_except_code[5:4] == 2'h2
       & (|_pipes_1_io_out_wb_except_code))
  );
  assign io_in_fetch_0_ready = slot0_fire & ~io_in_irq;
  assign io_in_fetch_1_ready = slot1_fire & ~io_in_irq;
  assign io_out_br_valid = io_out_br_valid_0;
  assign io_out_br_pc =
    io_in_csr_br_valid ? io_in_csr_br_pc : slot1_mismatch ? slot1_pc_actual : pc_q;
  assign io_out_bp_valid = io_out_bp_valid_0;
  assign io_out_bp_target =
    _io_out_bp_T_5 ? io_in_exec_1_bp_target : io_in_exec_0_bp_target;
  assign io_out_bp_isTaken =
    _io_out_bp_T_5 ? io_in_exec_1_bp_isTaken : io_in_exec_0_bp_isTaken;
  assign io_out_bp_isNotTaken =
    _io_out_bp_T_5 ? io_in_exec_1_bp_isNotTaken : io_in_exec_0_bp_isNotTaken;
  assign io_out_bp_source =
    _io_out_bp_T_5 ? io_in_exec_1_bp_source : io_in_exec_0_bp_source;
  assign io_out_bp_isCall =
    _io_out_bp_T_5 ? io_in_exec_1_bp_isCall : io_in_exec_0_bp_isCall;
  assign io_out_bp_isRet = _io_out_bp_T_5 ? io_in_exec_1_bp_isRet : io_in_exec_0_bp_isRet;
  assign io_out_bp_isJmp = _io_out_bp_T_5 ? io_in_exec_1_bp_isJmp : io_in_exec_0_bp_isJmp;
  assign io_out_op_0_valid = slot0_fire & ~io_in_fetch_0_bits_illegal;
  assign io_out_op_0_inst = io_in_fetch_0_bits_inst;
  assign io_out_op_0_pc = io_in_fetch_0_bits_pc;
  assign io_out_op_0_uop_op0 = io_in_fetch_0_bits_uop_op0;
  assign io_out_op_0_uop_op1 = io_in_fetch_0_bits_uop_op1;
  assign io_out_op_0_uop_op2 = io_in_fetch_0_bits_uop_op2;
  assign io_out_op_0_rs1 = _bypass_io_out_issue_0_a_data;
  assign io_out_op_0_rs2 = _bypass_io_out_issue_0_b_data;
  assign io_out_op_1_valid = slot1_fire & ~io_in_fetch_1_bits_illegal;
  assign io_out_op_1_inst = io_in_fetch_1_bits_inst;
  assign io_out_op_1_pc = io_in_fetch_1_bits_pc;
  assign io_out_op_1_uop_op0 = io_in_fetch_1_bits_uop_op0;
  assign io_out_op_1_uop_op1 = io_in_fetch_1_bits_uop_op1;
  assign io_out_op_1_uop_op2 = io_in_fetch_1_bits_uop_op2;
  assign io_out_op_1_rs1 = _bypass_io_out_issue_1_a_data;
  assign io_out_op_1_rs2 = _bypass_io_out_issue_1_b_data;
  assign io_out_op_2_valid =
    e1_lsu_op_valid
      ? e1_lsu_op_valid
      : (issue_slot0_lsu | io_in_fetch_1_bits_isLSU & slot1_fire
         & pipes_1_io_in_issue_rdy_stage[0] & ~(|(issue1_fault_w[4:0])))
        & ~(_pipes_0_io_out_e1_valid & (|_pipes_0_io_out_e1_except_code)
            | _pipes_1_io_out_e1_valid & (|_pipes_1_io_out_e1_except_code)) & ~e2_trap
        & ~wb_trap & ~io_in_irq;
  assign io_out_op_2_inst =
    e1_lsu_op_valid
      ? (e1_slot1_lsu ? _pipes_1_io_out_e1_info_inst : _pipes_0_io_out_e1_info_inst)
      : issue_slot0_lsu ? io_in_fetch_0_bits_inst : io_in_fetch_1_bits_inst;
  assign io_out_op_2_pc =
    e1_lsu_op_valid
      ? (e1_slot1_lsu ? _pipes_1_io_out_e1_info_pc : _pipes_0_io_out_e1_info_pc)
      : issue_slot0_lsu ? io_in_fetch_0_bits_pc : io_in_fetch_1_bits_pc;
  assign io_out_op_2_rs1 =
    e1_lsu_op_valid
      ? (e1_slot1_lsu ? _pipes_1_io_out_e1_rs1 : _pipes_0_io_out_e1_rs1)
      : issue_slot0_lsu ? _bypass_io_out_issue_0_a_data : _bypass_io_out_issue_1_a_data;
  assign io_out_op_2_rs2 =
    e1_lsu_op_valid
      ? (e1_slot1_lsu ? _pipes_1_io_out_e1_rs2 : _pipes_0_io_out_e1_rs2)
      : issue_slot0_lsu ? _bypass_io_out_issue_0_b_data : _bypass_io_out_issue_1_b_data;
  assign io_out_op_3_valid =
    e1_mul_op_valid
      ? e1_mul_op_valid
      : (issue_slot0_mul | io_in_fetch_1_bits_isMUL & slot1_fire
         & pipes_1_io_in_issue_rdy_stage[0] & ~(|(issue1_fault_w[4:0]))) & ~io_in_irq;
  assign io_out_op_3_inst =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_info_inst : _pipes_0_io_out_e1_info_inst)
      : issue_slot0_mul ? io_in_fetch_0_bits_inst : io_in_fetch_1_bits_inst;
  assign io_out_op_3_pc =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_info_pc : _pipes_0_io_out_e1_info_pc)
      : issue_slot0_mul ? io_in_fetch_0_bits_pc : io_in_fetch_1_bits_pc;
  assign io_out_op_3_wen =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_info_wen : _pipes_0_io_out_e1_info_wen)
      : issue_slot0_mul ? io_in_fetch_0_bits_wen : io_in_fetch_1_bits_wen;
  assign io_out_op_3_uop_op0 =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_info_uop_op0 : _pipes_0_io_out_e1_info_uop_op0)
      : issue_slot0_mul ? io_in_fetch_0_bits_uop_op0 : io_in_fetch_1_bits_uop_op0;
  assign io_out_op_3_uop_op1 =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_info_uop_op1 : _pipes_0_io_out_e1_info_uop_op1)
      : issue_slot0_mul ? io_in_fetch_0_bits_uop_op1 : io_in_fetch_1_bits_uop_op1;
  assign io_out_op_3_uop_op2 =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_info_uop_op2 : _pipes_0_io_out_e1_info_uop_op2)
      : issue_slot0_mul ? io_in_fetch_0_bits_uop_op2 : io_in_fetch_1_bits_uop_op2;
  assign io_out_op_3_rs1 =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_rs1 : _pipes_0_io_out_e1_rs1)
      : issue_slot0_mul ? _bypass_io_out_issue_0_a_data : _bypass_io_out_issue_1_a_data;
  assign io_out_op_3_rs2 =
    e1_mul_op_valid
      ? (e1_slot1_mul ? _pipes_1_io_out_e1_rs2 : _pipes_0_io_out_e1_rs2)
      : issue_slot0_mul ? _bypass_io_out_issue_0_b_data : _bypass_io_out_issue_1_b_data;
  assign io_out_op_4_valid = io_out_op_4_valid_0;
  assign io_out_op_4_inst = io_in_fetch_0_bits_inst;
  assign io_out_op_4_rs1 = _bypass_io_out_issue_0_a_data;
  assign io_out_op_4_rs2 = _bypass_io_out_issue_0_b_data;
  assign io_out_op_5_valid = io_out_op_5_valid_0;
  assign io_out_op_5_inst = io_in_fetch_0_bits_inst;
  assign io_out_op_5_pc = io_in_fetch_0_bits_pc;
  assign io_out_op_5_uop_op1 = io_in_fetch_0_bits_uop_op1;
  assign io_out_op_5_rs1 = _bypass_io_out_issue_0_a_data;
  assign io_out_op_6_valid =
    _pipes_0_io_out_e1_valid & _pipes_0_io_out_e1_info_isEXU
    & ~_pipes_0_io_out_e1_info_isBr & _pipes_0_io_out_e1_rdy_stage[0];
  assign io_out_op_6_inst = _pipes_0_io_out_e1_info_inst;
  assign io_out_op_6_pc = _pipes_0_io_out_e1_info_pc;
  assign io_out_op_6_uop_op0 = _pipes_0_io_out_e1_info_uop_op0;
  assign io_out_op_6_uop_op1 = _pipes_0_io_out_e1_info_uop_op1;
  assign io_out_op_6_uop_op2 = _pipes_0_io_out_e1_info_uop_op2;
  assign io_out_op_6_rs1 = _pipes_0_io_out_e1_rs1;
  assign io_out_op_6_rs2 = _pipes_0_io_out_e1_rs2;
  assign io_out_op_7_valid =
    _pipes_1_io_out_e1_valid & _pipes_1_io_out_e1_info_isEXU
    & ~_pipes_1_io_out_e1_info_isBr & _pipes_1_io_out_e1_rdy_stage[1];
  assign io_out_op_7_inst = _pipes_1_io_out_e1_info_inst;
  assign io_out_op_7_pc = _pipes_1_io_out_e1_info_pc;
  assign io_out_op_7_uop_op0 = _pipes_1_io_out_e1_info_uop_op0;
  assign io_out_op_7_uop_op1 = _pipes_1_io_out_e1_info_uop_op1;
  assign io_out_op_7_uop_op2 = _pipes_1_io_out_e1_info_uop_op2;
  assign io_out_op_7_rs1 = _pipes_1_io_out_e1_rs1;
  assign io_out_op_7_rs2 = _pipes_1_io_out_e1_rs2;
  assign io_out_csr_wen = _pipes_0_io_out_wb_csr_wen;
  assign io_out_csr_waddr = _pipes_0_io_out_wb_csr_waddr;
  assign io_out_csr_wdata = _pipes_0_io_out_wb_csr_wdata;
  assign io_out_csr_except_code =
    (|_pipes_0_io_out_wb_except_code)
      ? _pipes_0_io_out_wb_except_code
      : _pipes_1_io_out_wb_except_code;
  assign io_out_csr_except_pc =
    (|_pipes_0_io_out_wb_except_code)
      ? _pipes_0_io_out_wb_except_pc
      : _pipes_1_io_out_wb_except_pc;
  assign io_out_csr_except_tval =
    (|_pipes_0_io_out_wb_except_code)
      ? _pipes_0_io_out_wb_except_tval
      : _pipes_1_io_out_wb_except_tval;
  assign io_out_hold = stall;
  assign io_out_lsu_flush =
    _io_out_lsu_flush_T
    & (_io_out_debug_pipe1mem_T_2 & _pipes_1_io_out_e1_info_wen
       | _io_out_debug_pipe1mem_T_2 & ~_pipes_1_io_out_e1_info_wen)
    & _pipes_1_io_out_e1_rdy_stage[0];
  assign io_out_debug_fetch0_ok = fetch0_ok;
  assign io_out_debug_fetch1_ok = fetch1_ok;
  assign io_out_debug_slot0_data_check = slot0_data_check;
  assign io_out_debug_slot1_data_check = slot1_data_check;
  assign io_out_debug_slot0_struct_check = slot0_struct_check;
  assign io_out_debug_slot1_struct_check = slot1_struct_check;
  assign io_out_debug_slot0_order_check = slot0_order_check;
  assign io_out_debug_slot1_order_check = slot1_order_check;
  assign io_out_debug_slot1_type_check = slot1_type_check;
  assign io_out_debug_slot1_data_check_internal = slot1_data_check_internal;
  assign io_out_debug_delay0 =
    _io_out_debug_id0_T ? _bypass_io_out_issue_0_a_delay : _bypass_io_out_issue_0_b_delay;
  assign io_out_debug_id0 =
    _io_out_debug_id0_T ? _bypass_io_out_issue_0_a_id : _bypass_io_out_issue_0_b_id;
  assign io_out_debug_inst_delay0 =
    _io_out_debug_inst_delay0_T | _io_out_debug_inst_delay0_T_1
    | _io_out_debug_inst_delay0_T_2 | _io_out_debug_inst_delay0_T_3;
  assign io_out_debug_delay1 =
    _io_out_debug_id1_T ? _bypass_io_out_issue_1_a_delay : _bypass_io_out_issue_1_b_delay;
  assign io_out_debug_id1 =
    _io_out_debug_id1_T ? _bypass_io_out_issue_1_a_id : _bypass_io_out_issue_1_b_id;
  assign io_out_debug_inst_delay1 =
    _io_out_debug_inst_delay1_T | _io_out_debug_inst_delay1_T_1
    | _io_out_debug_inst_delay1_T_2 | _io_out_debug_inst_delay1_T_3;
  assign io_out_debug_slot0_rdIdx = io_in_fetch_0_bits_inst[11:7];
  assign io_out_debug_slot1_rs1Idx =
    ~(|io_in_fetch_1_bits_uop_op1) | _io_out_debug_slot1_rs1Idx_T_1
      ? 5'h0
      : io_in_fetch_1_bits_inst[19:15];
  assign io_out_debug_slot1_rs2Idx =
    _io_out_debug_slot1_rs2Idx_T ? io_in_fetch_1_bits_inst[24:20] : 5'h0;
  assign io_out_debug_mismatch0 = slot0_mismatch;
  assign io_out_debug_mismatch1 = slot1_mismatch;
  assign io_out_debug_dual_issue = dual_issue;
  assign io_out_debug_single_issue = single_issue;
  assign io_out_debug_pipe1mem =
    _io_out_debug_pipe1mem_T_2 & _pipes_1_io_out_e1_info_wen | _io_out_debug_pipe1mem_T_2
    & ~_pipes_1_io_out_e1_info_wen;
  assign io_out_debug_rdystage = _pipes_1_io_out_e1_rdy_stage[1];
  assign io_out_debug_mispred = mispred_q;
  assign io_out_debug_brj_num = brj_num_q;
endmodule

