// Generated by CIRCT firtool-1.133.0
module CL3RF(
  input         clock,
                reset,
  input  [4:0]  io_rd_0_raddr,
  output [31:0] io_rd_0_rdata,
  input  [4:0]  io_rd_1_raddr,
  output [31:0] io_rd_1_rdata,
  input  [4:0]  io_rd_2_raddr,
  output [31:0] io_rd_2_rdata,
  input  [4:0]  io_rd_3_raddr,
  output [31:0] io_rd_3_rdata,
  input         io_wr_0_wen,
  input  [31:0] io_wr_0_wdata,
  input  [4:0]  io_wr_0_waddr,
  input         io_wr_1_wen,
  input  [31:0] io_wr_1_wdata,
  input  [4:0]  io_wr_1_waddr
);

  reg  [31:0] regs_0;
  reg  [31:0] regs_1;
  reg  [31:0] regs_2;
  reg  [31:0] regs_3;
  reg  [31:0] regs_4;
  reg  [31:0] regs_5;
  reg  [31:0] regs_6;
  reg  [31:0] regs_7;
  reg  [31:0] regs_8;
  reg  [31:0] regs_9;
  reg  [31:0] regs_10;
  reg  [31:0] regs_11;
  reg  [31:0] regs_12;
  reg  [31:0] regs_13;
  reg  [31:0] regs_14;
  reg  [31:0] regs_15;
  reg  [31:0] regs_16;
  reg  [31:0] regs_17;
  reg  [31:0] regs_18;
  reg  [31:0] regs_19;
  reg  [31:0] regs_20;
  reg  [31:0] regs_21;
  reg  [31:0] regs_22;
  reg  [31:0] regs_23;
  reg  [31:0] regs_24;
  reg  [31:0] regs_25;
  reg  [31:0] regs_26;
  reg  [31:0] regs_27;
  reg  [31:0] regs_28;
  reg  [31:0] regs_29;
  reg  [31:0] regs_30;
  reg  [31:0] regs_31;
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (io_rd_0_raddr)
      5'b00000:
        casez_tmp = regs_0;
      5'b00001:
        casez_tmp = regs_1;
      5'b00010:
        casez_tmp = regs_2;
      5'b00011:
        casez_tmp = regs_3;
      5'b00100:
        casez_tmp = regs_4;
      5'b00101:
        casez_tmp = regs_5;
      5'b00110:
        casez_tmp = regs_6;
      5'b00111:
        casez_tmp = regs_7;
      5'b01000:
        casez_tmp = regs_8;
      5'b01001:
        casez_tmp = regs_9;
      5'b01010:
        casez_tmp = regs_10;
      5'b01011:
        casez_tmp = regs_11;
      5'b01100:
        casez_tmp = regs_12;
      5'b01101:
        casez_tmp = regs_13;
      5'b01110:
        casez_tmp = regs_14;
      5'b01111:
        casez_tmp = regs_15;
      5'b10000:
        casez_tmp = regs_16;
      5'b10001:
        casez_tmp = regs_17;
      5'b10010:
        casez_tmp = regs_18;
      5'b10011:
        casez_tmp = regs_19;
      5'b10100:
        casez_tmp = regs_20;
      5'b10101:
        casez_tmp = regs_21;
      5'b10110:
        casez_tmp = regs_22;
      5'b10111:
        casez_tmp = regs_23;
      5'b11000:
        casez_tmp = regs_24;
      5'b11001:
        casez_tmp = regs_25;
      5'b11010:
        casez_tmp = regs_26;
      5'b11011:
        casez_tmp = regs_27;
      5'b11100:
        casez_tmp = regs_28;
      5'b11101:
        casez_tmp = regs_29;
      5'b11110:
        casez_tmp = regs_30;
      default:
        casez_tmp = regs_31;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_0;
  always_comb begin
    casez (io_rd_1_raddr)
      5'b00000:
        casez_tmp_0 = regs_0;
      5'b00001:
        casez_tmp_0 = regs_1;
      5'b00010:
        casez_tmp_0 = regs_2;
      5'b00011:
        casez_tmp_0 = regs_3;
      5'b00100:
        casez_tmp_0 = regs_4;
      5'b00101:
        casez_tmp_0 = regs_5;
      5'b00110:
        casez_tmp_0 = regs_6;
      5'b00111:
        casez_tmp_0 = regs_7;
      5'b01000:
        casez_tmp_0 = regs_8;
      5'b01001:
        casez_tmp_0 = regs_9;
      5'b01010:
        casez_tmp_0 = regs_10;
      5'b01011:
        casez_tmp_0 = regs_11;
      5'b01100:
        casez_tmp_0 = regs_12;
      5'b01101:
        casez_tmp_0 = regs_13;
      5'b01110:
        casez_tmp_0 = regs_14;
      5'b01111:
        casez_tmp_0 = regs_15;
      5'b10000:
        casez_tmp_0 = regs_16;
      5'b10001:
        casez_tmp_0 = regs_17;
      5'b10010:
        casez_tmp_0 = regs_18;
      5'b10011:
        casez_tmp_0 = regs_19;
      5'b10100:
        casez_tmp_0 = regs_20;
      5'b10101:
        casez_tmp_0 = regs_21;
      5'b10110:
        casez_tmp_0 = regs_22;
      5'b10111:
        casez_tmp_0 = regs_23;
      5'b11000:
        casez_tmp_0 = regs_24;
      5'b11001:
        casez_tmp_0 = regs_25;
      5'b11010:
        casez_tmp_0 = regs_26;
      5'b11011:
        casez_tmp_0 = regs_27;
      5'b11100:
        casez_tmp_0 = regs_28;
      5'b11101:
        casez_tmp_0 = regs_29;
      5'b11110:
        casez_tmp_0 = regs_30;
      default:
        casez_tmp_0 = regs_31;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_1;
  always_comb begin
    casez (io_rd_2_raddr)
      5'b00000:
        casez_tmp_1 = regs_0;
      5'b00001:
        casez_tmp_1 = regs_1;
      5'b00010:
        casez_tmp_1 = regs_2;
      5'b00011:
        casez_tmp_1 = regs_3;
      5'b00100:
        casez_tmp_1 = regs_4;
      5'b00101:
        casez_tmp_1 = regs_5;
      5'b00110:
        casez_tmp_1 = regs_6;
      5'b00111:
        casez_tmp_1 = regs_7;
      5'b01000:
        casez_tmp_1 = regs_8;
      5'b01001:
        casez_tmp_1 = regs_9;
      5'b01010:
        casez_tmp_1 = regs_10;
      5'b01011:
        casez_tmp_1 = regs_11;
      5'b01100:
        casez_tmp_1 = regs_12;
      5'b01101:
        casez_tmp_1 = regs_13;
      5'b01110:
        casez_tmp_1 = regs_14;
      5'b01111:
        casez_tmp_1 = regs_15;
      5'b10000:
        casez_tmp_1 = regs_16;
      5'b10001:
        casez_tmp_1 = regs_17;
      5'b10010:
        casez_tmp_1 = regs_18;
      5'b10011:
        casez_tmp_1 = regs_19;
      5'b10100:
        casez_tmp_1 = regs_20;
      5'b10101:
        casez_tmp_1 = regs_21;
      5'b10110:
        casez_tmp_1 = regs_22;
      5'b10111:
        casez_tmp_1 = regs_23;
      5'b11000:
        casez_tmp_1 = regs_24;
      5'b11001:
        casez_tmp_1 = regs_25;
      5'b11010:
        casez_tmp_1 = regs_26;
      5'b11011:
        casez_tmp_1 = regs_27;
      5'b11100:
        casez_tmp_1 = regs_28;
      5'b11101:
        casez_tmp_1 = regs_29;
      5'b11110:
        casez_tmp_1 = regs_30;
      default:
        casez_tmp_1 = regs_31;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_2;
  always_comb begin
    casez (io_rd_3_raddr)
      5'b00000:
        casez_tmp_2 = regs_0;
      5'b00001:
        casez_tmp_2 = regs_1;
      5'b00010:
        casez_tmp_2 = regs_2;
      5'b00011:
        casez_tmp_2 = regs_3;
      5'b00100:
        casez_tmp_2 = regs_4;
      5'b00101:
        casez_tmp_2 = regs_5;
      5'b00110:
        casez_tmp_2 = regs_6;
      5'b00111:
        casez_tmp_2 = regs_7;
      5'b01000:
        casez_tmp_2 = regs_8;
      5'b01001:
        casez_tmp_2 = regs_9;
      5'b01010:
        casez_tmp_2 = regs_10;
      5'b01011:
        casez_tmp_2 = regs_11;
      5'b01100:
        casez_tmp_2 = regs_12;
      5'b01101:
        casez_tmp_2 = regs_13;
      5'b01110:
        casez_tmp_2 = regs_14;
      5'b01111:
        casez_tmp_2 = regs_15;
      5'b10000:
        casez_tmp_2 = regs_16;
      5'b10001:
        casez_tmp_2 = regs_17;
      5'b10010:
        casez_tmp_2 = regs_18;
      5'b10011:
        casez_tmp_2 = regs_19;
      5'b10100:
        casez_tmp_2 = regs_20;
      5'b10101:
        casez_tmp_2 = regs_21;
      5'b10110:
        casez_tmp_2 = regs_22;
      5'b10111:
        casez_tmp_2 = regs_23;
      5'b11000:
        casez_tmp_2 = regs_24;
      5'b11001:
        casez_tmp_2 = regs_25;
      5'b11010:
        casez_tmp_2 = regs_26;
      5'b11011:
        casez_tmp_2 = regs_27;
      5'b11100:
        casez_tmp_2 = regs_28;
      5'b11101:
        casez_tmp_2 = regs_29;
      5'b11110:
        casez_tmp_2 = regs_30;
      default:
        casez_tmp_2 = regs_31;
    endcase
  end // always_comb
  wire        _GEN = io_wr_1_wen & (|io_wr_1_waddr);
  wire        _GEN_0 =
    io_wr_0_wen & (|io_wr_0_waddr) & ~(io_wr_1_wen & io_wr_1_waddr == io_wr_0_waddr);
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
      regs_4 <= 32'h0;
      regs_5 <= 32'h0;
      regs_6 <= 32'h0;
      regs_7 <= 32'h0;
      regs_8 <= 32'h0;
      regs_9 <= 32'h0;
      regs_10 <= 32'h0;
      regs_11 <= 32'h80FFF9F0;
      regs_12 <= 32'h0;
      regs_13 <= 32'h0;
      regs_14 <= 32'h0;
      regs_15 <= 32'h0;
      regs_16 <= 32'h0;
      regs_17 <= 32'h0;
      regs_18 <= 32'h0;
      regs_19 <= 32'h0;
      regs_20 <= 32'h0;
      regs_21 <= 32'h0;
      regs_22 <= 32'h0;
      regs_23 <= 32'h0;
      regs_24 <= 32'h0;
      regs_25 <= 32'h0;
      regs_26 <= 32'h0;
      regs_27 <= 32'h0;
      regs_28 <= 32'h0;
      regs_29 <= 32'h0;
      regs_30 <= 32'h0;
      regs_31 <= 32'h0;
    end
    else begin
      if (_GEN_0 & ~(|io_wr_0_waddr))
        regs_0 <= io_wr_0_wdata;
      else if (_GEN & ~(|io_wr_1_waddr))
        regs_0 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h1)
        regs_1 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h1)
        regs_1 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h2)
        regs_2 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h2)
        regs_2 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h3)
        regs_3 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h3)
        regs_3 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h4)
        regs_4 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h4)
        regs_4 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h5)
        regs_5 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h5)
        regs_5 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h6)
        regs_6 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h6)
        regs_6 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h7)
        regs_7 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h7)
        regs_7 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h8)
        regs_8 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h8)
        regs_8 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h9)
        regs_9 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h9)
        regs_9 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'hA)
        regs_10 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'hA)
        regs_10 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'hB)
        regs_11 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'hB)
        regs_11 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'hC)
        regs_12 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'hC)
        regs_12 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'hD)
        regs_13 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'hD)
        regs_13 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'hE)
        regs_14 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'hE)
        regs_14 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'hF)
        regs_15 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'hF)
        regs_15 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h10)
        regs_16 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h10)
        regs_16 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h11)
        regs_17 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h11)
        regs_17 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h12)
        regs_18 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h12)
        regs_18 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h13)
        regs_19 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h13)
        regs_19 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h14)
        regs_20 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h14)
        regs_20 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h15)
        regs_21 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h15)
        regs_21 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h16)
        regs_22 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h16)
        regs_22 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h17)
        regs_23 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h17)
        regs_23 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h18)
        regs_24 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h18)
        regs_24 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h19)
        regs_25 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h19)
        regs_25 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h1A)
        regs_26 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h1A)
        regs_26 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h1B)
        regs_27 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h1B)
        regs_27 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h1C)
        regs_28 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h1C)
        regs_28 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h1D)
        regs_29 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h1D)
        regs_29 <= io_wr_1_wdata;
      if (_GEN_0 & io_wr_0_waddr == 5'h1E)
        regs_30 <= io_wr_0_wdata;
      else if (_GEN & io_wr_1_waddr == 5'h1E)
        regs_30 <= io_wr_1_wdata;
      if (_GEN_0 & (&io_wr_0_waddr))
        regs_31 <= io_wr_0_wdata;
      else if (_GEN & (&io_wr_1_waddr))
        regs_31 <= io_wr_1_wdata;
    end
  end // always @(posedge)
  assign io_rd_0_rdata = io_rd_0_raddr == 5'h0 ? 32'h0 : casez_tmp;
  assign io_rd_1_rdata = io_rd_1_raddr == 5'h0 ? 32'h0 : casez_tmp_0;
  assign io_rd_2_rdata = io_rd_2_raddr == 5'h0 ? 32'h0 : casez_tmp_1;
  assign io_rd_3_rdata = io_rd_3_raddr == 5'h0 ? 32'h0 : casez_tmp_2;
endmodule

