// Internal bridge for bundled CPU adapters.
//
// ECOS SoC always instantiates cpu_top. Bundled adapters expose a private ECOS
// CPU socket internally; this file adapts that implementation to the public
// cpu_top contract. User CPU filelists do not include this file and must
// provide cpu_top directly.

module cpu_top (
  input         clock,
  input         reset,
  input         io_extIrq,
  input         io_timerIrq,
  input         io_master_aw_ready,
  output        io_master_aw_valid,
  output [31:0] io_master_aw_bits_awaddr,
  output [3:0]  io_master_aw_bits_awid,
  output [7:0]  io_master_aw_bits_awlen,
  output [2:0]  io_master_aw_bits_awsize,
  output [1:0]  io_master_aw_bits_awburst,
  output        io_master_aw_bits_awlock,
  output [3:0]  io_master_aw_bits_awcache,
  output [2:0]  io_master_aw_bits_awprot,
  input         io_master_w_ready,
  output        io_master_w_valid,
  output [31:0] io_master_w_bits_wdata,
  output [3:0]  io_master_w_bits_wstrb,
  output        io_master_w_bits_wlast,
  output        io_master_b_ready,
  input         io_master_b_valid,
  input  [1:0]  io_master_b_bits_bresp,
  input  [3:0]  io_master_b_bits_bid,
  input         io_master_ar_ready,
  output        io_master_ar_valid,
  output [31:0] io_master_ar_bits_araddr,
  output [3:0]  io_master_ar_bits_arid,
  output [7:0]  io_master_ar_bits_arlen,
  output [2:0]  io_master_ar_bits_arsize,
  output [1:0]  io_master_ar_bits_arburst,
  output        io_master_ar_bits_arlock,
  output [3:0]  io_master_ar_bits_arcache,
  output [2:0]  io_master_ar_bits_arprot,
  output        io_master_r_ready,
  input         io_master_r_valid,
  input  [1:0]  io_master_r_bits_rresp,
  input  [31:0] io_master_r_bits_rdata,
  input         io_master_r_bits_rlast,
  input  [3:0]  io_master_r_bits_rid
);

  wire combined_interrupt = io_extIrq | io_timerIrq;

  ecos_internal_cpu_socket internal_cpu (
    .clock(clock),
    .reset(reset),
    .io_interrupt(combined_interrupt),
    .io_master_awready(io_master_aw_ready),
    .io_master_awvalid(io_master_aw_valid),
    .io_master_awaddr(io_master_aw_bits_awaddr),
    .io_master_awid(io_master_aw_bits_awid),
    .io_master_awlen(io_master_aw_bits_awlen),
    .io_master_awsize(io_master_aw_bits_awsize),
    .io_master_awburst(io_master_aw_bits_awburst),
    .io_master_awlock(io_master_aw_bits_awlock),
    .io_master_awcache(io_master_aw_bits_awcache),
    .io_master_awprot(io_master_aw_bits_awprot),
    .io_master_awqos(),
    .io_master_awregion(),
    .io_master_wready(io_master_w_ready),
    .io_master_wvalid(io_master_w_valid),
    .io_master_wdata(io_master_w_bits_wdata),
    .io_master_wstrb(io_master_w_bits_wstrb),
    .io_master_wlast(io_master_w_bits_wlast),
    .io_master_bready(io_master_b_ready),
    .io_master_bvalid(io_master_b_valid),
    .io_master_bresp(io_master_b_bits_bresp),
    .io_master_bid(io_master_b_bits_bid),
    .io_master_arready(io_master_ar_ready),
    .io_master_arvalid(io_master_ar_valid),
    .io_master_araddr(io_master_ar_bits_araddr),
    .io_master_arid(io_master_ar_bits_arid),
    .io_master_arlen(io_master_ar_bits_arlen),
    .io_master_arsize(io_master_ar_bits_arsize),
    .io_master_arburst(io_master_ar_bits_arburst),
    .io_master_arlock(io_master_ar_bits_arlock),
    .io_master_arcache(io_master_ar_bits_arcache),
    .io_master_arprot(io_master_ar_bits_arprot),
    .io_master_arqos(),
    .io_master_arregion(),
    .io_master_rready(io_master_r_ready),
    .io_master_rvalid(io_master_r_valid),
    .io_master_rresp(io_master_r_bits_rresp),
    .io_master_rdata(io_master_r_bits_rdata),
    .io_master_rlast(io_master_r_bits_rlast),
    .io_master_rid(io_master_r_bits_rid),
    .io_slave_awready(),
    .io_slave_awvalid(1'b0),
    .io_slave_awaddr(32'b0),
    .io_slave_awid(4'b0),
    .io_slave_awlen(8'b0),
    .io_slave_awsize(3'b0),
    .io_slave_awburst(2'b0),
    .io_slave_awlock(1'b0),
    .io_slave_awcache(4'b0),
    .io_slave_awprot(3'b0),
    .io_slave_awqos(4'b0),
    .io_slave_awregion(4'b0),
    .io_slave_wready(),
    .io_slave_wvalid(1'b0),
    .io_slave_wdata(32'b0),
    .io_slave_wstrb(4'b0),
    .io_slave_wlast(1'b0),
    .io_slave_bready(1'b0),
    .io_slave_bvalid(),
    .io_slave_bresp(),
    .io_slave_bid(),
    .io_slave_arready(),
    .io_slave_arvalid(1'b0),
    .io_slave_araddr(32'b0),
    .io_slave_arid(4'b0),
    .io_slave_arlen(8'b0),
    .io_slave_arsize(3'b0),
    .io_slave_arburst(2'b0),
    .io_slave_arlock(1'b0),
    .io_slave_arcache(4'b0),
    .io_slave_arprot(3'b0),
    .io_slave_arqos(4'b0),
    .io_slave_arregion(4'b0),
    .io_slave_rready(1'b0),
    .io_slave_rvalid(),
    .io_slave_rresp(),
    .io_slave_rdata(),
    .io_slave_rlast(),
    .io_slave_rid()
  );

endmodule
