// Generated by CIRCT firtool-1.133.0
module C32(
  input  io_a1,
         io_a2,
         io_cin,
  output io_s,
         io_c
);

  assign io_s = io_a1 ^ io_a2 ^ io_cin;
  assign io_c = io_a1 & io_a2 | io_a1 & io_cin | io_a2 & io_cin;
endmodule

