// Generated by CIRCT firtool-1.133.0
module CL3BTB(
  input         clock,
                reset,
  input  [29:0] io_rd_0_pc,
  output        io_rd_0_hit,
  output [29:0] io_rd_0_rdata_target,
  output        io_rd_0_rdata_isCall,
                io_rd_0_rdata_isRet,
                io_rd_0_rdata_isJmp,
  input  [29:0] io_rd_1_pc,
  output        io_rd_1_hit,
  output [29:0] io_rd_1_rdata_target,
  output        io_rd_1_rdata_isCall,
                io_rd_1_rdata_isRet,
                io_rd_1_rdata_isJmp,
  input  [29:0] io_wr_pc,
                io_wr_wdata_target,
  input         io_wr_wdata_isCall,
                io_wr_wdata_isRet,
                io_wr_wdata_isJmp,
                io_wr_wen
);

  wire        _lfsr_prng_io_out_0;
  wire        _lfsr_prng_io_out_1;
  wire        _lfsr_prng_io_out_2;
  wire        _lfsr_prng_io_out_3;
  wire        _lfsr_prng_io_out_4;
  reg         btb_bank_0_0_valid;
  reg  [28:0] btb_bank_0_0_tag;
  reg  [29:0] btb_bank_0_0_data_target;
  reg         btb_bank_0_0_data_isCall;
  reg         btb_bank_0_0_data_isRet;
  reg         btb_bank_0_0_data_isJmp;
  reg         btb_bank_0_1_valid;
  reg  [28:0] btb_bank_0_1_tag;
  reg  [29:0] btb_bank_0_1_data_target;
  reg         btb_bank_0_1_data_isCall;
  reg         btb_bank_0_1_data_isRet;
  reg         btb_bank_0_1_data_isJmp;
  reg         btb_bank_0_2_valid;
  reg  [28:0] btb_bank_0_2_tag;
  reg  [29:0] btb_bank_0_2_data_target;
  reg         btb_bank_0_2_data_isCall;
  reg         btb_bank_0_2_data_isRet;
  reg         btb_bank_0_2_data_isJmp;
  reg         btb_bank_0_3_valid;
  reg  [28:0] btb_bank_0_3_tag;
  reg  [29:0] btb_bank_0_3_data_target;
  reg         btb_bank_0_3_data_isCall;
  reg         btb_bank_0_3_data_isRet;
  reg         btb_bank_0_3_data_isJmp;
  reg         btb_bank_0_4_valid;
  reg  [28:0] btb_bank_0_4_tag;
  reg  [29:0] btb_bank_0_4_data_target;
  reg         btb_bank_0_4_data_isCall;
  reg         btb_bank_0_4_data_isRet;
  reg         btb_bank_0_4_data_isJmp;
  reg         btb_bank_0_5_valid;
  reg  [28:0] btb_bank_0_5_tag;
  reg  [29:0] btb_bank_0_5_data_target;
  reg         btb_bank_0_5_data_isCall;
  reg         btb_bank_0_5_data_isRet;
  reg         btb_bank_0_5_data_isJmp;
  reg         btb_bank_0_6_valid;
  reg  [28:0] btb_bank_0_6_tag;
  reg  [29:0] btb_bank_0_6_data_target;
  reg         btb_bank_0_6_data_isCall;
  reg         btb_bank_0_6_data_isRet;
  reg         btb_bank_0_6_data_isJmp;
  reg         btb_bank_0_7_valid;
  reg  [28:0] btb_bank_0_7_tag;
  reg  [29:0] btb_bank_0_7_data_target;
  reg         btb_bank_0_7_data_isCall;
  reg         btb_bank_0_7_data_isRet;
  reg         btb_bank_0_7_data_isJmp;
  reg         btb_bank_0_8_valid;
  reg  [28:0] btb_bank_0_8_tag;
  reg  [29:0] btb_bank_0_8_data_target;
  reg         btb_bank_0_8_data_isCall;
  reg         btb_bank_0_8_data_isRet;
  reg         btb_bank_0_8_data_isJmp;
  reg         btb_bank_0_9_valid;
  reg  [28:0] btb_bank_0_9_tag;
  reg  [29:0] btb_bank_0_9_data_target;
  reg         btb_bank_0_9_data_isCall;
  reg         btb_bank_0_9_data_isRet;
  reg         btb_bank_0_9_data_isJmp;
  reg         btb_bank_0_10_valid;
  reg  [28:0] btb_bank_0_10_tag;
  reg  [29:0] btb_bank_0_10_data_target;
  reg         btb_bank_0_10_data_isCall;
  reg         btb_bank_0_10_data_isRet;
  reg         btb_bank_0_10_data_isJmp;
  reg         btb_bank_0_11_valid;
  reg  [28:0] btb_bank_0_11_tag;
  reg  [29:0] btb_bank_0_11_data_target;
  reg         btb_bank_0_11_data_isCall;
  reg         btb_bank_0_11_data_isRet;
  reg         btb_bank_0_11_data_isJmp;
  reg         btb_bank_0_12_valid;
  reg  [28:0] btb_bank_0_12_tag;
  reg  [29:0] btb_bank_0_12_data_target;
  reg         btb_bank_0_12_data_isCall;
  reg         btb_bank_0_12_data_isRet;
  reg         btb_bank_0_12_data_isJmp;
  reg         btb_bank_0_13_valid;
  reg  [28:0] btb_bank_0_13_tag;
  reg  [29:0] btb_bank_0_13_data_target;
  reg         btb_bank_0_13_data_isCall;
  reg         btb_bank_0_13_data_isRet;
  reg         btb_bank_0_13_data_isJmp;
  reg         btb_bank_0_14_valid;
  reg  [28:0] btb_bank_0_14_tag;
  reg  [29:0] btb_bank_0_14_data_target;
  reg         btb_bank_0_14_data_isCall;
  reg         btb_bank_0_14_data_isRet;
  reg         btb_bank_0_14_data_isJmp;
  reg         btb_bank_0_15_valid;
  reg  [28:0] btb_bank_0_15_tag;
  reg  [29:0] btb_bank_0_15_data_target;
  reg         btb_bank_0_15_data_isCall;
  reg         btb_bank_0_15_data_isRet;
  reg         btb_bank_0_15_data_isJmp;
  reg         btb_bank_0_16_valid;
  reg  [28:0] btb_bank_0_16_tag;
  reg  [29:0] btb_bank_0_16_data_target;
  reg         btb_bank_0_16_data_isCall;
  reg         btb_bank_0_16_data_isRet;
  reg         btb_bank_0_16_data_isJmp;
  reg         btb_bank_0_17_valid;
  reg  [28:0] btb_bank_0_17_tag;
  reg  [29:0] btb_bank_0_17_data_target;
  reg         btb_bank_0_17_data_isCall;
  reg         btb_bank_0_17_data_isRet;
  reg         btb_bank_0_17_data_isJmp;
  reg         btb_bank_0_18_valid;
  reg  [28:0] btb_bank_0_18_tag;
  reg  [29:0] btb_bank_0_18_data_target;
  reg         btb_bank_0_18_data_isCall;
  reg         btb_bank_0_18_data_isRet;
  reg         btb_bank_0_18_data_isJmp;
  reg         btb_bank_0_19_valid;
  reg  [28:0] btb_bank_0_19_tag;
  reg  [29:0] btb_bank_0_19_data_target;
  reg         btb_bank_0_19_data_isCall;
  reg         btb_bank_0_19_data_isRet;
  reg         btb_bank_0_19_data_isJmp;
  reg         btb_bank_0_20_valid;
  reg  [28:0] btb_bank_0_20_tag;
  reg  [29:0] btb_bank_0_20_data_target;
  reg         btb_bank_0_20_data_isCall;
  reg         btb_bank_0_20_data_isRet;
  reg         btb_bank_0_20_data_isJmp;
  reg         btb_bank_0_21_valid;
  reg  [28:0] btb_bank_0_21_tag;
  reg  [29:0] btb_bank_0_21_data_target;
  reg         btb_bank_0_21_data_isCall;
  reg         btb_bank_0_21_data_isRet;
  reg         btb_bank_0_21_data_isJmp;
  reg         btb_bank_0_22_valid;
  reg  [28:0] btb_bank_0_22_tag;
  reg  [29:0] btb_bank_0_22_data_target;
  reg         btb_bank_0_22_data_isCall;
  reg         btb_bank_0_22_data_isRet;
  reg         btb_bank_0_22_data_isJmp;
  reg         btb_bank_0_23_valid;
  reg  [28:0] btb_bank_0_23_tag;
  reg  [29:0] btb_bank_0_23_data_target;
  reg         btb_bank_0_23_data_isCall;
  reg         btb_bank_0_23_data_isRet;
  reg         btb_bank_0_23_data_isJmp;
  reg         btb_bank_0_24_valid;
  reg  [28:0] btb_bank_0_24_tag;
  reg  [29:0] btb_bank_0_24_data_target;
  reg         btb_bank_0_24_data_isCall;
  reg         btb_bank_0_24_data_isRet;
  reg         btb_bank_0_24_data_isJmp;
  reg         btb_bank_0_25_valid;
  reg  [28:0] btb_bank_0_25_tag;
  reg  [29:0] btb_bank_0_25_data_target;
  reg         btb_bank_0_25_data_isCall;
  reg         btb_bank_0_25_data_isRet;
  reg         btb_bank_0_25_data_isJmp;
  reg         btb_bank_0_26_valid;
  reg  [28:0] btb_bank_0_26_tag;
  reg  [29:0] btb_bank_0_26_data_target;
  reg         btb_bank_0_26_data_isCall;
  reg         btb_bank_0_26_data_isRet;
  reg         btb_bank_0_26_data_isJmp;
  reg         btb_bank_0_27_valid;
  reg  [28:0] btb_bank_0_27_tag;
  reg  [29:0] btb_bank_0_27_data_target;
  reg         btb_bank_0_27_data_isCall;
  reg         btb_bank_0_27_data_isRet;
  reg         btb_bank_0_27_data_isJmp;
  reg         btb_bank_0_28_valid;
  reg  [28:0] btb_bank_0_28_tag;
  reg  [29:0] btb_bank_0_28_data_target;
  reg         btb_bank_0_28_data_isCall;
  reg         btb_bank_0_28_data_isRet;
  reg         btb_bank_0_28_data_isJmp;
  reg         btb_bank_0_29_valid;
  reg  [28:0] btb_bank_0_29_tag;
  reg  [29:0] btb_bank_0_29_data_target;
  reg         btb_bank_0_29_data_isCall;
  reg         btb_bank_0_29_data_isRet;
  reg         btb_bank_0_29_data_isJmp;
  reg         btb_bank_0_30_valid;
  reg  [28:0] btb_bank_0_30_tag;
  reg  [29:0] btb_bank_0_30_data_target;
  reg         btb_bank_0_30_data_isCall;
  reg         btb_bank_0_30_data_isRet;
  reg         btb_bank_0_30_data_isJmp;
  reg         btb_bank_0_31_valid;
  reg  [28:0] btb_bank_0_31_tag;
  reg  [29:0] btb_bank_0_31_data_target;
  reg         btb_bank_0_31_data_isCall;
  reg         btb_bank_0_31_data_isRet;
  reg         btb_bank_0_31_data_isJmp;
  reg         btb_bank_1_0_valid;
  reg  [28:0] btb_bank_1_0_tag;
  reg  [29:0] btb_bank_1_0_data_target;
  reg         btb_bank_1_0_data_isCall;
  reg         btb_bank_1_0_data_isRet;
  reg         btb_bank_1_0_data_isJmp;
  reg         btb_bank_1_1_valid;
  reg  [28:0] btb_bank_1_1_tag;
  reg  [29:0] btb_bank_1_1_data_target;
  reg         btb_bank_1_1_data_isCall;
  reg         btb_bank_1_1_data_isRet;
  reg         btb_bank_1_1_data_isJmp;
  reg         btb_bank_1_2_valid;
  reg  [28:0] btb_bank_1_2_tag;
  reg  [29:0] btb_bank_1_2_data_target;
  reg         btb_bank_1_2_data_isCall;
  reg         btb_bank_1_2_data_isRet;
  reg         btb_bank_1_2_data_isJmp;
  reg         btb_bank_1_3_valid;
  reg  [28:0] btb_bank_1_3_tag;
  reg  [29:0] btb_bank_1_3_data_target;
  reg         btb_bank_1_3_data_isCall;
  reg         btb_bank_1_3_data_isRet;
  reg         btb_bank_1_3_data_isJmp;
  reg         btb_bank_1_4_valid;
  reg  [28:0] btb_bank_1_4_tag;
  reg  [29:0] btb_bank_1_4_data_target;
  reg         btb_bank_1_4_data_isCall;
  reg         btb_bank_1_4_data_isRet;
  reg         btb_bank_1_4_data_isJmp;
  reg         btb_bank_1_5_valid;
  reg  [28:0] btb_bank_1_5_tag;
  reg  [29:0] btb_bank_1_5_data_target;
  reg         btb_bank_1_5_data_isCall;
  reg         btb_bank_1_5_data_isRet;
  reg         btb_bank_1_5_data_isJmp;
  reg         btb_bank_1_6_valid;
  reg  [28:0] btb_bank_1_6_tag;
  reg  [29:0] btb_bank_1_6_data_target;
  reg         btb_bank_1_6_data_isCall;
  reg         btb_bank_1_6_data_isRet;
  reg         btb_bank_1_6_data_isJmp;
  reg         btb_bank_1_7_valid;
  reg  [28:0] btb_bank_1_7_tag;
  reg  [29:0] btb_bank_1_7_data_target;
  reg         btb_bank_1_7_data_isCall;
  reg         btb_bank_1_7_data_isRet;
  reg         btb_bank_1_7_data_isJmp;
  reg         btb_bank_1_8_valid;
  reg  [28:0] btb_bank_1_8_tag;
  reg  [29:0] btb_bank_1_8_data_target;
  reg         btb_bank_1_8_data_isCall;
  reg         btb_bank_1_8_data_isRet;
  reg         btb_bank_1_8_data_isJmp;
  reg         btb_bank_1_9_valid;
  reg  [28:0] btb_bank_1_9_tag;
  reg  [29:0] btb_bank_1_9_data_target;
  reg         btb_bank_1_9_data_isCall;
  reg         btb_bank_1_9_data_isRet;
  reg         btb_bank_1_9_data_isJmp;
  reg         btb_bank_1_10_valid;
  reg  [28:0] btb_bank_1_10_tag;
  reg  [29:0] btb_bank_1_10_data_target;
  reg         btb_bank_1_10_data_isCall;
  reg         btb_bank_1_10_data_isRet;
  reg         btb_bank_1_10_data_isJmp;
  reg         btb_bank_1_11_valid;
  reg  [28:0] btb_bank_1_11_tag;
  reg  [29:0] btb_bank_1_11_data_target;
  reg         btb_bank_1_11_data_isCall;
  reg         btb_bank_1_11_data_isRet;
  reg         btb_bank_1_11_data_isJmp;
  reg         btb_bank_1_12_valid;
  reg  [28:0] btb_bank_1_12_tag;
  reg  [29:0] btb_bank_1_12_data_target;
  reg         btb_bank_1_12_data_isCall;
  reg         btb_bank_1_12_data_isRet;
  reg         btb_bank_1_12_data_isJmp;
  reg         btb_bank_1_13_valid;
  reg  [28:0] btb_bank_1_13_tag;
  reg  [29:0] btb_bank_1_13_data_target;
  reg         btb_bank_1_13_data_isCall;
  reg         btb_bank_1_13_data_isRet;
  reg         btb_bank_1_13_data_isJmp;
  reg         btb_bank_1_14_valid;
  reg  [28:0] btb_bank_1_14_tag;
  reg  [29:0] btb_bank_1_14_data_target;
  reg         btb_bank_1_14_data_isCall;
  reg         btb_bank_1_14_data_isRet;
  reg         btb_bank_1_14_data_isJmp;
  reg         btb_bank_1_15_valid;
  reg  [28:0] btb_bank_1_15_tag;
  reg  [29:0] btb_bank_1_15_data_target;
  reg         btb_bank_1_15_data_isCall;
  reg         btb_bank_1_15_data_isRet;
  reg         btb_bank_1_15_data_isJmp;
  reg         btb_bank_1_16_valid;
  reg  [28:0] btb_bank_1_16_tag;
  reg  [29:0] btb_bank_1_16_data_target;
  reg         btb_bank_1_16_data_isCall;
  reg         btb_bank_1_16_data_isRet;
  reg         btb_bank_1_16_data_isJmp;
  reg         btb_bank_1_17_valid;
  reg  [28:0] btb_bank_1_17_tag;
  reg  [29:0] btb_bank_1_17_data_target;
  reg         btb_bank_1_17_data_isCall;
  reg         btb_bank_1_17_data_isRet;
  reg         btb_bank_1_17_data_isJmp;
  reg         btb_bank_1_18_valid;
  reg  [28:0] btb_bank_1_18_tag;
  reg  [29:0] btb_bank_1_18_data_target;
  reg         btb_bank_1_18_data_isCall;
  reg         btb_bank_1_18_data_isRet;
  reg         btb_bank_1_18_data_isJmp;
  reg         btb_bank_1_19_valid;
  reg  [28:0] btb_bank_1_19_tag;
  reg  [29:0] btb_bank_1_19_data_target;
  reg         btb_bank_1_19_data_isCall;
  reg         btb_bank_1_19_data_isRet;
  reg         btb_bank_1_19_data_isJmp;
  reg         btb_bank_1_20_valid;
  reg  [28:0] btb_bank_1_20_tag;
  reg  [29:0] btb_bank_1_20_data_target;
  reg         btb_bank_1_20_data_isCall;
  reg         btb_bank_1_20_data_isRet;
  reg         btb_bank_1_20_data_isJmp;
  reg         btb_bank_1_21_valid;
  reg  [28:0] btb_bank_1_21_tag;
  reg  [29:0] btb_bank_1_21_data_target;
  reg         btb_bank_1_21_data_isCall;
  reg         btb_bank_1_21_data_isRet;
  reg         btb_bank_1_21_data_isJmp;
  reg         btb_bank_1_22_valid;
  reg  [28:0] btb_bank_1_22_tag;
  reg  [29:0] btb_bank_1_22_data_target;
  reg         btb_bank_1_22_data_isCall;
  reg         btb_bank_1_22_data_isRet;
  reg         btb_bank_1_22_data_isJmp;
  reg         btb_bank_1_23_valid;
  reg  [28:0] btb_bank_1_23_tag;
  reg  [29:0] btb_bank_1_23_data_target;
  reg         btb_bank_1_23_data_isCall;
  reg         btb_bank_1_23_data_isRet;
  reg         btb_bank_1_23_data_isJmp;
  reg         btb_bank_1_24_valid;
  reg  [28:0] btb_bank_1_24_tag;
  reg  [29:0] btb_bank_1_24_data_target;
  reg         btb_bank_1_24_data_isCall;
  reg         btb_bank_1_24_data_isRet;
  reg         btb_bank_1_24_data_isJmp;
  reg         btb_bank_1_25_valid;
  reg  [28:0] btb_bank_1_25_tag;
  reg  [29:0] btb_bank_1_25_data_target;
  reg         btb_bank_1_25_data_isCall;
  reg         btb_bank_1_25_data_isRet;
  reg         btb_bank_1_25_data_isJmp;
  reg         btb_bank_1_26_valid;
  reg  [28:0] btb_bank_1_26_tag;
  reg  [29:0] btb_bank_1_26_data_target;
  reg         btb_bank_1_26_data_isCall;
  reg         btb_bank_1_26_data_isRet;
  reg         btb_bank_1_26_data_isJmp;
  reg         btb_bank_1_27_valid;
  reg  [28:0] btb_bank_1_27_tag;
  reg  [29:0] btb_bank_1_27_data_target;
  reg         btb_bank_1_27_data_isCall;
  reg         btb_bank_1_27_data_isRet;
  reg         btb_bank_1_27_data_isJmp;
  reg         btb_bank_1_28_valid;
  reg  [28:0] btb_bank_1_28_tag;
  reg  [29:0] btb_bank_1_28_data_target;
  reg         btb_bank_1_28_data_isCall;
  reg         btb_bank_1_28_data_isRet;
  reg         btb_bank_1_28_data_isJmp;
  reg         btb_bank_1_29_valid;
  reg  [28:0] btb_bank_1_29_tag;
  reg  [29:0] btb_bank_1_29_data_target;
  reg         btb_bank_1_29_data_isCall;
  reg         btb_bank_1_29_data_isRet;
  reg         btb_bank_1_29_data_isJmp;
  reg         btb_bank_1_30_valid;
  reg  [28:0] btb_bank_1_30_tag;
  reg  [29:0] btb_bank_1_30_data_target;
  reg         btb_bank_1_30_data_isCall;
  reg         btb_bank_1_30_data_isRet;
  reg         btb_bank_1_30_data_isJmp;
  reg         btb_bank_1_31_valid;
  reg  [28:0] btb_bank_1_31_tag;
  reg  [29:0] btb_bank_1_31_data_target;
  reg         btb_bank_1_31_data_isCall;
  reg         btb_bank_1_31_data_isRet;
  reg         btb_bank_1_31_data_isJmp;
  wire [28:0] rd_tag_0 = io_rd_0_pc[0] ? io_rd_1_pc[29:1] : io_rd_0_pc[29:1];
  wire [28:0] rd_tag_1 = io_rd_0_pc[0] ? io_rd_0_pc[29:1] : io_rd_1_pc[29:1];
  wire        hits_0 = btb_bank_0_0_valid & btb_bank_0_0_tag == rd_tag_0;
  wire        hits_1 = btb_bank_0_1_valid & btb_bank_0_1_tag == rd_tag_0;
  wire        hits_2 = btb_bank_0_2_valid & btb_bank_0_2_tag == rd_tag_0;
  wire        hits_3 = btb_bank_0_3_valid & btb_bank_0_3_tag == rd_tag_0;
  wire        hits_4 = btb_bank_0_4_valid & btb_bank_0_4_tag == rd_tag_0;
  wire        hits_5 = btb_bank_0_5_valid & btb_bank_0_5_tag == rd_tag_0;
  wire        hits_6 = btb_bank_0_6_valid & btb_bank_0_6_tag == rd_tag_0;
  wire        hits_7 = btb_bank_0_7_valid & btb_bank_0_7_tag == rd_tag_0;
  wire        hits_8 = btb_bank_0_8_valid & btb_bank_0_8_tag == rd_tag_0;
  wire        hits_9 = btb_bank_0_9_valid & btb_bank_0_9_tag == rd_tag_0;
  wire        hits_10 = btb_bank_0_10_valid & btb_bank_0_10_tag == rd_tag_0;
  wire        hits_11 = btb_bank_0_11_valid & btb_bank_0_11_tag == rd_tag_0;
  wire        hits_12 = btb_bank_0_12_valid & btb_bank_0_12_tag == rd_tag_0;
  wire        hits_13 = btb_bank_0_13_valid & btb_bank_0_13_tag == rd_tag_0;
  wire        hits_14 = btb_bank_0_14_valid & btb_bank_0_14_tag == rd_tag_0;
  wire        hits_15 = btb_bank_0_15_valid & btb_bank_0_15_tag == rd_tag_0;
  wire        hits_16 = btb_bank_0_16_valid & btb_bank_0_16_tag == rd_tag_0;
  wire        hits_17 = btb_bank_0_17_valid & btb_bank_0_17_tag == rd_tag_0;
  wire        hits_18 = btb_bank_0_18_valid & btb_bank_0_18_tag == rd_tag_0;
  wire        hits_19 = btb_bank_0_19_valid & btb_bank_0_19_tag == rd_tag_0;
  wire        hits_20 = btb_bank_0_20_valid & btb_bank_0_20_tag == rd_tag_0;
  wire        hits_21 = btb_bank_0_21_valid & btb_bank_0_21_tag == rd_tag_0;
  wire        hits_22 = btb_bank_0_22_valid & btb_bank_0_22_tag == rd_tag_0;
  wire        hits_23 = btb_bank_0_23_valid & btb_bank_0_23_tag == rd_tag_0;
  wire        hits_24 = btb_bank_0_24_valid & btb_bank_0_24_tag == rd_tag_0;
  wire        hits_25 = btb_bank_0_25_valid & btb_bank_0_25_tag == rd_tag_0;
  wire        hits_26 = btb_bank_0_26_valid & btb_bank_0_26_tag == rd_tag_0;
  wire        hits_27 = btb_bank_0_27_valid & btb_bank_0_27_tag == rd_tag_0;
  wire        hits_28 = btb_bank_0_28_valid & btb_bank_0_28_tag == rd_tag_0;
  wire        hits_29 = btb_bank_0_29_valid & btb_bank_0_29_tag == rd_tag_0;
  wire        hits_30 = btb_bank_0_30_valid & btb_bank_0_30_tag == rd_tag_0;
  wire        hits_31 = btb_bank_0_31_valid & btb_bank_0_31_tag == rd_tag_0;
  wire [31:0] _rd_hit_0_T =
    {hits_31,
     hits_30,
     hits_29,
     hits_28,
     hits_27,
     hits_26,
     hits_25,
     hits_24,
     hits_23,
     hits_22,
     hits_21,
     hits_20,
     hits_19,
     hits_18,
     hits_17,
     hits_16,
     hits_15,
     hits_14,
     hits_13,
     hits_12,
     hits_11,
     hits_10,
     hits_9,
     hits_8,
     hits_7,
     hits_6,
     hits_5,
     hits_4,
     hits_3,
     hits_2,
     hits_1,
     hits_0};
  wire        rdata_0_isJmp =
    hits_0 & btb_bank_0_0_data_isJmp | hits_1 & btb_bank_0_1_data_isJmp | hits_2
    & btb_bank_0_2_data_isJmp | hits_3 & btb_bank_0_3_data_isJmp | hits_4
    & btb_bank_0_4_data_isJmp | hits_5 & btb_bank_0_5_data_isJmp | hits_6
    & btb_bank_0_6_data_isJmp | hits_7 & btb_bank_0_7_data_isJmp | hits_8
    & btb_bank_0_8_data_isJmp | hits_9 & btb_bank_0_9_data_isJmp | hits_10
    & btb_bank_0_10_data_isJmp | hits_11 & btb_bank_0_11_data_isJmp | hits_12
    & btb_bank_0_12_data_isJmp | hits_13 & btb_bank_0_13_data_isJmp | hits_14
    & btb_bank_0_14_data_isJmp | hits_15 & btb_bank_0_15_data_isJmp | hits_16
    & btb_bank_0_16_data_isJmp | hits_17 & btb_bank_0_17_data_isJmp | hits_18
    & btb_bank_0_18_data_isJmp | hits_19 & btb_bank_0_19_data_isJmp | hits_20
    & btb_bank_0_20_data_isJmp | hits_21 & btb_bank_0_21_data_isJmp | hits_22
    & btb_bank_0_22_data_isJmp | hits_23 & btb_bank_0_23_data_isJmp | hits_24
    & btb_bank_0_24_data_isJmp | hits_25 & btb_bank_0_25_data_isJmp | hits_26
    & btb_bank_0_26_data_isJmp | hits_27 & btb_bank_0_27_data_isJmp | hits_28
    & btb_bank_0_28_data_isJmp | hits_29 & btb_bank_0_29_data_isJmp | hits_30
    & btb_bank_0_30_data_isJmp | hits_31 & btb_bank_0_31_data_isJmp;
  wire        rdata_0_isRet =
    hits_0 & btb_bank_0_0_data_isRet | hits_1 & btb_bank_0_1_data_isRet | hits_2
    & btb_bank_0_2_data_isRet | hits_3 & btb_bank_0_3_data_isRet | hits_4
    & btb_bank_0_4_data_isRet | hits_5 & btb_bank_0_5_data_isRet | hits_6
    & btb_bank_0_6_data_isRet | hits_7 & btb_bank_0_7_data_isRet | hits_8
    & btb_bank_0_8_data_isRet | hits_9 & btb_bank_0_9_data_isRet | hits_10
    & btb_bank_0_10_data_isRet | hits_11 & btb_bank_0_11_data_isRet | hits_12
    & btb_bank_0_12_data_isRet | hits_13 & btb_bank_0_13_data_isRet | hits_14
    & btb_bank_0_14_data_isRet | hits_15 & btb_bank_0_15_data_isRet | hits_16
    & btb_bank_0_16_data_isRet | hits_17 & btb_bank_0_17_data_isRet | hits_18
    & btb_bank_0_18_data_isRet | hits_19 & btb_bank_0_19_data_isRet | hits_20
    & btb_bank_0_20_data_isRet | hits_21 & btb_bank_0_21_data_isRet | hits_22
    & btb_bank_0_22_data_isRet | hits_23 & btb_bank_0_23_data_isRet | hits_24
    & btb_bank_0_24_data_isRet | hits_25 & btb_bank_0_25_data_isRet | hits_26
    & btb_bank_0_26_data_isRet | hits_27 & btb_bank_0_27_data_isRet | hits_28
    & btb_bank_0_28_data_isRet | hits_29 & btb_bank_0_29_data_isRet | hits_30
    & btb_bank_0_30_data_isRet | hits_31 & btb_bank_0_31_data_isRet;
  wire        rdata_0_isCall =
    hits_0 & btb_bank_0_0_data_isCall | hits_1 & btb_bank_0_1_data_isCall | hits_2
    & btb_bank_0_2_data_isCall | hits_3 & btb_bank_0_3_data_isCall | hits_4
    & btb_bank_0_4_data_isCall | hits_5 & btb_bank_0_5_data_isCall | hits_6
    & btb_bank_0_6_data_isCall | hits_7 & btb_bank_0_7_data_isCall | hits_8
    & btb_bank_0_8_data_isCall | hits_9 & btb_bank_0_9_data_isCall | hits_10
    & btb_bank_0_10_data_isCall | hits_11 & btb_bank_0_11_data_isCall | hits_12
    & btb_bank_0_12_data_isCall | hits_13 & btb_bank_0_13_data_isCall | hits_14
    & btb_bank_0_14_data_isCall | hits_15 & btb_bank_0_15_data_isCall | hits_16
    & btb_bank_0_16_data_isCall | hits_17 & btb_bank_0_17_data_isCall | hits_18
    & btb_bank_0_18_data_isCall | hits_19 & btb_bank_0_19_data_isCall | hits_20
    & btb_bank_0_20_data_isCall | hits_21 & btb_bank_0_21_data_isCall | hits_22
    & btb_bank_0_22_data_isCall | hits_23 & btb_bank_0_23_data_isCall | hits_24
    & btb_bank_0_24_data_isCall | hits_25 & btb_bank_0_25_data_isCall | hits_26
    & btb_bank_0_26_data_isCall | hits_27 & btb_bank_0_27_data_isCall | hits_28
    & btb_bank_0_28_data_isCall | hits_29 & btb_bank_0_29_data_isCall | hits_30
    & btb_bank_0_30_data_isCall | hits_31 & btb_bank_0_31_data_isCall;
  wire [29:0] rdata_0_target =
    (hits_0 ? btb_bank_0_0_data_target : 30'h0)
    | (hits_1 ? btb_bank_0_1_data_target : 30'h0)
    | (hits_2 ? btb_bank_0_2_data_target : 30'h0)
    | (hits_3 ? btb_bank_0_3_data_target : 30'h0)
    | (hits_4 ? btb_bank_0_4_data_target : 30'h0)
    | (hits_5 ? btb_bank_0_5_data_target : 30'h0)
    | (hits_6 ? btb_bank_0_6_data_target : 30'h0)
    | (hits_7 ? btb_bank_0_7_data_target : 30'h0)
    | (hits_8 ? btb_bank_0_8_data_target : 30'h0)
    | (hits_9 ? btb_bank_0_9_data_target : 30'h0)
    | (hits_10 ? btb_bank_0_10_data_target : 30'h0)
    | (hits_11 ? btb_bank_0_11_data_target : 30'h0)
    | (hits_12 ? btb_bank_0_12_data_target : 30'h0)
    | (hits_13 ? btb_bank_0_13_data_target : 30'h0)
    | (hits_14 ? btb_bank_0_14_data_target : 30'h0)
    | (hits_15 ? btb_bank_0_15_data_target : 30'h0)
    | (hits_16 ? btb_bank_0_16_data_target : 30'h0)
    | (hits_17 ? btb_bank_0_17_data_target : 30'h0)
    | (hits_18 ? btb_bank_0_18_data_target : 30'h0)
    | (hits_19 ? btb_bank_0_19_data_target : 30'h0)
    | (hits_20 ? btb_bank_0_20_data_target : 30'h0)
    | (hits_21 ? btb_bank_0_21_data_target : 30'h0)
    | (hits_22 ? btb_bank_0_22_data_target : 30'h0)
    | (hits_23 ? btb_bank_0_23_data_target : 30'h0)
    | (hits_24 ? btb_bank_0_24_data_target : 30'h0)
    | (hits_25 ? btb_bank_0_25_data_target : 30'h0)
    | (hits_26 ? btb_bank_0_26_data_target : 30'h0)
    | (hits_27 ? btb_bank_0_27_data_target : 30'h0)
    | (hits_28 ? btb_bank_0_28_data_target : 30'h0)
    | (hits_29 ? btb_bank_0_29_data_target : 30'h0)
    | (hits_30 ? btb_bank_0_30_data_target : 30'h0)
    | (hits_31 ? btb_bank_0_31_data_target : 30'h0);
  wire        hits_1_0 = btb_bank_1_0_valid & btb_bank_1_0_tag == rd_tag_1;
  wire        hits_1_1 = btb_bank_1_1_valid & btb_bank_1_1_tag == rd_tag_1;
  wire        hits_1_2 = btb_bank_1_2_valid & btb_bank_1_2_tag == rd_tag_1;
  wire        hits_1_3 = btb_bank_1_3_valid & btb_bank_1_3_tag == rd_tag_1;
  wire        hits_1_4 = btb_bank_1_4_valid & btb_bank_1_4_tag == rd_tag_1;
  wire        hits_1_5 = btb_bank_1_5_valid & btb_bank_1_5_tag == rd_tag_1;
  wire        hits_1_6 = btb_bank_1_6_valid & btb_bank_1_6_tag == rd_tag_1;
  wire        hits_1_7 = btb_bank_1_7_valid & btb_bank_1_7_tag == rd_tag_1;
  wire        hits_1_8 = btb_bank_1_8_valid & btb_bank_1_8_tag == rd_tag_1;
  wire        hits_1_9 = btb_bank_1_9_valid & btb_bank_1_9_tag == rd_tag_1;
  wire        hits_1_10 = btb_bank_1_10_valid & btb_bank_1_10_tag == rd_tag_1;
  wire        hits_1_11 = btb_bank_1_11_valid & btb_bank_1_11_tag == rd_tag_1;
  wire        hits_1_12 = btb_bank_1_12_valid & btb_bank_1_12_tag == rd_tag_1;
  wire        hits_1_13 = btb_bank_1_13_valid & btb_bank_1_13_tag == rd_tag_1;
  wire        hits_1_14 = btb_bank_1_14_valid & btb_bank_1_14_tag == rd_tag_1;
  wire        hits_1_15 = btb_bank_1_15_valid & btb_bank_1_15_tag == rd_tag_1;
  wire        hits_1_16 = btb_bank_1_16_valid & btb_bank_1_16_tag == rd_tag_1;
  wire        hits_1_17 = btb_bank_1_17_valid & btb_bank_1_17_tag == rd_tag_1;
  wire        hits_1_18 = btb_bank_1_18_valid & btb_bank_1_18_tag == rd_tag_1;
  wire        hits_1_19 = btb_bank_1_19_valid & btb_bank_1_19_tag == rd_tag_1;
  wire        hits_1_20 = btb_bank_1_20_valid & btb_bank_1_20_tag == rd_tag_1;
  wire        hits_1_21 = btb_bank_1_21_valid & btb_bank_1_21_tag == rd_tag_1;
  wire        hits_1_22 = btb_bank_1_22_valid & btb_bank_1_22_tag == rd_tag_1;
  wire        hits_1_23 = btb_bank_1_23_valid & btb_bank_1_23_tag == rd_tag_1;
  wire        hits_1_24 = btb_bank_1_24_valid & btb_bank_1_24_tag == rd_tag_1;
  wire        hits_1_25 = btb_bank_1_25_valid & btb_bank_1_25_tag == rd_tag_1;
  wire        hits_1_26 = btb_bank_1_26_valid & btb_bank_1_26_tag == rd_tag_1;
  wire        hits_1_27 = btb_bank_1_27_valid & btb_bank_1_27_tag == rd_tag_1;
  wire        hits_1_28 = btb_bank_1_28_valid & btb_bank_1_28_tag == rd_tag_1;
  wire        hits_1_29 = btb_bank_1_29_valid & btb_bank_1_29_tag == rd_tag_1;
  wire        hits_1_30 = btb_bank_1_30_valid & btb_bank_1_30_tag == rd_tag_1;
  wire        hits_1_31 = btb_bank_1_31_valid & btb_bank_1_31_tag == rd_tag_1;
  wire [31:0] _rd_hit_1_T =
    {hits_1_31,
     hits_1_30,
     hits_1_29,
     hits_1_28,
     hits_1_27,
     hits_1_26,
     hits_1_25,
     hits_1_24,
     hits_1_23,
     hits_1_22,
     hits_1_21,
     hits_1_20,
     hits_1_19,
     hits_1_18,
     hits_1_17,
     hits_1_16,
     hits_1_15,
     hits_1_14,
     hits_1_13,
     hits_1_12,
     hits_1_11,
     hits_1_10,
     hits_1_9,
     hits_1_8,
     hits_1_7,
     hits_1_6,
     hits_1_5,
     hits_1_4,
     hits_1_3,
     hits_1_2,
     hits_1_1,
     hits_1_0};
  wire        rdata_1_isJmp =
    hits_1_0 & btb_bank_1_0_data_isJmp | hits_1_1 & btb_bank_1_1_data_isJmp | hits_1_2
    & btb_bank_1_2_data_isJmp | hits_1_3 & btb_bank_1_3_data_isJmp | hits_1_4
    & btb_bank_1_4_data_isJmp | hits_1_5 & btb_bank_1_5_data_isJmp | hits_1_6
    & btb_bank_1_6_data_isJmp | hits_1_7 & btb_bank_1_7_data_isJmp | hits_1_8
    & btb_bank_1_8_data_isJmp | hits_1_9 & btb_bank_1_9_data_isJmp | hits_1_10
    & btb_bank_1_10_data_isJmp | hits_1_11 & btb_bank_1_11_data_isJmp | hits_1_12
    & btb_bank_1_12_data_isJmp | hits_1_13 & btb_bank_1_13_data_isJmp | hits_1_14
    & btb_bank_1_14_data_isJmp | hits_1_15 & btb_bank_1_15_data_isJmp | hits_1_16
    & btb_bank_1_16_data_isJmp | hits_1_17 & btb_bank_1_17_data_isJmp | hits_1_18
    & btb_bank_1_18_data_isJmp | hits_1_19 & btb_bank_1_19_data_isJmp | hits_1_20
    & btb_bank_1_20_data_isJmp | hits_1_21 & btb_bank_1_21_data_isJmp | hits_1_22
    & btb_bank_1_22_data_isJmp | hits_1_23 & btb_bank_1_23_data_isJmp | hits_1_24
    & btb_bank_1_24_data_isJmp | hits_1_25 & btb_bank_1_25_data_isJmp | hits_1_26
    & btb_bank_1_26_data_isJmp | hits_1_27 & btb_bank_1_27_data_isJmp | hits_1_28
    & btb_bank_1_28_data_isJmp | hits_1_29 & btb_bank_1_29_data_isJmp | hits_1_30
    & btb_bank_1_30_data_isJmp | hits_1_31 & btb_bank_1_31_data_isJmp;
  wire        rdata_1_isRet =
    hits_1_0 & btb_bank_1_0_data_isRet | hits_1_1 & btb_bank_1_1_data_isRet | hits_1_2
    & btb_bank_1_2_data_isRet | hits_1_3 & btb_bank_1_3_data_isRet | hits_1_4
    & btb_bank_1_4_data_isRet | hits_1_5 & btb_bank_1_5_data_isRet | hits_1_6
    & btb_bank_1_6_data_isRet | hits_1_7 & btb_bank_1_7_data_isRet | hits_1_8
    & btb_bank_1_8_data_isRet | hits_1_9 & btb_bank_1_9_data_isRet | hits_1_10
    & btb_bank_1_10_data_isRet | hits_1_11 & btb_bank_1_11_data_isRet | hits_1_12
    & btb_bank_1_12_data_isRet | hits_1_13 & btb_bank_1_13_data_isRet | hits_1_14
    & btb_bank_1_14_data_isRet | hits_1_15 & btb_bank_1_15_data_isRet | hits_1_16
    & btb_bank_1_16_data_isRet | hits_1_17 & btb_bank_1_17_data_isRet | hits_1_18
    & btb_bank_1_18_data_isRet | hits_1_19 & btb_bank_1_19_data_isRet | hits_1_20
    & btb_bank_1_20_data_isRet | hits_1_21 & btb_bank_1_21_data_isRet | hits_1_22
    & btb_bank_1_22_data_isRet | hits_1_23 & btb_bank_1_23_data_isRet | hits_1_24
    & btb_bank_1_24_data_isRet | hits_1_25 & btb_bank_1_25_data_isRet | hits_1_26
    & btb_bank_1_26_data_isRet | hits_1_27 & btb_bank_1_27_data_isRet | hits_1_28
    & btb_bank_1_28_data_isRet | hits_1_29 & btb_bank_1_29_data_isRet | hits_1_30
    & btb_bank_1_30_data_isRet | hits_1_31 & btb_bank_1_31_data_isRet;
  wire        rdata_1_isCall =
    hits_1_0 & btb_bank_1_0_data_isCall | hits_1_1 & btb_bank_1_1_data_isCall | hits_1_2
    & btb_bank_1_2_data_isCall | hits_1_3 & btb_bank_1_3_data_isCall | hits_1_4
    & btb_bank_1_4_data_isCall | hits_1_5 & btb_bank_1_5_data_isCall | hits_1_6
    & btb_bank_1_6_data_isCall | hits_1_7 & btb_bank_1_7_data_isCall | hits_1_8
    & btb_bank_1_8_data_isCall | hits_1_9 & btb_bank_1_9_data_isCall | hits_1_10
    & btb_bank_1_10_data_isCall | hits_1_11 & btb_bank_1_11_data_isCall | hits_1_12
    & btb_bank_1_12_data_isCall | hits_1_13 & btb_bank_1_13_data_isCall | hits_1_14
    & btb_bank_1_14_data_isCall | hits_1_15 & btb_bank_1_15_data_isCall | hits_1_16
    & btb_bank_1_16_data_isCall | hits_1_17 & btb_bank_1_17_data_isCall | hits_1_18
    & btb_bank_1_18_data_isCall | hits_1_19 & btb_bank_1_19_data_isCall | hits_1_20
    & btb_bank_1_20_data_isCall | hits_1_21 & btb_bank_1_21_data_isCall | hits_1_22
    & btb_bank_1_22_data_isCall | hits_1_23 & btb_bank_1_23_data_isCall | hits_1_24
    & btb_bank_1_24_data_isCall | hits_1_25 & btb_bank_1_25_data_isCall | hits_1_26
    & btb_bank_1_26_data_isCall | hits_1_27 & btb_bank_1_27_data_isCall | hits_1_28
    & btb_bank_1_28_data_isCall | hits_1_29 & btb_bank_1_29_data_isCall | hits_1_30
    & btb_bank_1_30_data_isCall | hits_1_31 & btb_bank_1_31_data_isCall;
  wire [29:0] rdata_1_target =
    (hits_1_0 ? btb_bank_1_0_data_target : 30'h0)
    | (hits_1_1 ? btb_bank_1_1_data_target : 30'h0)
    | (hits_1_2 ? btb_bank_1_2_data_target : 30'h0)
    | (hits_1_3 ? btb_bank_1_3_data_target : 30'h0)
    | (hits_1_4 ? btb_bank_1_4_data_target : 30'h0)
    | (hits_1_5 ? btb_bank_1_5_data_target : 30'h0)
    | (hits_1_6 ? btb_bank_1_6_data_target : 30'h0)
    | (hits_1_7 ? btb_bank_1_7_data_target : 30'h0)
    | (hits_1_8 ? btb_bank_1_8_data_target : 30'h0)
    | (hits_1_9 ? btb_bank_1_9_data_target : 30'h0)
    | (hits_1_10 ? btb_bank_1_10_data_target : 30'h0)
    | (hits_1_11 ? btb_bank_1_11_data_target : 30'h0)
    | (hits_1_12 ? btb_bank_1_12_data_target : 30'h0)
    | (hits_1_13 ? btb_bank_1_13_data_target : 30'h0)
    | (hits_1_14 ? btb_bank_1_14_data_target : 30'h0)
    | (hits_1_15 ? btb_bank_1_15_data_target : 30'h0)
    | (hits_1_16 ? btb_bank_1_16_data_target : 30'h0)
    | (hits_1_17 ? btb_bank_1_17_data_target : 30'h0)
    | (hits_1_18 ? btb_bank_1_18_data_target : 30'h0)
    | (hits_1_19 ? btb_bank_1_19_data_target : 30'h0)
    | (hits_1_20 ? btb_bank_1_20_data_target : 30'h0)
    | (hits_1_21 ? btb_bank_1_21_data_target : 30'h0)
    | (hits_1_22 ? btb_bank_1_22_data_target : 30'h0)
    | (hits_1_23 ? btb_bank_1_23_data_target : 30'h0)
    | (hits_1_24 ? btb_bank_1_24_data_target : 30'h0)
    | (hits_1_25 ? btb_bank_1_25_data_target : 30'h0)
    | (hits_1_26 ? btb_bank_1_26_data_target : 30'h0)
    | (hits_1_27 ? btb_bank_1_27_data_target : 30'h0)
    | (hits_1_28 ? btb_bank_1_28_data_target : 30'h0)
    | (hits_1_29 ? btb_bank_1_29_data_target : 30'h0)
    | (hits_1_30 ? btb_bank_1_30_data_target : 30'h0)
    | (hits_1_31 ? btb_bank_1_31_data_target : 30'h0);
  wire [4:0]  lfsr =
    {_lfsr_prng_io_out_4,
     _lfsr_prng_io_out_3,
     _lfsr_prng_io_out_2,
     _lfsr_prng_io_out_1,
     _lfsr_prng_io_out_0};
  wire        wen_0 = io_wr_wen & ~(io_wr_pc[0]);
  wire        wen_1 = io_wr_wen & io_wr_pc[0];
  wire        hits_2_1 = btb_bank_0_1_valid & btb_bank_0_1_tag == io_wr_pc[29:1];
  wire        hits_2_2 = btb_bank_0_2_valid & btb_bank_0_2_tag == io_wr_pc[29:1];
  wire        hits_2_3 = btb_bank_0_3_valid & btb_bank_0_3_tag == io_wr_pc[29:1];
  wire        hits_2_4 = btb_bank_0_4_valid & btb_bank_0_4_tag == io_wr_pc[29:1];
  wire        hits_2_5 = btb_bank_0_5_valid & btb_bank_0_5_tag == io_wr_pc[29:1];
  wire        hits_2_6 = btb_bank_0_6_valid & btb_bank_0_6_tag == io_wr_pc[29:1];
  wire        hits_2_7 = btb_bank_0_7_valid & btb_bank_0_7_tag == io_wr_pc[29:1];
  wire        hits_2_8 = btb_bank_0_8_valid & btb_bank_0_8_tag == io_wr_pc[29:1];
  wire        hits_2_9 = btb_bank_0_9_valid & btb_bank_0_9_tag == io_wr_pc[29:1];
  wire        hits_2_10 = btb_bank_0_10_valid & btb_bank_0_10_tag == io_wr_pc[29:1];
  wire        hits_2_11 = btb_bank_0_11_valid & btb_bank_0_11_tag == io_wr_pc[29:1];
  wire        hits_2_12 = btb_bank_0_12_valid & btb_bank_0_12_tag == io_wr_pc[29:1];
  wire        hits_2_13 = btb_bank_0_13_valid & btb_bank_0_13_tag == io_wr_pc[29:1];
  wire        hits_2_14 = btb_bank_0_14_valid & btb_bank_0_14_tag == io_wr_pc[29:1];
  wire        hits_2_15 = btb_bank_0_15_valid & btb_bank_0_15_tag == io_wr_pc[29:1];
  wire        hits_2_16 = btb_bank_0_16_valid & btb_bank_0_16_tag == io_wr_pc[29:1];
  wire        hits_2_17 = btb_bank_0_17_valid & btb_bank_0_17_tag == io_wr_pc[29:1];
  wire        hits_2_18 = btb_bank_0_18_valid & btb_bank_0_18_tag == io_wr_pc[29:1];
  wire        hits_2_19 = btb_bank_0_19_valid & btb_bank_0_19_tag == io_wr_pc[29:1];
  wire        hits_2_20 = btb_bank_0_20_valid & btb_bank_0_20_tag == io_wr_pc[29:1];
  wire        hits_2_21 = btb_bank_0_21_valid & btb_bank_0_21_tag == io_wr_pc[29:1];
  wire        hits_2_22 = btb_bank_0_22_valid & btb_bank_0_22_tag == io_wr_pc[29:1];
  wire        hits_2_23 = btb_bank_0_23_valid & btb_bank_0_23_tag == io_wr_pc[29:1];
  wire        hits_2_24 = btb_bank_0_24_valid & btb_bank_0_24_tag == io_wr_pc[29:1];
  wire        hits_2_25 = btb_bank_0_25_valid & btb_bank_0_25_tag == io_wr_pc[29:1];
  wire        hits_2_26 = btb_bank_0_26_valid & btb_bank_0_26_tag == io_wr_pc[29:1];
  wire        hits_2_27 = btb_bank_0_27_valid & btb_bank_0_27_tag == io_wr_pc[29:1];
  wire        hits_2_28 = btb_bank_0_28_valid & btb_bank_0_28_tag == io_wr_pc[29:1];
  wire        hits_2_29 = btb_bank_0_29_valid & btb_bank_0_29_tag == io_wr_pc[29:1];
  wire        hits_2_30 = btb_bank_0_30_valid & btb_bank_0_30_tag == io_wr_pc[29:1];
  wire        hits_2_31 = btb_bank_0_31_valid & btb_bank_0_31_tag == io_wr_pc[29:1];
  wire [31:0] _hitIdx_T =
    {hits_2_31,
     hits_2_30,
     hits_2_29,
     hits_2_28,
     hits_2_27,
     hits_2_26,
     hits_2_25,
     hits_2_24,
     hits_2_23,
     hits_2_22,
     hits_2_21,
     hits_2_20,
     hits_2_19,
     hits_2_18,
     hits_2_17,
     hits_2_16,
     hits_2_15,
     hits_2_14,
     hits_2_13,
     hits_2_12,
     hits_2_11,
     hits_2_10,
     hits_2_9,
     hits_2_8,
     hits_2_7,
     hits_2_6,
     hits_2_5,
     hits_2_4,
     hits_2_3,
     hits_2_2,
     hits_2_1,
     btb_bank_0_0_valid & btb_bank_0_0_tag == io_wr_pc[29:1]};
  wire [14:0] _hitIdx_T_2 =
    {hits_2_31,
     hits_2_30,
     hits_2_29,
     hits_2_28,
     hits_2_27,
     hits_2_26,
     hits_2_25,
     hits_2_24,
     hits_2_23,
     hits_2_22,
     hits_2_21,
     hits_2_20,
     hits_2_19,
     hits_2_18,
     hits_2_17}
    | {hits_2_15,
       hits_2_14,
       hits_2_13,
       hits_2_12,
       hits_2_11,
       hits_2_10,
       hits_2_9,
       hits_2_8,
       hits_2_7,
       hits_2_6,
       hits_2_5,
       hits_2_4,
       hits_2_3,
       hits_2_2,
       hits_2_1};
  wire [6:0]  _hitIdx_T_4 = _hitIdx_T_2[14:8] | _hitIdx_T_2[6:0];
  wire [2:0]  _hitIdx_T_6 = _hitIdx_T_4[6:4] | _hitIdx_T_4[2:0];
  wire [4:0]  hitIdx =
    {|{hits_2_31,
       hits_2_30,
       hits_2_29,
       hits_2_28,
       hits_2_27,
       hits_2_26,
       hits_2_25,
       hits_2_24,
       hits_2_23,
       hits_2_22,
       hits_2_21,
       hits_2_20,
       hits_2_19,
       hits_2_18,
       hits_2_17,
       hits_2_16},
     |(_hitIdx_T_2[14:7]),
     |(_hitIdx_T_4[6:3]),
     |(_hitIdx_T_6[2:1]),
     _hitIdx_T_6[2] | _hitIdx_T_6[0]};
  wire        _GEN = wen_0 & (|_hitIdx_T);
  wire        _GEN_0 = wen_0 & ~(|_hitIdx_T);
  wire        _GEN_1 = lfsr == 5'h0;
  wire        _GEN_2 = _GEN_0 & _GEN_1;
  wire        _GEN_3 = lfsr == 5'h1;
  wire        _GEN_4 = _GEN_0 & _GEN_3;
  wire        _GEN_5 = lfsr == 5'h2;
  wire        _GEN_6 = _GEN_0 & _GEN_5;
  wire        _GEN_7 = lfsr == 5'h3;
  wire        _GEN_8 = _GEN_0 & _GEN_7;
  wire        _GEN_9 = lfsr == 5'h4;
  wire        _GEN_10 = _GEN_0 & _GEN_9;
  wire        _GEN_11 = lfsr == 5'h5;
  wire        _GEN_12 = _GEN_0 & _GEN_11;
  wire        _GEN_13 = lfsr == 5'h6;
  wire        _GEN_14 = _GEN_0 & _GEN_13;
  wire        _GEN_15 = lfsr == 5'h7;
  wire        _GEN_16 = _GEN_0 & _GEN_15;
  wire        _GEN_17 = lfsr == 5'h8;
  wire        _GEN_18 = _GEN_0 & _GEN_17;
  wire        _GEN_19 = lfsr == 5'h9;
  wire        _GEN_20 = _GEN_0 & _GEN_19;
  wire        _GEN_21 = lfsr == 5'hA;
  wire        _GEN_22 = _GEN_0 & _GEN_21;
  wire        _GEN_23 = lfsr == 5'hB;
  wire        _GEN_24 = _GEN_0 & _GEN_23;
  wire        _GEN_25 = lfsr == 5'hC;
  wire        _GEN_26 = _GEN_0 & _GEN_25;
  wire        _GEN_27 = lfsr == 5'hD;
  wire        _GEN_28 = _GEN_0 & _GEN_27;
  wire        _GEN_29 = lfsr == 5'hE;
  wire        _GEN_30 = _GEN_0 & _GEN_29;
  wire        _GEN_31 = lfsr == 5'hF;
  wire        _GEN_32 = _GEN_0 & _GEN_31;
  wire        _GEN_33 = lfsr == 5'h10;
  wire        _GEN_34 = _GEN_0 & _GEN_33;
  wire        _GEN_35 = lfsr == 5'h11;
  wire        _GEN_36 = _GEN_0 & _GEN_35;
  wire        _GEN_37 = lfsr == 5'h12;
  wire        _GEN_38 = _GEN_0 & _GEN_37;
  wire        _GEN_39 = lfsr == 5'h13;
  wire        _GEN_40 = _GEN_0 & _GEN_39;
  wire        _GEN_41 = lfsr == 5'h14;
  wire        _GEN_42 = _GEN_0 & _GEN_41;
  wire        _GEN_43 = lfsr == 5'h15;
  wire        _GEN_44 = _GEN_0 & _GEN_43;
  wire        _GEN_45 = lfsr == 5'h16;
  wire        _GEN_46 = _GEN_0 & _GEN_45;
  wire        _GEN_47 = lfsr == 5'h17;
  wire        _GEN_48 = _GEN_0 & _GEN_47;
  wire        _GEN_49 = lfsr == 5'h18;
  wire        _GEN_50 = _GEN_0 & _GEN_49;
  wire        _GEN_51 = lfsr == 5'h19;
  wire        _GEN_52 = _GEN_0 & _GEN_51;
  wire        _GEN_53 = lfsr == 5'h1A;
  wire        _GEN_54 = _GEN_0 & _GEN_53;
  wire        _GEN_55 = lfsr == 5'h1B;
  wire        _GEN_56 = _GEN_0 & _GEN_55;
  wire        _GEN_57 = lfsr == 5'h1C;
  wire        _GEN_58 = _GEN_0 & _GEN_57;
  wire        _GEN_59 = lfsr == 5'h1D;
  wire        _GEN_60 = _GEN_0 & _GEN_59;
  wire        _GEN_61 = lfsr == 5'h1E;
  wire        _GEN_62 = _GEN_0 & _GEN_61;
  wire        _GEN_63 = _GEN_0 & (&lfsr);
  wire        hits_3_1 = btb_bank_1_1_valid & btb_bank_1_1_tag == io_wr_pc[29:1];
  wire        hits_3_2 = btb_bank_1_2_valid & btb_bank_1_2_tag == io_wr_pc[29:1];
  wire        hits_3_3 = btb_bank_1_3_valid & btb_bank_1_3_tag == io_wr_pc[29:1];
  wire        hits_3_4 = btb_bank_1_4_valid & btb_bank_1_4_tag == io_wr_pc[29:1];
  wire        hits_3_5 = btb_bank_1_5_valid & btb_bank_1_5_tag == io_wr_pc[29:1];
  wire        hits_3_6 = btb_bank_1_6_valid & btb_bank_1_6_tag == io_wr_pc[29:1];
  wire        hits_3_7 = btb_bank_1_7_valid & btb_bank_1_7_tag == io_wr_pc[29:1];
  wire        hits_3_8 = btb_bank_1_8_valid & btb_bank_1_8_tag == io_wr_pc[29:1];
  wire        hits_3_9 = btb_bank_1_9_valid & btb_bank_1_9_tag == io_wr_pc[29:1];
  wire        hits_3_10 = btb_bank_1_10_valid & btb_bank_1_10_tag == io_wr_pc[29:1];
  wire        hits_3_11 = btb_bank_1_11_valid & btb_bank_1_11_tag == io_wr_pc[29:1];
  wire        hits_3_12 = btb_bank_1_12_valid & btb_bank_1_12_tag == io_wr_pc[29:1];
  wire        hits_3_13 = btb_bank_1_13_valid & btb_bank_1_13_tag == io_wr_pc[29:1];
  wire        hits_3_14 = btb_bank_1_14_valid & btb_bank_1_14_tag == io_wr_pc[29:1];
  wire        hits_3_15 = btb_bank_1_15_valid & btb_bank_1_15_tag == io_wr_pc[29:1];
  wire        hits_3_16 = btb_bank_1_16_valid & btb_bank_1_16_tag == io_wr_pc[29:1];
  wire        hits_3_17 = btb_bank_1_17_valid & btb_bank_1_17_tag == io_wr_pc[29:1];
  wire        hits_3_18 = btb_bank_1_18_valid & btb_bank_1_18_tag == io_wr_pc[29:1];
  wire        hits_3_19 = btb_bank_1_19_valid & btb_bank_1_19_tag == io_wr_pc[29:1];
  wire        hits_3_20 = btb_bank_1_20_valid & btb_bank_1_20_tag == io_wr_pc[29:1];
  wire        hits_3_21 = btb_bank_1_21_valid & btb_bank_1_21_tag == io_wr_pc[29:1];
  wire        hits_3_22 = btb_bank_1_22_valid & btb_bank_1_22_tag == io_wr_pc[29:1];
  wire        hits_3_23 = btb_bank_1_23_valid & btb_bank_1_23_tag == io_wr_pc[29:1];
  wire        hits_3_24 = btb_bank_1_24_valid & btb_bank_1_24_tag == io_wr_pc[29:1];
  wire        hits_3_25 = btb_bank_1_25_valid & btb_bank_1_25_tag == io_wr_pc[29:1];
  wire        hits_3_26 = btb_bank_1_26_valid & btb_bank_1_26_tag == io_wr_pc[29:1];
  wire        hits_3_27 = btb_bank_1_27_valid & btb_bank_1_27_tag == io_wr_pc[29:1];
  wire        hits_3_28 = btb_bank_1_28_valid & btb_bank_1_28_tag == io_wr_pc[29:1];
  wire        hits_3_29 = btb_bank_1_29_valid & btb_bank_1_29_tag == io_wr_pc[29:1];
  wire        hits_3_30 = btb_bank_1_30_valid & btb_bank_1_30_tag == io_wr_pc[29:1];
  wire        hits_3_31 = btb_bank_1_31_valid & btb_bank_1_31_tag == io_wr_pc[29:1];
  wire [31:0] _hitIdx_T_13 =
    {hits_3_31,
     hits_3_30,
     hits_3_29,
     hits_3_28,
     hits_3_27,
     hits_3_26,
     hits_3_25,
     hits_3_24,
     hits_3_23,
     hits_3_22,
     hits_3_21,
     hits_3_20,
     hits_3_19,
     hits_3_18,
     hits_3_17,
     hits_3_16,
     hits_3_15,
     hits_3_14,
     hits_3_13,
     hits_3_12,
     hits_3_11,
     hits_3_10,
     hits_3_9,
     hits_3_8,
     hits_3_7,
     hits_3_6,
     hits_3_5,
     hits_3_4,
     hits_3_3,
     hits_3_2,
     hits_3_1,
     btb_bank_1_0_valid & btb_bank_1_0_tag == io_wr_pc[29:1]};
  wire [14:0] _hitIdx_T_15 =
    {hits_3_31,
     hits_3_30,
     hits_3_29,
     hits_3_28,
     hits_3_27,
     hits_3_26,
     hits_3_25,
     hits_3_24,
     hits_3_23,
     hits_3_22,
     hits_3_21,
     hits_3_20,
     hits_3_19,
     hits_3_18,
     hits_3_17}
    | {hits_3_15,
       hits_3_14,
       hits_3_13,
       hits_3_12,
       hits_3_11,
       hits_3_10,
       hits_3_9,
       hits_3_8,
       hits_3_7,
       hits_3_6,
       hits_3_5,
       hits_3_4,
       hits_3_3,
       hits_3_2,
       hits_3_1};
  wire [6:0]  _hitIdx_T_17 = _hitIdx_T_15[14:8] | _hitIdx_T_15[6:0];
  wire [2:0]  _hitIdx_T_19 = _hitIdx_T_17[6:4] | _hitIdx_T_17[2:0];
  wire [4:0]  hitIdx_1 =
    {|{hits_3_31,
       hits_3_30,
       hits_3_29,
       hits_3_28,
       hits_3_27,
       hits_3_26,
       hits_3_25,
       hits_3_24,
       hits_3_23,
       hits_3_22,
       hits_3_21,
       hits_3_20,
       hits_3_19,
       hits_3_18,
       hits_3_17,
       hits_3_16},
     |(_hitIdx_T_15[14:7]),
     |(_hitIdx_T_17[6:3]),
     |(_hitIdx_T_19[2:1]),
     _hitIdx_T_19[2] | _hitIdx_T_19[0]};
  wire        _GEN_64 = wen_1 & (|_hitIdx_T_13);
  wire        _GEN_65 = wen_1 & ~(|_hitIdx_T_13);
  wire        _GEN_66 = _GEN_65 & _GEN_1;
  wire        _GEN_67 = _GEN_65 & _GEN_3;
  wire        _GEN_68 = _GEN_65 & _GEN_5;
  wire        _GEN_69 = _GEN_65 & _GEN_7;
  wire        _GEN_70 = _GEN_65 & _GEN_9;
  wire        _GEN_71 = _GEN_65 & _GEN_11;
  wire        _GEN_72 = _GEN_65 & _GEN_13;
  wire        _GEN_73 = _GEN_65 & _GEN_15;
  wire        _GEN_74 = _GEN_65 & _GEN_17;
  wire        _GEN_75 = _GEN_65 & _GEN_19;
  wire        _GEN_76 = _GEN_65 & _GEN_21;
  wire        _GEN_77 = _GEN_65 & _GEN_23;
  wire        _GEN_78 = _GEN_65 & _GEN_25;
  wire        _GEN_79 = _GEN_65 & _GEN_27;
  wire        _GEN_80 = _GEN_65 & _GEN_29;
  wire        _GEN_81 = _GEN_65 & _GEN_31;
  wire        _GEN_82 = _GEN_65 & _GEN_33;
  wire        _GEN_83 = _GEN_65 & _GEN_35;
  wire        _GEN_84 = _GEN_65 & _GEN_37;
  wire        _GEN_85 = _GEN_65 & _GEN_39;
  wire        _GEN_86 = _GEN_65 & _GEN_41;
  wire        _GEN_87 = _GEN_65 & _GEN_43;
  wire        _GEN_88 = _GEN_65 & _GEN_45;
  wire        _GEN_89 = _GEN_65 & _GEN_47;
  wire        _GEN_90 = _GEN_65 & _GEN_49;
  wire        _GEN_91 = _GEN_65 & _GEN_51;
  wire        _GEN_92 = _GEN_65 & _GEN_53;
  wire        _GEN_93 = _GEN_65 & _GEN_55;
  wire        _GEN_94 = _GEN_65 & _GEN_57;
  wire        _GEN_95 = _GEN_65 & _GEN_59;
  wire        _GEN_96 = _GEN_65 & _GEN_61;
  wire        _GEN_97 = _GEN_65 & (&lfsr);
  always @(posedge clock) begin
    if (reset) begin
      btb_bank_0_0_valid <= 1'h0;
      btb_bank_0_0_tag <= 29'h0;
      btb_bank_0_0_data_target <= 30'h0;
      btb_bank_0_0_data_isCall <= 1'h0;
      btb_bank_0_0_data_isRet <= 1'h0;
      btb_bank_0_0_data_isJmp <= 1'h0;
      btb_bank_0_1_valid <= 1'h0;
      btb_bank_0_1_tag <= 29'h0;
      btb_bank_0_1_data_target <= 30'h0;
      btb_bank_0_1_data_isCall <= 1'h0;
      btb_bank_0_1_data_isRet <= 1'h0;
      btb_bank_0_1_data_isJmp <= 1'h0;
      btb_bank_0_2_valid <= 1'h0;
      btb_bank_0_2_tag <= 29'h0;
      btb_bank_0_2_data_target <= 30'h0;
      btb_bank_0_2_data_isCall <= 1'h0;
      btb_bank_0_2_data_isRet <= 1'h0;
      btb_bank_0_2_data_isJmp <= 1'h0;
      btb_bank_0_3_valid <= 1'h0;
      btb_bank_0_3_tag <= 29'h0;
      btb_bank_0_3_data_target <= 30'h0;
      btb_bank_0_3_data_isCall <= 1'h0;
      btb_bank_0_3_data_isRet <= 1'h0;
      btb_bank_0_3_data_isJmp <= 1'h0;
      btb_bank_0_4_valid <= 1'h0;
      btb_bank_0_4_tag <= 29'h0;
      btb_bank_0_4_data_target <= 30'h0;
      btb_bank_0_4_data_isCall <= 1'h0;
      btb_bank_0_4_data_isRet <= 1'h0;
      btb_bank_0_4_data_isJmp <= 1'h0;
      btb_bank_0_5_valid <= 1'h0;
      btb_bank_0_5_tag <= 29'h0;
      btb_bank_0_5_data_target <= 30'h0;
      btb_bank_0_5_data_isCall <= 1'h0;
      btb_bank_0_5_data_isRet <= 1'h0;
      btb_bank_0_5_data_isJmp <= 1'h0;
      btb_bank_0_6_valid <= 1'h0;
      btb_bank_0_6_tag <= 29'h0;
      btb_bank_0_6_data_target <= 30'h0;
      btb_bank_0_6_data_isCall <= 1'h0;
      btb_bank_0_6_data_isRet <= 1'h0;
      btb_bank_0_6_data_isJmp <= 1'h0;
      btb_bank_0_7_valid <= 1'h0;
      btb_bank_0_7_tag <= 29'h0;
      btb_bank_0_7_data_target <= 30'h0;
      btb_bank_0_7_data_isCall <= 1'h0;
      btb_bank_0_7_data_isRet <= 1'h0;
      btb_bank_0_7_data_isJmp <= 1'h0;
      btb_bank_0_8_valid <= 1'h0;
      btb_bank_0_8_tag <= 29'h0;
      btb_bank_0_8_data_target <= 30'h0;
      btb_bank_0_8_data_isCall <= 1'h0;
      btb_bank_0_8_data_isRet <= 1'h0;
      btb_bank_0_8_data_isJmp <= 1'h0;
      btb_bank_0_9_valid <= 1'h0;
      btb_bank_0_9_tag <= 29'h0;
      btb_bank_0_9_data_target <= 30'h0;
      btb_bank_0_9_data_isCall <= 1'h0;
      btb_bank_0_9_data_isRet <= 1'h0;
      btb_bank_0_9_data_isJmp <= 1'h0;
      btb_bank_0_10_valid <= 1'h0;
      btb_bank_0_10_tag <= 29'h0;
      btb_bank_0_10_data_target <= 30'h0;
      btb_bank_0_10_data_isCall <= 1'h0;
      btb_bank_0_10_data_isRet <= 1'h0;
      btb_bank_0_10_data_isJmp <= 1'h0;
      btb_bank_0_11_valid <= 1'h0;
      btb_bank_0_11_tag <= 29'h0;
      btb_bank_0_11_data_target <= 30'h0;
      btb_bank_0_11_data_isCall <= 1'h0;
      btb_bank_0_11_data_isRet <= 1'h0;
      btb_bank_0_11_data_isJmp <= 1'h0;
      btb_bank_0_12_valid <= 1'h0;
      btb_bank_0_12_tag <= 29'h0;
      btb_bank_0_12_data_target <= 30'h0;
      btb_bank_0_12_data_isCall <= 1'h0;
      btb_bank_0_12_data_isRet <= 1'h0;
      btb_bank_0_12_data_isJmp <= 1'h0;
      btb_bank_0_13_valid <= 1'h0;
      btb_bank_0_13_tag <= 29'h0;
      btb_bank_0_13_data_target <= 30'h0;
      btb_bank_0_13_data_isCall <= 1'h0;
      btb_bank_0_13_data_isRet <= 1'h0;
      btb_bank_0_13_data_isJmp <= 1'h0;
      btb_bank_0_14_valid <= 1'h0;
      btb_bank_0_14_tag <= 29'h0;
      btb_bank_0_14_data_target <= 30'h0;
      btb_bank_0_14_data_isCall <= 1'h0;
      btb_bank_0_14_data_isRet <= 1'h0;
      btb_bank_0_14_data_isJmp <= 1'h0;
      btb_bank_0_15_valid <= 1'h0;
      btb_bank_0_15_tag <= 29'h0;
      btb_bank_0_15_data_target <= 30'h0;
      btb_bank_0_15_data_isCall <= 1'h0;
      btb_bank_0_15_data_isRet <= 1'h0;
      btb_bank_0_15_data_isJmp <= 1'h0;
      btb_bank_0_16_valid <= 1'h0;
      btb_bank_0_16_tag <= 29'h0;
      btb_bank_0_16_data_target <= 30'h0;
      btb_bank_0_16_data_isCall <= 1'h0;
      btb_bank_0_16_data_isRet <= 1'h0;
      btb_bank_0_16_data_isJmp <= 1'h0;
      btb_bank_0_17_valid <= 1'h0;
      btb_bank_0_17_tag <= 29'h0;
      btb_bank_0_17_data_target <= 30'h0;
      btb_bank_0_17_data_isCall <= 1'h0;
      btb_bank_0_17_data_isRet <= 1'h0;
      btb_bank_0_17_data_isJmp <= 1'h0;
      btb_bank_0_18_valid <= 1'h0;
      btb_bank_0_18_tag <= 29'h0;
      btb_bank_0_18_data_target <= 30'h0;
      btb_bank_0_18_data_isCall <= 1'h0;
      btb_bank_0_18_data_isRet <= 1'h0;
      btb_bank_0_18_data_isJmp <= 1'h0;
      btb_bank_0_19_valid <= 1'h0;
      btb_bank_0_19_tag <= 29'h0;
      btb_bank_0_19_data_target <= 30'h0;
      btb_bank_0_19_data_isCall <= 1'h0;
      btb_bank_0_19_data_isRet <= 1'h0;
      btb_bank_0_19_data_isJmp <= 1'h0;
      btb_bank_0_20_valid <= 1'h0;
      btb_bank_0_20_tag <= 29'h0;
      btb_bank_0_20_data_target <= 30'h0;
      btb_bank_0_20_data_isCall <= 1'h0;
      btb_bank_0_20_data_isRet <= 1'h0;
      btb_bank_0_20_data_isJmp <= 1'h0;
      btb_bank_0_21_valid <= 1'h0;
      btb_bank_0_21_tag <= 29'h0;
      btb_bank_0_21_data_target <= 30'h0;
      btb_bank_0_21_data_isCall <= 1'h0;
      btb_bank_0_21_data_isRet <= 1'h0;
      btb_bank_0_21_data_isJmp <= 1'h0;
      btb_bank_0_22_valid <= 1'h0;
      btb_bank_0_22_tag <= 29'h0;
      btb_bank_0_22_data_target <= 30'h0;
      btb_bank_0_22_data_isCall <= 1'h0;
      btb_bank_0_22_data_isRet <= 1'h0;
      btb_bank_0_22_data_isJmp <= 1'h0;
      btb_bank_0_23_valid <= 1'h0;
      btb_bank_0_23_tag <= 29'h0;
      btb_bank_0_23_data_target <= 30'h0;
      btb_bank_0_23_data_isCall <= 1'h0;
      btb_bank_0_23_data_isRet <= 1'h0;
      btb_bank_0_23_data_isJmp <= 1'h0;
      btb_bank_0_24_valid <= 1'h0;
      btb_bank_0_24_tag <= 29'h0;
      btb_bank_0_24_data_target <= 30'h0;
      btb_bank_0_24_data_isCall <= 1'h0;
      btb_bank_0_24_data_isRet <= 1'h0;
      btb_bank_0_24_data_isJmp <= 1'h0;
      btb_bank_0_25_valid <= 1'h0;
      btb_bank_0_25_tag <= 29'h0;
      btb_bank_0_25_data_target <= 30'h0;
      btb_bank_0_25_data_isCall <= 1'h0;
      btb_bank_0_25_data_isRet <= 1'h0;
      btb_bank_0_25_data_isJmp <= 1'h0;
      btb_bank_0_26_valid <= 1'h0;
      btb_bank_0_26_tag <= 29'h0;
      btb_bank_0_26_data_target <= 30'h0;
      btb_bank_0_26_data_isCall <= 1'h0;
      btb_bank_0_26_data_isRet <= 1'h0;
      btb_bank_0_26_data_isJmp <= 1'h0;
      btb_bank_0_27_valid <= 1'h0;
      btb_bank_0_27_tag <= 29'h0;
      btb_bank_0_27_data_target <= 30'h0;
      btb_bank_0_27_data_isCall <= 1'h0;
      btb_bank_0_27_data_isRet <= 1'h0;
      btb_bank_0_27_data_isJmp <= 1'h0;
      btb_bank_0_28_valid <= 1'h0;
      btb_bank_0_28_tag <= 29'h0;
      btb_bank_0_28_data_target <= 30'h0;
      btb_bank_0_28_data_isCall <= 1'h0;
      btb_bank_0_28_data_isRet <= 1'h0;
      btb_bank_0_28_data_isJmp <= 1'h0;
      btb_bank_0_29_valid <= 1'h0;
      btb_bank_0_29_tag <= 29'h0;
      btb_bank_0_29_data_target <= 30'h0;
      btb_bank_0_29_data_isCall <= 1'h0;
      btb_bank_0_29_data_isRet <= 1'h0;
      btb_bank_0_29_data_isJmp <= 1'h0;
      btb_bank_0_30_valid <= 1'h0;
      btb_bank_0_30_tag <= 29'h0;
      btb_bank_0_30_data_target <= 30'h0;
      btb_bank_0_30_data_isCall <= 1'h0;
      btb_bank_0_30_data_isRet <= 1'h0;
      btb_bank_0_30_data_isJmp <= 1'h0;
      btb_bank_0_31_valid <= 1'h0;
      btb_bank_0_31_tag <= 29'h0;
      btb_bank_0_31_data_target <= 30'h0;
      btb_bank_0_31_data_isCall <= 1'h0;
      btb_bank_0_31_data_isRet <= 1'h0;
      btb_bank_0_31_data_isJmp <= 1'h0;
      btb_bank_1_0_valid <= 1'h0;
      btb_bank_1_0_tag <= 29'h0;
      btb_bank_1_0_data_target <= 30'h0;
      btb_bank_1_0_data_isCall <= 1'h0;
      btb_bank_1_0_data_isRet <= 1'h0;
      btb_bank_1_0_data_isJmp <= 1'h0;
      btb_bank_1_1_valid <= 1'h0;
      btb_bank_1_1_tag <= 29'h0;
      btb_bank_1_1_data_target <= 30'h0;
      btb_bank_1_1_data_isCall <= 1'h0;
      btb_bank_1_1_data_isRet <= 1'h0;
      btb_bank_1_1_data_isJmp <= 1'h0;
      btb_bank_1_2_valid <= 1'h0;
      btb_bank_1_2_tag <= 29'h0;
      btb_bank_1_2_data_target <= 30'h0;
      btb_bank_1_2_data_isCall <= 1'h0;
      btb_bank_1_2_data_isRet <= 1'h0;
      btb_bank_1_2_data_isJmp <= 1'h0;
      btb_bank_1_3_valid <= 1'h0;
      btb_bank_1_3_tag <= 29'h0;
      btb_bank_1_3_data_target <= 30'h0;
      btb_bank_1_3_data_isCall <= 1'h0;
      btb_bank_1_3_data_isRet <= 1'h0;
      btb_bank_1_3_data_isJmp <= 1'h0;
      btb_bank_1_4_valid <= 1'h0;
      btb_bank_1_4_tag <= 29'h0;
      btb_bank_1_4_data_target <= 30'h0;
      btb_bank_1_4_data_isCall <= 1'h0;
      btb_bank_1_4_data_isRet <= 1'h0;
      btb_bank_1_4_data_isJmp <= 1'h0;
      btb_bank_1_5_valid <= 1'h0;
      btb_bank_1_5_tag <= 29'h0;
      btb_bank_1_5_data_target <= 30'h0;
      btb_bank_1_5_data_isCall <= 1'h0;
      btb_bank_1_5_data_isRet <= 1'h0;
      btb_bank_1_5_data_isJmp <= 1'h0;
      btb_bank_1_6_valid <= 1'h0;
      btb_bank_1_6_tag <= 29'h0;
      btb_bank_1_6_data_target <= 30'h0;
      btb_bank_1_6_data_isCall <= 1'h0;
      btb_bank_1_6_data_isRet <= 1'h0;
      btb_bank_1_6_data_isJmp <= 1'h0;
      btb_bank_1_7_valid <= 1'h0;
      btb_bank_1_7_tag <= 29'h0;
      btb_bank_1_7_data_target <= 30'h0;
      btb_bank_1_7_data_isCall <= 1'h0;
      btb_bank_1_7_data_isRet <= 1'h0;
      btb_bank_1_7_data_isJmp <= 1'h0;
      btb_bank_1_8_valid <= 1'h0;
      btb_bank_1_8_tag <= 29'h0;
      btb_bank_1_8_data_target <= 30'h0;
      btb_bank_1_8_data_isCall <= 1'h0;
      btb_bank_1_8_data_isRet <= 1'h0;
      btb_bank_1_8_data_isJmp <= 1'h0;
      btb_bank_1_9_valid <= 1'h0;
      btb_bank_1_9_tag <= 29'h0;
      btb_bank_1_9_data_target <= 30'h0;
      btb_bank_1_9_data_isCall <= 1'h0;
      btb_bank_1_9_data_isRet <= 1'h0;
      btb_bank_1_9_data_isJmp <= 1'h0;
      btb_bank_1_10_valid <= 1'h0;
      btb_bank_1_10_tag <= 29'h0;
      btb_bank_1_10_data_target <= 30'h0;
      btb_bank_1_10_data_isCall <= 1'h0;
      btb_bank_1_10_data_isRet <= 1'h0;
      btb_bank_1_10_data_isJmp <= 1'h0;
      btb_bank_1_11_valid <= 1'h0;
      btb_bank_1_11_tag <= 29'h0;
      btb_bank_1_11_data_target <= 30'h0;
      btb_bank_1_11_data_isCall <= 1'h0;
      btb_bank_1_11_data_isRet <= 1'h0;
      btb_bank_1_11_data_isJmp <= 1'h0;
      btb_bank_1_12_valid <= 1'h0;
      btb_bank_1_12_tag <= 29'h0;
      btb_bank_1_12_data_target <= 30'h0;
      btb_bank_1_12_data_isCall <= 1'h0;
      btb_bank_1_12_data_isRet <= 1'h0;
      btb_bank_1_12_data_isJmp <= 1'h0;
      btb_bank_1_13_valid <= 1'h0;
      btb_bank_1_13_tag <= 29'h0;
      btb_bank_1_13_data_target <= 30'h0;
      btb_bank_1_13_data_isCall <= 1'h0;
      btb_bank_1_13_data_isRet <= 1'h0;
      btb_bank_1_13_data_isJmp <= 1'h0;
      btb_bank_1_14_valid <= 1'h0;
      btb_bank_1_14_tag <= 29'h0;
      btb_bank_1_14_data_target <= 30'h0;
      btb_bank_1_14_data_isCall <= 1'h0;
      btb_bank_1_14_data_isRet <= 1'h0;
      btb_bank_1_14_data_isJmp <= 1'h0;
      btb_bank_1_15_valid <= 1'h0;
      btb_bank_1_15_tag <= 29'h0;
      btb_bank_1_15_data_target <= 30'h0;
      btb_bank_1_15_data_isCall <= 1'h0;
      btb_bank_1_15_data_isRet <= 1'h0;
      btb_bank_1_15_data_isJmp <= 1'h0;
      btb_bank_1_16_valid <= 1'h0;
      btb_bank_1_16_tag <= 29'h0;
      btb_bank_1_16_data_target <= 30'h0;
      btb_bank_1_16_data_isCall <= 1'h0;
      btb_bank_1_16_data_isRet <= 1'h0;
      btb_bank_1_16_data_isJmp <= 1'h0;
      btb_bank_1_17_valid <= 1'h0;
      btb_bank_1_17_tag <= 29'h0;
      btb_bank_1_17_data_target <= 30'h0;
      btb_bank_1_17_data_isCall <= 1'h0;
      btb_bank_1_17_data_isRet <= 1'h0;
      btb_bank_1_17_data_isJmp <= 1'h0;
      btb_bank_1_18_valid <= 1'h0;
      btb_bank_1_18_tag <= 29'h0;
      btb_bank_1_18_data_target <= 30'h0;
      btb_bank_1_18_data_isCall <= 1'h0;
      btb_bank_1_18_data_isRet <= 1'h0;
      btb_bank_1_18_data_isJmp <= 1'h0;
      btb_bank_1_19_valid <= 1'h0;
      btb_bank_1_19_tag <= 29'h0;
      btb_bank_1_19_data_target <= 30'h0;
      btb_bank_1_19_data_isCall <= 1'h0;
      btb_bank_1_19_data_isRet <= 1'h0;
      btb_bank_1_19_data_isJmp <= 1'h0;
      btb_bank_1_20_valid <= 1'h0;
      btb_bank_1_20_tag <= 29'h0;
      btb_bank_1_20_data_target <= 30'h0;
      btb_bank_1_20_data_isCall <= 1'h0;
      btb_bank_1_20_data_isRet <= 1'h0;
      btb_bank_1_20_data_isJmp <= 1'h0;
      btb_bank_1_21_valid <= 1'h0;
      btb_bank_1_21_tag <= 29'h0;
      btb_bank_1_21_data_target <= 30'h0;
      btb_bank_1_21_data_isCall <= 1'h0;
      btb_bank_1_21_data_isRet <= 1'h0;
      btb_bank_1_21_data_isJmp <= 1'h0;
      btb_bank_1_22_valid <= 1'h0;
      btb_bank_1_22_tag <= 29'h0;
      btb_bank_1_22_data_target <= 30'h0;
      btb_bank_1_22_data_isCall <= 1'h0;
      btb_bank_1_22_data_isRet <= 1'h0;
      btb_bank_1_22_data_isJmp <= 1'h0;
      btb_bank_1_23_valid <= 1'h0;
      btb_bank_1_23_tag <= 29'h0;
      btb_bank_1_23_data_target <= 30'h0;
      btb_bank_1_23_data_isCall <= 1'h0;
      btb_bank_1_23_data_isRet <= 1'h0;
      btb_bank_1_23_data_isJmp <= 1'h0;
      btb_bank_1_24_valid <= 1'h0;
      btb_bank_1_24_tag <= 29'h0;
      btb_bank_1_24_data_target <= 30'h0;
      btb_bank_1_24_data_isCall <= 1'h0;
      btb_bank_1_24_data_isRet <= 1'h0;
      btb_bank_1_24_data_isJmp <= 1'h0;
      btb_bank_1_25_valid <= 1'h0;
      btb_bank_1_25_tag <= 29'h0;
      btb_bank_1_25_data_target <= 30'h0;
      btb_bank_1_25_data_isCall <= 1'h0;
      btb_bank_1_25_data_isRet <= 1'h0;
      btb_bank_1_25_data_isJmp <= 1'h0;
      btb_bank_1_26_valid <= 1'h0;
      btb_bank_1_26_tag <= 29'h0;
      btb_bank_1_26_data_target <= 30'h0;
      btb_bank_1_26_data_isCall <= 1'h0;
      btb_bank_1_26_data_isRet <= 1'h0;
      btb_bank_1_26_data_isJmp <= 1'h0;
      btb_bank_1_27_valid <= 1'h0;
      btb_bank_1_27_tag <= 29'h0;
      btb_bank_1_27_data_target <= 30'h0;
      btb_bank_1_27_data_isCall <= 1'h0;
      btb_bank_1_27_data_isRet <= 1'h0;
      btb_bank_1_27_data_isJmp <= 1'h0;
      btb_bank_1_28_valid <= 1'h0;
      btb_bank_1_28_tag <= 29'h0;
      btb_bank_1_28_data_target <= 30'h0;
      btb_bank_1_28_data_isCall <= 1'h0;
      btb_bank_1_28_data_isRet <= 1'h0;
      btb_bank_1_28_data_isJmp <= 1'h0;
      btb_bank_1_29_valid <= 1'h0;
      btb_bank_1_29_tag <= 29'h0;
      btb_bank_1_29_data_target <= 30'h0;
      btb_bank_1_29_data_isCall <= 1'h0;
      btb_bank_1_29_data_isRet <= 1'h0;
      btb_bank_1_29_data_isJmp <= 1'h0;
      btb_bank_1_30_valid <= 1'h0;
      btb_bank_1_30_tag <= 29'h0;
      btb_bank_1_30_data_target <= 30'h0;
      btb_bank_1_30_data_isCall <= 1'h0;
      btb_bank_1_30_data_isRet <= 1'h0;
      btb_bank_1_30_data_isJmp <= 1'h0;
      btb_bank_1_31_valid <= 1'h0;
      btb_bank_1_31_tag <= 29'h0;
      btb_bank_1_31_data_target <= 30'h0;
      btb_bank_1_31_data_isCall <= 1'h0;
      btb_bank_1_31_data_isRet <= 1'h0;
      btb_bank_1_31_data_isJmp <= 1'h0;
    end
    else begin
      btb_bank_0_0_valid <= ~_GEN & _GEN_2 | btb_bank_0_0_valid;
      if (_GEN | ~_GEN_2) begin
      end
      else
        btb_bank_0_0_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h0 : _GEN_2) begin
        btb_bank_0_0_data_target <= io_wr_wdata_target;
        btb_bank_0_0_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_0_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_0_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_1_valid <= ~_GEN & _GEN_4 | btb_bank_0_1_valid;
      if (_GEN | ~_GEN_4) begin
      end
      else
        btb_bank_0_1_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h1 : _GEN_4) begin
        btb_bank_0_1_data_target <= io_wr_wdata_target;
        btb_bank_0_1_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_1_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_1_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_2_valid <= ~_GEN & _GEN_6 | btb_bank_0_2_valid;
      if (_GEN | ~_GEN_6) begin
      end
      else
        btb_bank_0_2_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h2 : _GEN_6) begin
        btb_bank_0_2_data_target <= io_wr_wdata_target;
        btb_bank_0_2_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_2_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_2_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_3_valid <= ~_GEN & _GEN_8 | btb_bank_0_3_valid;
      if (_GEN | ~_GEN_8) begin
      end
      else
        btb_bank_0_3_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h3 : _GEN_8) begin
        btb_bank_0_3_data_target <= io_wr_wdata_target;
        btb_bank_0_3_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_3_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_3_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_4_valid <= ~_GEN & _GEN_10 | btb_bank_0_4_valid;
      if (_GEN | ~_GEN_10) begin
      end
      else
        btb_bank_0_4_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h4 : _GEN_10) begin
        btb_bank_0_4_data_target <= io_wr_wdata_target;
        btb_bank_0_4_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_4_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_4_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_5_valid <= ~_GEN & _GEN_12 | btb_bank_0_5_valid;
      if (_GEN | ~_GEN_12) begin
      end
      else
        btb_bank_0_5_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h5 : _GEN_12) begin
        btb_bank_0_5_data_target <= io_wr_wdata_target;
        btb_bank_0_5_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_5_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_5_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_6_valid <= ~_GEN & _GEN_14 | btb_bank_0_6_valid;
      if (_GEN | ~_GEN_14) begin
      end
      else
        btb_bank_0_6_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h6 : _GEN_14) begin
        btb_bank_0_6_data_target <= io_wr_wdata_target;
        btb_bank_0_6_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_6_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_6_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_7_valid <= ~_GEN & _GEN_16 | btb_bank_0_7_valid;
      if (_GEN | ~_GEN_16) begin
      end
      else
        btb_bank_0_7_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h7 : _GEN_16) begin
        btb_bank_0_7_data_target <= io_wr_wdata_target;
        btb_bank_0_7_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_7_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_7_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_8_valid <= ~_GEN & _GEN_18 | btb_bank_0_8_valid;
      if (_GEN | ~_GEN_18) begin
      end
      else
        btb_bank_0_8_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h8 : _GEN_18) begin
        btb_bank_0_8_data_target <= io_wr_wdata_target;
        btb_bank_0_8_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_8_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_8_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_9_valid <= ~_GEN & _GEN_20 | btb_bank_0_9_valid;
      if (_GEN | ~_GEN_20) begin
      end
      else
        btb_bank_0_9_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h9 : _GEN_20) begin
        btb_bank_0_9_data_target <= io_wr_wdata_target;
        btb_bank_0_9_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_9_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_9_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_10_valid <= ~_GEN & _GEN_22 | btb_bank_0_10_valid;
      if (_GEN | ~_GEN_22) begin
      end
      else
        btb_bank_0_10_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'hA : _GEN_22) begin
        btb_bank_0_10_data_target <= io_wr_wdata_target;
        btb_bank_0_10_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_10_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_10_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_11_valid <= ~_GEN & _GEN_24 | btb_bank_0_11_valid;
      if (_GEN | ~_GEN_24) begin
      end
      else
        btb_bank_0_11_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'hB : _GEN_24) begin
        btb_bank_0_11_data_target <= io_wr_wdata_target;
        btb_bank_0_11_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_11_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_11_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_12_valid <= ~_GEN & _GEN_26 | btb_bank_0_12_valid;
      if (_GEN | ~_GEN_26) begin
      end
      else
        btb_bank_0_12_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'hC : _GEN_26) begin
        btb_bank_0_12_data_target <= io_wr_wdata_target;
        btb_bank_0_12_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_12_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_12_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_13_valid <= ~_GEN & _GEN_28 | btb_bank_0_13_valid;
      if (_GEN | ~_GEN_28) begin
      end
      else
        btb_bank_0_13_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'hD : _GEN_28) begin
        btb_bank_0_13_data_target <= io_wr_wdata_target;
        btb_bank_0_13_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_13_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_13_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_14_valid <= ~_GEN & _GEN_30 | btb_bank_0_14_valid;
      if (_GEN | ~_GEN_30) begin
      end
      else
        btb_bank_0_14_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'hE : _GEN_30) begin
        btb_bank_0_14_data_target <= io_wr_wdata_target;
        btb_bank_0_14_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_14_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_14_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_15_valid <= ~_GEN & _GEN_32 | btb_bank_0_15_valid;
      if (_GEN | ~_GEN_32) begin
      end
      else
        btb_bank_0_15_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'hF : _GEN_32) begin
        btb_bank_0_15_data_target <= io_wr_wdata_target;
        btb_bank_0_15_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_15_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_15_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_16_valid <= ~_GEN & _GEN_34 | btb_bank_0_16_valid;
      if (_GEN | ~_GEN_34) begin
      end
      else
        btb_bank_0_16_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h10 : _GEN_34) begin
        btb_bank_0_16_data_target <= io_wr_wdata_target;
        btb_bank_0_16_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_16_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_16_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_17_valid <= ~_GEN & _GEN_36 | btb_bank_0_17_valid;
      if (_GEN | ~_GEN_36) begin
      end
      else
        btb_bank_0_17_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h11 : _GEN_36) begin
        btb_bank_0_17_data_target <= io_wr_wdata_target;
        btb_bank_0_17_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_17_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_17_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_18_valid <= ~_GEN & _GEN_38 | btb_bank_0_18_valid;
      if (_GEN | ~_GEN_38) begin
      end
      else
        btb_bank_0_18_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h12 : _GEN_38) begin
        btb_bank_0_18_data_target <= io_wr_wdata_target;
        btb_bank_0_18_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_18_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_18_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_19_valid <= ~_GEN & _GEN_40 | btb_bank_0_19_valid;
      if (_GEN | ~_GEN_40) begin
      end
      else
        btb_bank_0_19_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h13 : _GEN_40) begin
        btb_bank_0_19_data_target <= io_wr_wdata_target;
        btb_bank_0_19_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_19_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_19_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_20_valid <= ~_GEN & _GEN_42 | btb_bank_0_20_valid;
      if (_GEN | ~_GEN_42) begin
      end
      else
        btb_bank_0_20_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h14 : _GEN_42) begin
        btb_bank_0_20_data_target <= io_wr_wdata_target;
        btb_bank_0_20_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_20_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_20_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_21_valid <= ~_GEN & _GEN_44 | btb_bank_0_21_valid;
      if (_GEN | ~_GEN_44) begin
      end
      else
        btb_bank_0_21_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h15 : _GEN_44) begin
        btb_bank_0_21_data_target <= io_wr_wdata_target;
        btb_bank_0_21_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_21_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_21_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_22_valid <= ~_GEN & _GEN_46 | btb_bank_0_22_valid;
      if (_GEN | ~_GEN_46) begin
      end
      else
        btb_bank_0_22_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h16 : _GEN_46) begin
        btb_bank_0_22_data_target <= io_wr_wdata_target;
        btb_bank_0_22_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_22_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_22_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_23_valid <= ~_GEN & _GEN_48 | btb_bank_0_23_valid;
      if (_GEN | ~_GEN_48) begin
      end
      else
        btb_bank_0_23_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h17 : _GEN_48) begin
        btb_bank_0_23_data_target <= io_wr_wdata_target;
        btb_bank_0_23_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_23_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_23_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_24_valid <= ~_GEN & _GEN_50 | btb_bank_0_24_valid;
      if (_GEN | ~_GEN_50) begin
      end
      else
        btb_bank_0_24_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h18 : _GEN_50) begin
        btb_bank_0_24_data_target <= io_wr_wdata_target;
        btb_bank_0_24_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_24_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_24_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_25_valid <= ~_GEN & _GEN_52 | btb_bank_0_25_valid;
      if (_GEN | ~_GEN_52) begin
      end
      else
        btb_bank_0_25_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h19 : _GEN_52) begin
        btb_bank_0_25_data_target <= io_wr_wdata_target;
        btb_bank_0_25_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_25_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_25_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_26_valid <= ~_GEN & _GEN_54 | btb_bank_0_26_valid;
      if (_GEN | ~_GEN_54) begin
      end
      else
        btb_bank_0_26_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h1A : _GEN_54) begin
        btb_bank_0_26_data_target <= io_wr_wdata_target;
        btb_bank_0_26_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_26_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_26_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_27_valid <= ~_GEN & _GEN_56 | btb_bank_0_27_valid;
      if (_GEN | ~_GEN_56) begin
      end
      else
        btb_bank_0_27_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h1B : _GEN_56) begin
        btb_bank_0_27_data_target <= io_wr_wdata_target;
        btb_bank_0_27_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_27_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_27_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_28_valid <= ~_GEN & _GEN_58 | btb_bank_0_28_valid;
      if (_GEN | ~_GEN_58) begin
      end
      else
        btb_bank_0_28_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h1C : _GEN_58) begin
        btb_bank_0_28_data_target <= io_wr_wdata_target;
        btb_bank_0_28_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_28_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_28_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_29_valid <= ~_GEN & _GEN_60 | btb_bank_0_29_valid;
      if (_GEN | ~_GEN_60) begin
      end
      else
        btb_bank_0_29_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h1D : _GEN_60) begin
        btb_bank_0_29_data_target <= io_wr_wdata_target;
        btb_bank_0_29_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_29_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_29_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_30_valid <= ~_GEN & _GEN_62 | btb_bank_0_30_valid;
      if (_GEN | ~_GEN_62) begin
      end
      else
        btb_bank_0_30_tag <= io_wr_pc[29:1];
      if (_GEN ? hitIdx == 5'h1E : _GEN_62) begin
        btb_bank_0_30_data_target <= io_wr_wdata_target;
        btb_bank_0_30_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_30_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_30_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_0_31_valid <= ~_GEN & _GEN_63 | btb_bank_0_31_valid;
      if (_GEN | ~_GEN_63) begin
      end
      else
        btb_bank_0_31_tag <= io_wr_pc[29:1];
      if (_GEN ? (&hitIdx) : _GEN_63) begin
        btb_bank_0_31_data_target <= io_wr_wdata_target;
        btb_bank_0_31_data_isCall <= io_wr_wdata_isCall;
        btb_bank_0_31_data_isRet <= io_wr_wdata_isRet;
        btb_bank_0_31_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_0_valid <= ~_GEN_64 & _GEN_66 | btb_bank_1_0_valid;
      if (_GEN_64 | ~_GEN_66) begin
      end
      else
        btb_bank_1_0_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h0 : _GEN_66) begin
        btb_bank_1_0_data_target <= io_wr_wdata_target;
        btb_bank_1_0_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_0_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_0_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_1_valid <= ~_GEN_64 & _GEN_67 | btb_bank_1_1_valid;
      if (_GEN_64 | ~_GEN_67) begin
      end
      else
        btb_bank_1_1_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h1 : _GEN_67) begin
        btb_bank_1_1_data_target <= io_wr_wdata_target;
        btb_bank_1_1_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_1_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_1_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_2_valid <= ~_GEN_64 & _GEN_68 | btb_bank_1_2_valid;
      if (_GEN_64 | ~_GEN_68) begin
      end
      else
        btb_bank_1_2_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h2 : _GEN_68) begin
        btb_bank_1_2_data_target <= io_wr_wdata_target;
        btb_bank_1_2_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_2_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_2_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_3_valid <= ~_GEN_64 & _GEN_69 | btb_bank_1_3_valid;
      if (_GEN_64 | ~_GEN_69) begin
      end
      else
        btb_bank_1_3_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h3 : _GEN_69) begin
        btb_bank_1_3_data_target <= io_wr_wdata_target;
        btb_bank_1_3_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_3_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_3_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_4_valid <= ~_GEN_64 & _GEN_70 | btb_bank_1_4_valid;
      if (_GEN_64 | ~_GEN_70) begin
      end
      else
        btb_bank_1_4_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h4 : _GEN_70) begin
        btb_bank_1_4_data_target <= io_wr_wdata_target;
        btb_bank_1_4_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_4_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_4_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_5_valid <= ~_GEN_64 & _GEN_71 | btb_bank_1_5_valid;
      if (_GEN_64 | ~_GEN_71) begin
      end
      else
        btb_bank_1_5_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h5 : _GEN_71) begin
        btb_bank_1_5_data_target <= io_wr_wdata_target;
        btb_bank_1_5_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_5_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_5_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_6_valid <= ~_GEN_64 & _GEN_72 | btb_bank_1_6_valid;
      if (_GEN_64 | ~_GEN_72) begin
      end
      else
        btb_bank_1_6_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h6 : _GEN_72) begin
        btb_bank_1_6_data_target <= io_wr_wdata_target;
        btb_bank_1_6_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_6_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_6_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_7_valid <= ~_GEN_64 & _GEN_73 | btb_bank_1_7_valid;
      if (_GEN_64 | ~_GEN_73) begin
      end
      else
        btb_bank_1_7_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h7 : _GEN_73) begin
        btb_bank_1_7_data_target <= io_wr_wdata_target;
        btb_bank_1_7_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_7_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_7_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_8_valid <= ~_GEN_64 & _GEN_74 | btb_bank_1_8_valid;
      if (_GEN_64 | ~_GEN_74) begin
      end
      else
        btb_bank_1_8_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h8 : _GEN_74) begin
        btb_bank_1_8_data_target <= io_wr_wdata_target;
        btb_bank_1_8_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_8_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_8_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_9_valid <= ~_GEN_64 & _GEN_75 | btb_bank_1_9_valid;
      if (_GEN_64 | ~_GEN_75) begin
      end
      else
        btb_bank_1_9_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h9 : _GEN_75) begin
        btb_bank_1_9_data_target <= io_wr_wdata_target;
        btb_bank_1_9_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_9_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_9_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_10_valid <= ~_GEN_64 & _GEN_76 | btb_bank_1_10_valid;
      if (_GEN_64 | ~_GEN_76) begin
      end
      else
        btb_bank_1_10_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'hA : _GEN_76) begin
        btb_bank_1_10_data_target <= io_wr_wdata_target;
        btb_bank_1_10_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_10_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_10_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_11_valid <= ~_GEN_64 & _GEN_77 | btb_bank_1_11_valid;
      if (_GEN_64 | ~_GEN_77) begin
      end
      else
        btb_bank_1_11_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'hB : _GEN_77) begin
        btb_bank_1_11_data_target <= io_wr_wdata_target;
        btb_bank_1_11_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_11_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_11_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_12_valid <= ~_GEN_64 & _GEN_78 | btb_bank_1_12_valid;
      if (_GEN_64 | ~_GEN_78) begin
      end
      else
        btb_bank_1_12_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'hC : _GEN_78) begin
        btb_bank_1_12_data_target <= io_wr_wdata_target;
        btb_bank_1_12_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_12_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_12_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_13_valid <= ~_GEN_64 & _GEN_79 | btb_bank_1_13_valid;
      if (_GEN_64 | ~_GEN_79) begin
      end
      else
        btb_bank_1_13_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'hD : _GEN_79) begin
        btb_bank_1_13_data_target <= io_wr_wdata_target;
        btb_bank_1_13_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_13_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_13_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_14_valid <= ~_GEN_64 & _GEN_80 | btb_bank_1_14_valid;
      if (_GEN_64 | ~_GEN_80) begin
      end
      else
        btb_bank_1_14_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'hE : _GEN_80) begin
        btb_bank_1_14_data_target <= io_wr_wdata_target;
        btb_bank_1_14_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_14_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_14_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_15_valid <= ~_GEN_64 & _GEN_81 | btb_bank_1_15_valid;
      if (_GEN_64 | ~_GEN_81) begin
      end
      else
        btb_bank_1_15_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'hF : _GEN_81) begin
        btb_bank_1_15_data_target <= io_wr_wdata_target;
        btb_bank_1_15_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_15_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_15_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_16_valid <= ~_GEN_64 & _GEN_82 | btb_bank_1_16_valid;
      if (_GEN_64 | ~_GEN_82) begin
      end
      else
        btb_bank_1_16_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h10 : _GEN_82) begin
        btb_bank_1_16_data_target <= io_wr_wdata_target;
        btb_bank_1_16_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_16_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_16_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_17_valid <= ~_GEN_64 & _GEN_83 | btb_bank_1_17_valid;
      if (_GEN_64 | ~_GEN_83) begin
      end
      else
        btb_bank_1_17_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h11 : _GEN_83) begin
        btb_bank_1_17_data_target <= io_wr_wdata_target;
        btb_bank_1_17_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_17_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_17_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_18_valid <= ~_GEN_64 & _GEN_84 | btb_bank_1_18_valid;
      if (_GEN_64 | ~_GEN_84) begin
      end
      else
        btb_bank_1_18_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h12 : _GEN_84) begin
        btb_bank_1_18_data_target <= io_wr_wdata_target;
        btb_bank_1_18_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_18_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_18_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_19_valid <= ~_GEN_64 & _GEN_85 | btb_bank_1_19_valid;
      if (_GEN_64 | ~_GEN_85) begin
      end
      else
        btb_bank_1_19_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h13 : _GEN_85) begin
        btb_bank_1_19_data_target <= io_wr_wdata_target;
        btb_bank_1_19_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_19_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_19_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_20_valid <= ~_GEN_64 & _GEN_86 | btb_bank_1_20_valid;
      if (_GEN_64 | ~_GEN_86) begin
      end
      else
        btb_bank_1_20_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h14 : _GEN_86) begin
        btb_bank_1_20_data_target <= io_wr_wdata_target;
        btb_bank_1_20_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_20_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_20_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_21_valid <= ~_GEN_64 & _GEN_87 | btb_bank_1_21_valid;
      if (_GEN_64 | ~_GEN_87) begin
      end
      else
        btb_bank_1_21_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h15 : _GEN_87) begin
        btb_bank_1_21_data_target <= io_wr_wdata_target;
        btb_bank_1_21_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_21_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_21_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_22_valid <= ~_GEN_64 & _GEN_88 | btb_bank_1_22_valid;
      if (_GEN_64 | ~_GEN_88) begin
      end
      else
        btb_bank_1_22_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h16 : _GEN_88) begin
        btb_bank_1_22_data_target <= io_wr_wdata_target;
        btb_bank_1_22_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_22_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_22_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_23_valid <= ~_GEN_64 & _GEN_89 | btb_bank_1_23_valid;
      if (_GEN_64 | ~_GEN_89) begin
      end
      else
        btb_bank_1_23_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h17 : _GEN_89) begin
        btb_bank_1_23_data_target <= io_wr_wdata_target;
        btb_bank_1_23_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_23_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_23_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_24_valid <= ~_GEN_64 & _GEN_90 | btb_bank_1_24_valid;
      if (_GEN_64 | ~_GEN_90) begin
      end
      else
        btb_bank_1_24_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h18 : _GEN_90) begin
        btb_bank_1_24_data_target <= io_wr_wdata_target;
        btb_bank_1_24_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_24_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_24_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_25_valid <= ~_GEN_64 & _GEN_91 | btb_bank_1_25_valid;
      if (_GEN_64 | ~_GEN_91) begin
      end
      else
        btb_bank_1_25_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h19 : _GEN_91) begin
        btb_bank_1_25_data_target <= io_wr_wdata_target;
        btb_bank_1_25_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_25_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_25_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_26_valid <= ~_GEN_64 & _GEN_92 | btb_bank_1_26_valid;
      if (_GEN_64 | ~_GEN_92) begin
      end
      else
        btb_bank_1_26_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h1A : _GEN_92) begin
        btb_bank_1_26_data_target <= io_wr_wdata_target;
        btb_bank_1_26_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_26_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_26_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_27_valid <= ~_GEN_64 & _GEN_93 | btb_bank_1_27_valid;
      if (_GEN_64 | ~_GEN_93) begin
      end
      else
        btb_bank_1_27_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h1B : _GEN_93) begin
        btb_bank_1_27_data_target <= io_wr_wdata_target;
        btb_bank_1_27_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_27_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_27_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_28_valid <= ~_GEN_64 & _GEN_94 | btb_bank_1_28_valid;
      if (_GEN_64 | ~_GEN_94) begin
      end
      else
        btb_bank_1_28_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h1C : _GEN_94) begin
        btb_bank_1_28_data_target <= io_wr_wdata_target;
        btb_bank_1_28_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_28_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_28_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_29_valid <= ~_GEN_64 & _GEN_95 | btb_bank_1_29_valid;
      if (_GEN_64 | ~_GEN_95) begin
      end
      else
        btb_bank_1_29_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h1D : _GEN_95) begin
        btb_bank_1_29_data_target <= io_wr_wdata_target;
        btb_bank_1_29_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_29_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_29_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_30_valid <= ~_GEN_64 & _GEN_96 | btb_bank_1_30_valid;
      if (_GEN_64 | ~_GEN_96) begin
      end
      else
        btb_bank_1_30_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? hitIdx_1 == 5'h1E : _GEN_96) begin
        btb_bank_1_30_data_target <= io_wr_wdata_target;
        btb_bank_1_30_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_30_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_30_data_isJmp <= io_wr_wdata_isJmp;
      end
      btb_bank_1_31_valid <= ~_GEN_64 & _GEN_97 | btb_bank_1_31_valid;
      if (_GEN_64 | ~_GEN_97) begin
      end
      else
        btb_bank_1_31_tag <= io_wr_pc[29:1];
      if (_GEN_64 ? (&hitIdx_1) : _GEN_97) begin
        btb_bank_1_31_data_target <= io_wr_wdata_target;
        btb_bank_1_31_data_isCall <= io_wr_wdata_isCall;
        btb_bank_1_31_data_isRet <= io_wr_wdata_isRet;
        btb_bank_1_31_data_isJmp <= io_wr_wdata_isJmp;
      end
    end
  end // always @(posedge)
  MaxPeriodGaloisLFSR lfsr_prng (
    .clock    (clock),
    .reset    (reset),
    .io_out_0 (_lfsr_prng_io_out_0),
    .io_out_1 (_lfsr_prng_io_out_1),
    .io_out_2 (_lfsr_prng_io_out_2),
    .io_out_3 (_lfsr_prng_io_out_3),
    .io_out_4 (_lfsr_prng_io_out_4)
  );
  assign io_rd_0_hit = io_rd_0_pc[0] ? (|_rd_hit_1_T) : (|_rd_hit_0_T);
  assign io_rd_0_rdata_target = io_rd_0_pc[0] ? rdata_1_target : rdata_0_target;
  assign io_rd_0_rdata_isCall = io_rd_0_pc[0] ? rdata_1_isCall : rdata_0_isCall;
  assign io_rd_0_rdata_isRet = io_rd_0_pc[0] ? rdata_1_isRet : rdata_0_isRet;
  assign io_rd_0_rdata_isJmp = io_rd_0_pc[0] ? rdata_1_isJmp : rdata_0_isJmp;
  assign io_rd_1_hit = io_rd_0_pc[0] ? (|_rd_hit_0_T) : (|_rd_hit_1_T);
  assign io_rd_1_rdata_target = io_rd_0_pc[0] ? rdata_0_target : rdata_1_target;
  assign io_rd_1_rdata_isCall = io_rd_0_pc[0] ? rdata_0_isCall : rdata_1_isCall;
  assign io_rd_1_rdata_isRet = io_rd_0_pc[0] ? rdata_0_isRet : rdata_1_isRet;
  assign io_rd_1_rdata_isJmp = io_rd_0_pc[0] ? rdata_0_isJmp : rdata_1_isJmp;
endmodule

