// Generated by CIRCT firtool-1.133.0
module CL3CSRRF(
  input         clock,
                reset,
                io_in_irq_t,
  input  [11:0] io_in_raddr,
  input         io_in_wen,
  input  [11:0] io_in_waddr,
  input  [31:0] io_in_wdata,
  input  [5:0]  io_in_trap,
  input  [31:0] io_in_pc,
                io_in_tval,
  output [31:0] io_out_rdata,
  output        io_out_br_valid,
  output [31:0] io_out_br_pc,
  output [1:0]  io_out_br_priv,
  output [31:0] io_out_irq,
                io_tvec,
                io_epc
);

  reg  [31:0] csr_mepc_q;
  reg  [31:0] csr_sr_q;
  reg  [31:0] csr_mcause_q;
  reg  [31:0] csr_mtvec_q;
  reg  [31:0] csr_mip_q;
  reg  [31:0] csr_mie_q;
  reg  [1:0]  csr_mpriv_q;
  reg  [31:0] csr_mscratch_q;
  reg  [31:0] csr_mtval_q;
  wire [31:0] irq_masked = csr_sr_q[3] ? csr_mip_q & csr_mie_q : 32'h0;
  wire        csr_rd_cases_6_1 = io_in_raddr == 12'h344;
  wire        csr_rd_cases_0_1 = io_in_raddr == 12'h340;
  wire        csr_rd_cases_1_1 = io_in_raddr == 12'h341;
  wire        csr_rd_cases_2_1 = io_in_raddr == 12'h305;
  wire        csr_rd_cases_3_1 = io_in_raddr == 12'h342;
  wire        csr_rd_cases_4_1 = io_in_raddr == 12'h343;
  wire        csr_rd_cases_5_1 = io_in_raddr == 12'h300;
  wire        csr_rd_cases_7_1 = io_in_raddr == 12'h304;
  wire        csr_rd_cases_9_1 = io_in_raddr == 12'h301;
  wire        is_exception = io_in_trap[5:4] == 2'h1;
  wire        _GEN = io_in_trap[5:4] == 2'h2;
  wire        _GEN_0 = io_in_trap == 6'h33;
  wire        _GEN_1 = _GEN | _GEN_0 | is_exception;
  always @(posedge clock) begin
    if (reset) begin
      csr_mepc_q <= 32'h0;
      csr_sr_q <= 32'h1800;
      csr_mcause_q <= 32'h0;
      csr_mtvec_q <= 32'h0;
      csr_mip_q <= 32'h0;
      csr_mie_q <= 32'h0;
      csr_mpriv_q <= 2'h3;
      csr_mscratch_q <= 32'h0;
      csr_mtval_q <= 32'h0;
    end
    else begin
      if (_GEN) begin
        csr_mepc_q <= io_in_pc;
        csr_sr_q <=
          {csr_sr_q[31:13],
           csr_mpriv_q,
           csr_sr_q[10:8],
           csr_sr_q[3],
           csr_sr_q[6:4],
           1'h0,
           csr_sr_q[2:0]};
        if (irq_masked[3])
          csr_mcause_q <= 32'h80000003;
        else if (irq_masked[7])
          csr_mcause_q <= 32'h80000007;
        else if (irq_masked[11])
          csr_mcause_q <= 32'h8000000B;
        csr_mpriv_q <= 2'h3;
        csr_mtval_q <= 32'h0;
      end
      else if (_GEN_0) begin
        csr_sr_q <=
          {csr_sr_q[31:13],
           2'h0,
           csr_sr_q[10:8],
           1'h1,
           csr_sr_q[6:4],
           csr_sr_q[7],
           csr_sr_q[2:0]};
        csr_mpriv_q <= csr_sr_q[12:11];
      end
      else if (is_exception) begin
        csr_mepc_q <= io_in_pc;
        csr_sr_q <=
          {csr_sr_q[31:13],
           csr_mpriv_q,
           csr_sr_q[10:8],
           csr_sr_q[3],
           csr_sr_q[6:4],
           1'h0,
           csr_sr_q[2:0]};
        csr_mcause_q <= {28'h0, io_in_trap[3:0]};
        csr_mpriv_q <= 2'h3;
        csr_mtval_q <= io_in_tval;
      end
      else begin
        if (io_in_wen & io_in_waddr == 12'h341)
          csr_mepc_q <= io_in_wdata;
        if (io_in_wen & io_in_waddr == 12'h300)
          csr_sr_q <= io_in_wdata;
        if (io_in_wen & io_in_waddr == 12'h342)
          csr_mcause_q <= io_in_wdata & 32'h8000000F;
        if (io_in_wen & io_in_waddr == 12'h343)
          csr_mtval_q <= io_in_wdata;
      end
      if (_GEN_1 | ~(io_in_wen & io_in_waddr == 12'h305)) begin
      end
      else
        csr_mtvec_q <= io_in_wdata;
      csr_mip_q <= csr_mip_q & 32'hFFFFF77F | {24'h0, io_in_irq_t, 7'h0};
      if (_GEN_1 | ~(io_in_wen & io_in_waddr == 12'h304)) begin
      end
      else
        csr_mie_q <= {20'h0, io_in_wdata[11:0] & 12'hBBB};
      if (_GEN_1 | ~(io_in_wen & io_in_waddr == 12'h340)) begin
      end
      else
        csr_mscratch_q <= io_in_wdata;
    end
  end // always @(posedge)
  assign io_out_rdata =
    csr_rd_cases_0_1 | csr_rd_cases_1_1 | csr_rd_cases_2_1 | csr_rd_cases_3_1
    | csr_rd_cases_4_1 | csr_rd_cases_5_1 | csr_rd_cases_6_1 | csr_rd_cases_7_1
    | io_in_raddr == 12'hF14 | csr_rd_cases_9_1
      ? (csr_rd_cases_0_1 ? csr_mscratch_q : 32'h0)
        | (csr_rd_cases_1_1 ? csr_mepc_q : 32'h0)
        | (csr_rd_cases_2_1 ? csr_mtvec_q : 32'h0)
        | (csr_rd_cases_3_1 ? csr_mcause_q : 32'h0)
        | (csr_rd_cases_4_1 ? csr_mtval_q : 32'h0) | (csr_rd_cases_5_1 ? csr_sr_q : 32'h0)
        | (csr_rd_cases_6_1 ? csr_mip_q : 32'h0) | (csr_rd_cases_7_1 ? csr_mie_q : 32'h0)
        | (csr_rd_cases_9_1 ? 32'h40401101 : 32'h0)
      : 32'h0;
  assign io_out_br_valid = |(io_in_trap[5:4]);
  assign io_out_br_pc = io_in_trap == 6'h33 ? csr_mepc_q : csr_mtvec_q;
  assign io_out_br_priv = csr_mpriv_q;
  assign io_out_irq = irq_masked;
  assign io_tvec = csr_mtvec_q;
  assign io_epc = csr_mepc_q;
endmodule

