// Generated by CIRCT firtool-1.133.0
module CL3Core(
  input         clock,
                reset,
                io_imem_req_ready,
  output        io_imem_req_valid,
  output [31:0] io_imem_req_bits_addr,
  input         io_imem_resp_valid,
  input  [3:0]  io_imem_resp_bits_err,
  input  [63:0] io_imem_resp_bits_rdata,
  input         io_dmem_req_ready,
  output        io_dmem_req_valid,
  output [31:0] io_dmem_req_bits_addr,
                io_dmem_req_bits_wdata,
  output [3:0]  io_dmem_req_bits_mask,
  output        io_dmem_req_bits_cacheable,
                io_dmem_req_bits_atomic_isAmo,
                io_dmem_req_bits_atomic_isLR,
                io_dmem_req_bits_atomic_isSC,
  output [3:0]  io_dmem_req_bits_atomic_amoCode,
  input         io_dmem_resp_valid,
  input  [3:0]  io_dmem_resp_bits_err,
  input  [31:0] io_dmem_resp_bits_rdata,
  input         io_timer_irq
);

  wire [31:0] _exec3_io_out_info_result;
  wire [31:0] _exec2_io_out_info_result;
  wire        _exec1_io_out_info_br_valid;
  wire [31:0] _exec1_io_out_info_br_pc;
  wire        _exec1_io_out_info_bp_valid;
  wire [31:0] _exec1_io_out_info_bp_target;
  wire        _exec1_io_out_info_bp_isTaken;
  wire        _exec1_io_out_info_bp_isNotTaken;
  wire [31:0] _exec1_io_out_info_bp_source;
  wire        _exec1_io_out_info_bp_isCall;
  wire        _exec1_io_out_info_bp_isRet;
  wire        _exec1_io_out_info_bp_isJmp;
  wire [31:0] _exec1_io_out_info_result;
  wire        _exec0_io_out_info_br_valid;
  wire [31:0] _exec0_io_out_info_br_pc;
  wire        _exec0_io_out_info_bp_valid;
  wire [31:0] _exec0_io_out_info_bp_target;
  wire        _exec0_io_out_info_bp_isTaken;
  wire        _exec0_io_out_info_bp_isNotTaken;
  wire [31:0] _exec0_io_out_info_bp_source;
  wire        _exec0_io_out_info_bp_isCall;
  wire        _exec0_io_out_info_bp_isRet;
  wire        _exec0_io_out_info_bp_isJmp;
  wire [31:0] _exec0_io_out_info_result;
  wire        _div_io_out_wb_valid;
  wire [31:0] _div_io_out_wb_result;
  wire [31:0] _mul_io_out_result;
  wire        _csr_io_out_info_br_valid;
  wire [31:0] _csr_io_out_info_br_pc;
  wire        _csr_io_out_info_wen;
  wire [31:0] _csr_io_out_info_rdata;
  wire [31:0] _csr_io_out_info_wdata;
  wire [5:0]  _csr_io_out_info_except_code;
  wire [31:0] _csr_io_out_info_except_pc;
  wire [31:0] _csr_io_out_info_except_tval;
  wire        _csr_io_out_irq;
  wire [31:0] _csr_io_out_tvec;
  wire [31:0] _csr_io_out_epc;
  wire        _lsu_io_out_mem_valid;
  wire [31:0] _lsu_io_out_mem_bits_addr;
  wire [31:0] _lsu_io_out_mem_bits_wdata;
  wire [3:0]  _lsu_io_out_mem_bits_mask;
  wire        _lsu_io_out_mem_bits_cacheable;
  wire        _lsu_io_out_mem_bits_atomic_isAmo;
  wire        _lsu_io_out_mem_bits_atomic_isLR;
  wire        _lsu_io_out_mem_bits_atomic_isSC;
  wire [3:0]  _lsu_io_out_mem_bits_atomic_amoCode;
  wire        _lsu_io_out_info_valid;
  wire [31:0] _lsu_io_out_info_rdata;
  wire [5:0]  _lsu_io_out_info_except_code;
  wire [31:0] _lsu_io_out_info_except_pc;
  wire [31:0] _lsu_io_out_info_except_tval;
  wire        _lsu_io_out_info_stall;
  wire        _lsu_io_out_info_cacheable;
  wire        _issue_io_in_fetch_0_ready;
  wire        _issue_io_in_fetch_1_ready;
  wire        _issue_io_out_br_valid;
  wire [31:0] _issue_io_out_br_pc;
  wire        _issue_io_out_bp_valid;
  wire [31:0] _issue_io_out_bp_target;
  wire        _issue_io_out_bp_isTaken;
  wire        _issue_io_out_bp_isNotTaken;
  wire [31:0] _issue_io_out_bp_source;
  wire        _issue_io_out_bp_isCall;
  wire        _issue_io_out_bp_isRet;
  wire        _issue_io_out_bp_isJmp;
  wire        _issue_io_out_op_0_valid;
  wire [31:0] _issue_io_out_op_0_inst;
  wire [31:0] _issue_io_out_op_0_pc;
  wire [3:0]  _issue_io_out_op_0_uop_op0;
  wire [2:0]  _issue_io_out_op_0_uop_op1;
  wire [2:0]  _issue_io_out_op_0_uop_op2;
  wire [31:0] _issue_io_out_op_0_rs1;
  wire [31:0] _issue_io_out_op_0_rs2;
  wire        _issue_io_out_op_1_valid;
  wire [31:0] _issue_io_out_op_1_inst;
  wire [31:0] _issue_io_out_op_1_pc;
  wire [3:0]  _issue_io_out_op_1_uop_op0;
  wire [2:0]  _issue_io_out_op_1_uop_op1;
  wire [2:0]  _issue_io_out_op_1_uop_op2;
  wire [31:0] _issue_io_out_op_1_rs1;
  wire [31:0] _issue_io_out_op_1_rs2;
  wire        _issue_io_out_op_2_valid;
  wire [31:0] _issue_io_out_op_2_inst;
  wire [31:0] _issue_io_out_op_2_pc;
  wire [31:0] _issue_io_out_op_2_rs1;
  wire [31:0] _issue_io_out_op_2_rs2;
  wire        _issue_io_out_op_3_valid;
  wire [31:0] _issue_io_out_op_3_inst;
  wire [31:0] _issue_io_out_op_3_pc;
  wire        _issue_io_out_op_3_wen;
  wire [3:0]  _issue_io_out_op_3_uop_op0;
  wire [2:0]  _issue_io_out_op_3_uop_op1;
  wire [2:0]  _issue_io_out_op_3_uop_op2;
  wire [31:0] _issue_io_out_op_3_rs1;
  wire [31:0] _issue_io_out_op_3_rs2;
  wire        _issue_io_out_op_4_valid;
  wire [31:0] _issue_io_out_op_4_inst;
  wire [31:0] _issue_io_out_op_4_rs1;
  wire [31:0] _issue_io_out_op_4_rs2;
  wire        _issue_io_out_op_5_valid;
  wire [31:0] _issue_io_out_op_5_inst;
  wire [31:0] _issue_io_out_op_5_pc;
  wire [2:0]  _issue_io_out_op_5_uop_op1;
  wire [31:0] _issue_io_out_op_5_rs1;
  wire        _issue_io_out_op_6_valid;
  wire [31:0] _issue_io_out_op_6_inst;
  wire [31:0] _issue_io_out_op_6_pc;
  wire [3:0]  _issue_io_out_op_6_uop_op0;
  wire [2:0]  _issue_io_out_op_6_uop_op1;
  wire [2:0]  _issue_io_out_op_6_uop_op2;
  wire [31:0] _issue_io_out_op_6_rs1;
  wire [31:0] _issue_io_out_op_6_rs2;
  wire        _issue_io_out_op_7_valid;
  wire [31:0] _issue_io_out_op_7_inst;
  wire [31:0] _issue_io_out_op_7_pc;
  wire [3:0]  _issue_io_out_op_7_uop_op0;
  wire [2:0]  _issue_io_out_op_7_uop_op1;
  wire [2:0]  _issue_io_out_op_7_uop_op2;
  wire [31:0] _issue_io_out_op_7_rs1;
  wire [31:0] _issue_io_out_op_7_rs2;
  wire        _issue_io_out_csr_wen;
  wire [11:0] _issue_io_out_csr_waddr;
  wire [31:0] _issue_io_out_csr_wdata;
  wire [5:0]  _issue_io_out_csr_except_code;
  wire [31:0] _issue_io_out_csr_except_pc;
  wire [31:0] _issue_io_out_csr_except_tval;
  wire        _issue_io_out_hold;
  wire        _issue_io_out_lsu_flush;
  wire        _mmu_io_fetchIn_req_ready;
  wire        _mmu_io_fetchIn_resp_valid;
  wire [3:0]  _mmu_io_fetchIn_resp_bits_err;
  wire [63:0] _mmu_io_fetchIn_resp_bits_rdata;
  wire        _mmu_io_lsuIn_req_ready;
  wire        _mmu_io_lsuIn_resp_valid;
  wire [3:0]  _mmu_io_lsuIn_resp_bits_err;
  wire [31:0] _mmu_io_lsuIn_resp_bits_rdata;
  wire        _frontend_io_mem_req_valid;
  wire [31:0] _frontend_io_mem_req_bits_addr;
  wire        _frontend_io_out_0_valid;
  wire [31:0] _frontend_io_out_0_bits_inst;
  wire [31:0] _frontend_io_out_0_bits_pc;
  wire        _frontend_io_out_0_bits_wen;
  wire        _frontend_io_out_0_bits_isLSU;
  wire        _frontend_io_out_0_bits_isMUL;
  wire        _frontend_io_out_0_bits_isDIV;
  wire        _frontend_io_out_0_bits_isCSR;
  wire        _frontend_io_out_0_bits_isEXU;
  wire        _frontend_io_out_0_bits_isBr;
  wire [3:0]  _frontend_io_out_0_bits_uop_op0;
  wire [2:0]  _frontend_io_out_0_bits_uop_op1;
  wire [2:0]  _frontend_io_out_0_bits_uop_op2;
  wire        _frontend_io_out_0_bits_illegal;
  wire        _frontend_io_out_0_bits_fault_fetch;
  wire        _frontend_io_out_0_bits_fault_page;
  wire        _frontend_io_out_1_valid;
  wire [31:0] _frontend_io_out_1_bits_inst;
  wire [31:0] _frontend_io_out_1_bits_pc;
  wire        _frontend_io_out_1_bits_wen;
  wire        _frontend_io_out_1_bits_isLSU;
  wire        _frontend_io_out_1_bits_isMUL;
  wire        _frontend_io_out_1_bits_isDIV;
  wire        _frontend_io_out_1_bits_isCSR;
  wire        _frontend_io_out_1_bits_isEXU;
  wire        _frontend_io_out_1_bits_isBr;
  wire [3:0]  _frontend_io_out_1_bits_uop_op0;
  wire [2:0]  _frontend_io_out_1_bits_uop_op1;
  wire [2:0]  _frontend_io_out_1_bits_uop_op2;
  wire        _frontend_io_out_1_bits_illegal;
  wire        _frontend_io_out_1_bits_fault_fetch;
  wire        _frontend_io_out_1_bits_fault_page;
  CL3Frontend frontend (
    .clock                     (clock),
    .reset                     (reset),
    .io_mem_req_ready          (_mmu_io_fetchIn_req_ready),
    .io_mem_req_valid          (_frontend_io_mem_req_valid),
    .io_mem_req_bits_addr      (_frontend_io_mem_req_bits_addr),
    .io_mem_resp_valid         (_mmu_io_fetchIn_resp_valid),
    .io_mem_resp_bits_err      (_mmu_io_fetchIn_resp_bits_err),
    .io_mem_resp_bits_rdata    (_mmu_io_fetchIn_resp_bits_rdata),
    .io_br_valid               (_issue_io_out_br_valid),
    .io_br_pc                  (_issue_io_out_br_pc),
    .io_bp_valid               (_issue_io_out_bp_valid),
    .io_bp_target              (_issue_io_out_bp_target),
    .io_bp_isTaken             (_issue_io_out_bp_isTaken),
    .io_bp_isNotTaken          (_issue_io_out_bp_isNotTaken),
    .io_bp_source              (_issue_io_out_bp_source),
    .io_bp_isCall              (_issue_io_out_bp_isCall),
    .io_bp_isRet               (_issue_io_out_bp_isRet),
    .io_bp_isJmp               (_issue_io_out_bp_isJmp),
    .io_out_0_ready            (_issue_io_in_fetch_0_ready),
    .io_out_0_valid            (_frontend_io_out_0_valid),
    .io_out_0_bits_inst        (_frontend_io_out_0_bits_inst),
    .io_out_0_bits_pc          (_frontend_io_out_0_bits_pc),
    .io_out_0_bits_wen         (_frontend_io_out_0_bits_wen),
    .io_out_0_bits_isLSU       (_frontend_io_out_0_bits_isLSU),
    .io_out_0_bits_isMUL       (_frontend_io_out_0_bits_isMUL),
    .io_out_0_bits_isDIV       (_frontend_io_out_0_bits_isDIV),
    .io_out_0_bits_isCSR       (_frontend_io_out_0_bits_isCSR),
    .io_out_0_bits_isEXU       (_frontend_io_out_0_bits_isEXU),
    .io_out_0_bits_isBr        (_frontend_io_out_0_bits_isBr),
    .io_out_0_bits_uop_op0     (_frontend_io_out_0_bits_uop_op0),
    .io_out_0_bits_uop_op1     (_frontend_io_out_0_bits_uop_op1),
    .io_out_0_bits_uop_op2     (_frontend_io_out_0_bits_uop_op2),
    .io_out_0_bits_illegal     (_frontend_io_out_0_bits_illegal),
    .io_out_0_bits_fault_fetch (_frontend_io_out_0_bits_fault_fetch),
    .io_out_0_bits_fault_page  (_frontend_io_out_0_bits_fault_page),
    .io_out_1_ready            (_issue_io_in_fetch_1_ready),
    .io_out_1_valid            (_frontend_io_out_1_valid),
    .io_out_1_bits_inst        (_frontend_io_out_1_bits_inst),
    .io_out_1_bits_pc          (_frontend_io_out_1_bits_pc),
    .io_out_1_bits_wen         (_frontend_io_out_1_bits_wen),
    .io_out_1_bits_isLSU       (_frontend_io_out_1_bits_isLSU),
    .io_out_1_bits_isMUL       (_frontend_io_out_1_bits_isMUL),
    .io_out_1_bits_isDIV       (_frontend_io_out_1_bits_isDIV),
    .io_out_1_bits_isCSR       (_frontend_io_out_1_bits_isCSR),
    .io_out_1_bits_isEXU       (_frontend_io_out_1_bits_isEXU),
    .io_out_1_bits_isBr        (_frontend_io_out_1_bits_isBr),
    .io_out_1_bits_uop_op0     (_frontend_io_out_1_bits_uop_op0),
    .io_out_1_bits_uop_op1     (_frontend_io_out_1_bits_uop_op1),
    .io_out_1_bits_uop_op2     (_frontend_io_out_1_bits_uop_op2),
    .io_out_1_bits_illegal     (_frontend_io_out_1_bits_illegal),
    .io_out_1_bits_fault_fetch (_frontend_io_out_1_bits_fault_fetch),
    .io_out_1_bits_fault_page  (_frontend_io_out_1_bits_fault_page)
  );
  CL3MMU mmu (
    .io_fetchIn_req_ready              (_mmu_io_fetchIn_req_ready),
    .io_fetchIn_req_valid              (_frontend_io_mem_req_valid),
    .io_fetchIn_req_bits_addr          (_frontend_io_mem_req_bits_addr),
    .io_fetchIn_resp_valid             (_mmu_io_fetchIn_resp_valid),
    .io_fetchIn_resp_bits_err          (_mmu_io_fetchIn_resp_bits_err),
    .io_fetchIn_resp_bits_rdata        (_mmu_io_fetchIn_resp_bits_rdata),
    .io_fetchOut_req_ready             (io_imem_req_ready),
    .io_fetchOut_req_valid             (io_imem_req_valid),
    .io_fetchOut_req_bits_addr         (io_imem_req_bits_addr),
    .io_fetchOut_resp_valid            (io_imem_resp_valid),
    .io_fetchOut_resp_bits_err         (io_imem_resp_bits_err),
    .io_fetchOut_resp_bits_rdata       (io_imem_resp_bits_rdata),
    .io_lsuIn_req_ready                (_mmu_io_lsuIn_req_ready),
    .io_lsuIn_req_valid                (_lsu_io_out_mem_valid),
    .io_lsuIn_req_bits_addr            (_lsu_io_out_mem_bits_addr),
    .io_lsuIn_req_bits_wdata           (_lsu_io_out_mem_bits_wdata),
    .io_lsuIn_req_bits_mask            (_lsu_io_out_mem_bits_mask),
    .io_lsuIn_req_bits_cacheable       (_lsu_io_out_mem_bits_cacheable),
    .io_lsuIn_req_bits_atomic_isAmo    (_lsu_io_out_mem_bits_atomic_isAmo),
    .io_lsuIn_req_bits_atomic_isLR     (_lsu_io_out_mem_bits_atomic_isLR),
    .io_lsuIn_req_bits_atomic_isSC     (_lsu_io_out_mem_bits_atomic_isSC),
    .io_lsuIn_req_bits_atomic_amoCode  (_lsu_io_out_mem_bits_atomic_amoCode),
    .io_lsuIn_resp_valid               (_mmu_io_lsuIn_resp_valid),
    .io_lsuIn_resp_bits_err            (_mmu_io_lsuIn_resp_bits_err),
    .io_lsuIn_resp_bits_rdata          (_mmu_io_lsuIn_resp_bits_rdata),
    .io_lsuOut_req_ready               (io_dmem_req_ready),
    .io_lsuOut_req_valid               (io_dmem_req_valid),
    .io_lsuOut_req_bits_addr           (io_dmem_req_bits_addr),
    .io_lsuOut_req_bits_wdata          (io_dmem_req_bits_wdata),
    .io_lsuOut_req_bits_mask           (io_dmem_req_bits_mask),
    .io_lsuOut_req_bits_cacheable      (io_dmem_req_bits_cacheable),
    .io_lsuOut_req_bits_atomic_isAmo   (io_dmem_req_bits_atomic_isAmo),
    .io_lsuOut_req_bits_atomic_isLR    (io_dmem_req_bits_atomic_isLR),
    .io_lsuOut_req_bits_atomic_isSC    (io_dmem_req_bits_atomic_isSC),
    .io_lsuOut_req_bits_atomic_amoCode (io_dmem_req_bits_atomic_amoCode),
    .io_lsuOut_resp_valid              (io_dmem_resp_valid),
    .io_lsuOut_resp_bits_err           (io_dmem_resp_bits_err),
    .io_lsuOut_resp_bits_rdata         (io_dmem_resp_bits_rdata)
  );
  CL3Issue issue (
    .clock                                  (clock),
    .reset                                  (reset),
    .io_in_fetch_0_ready                    (_issue_io_in_fetch_0_ready),
    .io_in_fetch_0_valid                    (_frontend_io_out_0_valid),
    .io_in_fetch_0_bits_inst                (_frontend_io_out_0_bits_inst),
    .io_in_fetch_0_bits_pc                  (_frontend_io_out_0_bits_pc),
    .io_in_fetch_0_bits_wen                 (_frontend_io_out_0_bits_wen),
    .io_in_fetch_0_bits_isLSU               (_frontend_io_out_0_bits_isLSU),
    .io_in_fetch_0_bits_isMUL               (_frontend_io_out_0_bits_isMUL),
    .io_in_fetch_0_bits_isDIV               (_frontend_io_out_0_bits_isDIV),
    .io_in_fetch_0_bits_isCSR               (_frontend_io_out_0_bits_isCSR),
    .io_in_fetch_0_bits_isEXU               (_frontend_io_out_0_bits_isEXU),
    .io_in_fetch_0_bits_isBr                (_frontend_io_out_0_bits_isBr),
    .io_in_fetch_0_bits_uop_op0             (_frontend_io_out_0_bits_uop_op0),
    .io_in_fetch_0_bits_uop_op1             (_frontend_io_out_0_bits_uop_op1),
    .io_in_fetch_0_bits_uop_op2             (_frontend_io_out_0_bits_uop_op2),
    .io_in_fetch_0_bits_illegal             (_frontend_io_out_0_bits_illegal),
    .io_in_fetch_0_bits_fault_fetch         (_frontend_io_out_0_bits_fault_fetch),
    .io_in_fetch_0_bits_fault_page          (_frontend_io_out_0_bits_fault_page),
    .io_in_fetch_1_ready                    (_issue_io_in_fetch_1_ready),
    .io_in_fetch_1_valid                    (_frontend_io_out_1_valid),
    .io_in_fetch_1_bits_inst                (_frontend_io_out_1_bits_inst),
    .io_in_fetch_1_bits_pc                  (_frontend_io_out_1_bits_pc),
    .io_in_fetch_1_bits_wen                 (_frontend_io_out_1_bits_wen),
    .io_in_fetch_1_bits_isLSU               (_frontend_io_out_1_bits_isLSU),
    .io_in_fetch_1_bits_isMUL               (_frontend_io_out_1_bits_isMUL),
    .io_in_fetch_1_bits_isDIV               (_frontend_io_out_1_bits_isDIV),
    .io_in_fetch_1_bits_isCSR               (_frontend_io_out_1_bits_isCSR),
    .io_in_fetch_1_bits_isEXU               (_frontend_io_out_1_bits_isEXU),
    .io_in_fetch_1_bits_isBr                (_frontend_io_out_1_bits_isBr),
    .io_in_fetch_1_bits_uop_op0             (_frontend_io_out_1_bits_uop_op0),
    .io_in_fetch_1_bits_uop_op1             (_frontend_io_out_1_bits_uop_op1),
    .io_in_fetch_1_bits_uop_op2             (_frontend_io_out_1_bits_uop_op2),
    .io_in_fetch_1_bits_illegal             (_frontend_io_out_1_bits_illegal),
    .io_in_fetch_1_bits_fault_fetch         (_frontend_io_out_1_bits_fault_fetch),
    .io_in_fetch_1_bits_fault_page          (_frontend_io_out_1_bits_fault_page),
    .io_in_csr_br_valid                     (_csr_io_out_info_br_valid),
    .io_in_csr_br_pc                        (_csr_io_out_info_br_pc),
    .io_in_csr_wen                          (_csr_io_out_info_wen),
    .io_in_csr_rdata                        (_csr_io_out_info_rdata),
    .io_in_csr_wdata                        (_csr_io_out_info_wdata),
    .io_in_csr_except_code                  (_csr_io_out_info_except_code),
    .io_in_csr_except_pc                    (_csr_io_out_info_except_pc),
    .io_in_csr_except_tval                  (_csr_io_out_info_except_tval),
    .io_in_exec_0_br_valid                  (_exec0_io_out_info_br_valid),
    .io_in_exec_0_br_pc                     (_exec0_io_out_info_br_pc),
    .io_in_exec_0_bp_valid                  (_exec0_io_out_info_bp_valid),
    .io_in_exec_0_bp_target                 (_exec0_io_out_info_bp_target),
    .io_in_exec_0_bp_isTaken                (_exec0_io_out_info_bp_isTaken),
    .io_in_exec_0_bp_isNotTaken             (_exec0_io_out_info_bp_isNotTaken),
    .io_in_exec_0_bp_source                 (_exec0_io_out_info_bp_source),
    .io_in_exec_0_bp_isCall                 (_exec0_io_out_info_bp_isCall),
    .io_in_exec_0_bp_isRet                  (_exec0_io_out_info_bp_isRet),
    .io_in_exec_0_bp_isJmp                  (_exec0_io_out_info_bp_isJmp),
    .io_in_exec_0_result                    (_exec0_io_out_info_result),
    .io_in_exec_1_br_valid                  (_exec1_io_out_info_br_valid),
    .io_in_exec_1_br_pc                     (_exec1_io_out_info_br_pc),
    .io_in_exec_1_bp_valid                  (_exec1_io_out_info_bp_valid),
    .io_in_exec_1_bp_target                 (_exec1_io_out_info_bp_target),
    .io_in_exec_1_bp_isTaken                (_exec1_io_out_info_bp_isTaken),
    .io_in_exec_1_bp_isNotTaken             (_exec1_io_out_info_bp_isNotTaken),
    .io_in_exec_1_bp_source                 (_exec1_io_out_info_bp_source),
    .io_in_exec_1_bp_isCall                 (_exec1_io_out_info_bp_isCall),
    .io_in_exec_1_bp_isRet                  (_exec1_io_out_info_bp_isRet),
    .io_in_exec_1_bp_isJmp                  (_exec1_io_out_info_bp_isJmp),
    .io_in_exec_1_result                    (_exec1_io_out_info_result),
    .io_in_exec_2_result                    (_exec2_io_out_info_result),
    .io_in_exec_3_result                    (_exec3_io_out_info_result),
    .io_in_mul_result                       (_mul_io_out_result),
    .io_in_div_valid                        (_div_io_out_wb_valid),
    .io_in_div_result                       (_div_io_out_wb_result),
    .io_in_lsu_valid                        (_lsu_io_out_info_valid),
    .io_in_lsu_rdata                        (_lsu_io_out_info_rdata),
    .io_in_lsu_except_code                  (_lsu_io_out_info_except_code),
    .io_in_lsu_except_pc                    (_lsu_io_out_info_except_pc),
    .io_in_lsu_except_tval                  (_lsu_io_out_info_except_tval),
    .io_in_lsu_stall                        (_lsu_io_out_info_stall),
    .io_in_lsu_cacheable                    (_lsu_io_out_info_cacheable),
    .io_in_irq                              (_csr_io_out_irq),
    .io_in_tvec                             (_csr_io_out_tvec),
    .io_in_epc                              (_csr_io_out_epc),
    .io_out_br_valid                        (_issue_io_out_br_valid),
    .io_out_br_pc                           (_issue_io_out_br_pc),
    .io_out_bp_valid                        (_issue_io_out_bp_valid),
    .io_out_bp_target                       (_issue_io_out_bp_target),
    .io_out_bp_isTaken                      (_issue_io_out_bp_isTaken),
    .io_out_bp_isNotTaken                   (_issue_io_out_bp_isNotTaken),
    .io_out_bp_source                       (_issue_io_out_bp_source),
    .io_out_bp_isCall                       (_issue_io_out_bp_isCall),
    .io_out_bp_isRet                        (_issue_io_out_bp_isRet),
    .io_out_bp_isJmp                        (_issue_io_out_bp_isJmp),
    .io_out_op_0_valid                      (_issue_io_out_op_0_valid),
    .io_out_op_0_inst                       (_issue_io_out_op_0_inst),
    .io_out_op_0_pc                         (_issue_io_out_op_0_pc),
    .io_out_op_0_uop_op0                    (_issue_io_out_op_0_uop_op0),
    .io_out_op_0_uop_op1                    (_issue_io_out_op_0_uop_op1),
    .io_out_op_0_uop_op2                    (_issue_io_out_op_0_uop_op2),
    .io_out_op_0_rs1                        (_issue_io_out_op_0_rs1),
    .io_out_op_0_rs2                        (_issue_io_out_op_0_rs2),
    .io_out_op_1_valid                      (_issue_io_out_op_1_valid),
    .io_out_op_1_inst                       (_issue_io_out_op_1_inst),
    .io_out_op_1_pc                         (_issue_io_out_op_1_pc),
    .io_out_op_1_uop_op0                    (_issue_io_out_op_1_uop_op0),
    .io_out_op_1_uop_op1                    (_issue_io_out_op_1_uop_op1),
    .io_out_op_1_uop_op2                    (_issue_io_out_op_1_uop_op2),
    .io_out_op_1_rs1                        (_issue_io_out_op_1_rs1),
    .io_out_op_1_rs2                        (_issue_io_out_op_1_rs2),
    .io_out_op_2_valid                      (_issue_io_out_op_2_valid),
    .io_out_op_2_inst                       (_issue_io_out_op_2_inst),
    .io_out_op_2_pc                         (_issue_io_out_op_2_pc),
    .io_out_op_2_rs1                        (_issue_io_out_op_2_rs1),
    .io_out_op_2_rs2                        (_issue_io_out_op_2_rs2),
    .io_out_op_3_valid                      (_issue_io_out_op_3_valid),
    .io_out_op_3_inst                       (_issue_io_out_op_3_inst),
    .io_out_op_3_pc                         (_issue_io_out_op_3_pc),
    .io_out_op_3_wen                        (_issue_io_out_op_3_wen),
    .io_out_op_3_uop_op0                    (_issue_io_out_op_3_uop_op0),
    .io_out_op_3_uop_op1                    (_issue_io_out_op_3_uop_op1),
    .io_out_op_3_uop_op2                    (_issue_io_out_op_3_uop_op2),
    .io_out_op_3_rs1                        (_issue_io_out_op_3_rs1),
    .io_out_op_3_rs2                        (_issue_io_out_op_3_rs2),
    .io_out_op_4_valid                      (_issue_io_out_op_4_valid),
    .io_out_op_4_inst                       (_issue_io_out_op_4_inst),
    .io_out_op_4_rs1                        (_issue_io_out_op_4_rs1),
    .io_out_op_4_rs2                        (_issue_io_out_op_4_rs2),
    .io_out_op_5_valid                      (_issue_io_out_op_5_valid),
    .io_out_op_5_inst                       (_issue_io_out_op_5_inst),
    .io_out_op_5_pc                         (_issue_io_out_op_5_pc),
    .io_out_op_5_uop_op1                    (_issue_io_out_op_5_uop_op1),
    .io_out_op_5_rs1                        (_issue_io_out_op_5_rs1),
    .io_out_op_6_valid                      (_issue_io_out_op_6_valid),
    .io_out_op_6_inst                       (_issue_io_out_op_6_inst),
    .io_out_op_6_pc                         (_issue_io_out_op_6_pc),
    .io_out_op_6_uop_op0                    (_issue_io_out_op_6_uop_op0),
    .io_out_op_6_uop_op1                    (_issue_io_out_op_6_uop_op1),
    .io_out_op_6_uop_op2                    (_issue_io_out_op_6_uop_op2),
    .io_out_op_6_rs1                        (_issue_io_out_op_6_rs1),
    .io_out_op_6_rs2                        (_issue_io_out_op_6_rs2),
    .io_out_op_7_valid                      (_issue_io_out_op_7_valid),
    .io_out_op_7_inst                       (_issue_io_out_op_7_inst),
    .io_out_op_7_pc                         (_issue_io_out_op_7_pc),
    .io_out_op_7_uop_op0                    (_issue_io_out_op_7_uop_op0),
    .io_out_op_7_uop_op1                    (_issue_io_out_op_7_uop_op1),
    .io_out_op_7_uop_op2                    (_issue_io_out_op_7_uop_op2),
    .io_out_op_7_rs1                        (_issue_io_out_op_7_rs1),
    .io_out_op_7_rs2                        (_issue_io_out_op_7_rs2),
    .io_out_csr_wen                         (_issue_io_out_csr_wen),
    .io_out_csr_waddr                       (_issue_io_out_csr_waddr),
    .io_out_csr_wdata                       (_issue_io_out_csr_wdata),
    .io_out_csr_except_code                 (_issue_io_out_csr_except_code),
    .io_out_csr_except_pc                   (_issue_io_out_csr_except_pc),
    .io_out_csr_except_tval                 (_issue_io_out_csr_except_tval),
    .io_out_hold                            (_issue_io_out_hold),
    .io_out_lsu_flush                       (_issue_io_out_lsu_flush),
    .io_out_debug_fetch0_ok                 (/* unused */),
    .io_out_debug_fetch1_ok                 (/* unused */),
    .io_out_debug_slot0_data_check          (/* unused */),
    .io_out_debug_slot1_data_check          (/* unused */),
    .io_out_debug_slot0_struct_check        (/* unused */),
    .io_out_debug_slot1_struct_check        (/* unused */),
    .io_out_debug_slot0_order_check         (/* unused */),
    .io_out_debug_slot1_order_check         (/* unused */),
    .io_out_debug_slot1_type_check          (/* unused */),
    .io_out_debug_slot1_data_check_internal (/* unused */),
    .io_out_debug_delay0                    (/* unused */),
    .io_out_debug_id0                       (/* unused */),
    .io_out_debug_inst_delay0               (/* unused */),
    .io_out_debug_delay1                    (/* unused */),
    .io_out_debug_id1                       (/* unused */),
    .io_out_debug_inst_delay1               (/* unused */),
    .io_out_debug_slot0_rdIdx               (/* unused */),
    .io_out_debug_slot1_rs1Idx              (/* unused */),
    .io_out_debug_slot1_rs2Idx              (/* unused */),
    .io_out_debug_mismatch0                 (/* unused */),
    .io_out_debug_mismatch1                 (/* unused */),
    .io_out_debug_dual_issue                (/* unused */),
    .io_out_debug_single_issue              (/* unused */),
    .io_out_debug_pipe1mem                  (/* unused */),
    .io_out_debug_rdystage                  (/* unused */),
    .io_out_debug_mispred                   (/* unused */),
    .io_out_debug_brj_num                   (/* unused */)
  );
  CL3LSU lsu (
    .clock                          (clock),
    .reset                          (reset),
    .io_in_info_valid               (_issue_io_out_op_2_valid),
    .io_in_info_inst                (_issue_io_out_op_2_inst),
    .io_in_info_pc                  (_issue_io_out_op_2_pc),
    .io_in_info_rs1                 (_issue_io_out_op_2_rs1),
    .io_in_info_rs2                 (_issue_io_out_op_2_rs2),
    .io_in_mem_valid                (_mmu_io_lsuIn_resp_valid),
    .io_in_mem_bits_err             (_mmu_io_lsuIn_resp_bits_err),
    .io_in_mem_bits_rdata           (_mmu_io_lsuIn_resp_bits_rdata),
    .io_in_flush                    (_issue_io_out_lsu_flush),
    .io_out_mem_ready               (_mmu_io_lsuIn_req_ready),
    .io_out_mem_valid               (_lsu_io_out_mem_valid),
    .io_out_mem_bits_addr           (_lsu_io_out_mem_bits_addr),
    .io_out_mem_bits_wdata          (_lsu_io_out_mem_bits_wdata),
    .io_out_mem_bits_mask           (_lsu_io_out_mem_bits_mask),
    .io_out_mem_bits_cacheable      (_lsu_io_out_mem_bits_cacheable),
    .io_out_mem_bits_atomic_isAmo   (_lsu_io_out_mem_bits_atomic_isAmo),
    .io_out_mem_bits_atomic_isLR    (_lsu_io_out_mem_bits_atomic_isLR),
    .io_out_mem_bits_atomic_isSC    (_lsu_io_out_mem_bits_atomic_isSC),
    .io_out_mem_bits_atomic_amoCode (_lsu_io_out_mem_bits_atomic_amoCode),
    .io_out_info_valid              (_lsu_io_out_info_valid),
    .io_out_info_rdata              (_lsu_io_out_info_rdata),
    .io_out_info_except_code        (_lsu_io_out_info_except_code),
    .io_out_info_except_pc          (_lsu_io_out_info_except_pc),
    .io_out_info_except_tval        (_lsu_io_out_info_except_tval),
    .io_out_info_stall              (_lsu_io_out_info_stall),
    .io_out_info_cacheable          (_lsu_io_out_info_cacheable)
  );
  CL3CSR csr (
    .clock                   (clock),
    .reset                   (reset),
    .io_in_info_valid        (_issue_io_out_op_5_valid),
    .io_in_info_inst         (_issue_io_out_op_5_inst),
    .io_in_info_pc           (_issue_io_out_op_5_pc),
    .io_in_info_uop_op1      (_issue_io_out_op_5_uop_op1),
    .io_in_info_rs1          (_issue_io_out_op_5_rs1),
    .io_in_wb_wen            (_issue_io_out_csr_wen),
    .io_in_wb_waddr          (_issue_io_out_csr_waddr),
    .io_in_wb_wdata          (_issue_io_out_csr_wdata),
    .io_in_wb_except_code    (_issue_io_out_csr_except_code),
    .io_in_wb_except_pc      (_issue_io_out_csr_except_pc),
    .io_in_wb_except_tval    (_issue_io_out_csr_except_tval),
    .io_in_irq_t             (io_timer_irq),
    .io_in_hold              (_issue_io_out_hold),
    .io_out_info_br_valid    (_csr_io_out_info_br_valid),
    .io_out_info_br_pc       (_csr_io_out_info_br_pc),
    .io_out_info_wen         (_csr_io_out_info_wen),
    .io_out_info_rdata       (_csr_io_out_info_rdata),
    .io_out_info_wdata       (_csr_io_out_info_wdata),
    .io_out_info_except_code (_csr_io_out_info_except_code),
    .io_out_info_except_pc   (_csr_io_out_info_except_pc),
    .io_out_info_except_tval (_csr_io_out_info_except_tval),
    .io_out_irq              (_csr_io_out_irq),
    .io_out_tvec             (_csr_io_out_tvec),
    .io_out_epc              (_csr_io_out_epc)
  );
  CL3MUL mul (
    .clock              (clock),
    .io_in_info_valid   (_issue_io_out_op_3_valid),
    .io_in_info_inst    (_issue_io_out_op_3_inst),
    .io_in_info_pc      (_issue_io_out_op_3_pc),
    .io_in_info_wen     (_issue_io_out_op_3_wen),
    .io_in_info_uop_op0 (_issue_io_out_op_3_uop_op0),
    .io_in_info_uop_op1 (_issue_io_out_op_3_uop_op1),
    .io_in_info_uop_op2 (_issue_io_out_op_3_uop_op2),
    .io_in_info_rs1     (_issue_io_out_op_3_rs1),
    .io_in_info_rs2     (_issue_io_out_op_3_rs2),
    .io_in_hold         (_issue_io_out_hold),
    .io_out_result      (_mul_io_out_result)
  );
  CL3DIV div (
    .clock            (clock),
    .reset            (reset),
    .io_in_info_valid (_issue_io_out_op_4_valid),
    .io_in_info_inst  (_issue_io_out_op_4_inst),
    .io_in_info_rs1   (_issue_io_out_op_4_rs1),
    .io_in_info_rs2   (_issue_io_out_op_4_rs2),
    .io_out_wb_valid  (_div_io_out_wb_valid),
    .io_out_wb_result (_div_io_out_wb_result)
  );
  CL3EXU exec0 (
    .clock                     (clock),
    .reset                     (reset),
    .io_in_info_valid          (_issue_io_out_op_0_valid),
    .io_in_info_inst           (_issue_io_out_op_0_inst),
    .io_in_info_pc             (_issue_io_out_op_0_pc),
    .io_in_info_uop_op0        (_issue_io_out_op_0_uop_op0),
    .io_in_info_uop_op1        (_issue_io_out_op_0_uop_op1),
    .io_in_info_uop_op2        (_issue_io_out_op_0_uop_op2),
    .io_in_info_rs1            (_issue_io_out_op_0_rs1),
    .io_in_info_rs2            (_issue_io_out_op_0_rs2),
    .io_in_hold                (_issue_io_out_hold),
    .io_out_info_br_valid      (_exec0_io_out_info_br_valid),
    .io_out_info_br_pc         (_exec0_io_out_info_br_pc),
    .io_out_info_bp_valid      (_exec0_io_out_info_bp_valid),
    .io_out_info_bp_target     (_exec0_io_out_info_bp_target),
    .io_out_info_bp_isTaken    (_exec0_io_out_info_bp_isTaken),
    .io_out_info_bp_isNotTaken (_exec0_io_out_info_bp_isNotTaken),
    .io_out_info_bp_source     (_exec0_io_out_info_bp_source),
    .io_out_info_bp_isCall     (_exec0_io_out_info_bp_isCall),
    .io_out_info_bp_isRet      (_exec0_io_out_info_bp_isRet),
    .io_out_info_bp_isJmp      (_exec0_io_out_info_bp_isJmp),
    .io_out_info_result        (_exec0_io_out_info_result)
  );
  CL3EXU exec1 (
    .clock                     (clock),
    .reset                     (reset),
    .io_in_info_valid          (_issue_io_out_op_1_valid),
    .io_in_info_inst           (_issue_io_out_op_1_inst),
    .io_in_info_pc             (_issue_io_out_op_1_pc),
    .io_in_info_uop_op0        (_issue_io_out_op_1_uop_op0),
    .io_in_info_uop_op1        (_issue_io_out_op_1_uop_op1),
    .io_in_info_uop_op2        (_issue_io_out_op_1_uop_op2),
    .io_in_info_rs1            (_issue_io_out_op_1_rs1),
    .io_in_info_rs2            (_issue_io_out_op_1_rs2),
    .io_in_hold                (_issue_io_out_hold),
    .io_out_info_br_valid      (_exec1_io_out_info_br_valid),
    .io_out_info_br_pc         (_exec1_io_out_info_br_pc),
    .io_out_info_bp_valid      (_exec1_io_out_info_bp_valid),
    .io_out_info_bp_target     (_exec1_io_out_info_bp_target),
    .io_out_info_bp_isTaken    (_exec1_io_out_info_bp_isTaken),
    .io_out_info_bp_isNotTaken (_exec1_io_out_info_bp_isNotTaken),
    .io_out_info_bp_source     (_exec1_io_out_info_bp_source),
    .io_out_info_bp_isCall     (_exec1_io_out_info_bp_isCall),
    .io_out_info_bp_isRet      (_exec1_io_out_info_bp_isRet),
    .io_out_info_bp_isJmp      (_exec1_io_out_info_bp_isJmp),
    .io_out_info_result        (_exec1_io_out_info_result)
  );
  CL3EXU exec2 (
    .clock                     (clock),
    .reset                     (reset),
    .io_in_info_valid          (_issue_io_out_op_6_valid),
    .io_in_info_inst           (_issue_io_out_op_6_inst),
    .io_in_info_pc             (_issue_io_out_op_6_pc),
    .io_in_info_uop_op0        (_issue_io_out_op_6_uop_op0),
    .io_in_info_uop_op1        (_issue_io_out_op_6_uop_op1),
    .io_in_info_uop_op2        (_issue_io_out_op_6_uop_op2),
    .io_in_info_rs1            (_issue_io_out_op_6_rs1),
    .io_in_info_rs2            (_issue_io_out_op_6_rs2),
    .io_in_hold                (_issue_io_out_hold),
    .io_out_info_br_valid      (/* unused */),
    .io_out_info_br_pc         (/* unused */),
    .io_out_info_bp_valid      (/* unused */),
    .io_out_info_bp_target     (/* unused */),
    .io_out_info_bp_isTaken    (/* unused */),
    .io_out_info_bp_isNotTaken (/* unused */),
    .io_out_info_bp_source     (/* unused */),
    .io_out_info_bp_isCall     (/* unused */),
    .io_out_info_bp_isRet      (/* unused */),
    .io_out_info_bp_isJmp      (/* unused */),
    .io_out_info_result        (_exec2_io_out_info_result)
  );
  CL3EXU exec3 (
    .clock                     (clock),
    .reset                     (reset),
    .io_in_info_valid          (_issue_io_out_op_7_valid),
    .io_in_info_inst           (_issue_io_out_op_7_inst),
    .io_in_info_pc             (_issue_io_out_op_7_pc),
    .io_in_info_uop_op0        (_issue_io_out_op_7_uop_op0),
    .io_in_info_uop_op1        (_issue_io_out_op_7_uop_op1),
    .io_in_info_uop_op2        (_issue_io_out_op_7_uop_op2),
    .io_in_info_rs1            (_issue_io_out_op_7_rs1),
    .io_in_info_rs2            (_issue_io_out_op_7_rs2),
    .io_in_hold                (_issue_io_out_hold),
    .io_out_info_br_valid      (/* unused */),
    .io_out_info_br_pc         (/* unused */),
    .io_out_info_bp_valid      (/* unused */),
    .io_out_info_bp_target     (/* unused */),
    .io_out_info_bp_isTaken    (/* unused */),
    .io_out_info_bp_isNotTaken (/* unused */),
    .io_out_info_bp_source     (/* unused */),
    .io_out_info_bp_isCall     (/* unused */),
    .io_out_info_bp_isRet      (/* unused */),
    .io_out_info_bp_isJmp      (/* unused */),
    .io_out_info_result        (_exec3_io_out_info_result)
  );
endmodule

