// Generated by CIRCT firtool-1.133.0
module CL3CLINT(
  input         clock,
                reset,
  output        io_axi_aw_ready,
  input         io_axi_aw_valid,
  input  [31:0] io_axi_aw_bits_awaddr,
  output        io_axi_w_ready,
  input         io_axi_w_valid,
  input  [31:0] io_axi_w_bits_wdata,
  input         io_axi_b_ready,
  output        io_axi_b_valid,
                io_axi_ar_ready,
  input         io_axi_ar_valid,
  input  [31:0] io_axi_ar_bits_araddr,
  input         io_axi_r_ready,
  output        io_axi_r_valid,
  output [31:0] io_axi_r_bits_rdata,
  output        io_irq
);

  reg  [31:0] mtimel;
  reg  [31:0] mtimeh;
  reg  [31:0] mtimecmpl;
  reg  [31:0] mtimecmph;
  wire [63:0] mtimecmp = {mtimecmph, mtimecmpl};
  reg  [31:0] readDataReg;
  reg         rvalidReg;
  reg         awPending;
  reg         wPending;
  reg  [31:0] storedAddr;
  reg  [31:0] storedWdata;
  reg         bvalidReg;
  wire        io_axi_aw_ready_0 = ~awPending & ~bvalidReg;
  wire        io_axi_w_ready_0 = ~wPending & ~bvalidReg;
  wire [31:0] _nextLo_T = mtimel + 32'h1;
  wire        _GEN = ~rvalidReg & io_axi_ar_valid;
  wire        _GEN_0 = io_axi_aw_ready_0 & io_axi_aw_valid;
  wire        _GEN_1 = io_axi_w_ready_0 & io_axi_w_valid;
  wire        canWrite = awPending & wPending & ~bvalidReg;
  wire        _GEN_2 = storedAddr[15:0] == 16'h4004;
  always @(posedge clock) begin
    if (reset) begin
      mtimel <= 32'h0;
      mtimeh <= 32'h0;
      mtimecmpl <= 32'h0;
      mtimecmph <= 32'h0;
      readDataReg <= 32'h0;
      rvalidReg <= 1'h0;
      awPending <= 1'h0;
      wPending <= 1'h0;
      storedAddr <= 32'h0;
      storedWdata <= 32'h0;
      bvalidReg <= 1'h0;
    end
    else begin
      mtimel <= _nextLo_T;
      if (_nextLo_T == 32'h0)
        mtimeh <= mtimeh + 32'h1;
      if (~canWrite | _GEN_2 | storedAddr[15:0] != 16'h4000) begin
      end
      else
        mtimecmpl <= storedWdata;
      if (canWrite & _GEN_2)
        mtimecmph <= storedWdata;
      if (_GEN)
        readDataReg <=
          io_axi_ar_bits_araddr[15:0] == 16'hBFF8
            ? mtimel
            : io_axi_ar_bits_araddr[15:0] == 16'hBFFC ? mtimeh : 32'h0;
      rvalidReg <= ~(io_axi_r_ready & rvalidReg) & (_GEN | rvalidReg);
      awPending <= ~canWrite & (_GEN_0 | awPending);
      wPending <= ~canWrite & (_GEN_1 | wPending);
      if (_GEN_0)
        storedAddr <= io_axi_aw_bits_awaddr;
      if (_GEN_1)
        storedWdata <= io_axi_w_bits_wdata;
      bvalidReg <= ~(io_axi_b_ready & bvalidReg) & (canWrite | bvalidReg);
    end
  end // always @(posedge)
  assign io_axi_aw_ready = io_axi_aw_ready_0;
  assign io_axi_w_ready = io_axi_w_ready_0;
  assign io_axi_b_valid = bvalidReg;
  assign io_axi_ar_ready = ~rvalidReg;
  assign io_axi_r_valid = rvalidReg;
  assign io_axi_r_bits_rdata = readDataReg;
  assign io_irq = {mtimeh, mtimel} > mtimecmp & (|mtimecmp);
endmodule

