// Generated by CIRCT firtool-1.133.0
module CL3EXU(
  input         clock,
                reset,
                io_in_info_valid,
  input  [31:0] io_in_info_inst,
                io_in_info_pc,
  input  [3:0]  io_in_info_uop_op0,
  input  [2:0]  io_in_info_uop_op1,
                io_in_info_uop_op2,
  input  [31:0] io_in_info_rs1,
                io_in_info_rs2,
  input         io_in_hold,
  output        io_out_info_br_valid,
  output [31:0] io_out_info_br_pc,
  output        io_out_info_bp_valid,
  output [31:0] io_out_info_bp_target,
  output        io_out_info_bp_isTaken,
                io_out_info_bp_isNotTaken,
  output [31:0] io_out_info_bp_source,
  output        io_out_info_bp_isCall,
                io_out_info_bp_isRet,
                io_out_info_bp_isJmp,
  output [31:0] io_out_info_result
);

  wire [31:0] _alu_io_res;
  wire        _alu_io_eq;
  wire        _alu_io_lt;
  wire        _is_ret_T_1 = io_in_info_uop_op1 == 3'h2;
  wire        _is_ret_T = io_in_info_uop_op1 == 3'h0;
  wire [31:0] _GEN =
    {{20{io_in_info_inst[31]}},
     io_in_info_inst[7],
     io_in_info_inst[30:25],
     io_in_info_inst[11:8],
     1'h0};
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (io_in_info_uop_op2)
      3'b000:
        casez_tmp = 32'h0;
      3'b001:
        casez_tmp = io_in_info_rs2;
      3'b010:
        casez_tmp = 32'h0;
      3'b011:
        casez_tmp = 32'h0;
      3'b100:
        casez_tmp = {io_in_info_inst[31:12], 12'h0};
      3'b101:
        casez_tmp = {{20{io_in_info_inst[31]}}, io_in_info_inst[31:20]};
      3'b110:
        casez_tmp = _GEN;
      default:
        casez_tmp =
          {{12{io_in_info_inst[31]}},
           io_in_info_inst[19:12],
           io_in_info_inst[20],
           io_in_info_inst[30:21],
           1'h0};
    endcase
  end // always_comb
  wire        isJalr = io_in_info_uop_op0 == 4'h0;
  wire        _result_q_T = (&io_in_info_uop_op2) | isJalr;
  wire        taken =
    _result_q_T
    | (io_in_info_uop_op1 == 3'h5
         ? ~_alu_io_lt
         : io_in_info_uop_op1 == 3'h6
             ? ~_alu_io_eq
             : (&io_in_info_uop_op1)
                 ? _alu_io_lt
                 : io_in_info_uop_op1 == 3'h4 & _alu_io_eq);
  wire [31:0] _br_target_T = io_in_info_pc + _GEN;
  wire [31:0] _GEN_0 = {_alu_io_res[31:1], 1'h0};
  reg         bp_q_valid;
  reg  [31:0] bp_q_target;
  reg         bp_q_isTaken;
  reg         bp_q_isNotTaken;
  reg  [31:0] bp_q_source;
  reg         bp_q_isCall;
  reg         bp_q_isRet;
  reg         bp_q_isJmp;
  reg  [31:0] result_q;
  wire        is_ret =
    isJalr & (_is_ret_T | _is_ret_T_1 ? 5'h0 : io_in_info_inst[19:15]) == 5'h1
    & {{21{io_in_info_inst[31]}}, io_in_info_inst[31:20]} != 33'h1FFFFFFFF;
  always @(posedge clock) begin
    if (reset) begin
      bp_q_valid <= 1'h0;
      bp_q_target <= 32'h0;
      bp_q_isTaken <= 1'h0;
      bp_q_isNotTaken <= 1'h0;
      bp_q_source <= 32'h0;
      bp_q_isCall <= 1'h0;
      bp_q_isRet <= 1'h0;
      bp_q_isJmp <= 1'h0;
      result_q <= 32'h0;
    end
    else begin
      bp_q_valid <=
        io_in_info_valid & (io_in_info_uop_op1[2] | (&io_in_info_uop_op2) | isJalr);
      bp_q_target <= _result_q_T ? _GEN_0 : _br_target_T;
      bp_q_isTaken <= taken;
      bp_q_isNotTaken <= ~taken;
      bp_q_source <= io_in_info_pc;
      bp_q_isCall <=
        (&io_in_info_uop_op2) & io_in_info_inst[11:7] == 5'h1 | isJalr
        & io_in_info_inst[11:7] == 5'h1 & ~is_ret;
      bp_q_isRet <= is_ret;
      bp_q_isJmp <= _result_q_T;
      if (io_in_hold) begin
      end
      else
        result_q <= _result_q_T ? io_in_info_pc + 32'h4 : _alu_io_res;
    end
  end // always @(posedge)
  CL3ALU alu (
    .io_a   (_is_ret_T ? 32'h0 : _is_ret_T_1 ? io_in_info_pc : io_in_info_rs1),
    .io_b   (casez_tmp),
    .io_op  (io_in_info_uop_op0),
    .io_res (_alu_io_res),
    .io_eq  (_alu_io_eq),
    .io_lt  (_alu_io_lt)
  );
  assign io_out_info_br_valid = io_in_info_valid & taken;
  assign io_out_info_br_pc = _result_q_T ? _GEN_0 : _br_target_T;
  assign io_out_info_bp_valid = bp_q_valid;
  assign io_out_info_bp_target = bp_q_target;
  assign io_out_info_bp_isTaken = bp_q_isTaken;
  assign io_out_info_bp_isNotTaken = bp_q_isNotTaken;
  assign io_out_info_bp_source = bp_q_source;
  assign io_out_info_bp_isCall = bp_q_isCall;
  assign io_out_info_bp_isRet = bp_q_isRet;
  assign io_out_info_bp_isJmp = bp_q_isJmp;
  assign io_out_info_result = result_q;
endmodule

