// Generated by CIRCT firtool-1.133.0
module CL3LSU(
  input         clock,
                reset,
                io_in_info_valid,
  input  [31:0] io_in_info_inst,
                io_in_info_pc,
                io_in_info_rs1,
                io_in_info_rs2,
  input         io_in_mem_valid,
  input  [3:0]  io_in_mem_bits_err,
  input  [31:0] io_in_mem_bits_rdata,
  input         io_in_flush,
                io_out_mem_ready,
  output        io_out_mem_valid,
  output [31:0] io_out_mem_bits_addr,
                io_out_mem_bits_wdata,
  output [3:0]  io_out_mem_bits_mask,
  output        io_out_mem_bits_cacheable,
                io_out_mem_bits_atomic_isAmo,
                io_out_mem_bits_atomic_isLR,
                io_out_mem_bits_atomic_isSC,
  output [3:0]  io_out_mem_bits_atomic_amoCode,
  output        io_out_info_valid,
  output [31:0] io_out_info_rdata,
  output [5:0]  io_out_info_except_code,
  output [31:0] io_out_info_except_pc,
                io_out_info_except_tval,
  output        io_out_info_stall,
                io_out_info_cacheable
);

  wire [29:0] res_invInputs = ~(io_in_info_inst[31:2]);
  wire [4:0]  _res_andMatrixOutputs_T_1 =
    {io_in_info_inst[2],
     res_invInputs[25],
     res_invInputs[26],
     res_invInputs[27],
     res_invInputs[28]};
  wire [3:0]  _res_andMatrixOutputs_T_7 =
    {io_in_info_inst[2], res_invInputs[27], io_in_info_inst[30], res_invInputs[29]};
  wire [3:0]  _res_andMatrixOutputs_T_11 =
    {io_in_info_inst[2], res_invInputs[27], io_in_info_inst[30], io_in_info_inst[31]};
  wire [4:0]  res_LSUOP =
    {io_in_info_inst[2],
     |{&{res_invInputs[0], io_in_info_inst[5]},
       &{io_in_info_inst[2], io_in_info_inst[29], io_in_info_inst[31]},
       &_res_andMatrixOutputs_T_11},
     |{io_in_info_inst[12],
       &{res_invInputs[0], io_in_info_inst[13]},
       &{io_in_info_inst[2], io_in_info_inst[29], res_invInputs[29]},
       &_res_andMatrixOutputs_T_7,
       &{io_in_info_inst[2], res_invInputs[27], res_invInputs[28], io_in_info_inst[31]}},
     |{&{res_invInputs[0], res_invInputs[10]},
       &_res_andMatrixOutputs_T_1,
       &{io_in_info_inst[2], io_in_info_inst[27], res_invInputs[26]},
       &_res_andMatrixOutputs_T_7,
       &{io_in_info_inst[2],
         io_in_info_inst[29],
         io_in_info_inst[30],
         io_in_info_inst[31]}},
     |{&_res_andMatrixOutputs_T_1,
       io_in_info_inst[14],
       &{io_in_info_inst[2], io_in_info_inst[27], io_in_info_inst[28]},
       &{io_in_info_inst[2], io_in_info_inst[29], io_in_info_inst[30], res_invInputs[29]},
       &_res_andMatrixOutputs_T_11}};
  wire        is_ato = res_LSUOP[4];
  wire        is_load = ~(res_LSUOP[3]) & ~is_ato;
  wire        is_store = res_LSUOP[3] & ~is_ato;
  wire        complete_err_w = (|io_in_mem_bits_err) & io_in_mem_valid;
  reg         outstanding_q;
  wire        pending = outstanding_q & ~io_in_mem_valid;
  reg  [31:0] req_q_addr;
  reg         req_q_wen;
  reg  [31:0] req_q_wdata;
  reg  [3:0]  req_q_mask;
  reg         req_q_cacheable;
  reg         req_q_atomic_isAmo;
  reg         req_q_atomic_isLR;
  reg         req_q_atomic_isSC;
  reg  [3:0]  req_q_atomic_amoCode;
  reg  [4:0]  op_q;
  reg  [31:0] req_pc_q;
  reg         req_valid_q;
  reg         mem_unaligned_e1_q;
  reg         mem_unaligned_e2_q;
  wire        io_out_mem_valid_0 =
    req_valid_q & ~mem_unaligned_e1_q & ~pending & ~io_in_flush;
  wire        is_word_mask = (&req_q_mask) | op_q[4];
  wire        _half_data_T = req_q_mask == 4'hC;
  wire        is_half_mask = _half_data_T | req_q_mask == 4'h3;
  reg  [3:0]  req_record_q_mask;
  reg  [4:0]  req_record_q_op;
  reg         req_record_q_cacheable;
  reg  [31:0] req_record_q_addr;
  reg  [31:0] req_record_q_pc;
  wire [7:0]  lb_data =
    (req_record_q_mask[0] ? io_in_mem_bits_rdata[7:0] : 8'h0)
    | (req_record_q_mask[1] ? io_in_mem_bits_rdata[15:8] : 8'h0)
    | (req_record_q_mask[2] ? io_in_mem_bits_rdata[23:16] : 8'h0)
    | (req_record_q_mask[3] ? io_in_mem_bits_rdata[31:24] : 8'h0);
  wire [15:0] lh_data =
    (&(req_record_q_mask[1:0]))
      ? io_in_mem_bits_rdata[15:0]
      : io_in_mem_bits_rdata[31:16];
  wire        is_lr = is_ato & res_LSUOP[3:0] == 4'h0;
  wire        is_sc = is_ato & res_LSUOP[3:0] == 4'h1;
  wire [31:0] _addr_T_2 =
    io_in_info_rs1
    + (is_ato
         ? 32'h0
         : is_load
             ? {{20{io_in_info_inst[31]}}, io_in_info_inst[31:20]}
             : {{20{io_in_info_inst[31]}},
                io_in_info_inst[31:25],
                io_in_info_inst[11:7]});
  wire        _GEN = io_out_mem_ready & io_out_mem_valid_0;
  wire        _GEN_0 = io_in_info_valid & ~(req_valid_q & ~_GEN);
  wire        _GEN_1 = _GEN | mem_unaligned_e1_q;
  always @(posedge clock) begin
    if (reset) begin
      outstanding_q <= 1'h0;
      req_q_addr <= 32'h0;
      req_q_wen <= 1'h0;
      req_q_wdata <= 32'h0;
      req_q_mask <= 4'h0;
      req_q_cacheable <= 1'h0;
      req_q_atomic_isAmo <= 1'h0;
      req_q_atomic_isLR <= 1'h0;
      req_q_atomic_isSC <= 1'h0;
      req_q_atomic_amoCode <= 4'h0;
      op_q <= 5'h0;
      req_pc_q <= 32'h0;
      req_valid_q <= 1'h0;
      mem_unaligned_e1_q <= 1'h0;
      mem_unaligned_e2_q <= 1'h0;
      req_record_q_mask <= 4'h0;
      req_record_q_op <= 5'h0;
      req_record_q_cacheable <= 1'h0;
      req_record_q_addr <= 32'h0;
      req_record_q_pc <= 32'h0;
    end
    else begin
      outstanding_q <= _GEN | ~io_in_mem_valid & outstanding_q;
      if (io_in_flush | ~_GEN_0) begin
      end
      else begin
        req_q_addr <= _addr_T_2;
        req_q_wen <= is_store;
        req_q_wdata <= io_in_info_rs2;
        req_q_mask <=
          res_LSUOP[2:1] == 2'h1
            ? 4'h1 << _addr_T_2[1:0]
            : res_LSUOP[2:1] == 2'h2
                ? (_addr_T_2[1] ? 4'hC : 4'h3)
                : {4{&(res_LSUOP[2:1])}};
        req_q_cacheable <= _addr_T_2[31:28] == 4'h8;
        req_q_atomic_isAmo <= is_ato & ~(is_lr | is_sc);
        req_q_atomic_isLR <= is_lr;
        req_q_atomic_isSC <= is_sc;
        req_q_atomic_amoCode <= res_LSUOP[3:0];
        op_q <= res_LSUOP;
        req_pc_q <= io_in_info_pc;
      end
      req_valid_q <=
        ~io_in_flush & (_GEN_0 | ~(_GEN_1 & ~io_in_info_valid) & req_valid_q);
      mem_unaligned_e1_q <=
        ~io_in_flush
        & (_GEN_0
             ? ((&(res_LSUOP[2:1])) | is_ato) & (_addr_T_2[1] | _addr_T_2[0])
               | res_LSUOP[2:1] == 2'h2 & ~is_ato & _addr_T_2[0]
             : mem_unaligned_e1_q);
      mem_unaligned_e2_q <=
        ~io_in_flush & (pending ? mem_unaligned_e2_q : mem_unaligned_e1_q);
      if (_GEN_1) begin
        req_record_q_mask <= req_q_mask;
        req_record_q_op <= op_q;
        req_record_q_cacheable <= req_q_cacheable;
        req_record_q_addr <= req_q_addr;
        req_record_q_pc <= req_pc_q;
      end
    end
  end // always @(posedge)
  assign io_out_mem_valid = io_out_mem_valid_0;
  assign io_out_mem_bits_addr = req_q_addr;
  assign io_out_mem_bits_wdata =
    (is_word_mask ? req_q_wdata : 32'h0)
    | (is_half_mask
         ? (_half_data_T ? {req_q_wdata[15:0], 16'h0} : {16'h0, req_q_wdata[15:0]})
         : 32'h0)
    | ((|req_q_mask) & ~is_half_mask & ~is_word_mask
         ? (req_q_mask[0] ? {24'h0, req_q_wdata[7:0]} : 32'h0)
           | (req_q_mask[1] ? {16'h0, req_q_wdata[7:0], 8'h0} : 32'h0)
           | (req_q_mask[2] ? {8'h0, req_q_wdata[7:0], 16'h0} : 32'h0)
           | (req_q_mask[3] ? {req_q_wdata[7:0], 24'h0} : 32'h0)
         : 32'h0);
  assign io_out_mem_bits_mask = req_q_wen ? req_q_mask : 4'h0;
  assign io_out_mem_bits_cacheable = req_q_cacheable;
  assign io_out_mem_bits_atomic_isAmo = req_q_atomic_isAmo;
  assign io_out_mem_bits_atomic_isLR = req_q_atomic_isLR;
  assign io_out_mem_bits_atomic_isSC = req_q_atomic_isSC;
  assign io_out_mem_bits_atomic_amoCode = req_q_atomic_amoCode;
  assign io_out_info_valid = io_in_mem_valid & outstanding_q | mem_unaligned_e2_q;
  assign io_out_info_rdata =
    mem_unaligned_e2_q
      ? req_q_addr
      : req_record_q_op[4]
          ? io_in_mem_bits_rdata
          : req_record_q_op[2:0] == 3'h5
              ? {16'h0, lh_data}
              : req_record_q_op[2:0] == 3'h4
                  ? {{16{lh_data[15]}}, lh_data}
                  : req_record_q_op[2:0] == 3'h3
                      ? {24'h0, lb_data}
                      : req_record_q_op[2:0] == 3'h2
                          ? {{24{lb_data[7]}}, lb_data}
                          : io_in_mem_bits_rdata;
  assign io_out_info_except_code =
    mem_unaligned_e2_q & ~(op_q[3])
      ? 6'h14
      : mem_unaligned_e2_q & op_q[3]
          ? 6'h16
          : complete_err_w & ~(req_record_q_op[3])
              ? 6'h15
              : complete_err_w & req_record_q_op[3] ? 6'h17 : 6'h0;
  assign io_out_info_except_pc = req_record_q_pc;
  assign io_out_info_except_tval = req_record_q_addr;
  assign io_out_info_stall = pending | io_out_mem_valid_0 & ~io_out_mem_ready;
  assign io_out_info_cacheable = req_record_q_cacheable;
endmodule

