// Generated by CIRCT firtool-1.133.0
module CL3MMU(
  output        io_fetchIn_req_ready,
  input         io_fetchIn_req_valid,
  input  [31:0] io_fetchIn_req_bits_addr,
  output        io_fetchIn_resp_valid,
  output [3:0]  io_fetchIn_resp_bits_err,
  output [63:0] io_fetchIn_resp_bits_rdata,
  input         io_fetchOut_req_ready,
  output        io_fetchOut_req_valid,
  output [31:0] io_fetchOut_req_bits_addr,
  input         io_fetchOut_resp_valid,
  input  [3:0]  io_fetchOut_resp_bits_err,
  input  [63:0] io_fetchOut_resp_bits_rdata,
  output        io_lsuIn_req_ready,
  input         io_lsuIn_req_valid,
  input  [31:0] io_lsuIn_req_bits_addr,
                io_lsuIn_req_bits_wdata,
  input  [3:0]  io_lsuIn_req_bits_mask,
  input         io_lsuIn_req_bits_cacheable,
                io_lsuIn_req_bits_atomic_isAmo,
                io_lsuIn_req_bits_atomic_isLR,
                io_lsuIn_req_bits_atomic_isSC,
  input  [3:0]  io_lsuIn_req_bits_atomic_amoCode,
  output        io_lsuIn_resp_valid,
  output [3:0]  io_lsuIn_resp_bits_err,
  output [31:0] io_lsuIn_resp_bits_rdata,
  input         io_lsuOut_req_ready,
  output        io_lsuOut_req_valid,
  output [31:0] io_lsuOut_req_bits_addr,
                io_lsuOut_req_bits_wdata,
  output [3:0]  io_lsuOut_req_bits_mask,
  output        io_lsuOut_req_bits_cacheable,
                io_lsuOut_req_bits_atomic_isAmo,
                io_lsuOut_req_bits_atomic_isLR,
                io_lsuOut_req_bits_atomic_isSC,
  output [3:0]  io_lsuOut_req_bits_atomic_amoCode,
  input         io_lsuOut_resp_valid,
  input  [3:0]  io_lsuOut_resp_bits_err,
  input  [31:0] io_lsuOut_resp_bits_rdata
);

  assign io_fetchIn_req_ready = io_fetchOut_req_ready;
  assign io_fetchIn_resp_valid = io_fetchOut_resp_valid;
  assign io_fetchIn_resp_bits_err = io_fetchOut_resp_bits_err;
  assign io_fetchIn_resp_bits_rdata = io_fetchOut_resp_bits_rdata;
  assign io_fetchOut_req_valid = io_fetchIn_req_valid;
  assign io_fetchOut_req_bits_addr = io_fetchIn_req_bits_addr;
  assign io_lsuIn_req_ready = io_lsuOut_req_ready;
  assign io_lsuIn_resp_valid = io_lsuOut_resp_valid;
  assign io_lsuIn_resp_bits_err = io_lsuOut_resp_bits_err;
  assign io_lsuIn_resp_bits_rdata = io_lsuOut_resp_bits_rdata;
  assign io_lsuOut_req_valid = io_lsuIn_req_valid;
  assign io_lsuOut_req_bits_addr = io_lsuIn_req_bits_addr;
  assign io_lsuOut_req_bits_wdata = io_lsuIn_req_bits_wdata;
  assign io_lsuOut_req_bits_mask = io_lsuIn_req_bits_mask;
  assign io_lsuOut_req_bits_cacheable = io_lsuIn_req_bits_cacheable;
  assign io_lsuOut_req_bits_atomic_isAmo = io_lsuIn_req_bits_atomic_isAmo;
  assign io_lsuOut_req_bits_atomic_isLR = io_lsuIn_req_bits_atomic_isLR;
  assign io_lsuOut_req_bits_atomic_isSC = io_lsuIn_req_bits_atomic_isSC;
  assign io_lsuOut_req_bits_atomic_amoCode = io_lsuIn_req_bits_atomic_amoCode;
endmodule

