// Generated by CIRCT firtool-1.133.0
module CL3Pipe(
  input         clock,
                reset,
                io_in_issue_fire,
  input  [31:0] io_in_issue_info_inst,
                io_in_issue_info_pc,
  input         io_in_issue_info_wen,
                io_in_issue_info_isLSU,
                io_in_issue_info_isMUL,
                io_in_issue_info_isDIV,
                io_in_issue_info_isCSR,
                io_in_issue_info_isEXU,
                io_in_issue_info_isBr,
  input  [3:0]  io_in_issue_info_uop_op0,
  input  [2:0]  io_in_issue_info_uop_op1,
                io_in_issue_info_uop_op2,
  input  [31:0] io_in_issue_rs1,
                io_in_issue_rs2,
  input  [2:0]  io_in_issue_rs1_id,
                io_in_issue_rs2_id,
  input  [5:0]  io_in_issue_except_code,
  input  [31:0] io_in_issue_except_pc,
                io_in_issue_except_tval,
  input  [1:0]  io_in_issue_rdy_stage,
  input         io_in_lsu_valid,
  input  [31:0] io_in_lsu_rdata,
  input  [5:0]  io_in_lsu_except_code,
  input  [31:0] io_in_lsu_except_pc,
                io_in_lsu_except_tval,
  input         io_in_lsu_stall,
                io_in_lsu_cacheable,
  input  [31:0] io_in_exu_0_result,
  input         io_in_exu_0_br_valid,
  input  [31:0] io_in_exu_0_br_pc,
                io_in_exu_1_result,
  input         io_in_div_valid,
  input  [31:0] io_in_div_result,
                io_in_mul_result,
  input         io_in_csr_wen,
  input  [31:0] io_in_csr_rdata,
                io_in_csr_wdata,
  input  [5:0]  io_in_csr_except_code,
  input  [31:0] io_in_csr_except_pc,
                io_in_csr_except_tval,
  input         io_in_pipe_e1_stall,
  input  [31:0] io_in_pipe_e2_result,
  input         io_in_pipe_e2_stall,
  input  [31:0] io_in_pipe_wb_result,
  input         io_in_pipe_wb_stall,
                io_in_irq,
                io_in_e1_flush,
                io_in_e2_flush,
                io_in_wb_flush,
  input  [31:0] io_in_tvec,
                io_in_epc,
  output        io_out_e1_valid,
  output [31:0] io_out_e1_info_inst,
                io_out_e1_info_pc,
  output        io_out_e1_info_wen,
                io_out_e1_info_isLSU,
                io_out_e1_info_isMUL,
                io_out_e1_info_isEXU,
                io_out_e1_info_isBr,
  output [3:0]  io_out_e1_info_uop_op0,
  output [2:0]  io_out_e1_info_uop_op1,
                io_out_e1_info_uop_op2,
  output [31:0] io_out_e1_rs1,
                io_out_e1_rs2,
                io_out_e1_result,
  output [1:0]  io_out_e1_rdy_stage,
  output        io_out_e1_commit,
                io_out_e1_stall,
  output [5:0]  io_out_e1_except_code,
  output        io_out_e2_valid,
  output [31:0] io_out_e2_info_inst,
  output        io_out_e2_info_wen,
  output [31:0] io_out_e2_result,
  output [1:0]  io_out_e2_rdy_stage,
  output        io_out_e2_stall,
  output [5:0]  io_out_e2_except_code,
  output        io_out_wb_valid,
  output [31:0] io_out_wb_info_inst,
                io_out_wb_info_pc,
  output        io_out_wb_info_wen,
  output [31:0] io_out_wb_npc,
                io_out_wb_result,
  output [1:0]  io_out_wb_rdy_stage,
  output        io_out_wb_commit,
                io_out_wb_stall,
  output [11:0] io_out_wb_csr_waddr,
  output [31:0] io_out_wb_csr_wdata,
  output        io_out_wb_csr_wen,
  output [5:0]  io_out_wb_except_code,
  output [31:0] io_out_wb_except_pc,
                io_out_wb_except_tval,
  output        io_out_wb_mem_cacheable
);

  wire [5:0]  io_out_wb_except_code_0;
  wire        io_out_wb_info_wen_0;
  wire        io_out_wb_stall_0;
  wire [31:0] io_out_wb_result_0;
  wire        wb_stall;
  wire        io_out_e2_stall_0;
  wire [31:0] io_out_e2_result_0;
  wire        e2_stall;
  reg         e1_q_valid;
  reg  [31:0] e1_q_info_inst;
  reg  [31:0] e1_q_info_pc;
  reg         e1_q_info_wen;
  reg         e1_q_info_isLSU;
  reg         e1_q_info_isMUL;
  reg         e1_q_info_isDIV;
  reg         e1_q_info_isCSR;
  reg         e1_q_info_isEXU;
  reg         e1_q_info_isBr;
  reg  [3:0]  e1_q_info_uop_op0;
  reg  [2:0]  e1_q_info_uop_op1;
  reg  [2:0]  e1_q_info_uop_op2;
  reg  [31:0] e1_q_npc;
  reg  [31:0] e1_q_rs1;
  reg  [31:0] e1_q_rs2;
  reg  [2:0]  e1_q_rs1_id;
  reg  [2:0]  e1_q_rs2_id;
  reg  [1:0]  e1_q_rdy_stage;
  reg  [5:0]  e1_q_except_code;
  reg  [31:0] e1_q_except_pc;
  reg  [31:0] e1_q_except_tval;
  wire        io_out_e1_stall_0 =
    e2_stall | e1_q_valid & e1_q_info_isDIV & ~io_in_div_valid | e1_q_valid
    & e1_q_info_isLSU & e1_q_rdy_stage[0] & io_in_lsu_stall;
  reg         e2_q_valid;
  reg  [31:0] e2_q_info_inst;
  reg  [31:0] e2_q_info_pc;
  reg         e2_q_info_wen;
  reg         e2_q_info_isLSU;
  reg         e2_q_info_isMUL;
  reg  [31:0] e2_q_npc;
  reg  [31:0] e2_q_result;
  reg  [1:0]  e2_q_rdy_stage;
  reg  [31:0] e2_q_csr_wdata;
  reg         e2_q_csr_wen;
  reg  [5:0]  e2_q_except_code;
  reg  [31:0] e2_q_except_pc;
  reg  [31:0] e2_q_except_tval;
  assign e2_stall = io_in_pipe_e2_stall | io_out_e2_stall_0;
  wire        _wb_q_mem_cacheable_T_2 = e2_q_valid & e2_q_info_isLSU;
  wire        e2_is_waiting_lsu =
    _wb_q_mem_cacheable_T_2 & e2_q_rdy_stage[0] & ~(|e2_q_except_code);
  wire        io_out_e2_info_wen_0 = ~e2_stall & e2_q_info_wen;
  assign io_out_e2_result_0 =
    e2_q_valid & e2_q_info_isLSU & io_out_e2_info_wen_0
      ? io_in_lsu_rdata
      : e2_q_valid & e2_q_info_isMUL
          ? io_in_mul_result
          : e2_q_rdy_stage[0] ? io_in_exu_1_result : e2_q_result;
  assign io_out_e2_stall_0 =
    wb_stall | e2_is_waiting_lsu & ~io_in_lsu_valid | _wb_q_mem_cacheable_T_2
    & e2_q_rdy_stage[1] & ~(|e2_q_except_code) & io_in_lsu_stall;
  wire [5:0]  io_out_e2_except_code_0 =
    e2_is_waiting_lsu ? io_in_lsu_except_code : e2_q_except_code;
  reg         wb_q_valid;
  reg  [31:0] wb_q_info_inst;
  reg  [31:0] wb_q_info_pc;
  reg         wb_q_info_wen;
  reg         wb_q_info_isLSU;
  reg         wb_q_info_isMUL;
  reg  [31:0] wb_q_npc;
  reg  [31:0] wb_q_result;
  reg  [1:0]  wb_q_rdy_stage;
  reg  [11:0] wb_q_csr_waddr;
  reg  [31:0] wb_q_csr_wdata;
  reg         wb_q_csr_wen;
  reg  [5:0]  wb_q_except_code;
  reg  [31:0] wb_q_except_pc;
  reg  [31:0] wb_q_except_tval;
  reg         wb_q_mem_cacheable;
  assign wb_stall = io_in_pipe_wb_stall | io_out_wb_stall_0;
  wire        wb_is_waiting_lsu =
    wb_q_valid & wb_q_info_isLSU & wb_q_rdy_stage[1] & wb_q_except_code == 6'h0;
  reg  [31:0] wb_result_buf_q;
  reg         wb_result_buf_valid_q;
  wire        _io_out_wb_result_T = wb_q_valid & wb_q_info_isLSU;
  wire        _io_out_wb_result_T_4 = wb_q_valid & wb_q_info_isMUL;
  wire        _io_out_wb_result_T_3 =
    _io_out_wb_result_T & io_out_wb_info_wen_0 & wb_q_rdy_stage[1];
  wire        _io_out_wb_result_T_6 = _io_out_wb_result_T_4 & wb_q_rdy_stage[1];
  assign io_out_wb_result_0 =
    _io_out_wb_result_T_3
      ? io_in_lsu_rdata
      : _io_out_wb_result_T_6
          ? io_in_mul_result
          : wb_result_buf_valid_q ? wb_result_buf_q : wb_q_result;
  wire        io_out_wb_commit_0 = wb_q_valid & ~wb_stall & ~io_in_wb_flush;
  assign io_out_wb_stall_0 = wb_is_waiting_lsu & ~io_in_lsu_valid;
  assign io_out_wb_info_wen_0 = wb_q_info_wen & ~(|io_out_wb_except_code_0);
  assign io_out_wb_except_code_0 =
    (wb_is_waiting_lsu ? io_in_lsu_except_code : wb_q_except_code)
    & {6{io_out_wb_commit_0}};
  wire        branch_misaligned_w = io_in_exu_0_br_valid & (|(io_in_exu_0_br_pc[1:0]));
  wire        _e2_q_except_T_2 = e1_q_except_code == 6'h0 & e1_q_info_isCSR;
  wire        e1_stall = io_in_pipe_e1_stall | io_out_e1_stall_0;
  wire        e2_flush =
    e1_stall & ~e2_stall | io_in_e1_flush & ~e2_stall | io_in_e2_flush;
  wire        _GEN = ~e2_flush & ~e2_stall;
  wire        wb_flush = ~wb_stall & e2_stall | io_in_wb_flush;
  wire        _GEN_0 = ~wb_flush & ~wb_stall;
  wire        _GEN_1 =
    wb_flush & io_out_wb_commit_0
    & (_io_out_wb_result_T & io_out_wb_info_wen_0 | _io_out_wb_result_T_4);
  always @(posedge clock) begin
    if (reset) begin
      e1_q_valid <= 1'h0;
      e1_q_info_inst <= 32'h0;
      e1_q_info_pc <= 32'h0;
      e1_q_info_wen <= 1'h0;
      e1_q_info_isLSU <= 1'h0;
      e1_q_info_isMUL <= 1'h0;
      e1_q_info_isDIV <= 1'h0;
      e1_q_info_isCSR <= 1'h0;
      e1_q_info_isEXU <= 1'h0;
      e1_q_info_isBr <= 1'h0;
      e1_q_info_uop_op0 <= 4'h0;
      e1_q_info_uop_op1 <= 3'h0;
      e1_q_info_uop_op2 <= 3'h0;
      e1_q_npc <= 32'h0;
      e1_q_rs1 <= 32'h0;
      e1_q_rs2 <= 32'h0;
      e1_q_rs1_id <= 3'h0;
      e1_q_rs2_id <= 3'h0;
      e1_q_rdy_stage <= 2'h0;
      e1_q_except_code <= 6'h0;
      e1_q_except_pc <= 32'h0;
      e1_q_except_tval <= 32'h0;
      e2_q_valid <= 1'h0;
      e2_q_info_inst <= 32'h0;
      e2_q_info_pc <= 32'h0;
      e2_q_info_wen <= 1'h0;
      e2_q_info_isLSU <= 1'h0;
      e2_q_info_isMUL <= 1'h0;
      e2_q_npc <= 32'h0;
      e2_q_result <= 32'h0;
      e2_q_rdy_stage <= 2'h0;
      e2_q_csr_wdata <= 32'h0;
      e2_q_csr_wen <= 1'h0;
      e2_q_except_code <= 6'h0;
      e2_q_except_pc <= 32'h0;
      e2_q_except_tval <= 32'h0;
      wb_q_valid <= 1'h0;
      wb_q_info_inst <= 32'h0;
      wb_q_info_pc <= 32'h0;
      wb_q_info_wen <= 1'h0;
      wb_q_info_isLSU <= 1'h0;
      wb_q_info_isMUL <= 1'h0;
      wb_q_npc <= 32'h0;
      wb_q_result <= 32'h0;
      wb_q_rdy_stage <= 2'h0;
      wb_q_csr_waddr <= 12'h0;
      wb_q_csr_wdata <= 32'h0;
      wb_q_csr_wen <= 1'h0;
      wb_q_except_code <= 6'h0;
      wb_q_except_pc <= 32'h0;
      wb_q_except_tval <= 32'h0;
      wb_q_mem_cacheable <= 1'h0;
      wb_result_buf_q <= 32'h0;
      wb_result_buf_valid_q <= 1'h0;
    end
    else begin
      e1_q_valid <=
        ~io_in_e1_flush & ~e1_stall & io_in_issue_fire | ~io_in_e1_flush & e1_stall
        & e1_q_valid;
      if (io_in_issue_fire & ~io_in_e1_flush & ~e1_stall) begin
        e1_q_info_inst <= io_in_issue_info_inst;
        e1_q_info_pc <= io_in_issue_info_pc;
        e1_q_info_wen <= io_in_issue_info_wen;
        e1_q_info_isLSU <= io_in_issue_info_isLSU;
        e1_q_info_isMUL <= io_in_issue_info_isMUL;
        e1_q_info_isDIV <= io_in_issue_info_isDIV;
        e1_q_info_isCSR <= io_in_issue_info_isCSR;
        e1_q_info_isEXU <= io_in_issue_info_isEXU;
        e1_q_info_isBr <= io_in_issue_info_isBr;
        e1_q_info_uop_op0 <= io_in_issue_info_uop_op0;
        e1_q_info_uop_op1 <= io_in_issue_info_uop_op1;
        e1_q_info_uop_op2 <= io_in_issue_info_uop_op2;
        e1_q_npc <=
          io_in_exu_0_br_valid ? io_in_exu_0_br_pc : io_in_issue_info_pc + 32'h4;
        e1_q_rs1 <= io_in_issue_rs1;
        e1_q_rs2 <= io_in_issue_rs2;
        e1_q_rs1_id <= io_in_issue_rs1_id;
        e1_q_rs2_id <= io_in_issue_rs2_id;
        e1_q_rdy_stage <= io_in_issue_rdy_stage;
        e1_q_except_code <=
          io_in_irq
            ? 6'h20
            : (|io_in_issue_except_code)
                ? io_in_issue_except_code
                : {1'h0, branch_misaligned_w, 4'h0};
        e1_q_except_pc <=
          io_in_irq
            ? io_in_issue_info_pc
            : (|io_in_issue_except_code)
                ? io_in_issue_except_pc
                : branch_misaligned_w ? io_in_issue_info_pc : 32'h0;
        e1_q_except_tval <=
          io_in_irq
            ? 32'h0
            : (|io_in_issue_except_code)
                ? io_in_issue_except_tval
                : branch_misaligned_w ? io_in_exu_0_br_pc : 32'h0;
      end
      e2_q_valid <=
        _GEN
          ? e1_q_valid
          : ~e2_flush & ~e2_stall & e1_q_valid | ~e2_flush & e2_stall & e2_q_valid;
      if (_GEN) begin
        e2_q_info_inst <= e1_q_info_inst;
        e2_q_info_pc <= e1_q_info_pc;
        e2_q_info_wen <= e1_q_info_wen;
        e2_q_info_isLSU <= e1_q_info_isLSU;
        e2_q_info_isMUL <= e1_q_info_isMUL;
        e2_q_npc <= e1_q_npc;
        e2_q_result <=
          e1_q_info_isDIV
            ? io_in_div_result
            : e1_q_info_isCSR ? io_in_csr_rdata : io_in_exu_0_result;
        e2_q_rdy_stage <= e1_q_rdy_stage;
        e2_q_csr_wdata <= io_in_csr_wdata;
        e2_q_csr_wen <= io_in_csr_wen & e1_q_info_isCSR;
        e2_q_except_code <= _e2_q_except_T_2 ? io_in_csr_except_code : e1_q_except_code;
        e2_q_except_pc <= _e2_q_except_T_2 ? io_in_csr_except_pc : e1_q_except_pc;
        e2_q_except_tval <= _e2_q_except_T_2 ? io_in_csr_except_tval : e1_q_except_tval;
      end
      wb_q_valid <=
        _GEN_0
          ? e2_q_valid
          : ~wb_flush & ~wb_stall & e2_q_valid | ~wb_flush & wb_stall & wb_q_valid;
      if (_GEN_0) begin
        wb_q_info_inst <= e2_q_info_inst;
        wb_q_info_pc <= e2_q_info_pc;
        wb_q_info_wen <= e2_q_info_wen;
        wb_q_info_isLSU <= e2_q_info_isLSU;
        wb_q_info_isMUL <= e2_q_info_isMUL;
        wb_q_npc <= e2_q_npc;
        wb_q_result <= io_out_e2_result_0;
        wb_q_rdy_stage <= e2_q_rdy_stage;
        wb_q_csr_waddr <= e2_q_csr_wen ? e2_q_info_inst[31:20] : 12'h0;
        wb_q_csr_wdata <= e2_q_csr_wdata;
        wb_q_csr_wen <= e2_q_csr_wen;
        wb_q_except_code <= io_out_e2_except_code_0;
        wb_q_except_pc <= e2_is_waiting_lsu ? io_in_lsu_except_pc : e2_q_except_pc;
        wb_q_except_tval <= e2_is_waiting_lsu ? io_in_lsu_except_tval : e2_q_except_tval;
        wb_q_mem_cacheable <=
          ~(_wb_q_mem_cacheable_T_2 & e2_q_info_wen | _wb_q_mem_cacheable_T_2
            & ~e2_q_info_wen) | io_in_lsu_cacheable;
      end
      if (_GEN_1) begin
        if (_io_out_wb_result_T_3)
          wb_result_buf_q <= io_in_lsu_rdata;
        else if (_io_out_wb_result_T_6)
          wb_result_buf_q <= io_in_mul_result;
        else if (wb_result_buf_valid_q) begin
        end
        else
          wb_result_buf_q <= wb_q_result;
      end
      wb_result_buf_valid_q <= _GEN_1 | ~_GEN_0 & wb_result_buf_valid_q;
    end
  end // always @(posedge)
  assign io_out_e1_valid = e1_q_valid;
  assign io_out_e1_info_inst = e1_q_info_inst;
  assign io_out_e1_info_pc = e1_q_info_pc;
  assign io_out_e1_info_wen = e1_q_info_wen;
  assign io_out_e1_info_isLSU = e1_q_info_isLSU;
  assign io_out_e1_info_isMUL = e1_q_info_isMUL;
  assign io_out_e1_info_isEXU = e1_q_info_isEXU;
  assign io_out_e1_info_isBr = e1_q_info_isBr;
  assign io_out_e1_info_uop_op0 = e1_q_info_uop_op0;
  assign io_out_e1_info_uop_op1 = e1_q_info_uop_op1;
  assign io_out_e1_info_uop_op2 = e1_q_info_uop_op2;
  assign io_out_e1_rs1 =
    e1_q_rs1_id == 3'h5
      ? io_in_pipe_wb_result
      : e1_q_rs1_id == 3'h4
          ? io_out_wb_result_0
          : e1_q_rs1_id == 3'h3
              ? io_in_pipe_e2_result
              : e1_q_rs1_id == 3'h2 ? io_out_e2_result_0 : e1_q_rs1;
  assign io_out_e1_rs2 =
    e1_q_rs2_id == 3'h5
      ? io_in_pipe_wb_result
      : e1_q_rs2_id == 3'h4
          ? io_out_wb_result_0
          : e1_q_rs2_id == 3'h3
              ? io_in_pipe_e2_result
              : e1_q_rs2_id == 3'h2 ? io_out_e2_result_0 : e1_q_rs2;
  assign io_out_e1_result = io_in_exu_0_result;
  assign io_out_e1_rdy_stage = e1_q_rdy_stage;
  assign io_out_e1_commit = e1_q_valid & ~io_out_e1_stall_0;
  assign io_out_e1_stall = io_out_e1_stall_0;
  assign io_out_e1_except_code = e1_q_except_code;
  assign io_out_e2_valid = e2_q_valid;
  assign io_out_e2_info_inst = e2_q_info_inst;
  assign io_out_e2_info_wen = io_out_e2_info_wen_0;
  assign io_out_e2_result = io_out_e2_result_0;
  assign io_out_e2_rdy_stage = e2_q_rdy_stage;
  assign io_out_e2_stall = io_out_e2_stall_0;
  assign io_out_e2_except_code = io_out_e2_except_code_0;
  assign io_out_wb_valid = wb_q_valid;
  assign io_out_wb_info_inst = wb_q_info_inst;
  assign io_out_wb_info_pc = wb_q_info_pc;
  assign io_out_wb_info_wen = io_out_wb_info_wen_0;
  assign io_out_wb_npc =
    (|io_out_wb_except_code_0)
      ? (io_out_wb_except_code_0 == 6'h33 ? io_in_epc : io_in_tvec)
      : wb_q_npc;
  assign io_out_wb_result = io_out_wb_result_0;
  assign io_out_wb_rdy_stage = wb_q_rdy_stage;
  assign io_out_wb_commit = io_out_wb_commit_0;
  assign io_out_wb_stall = io_out_wb_stall_0;
  assign io_out_wb_csr_waddr = wb_q_csr_waddr;
  assign io_out_wb_csr_wdata = wb_q_csr_wdata;
  assign io_out_wb_csr_wen = wb_q_csr_wen & ~(|io_out_wb_except_code_0);
  assign io_out_wb_except_code = io_out_wb_except_code_0;
  assign io_out_wb_except_pc = wb_is_waiting_lsu ? io_in_lsu_except_pc : wb_q_except_pc;
  assign io_out_wb_except_tval =
    wb_is_waiting_lsu ? io_in_lsu_except_tval : wb_q_except_tval;
  assign io_out_wb_mem_cacheable =
    wb_q_rdy_stage[1] ? io_in_lsu_cacheable : wb_q_mem_cacheable;
endmodule

