// Generated by CIRCT firtool-1.133.0
module CL3Xbar(
  input         clock,
                reset,
  output        io_xbar_aw_ready,
  input         io_xbar_aw_valid,
  input  [31:0] io_xbar_aw_bits_awaddr,
  input  [7:0]  io_xbar_aw_bits_awlen,
  output        io_xbar_w_ready,
  input         io_xbar_w_valid,
  input  [31:0] io_xbar_w_bits_wdata,
  input  [3:0]  io_xbar_w_bits_wstrb,
  input         io_xbar_w_bits_wlast,
  output        io_xbar_b_valid,
  output [1:0]  io_xbar_b_bits_bresp,
  output        io_xbar_ar_ready,
  input         io_xbar_ar_valid,
  input  [31:0] io_xbar_ar_bits_araddr,
  input  [7:0]  io_xbar_ar_bits_arlen,
  input  [2:0]  io_xbar_ar_bits_arsize,
  input  [1:0]  io_xbar_ar_bits_arburst,
  input  [3:0]  io_xbar_ar_bits_arcache,
  output        io_xbar_r_valid,
  output [1:0]  io_xbar_r_bits_rresp,
  output [31:0] io_xbar_r_bits_rdata,
  output        io_xbar_r_bits_rlast,
  input         io_clint_aw_ready,
  output        io_clint_aw_valid,
  output [31:0] io_clint_aw_bits_awaddr,
  input         io_clint_w_ready,
  output        io_clint_w_valid,
  output [31:0] io_clint_w_bits_wdata,
  output        io_clint_b_ready,
  input         io_clint_b_valid,
                io_clint_ar_ready,
  output        io_clint_ar_valid,
  output [31:0] io_clint_ar_bits_araddr,
  output        io_clint_r_ready,
  input         io_clint_r_valid,
  input  [31:0] io_clint_r_bits_rdata,
  input         io_top_aw_ready,
  output        io_top_aw_valid,
  output [31:0] io_top_aw_bits_awaddr,
  output [7:0]  io_top_aw_bits_awlen,
  input         io_top_w_ready,
  output        io_top_w_valid,
  output [31:0] io_top_w_bits_wdata,
  output [3:0]  io_top_w_bits_wstrb,
  output        io_top_w_bits_wlast,
                io_top_b_ready,
  input         io_top_b_valid,
  input  [1:0]  io_top_b_bits_bresp,
  input         io_top_ar_ready,
  output        io_top_ar_valid,
  output [31:0] io_top_ar_bits_araddr,
  output [7:0]  io_top_ar_bits_arlen,
  output [2:0]  io_top_ar_bits_arsize,
  output [1:0]  io_top_ar_bits_arburst,
  output [3:0]  io_top_ar_bits_arcache,
  output        io_top_r_ready,
  input         io_top_r_valid,
  input  [1:0]  io_top_r_bits_rresp,
  input  [31:0] io_top_r_bits_rdata,
  input         io_top_r_bits_rlast
);

  wire arToClint = io_xbar_ar_bits_araddr[31:24] == 8'h2;
  reg  readActive;
  reg  readSelClint;
  wire io_xbar_ar_ready_0 =
    (arToClint ? io_clint_ar_ready : io_top_ar_ready) & ~readActive;
  wire io_xbar_r_valid_0 = readSelClint ? io_clint_r_valid : io_top_r_valid;
  wire io_xbar_r_bits_rlast_0 = readSelClint | io_top_r_bits_rlast;
  wire awToClint = io_xbar_aw_bits_awaddr[31:24] == 8'h2;
  reg  writeActiveReg;
  reg  writeSelClintReg;
  wire io_xbar_aw_ready_0 =
    (awToClint ? io_clint_aw_ready : io_top_aw_ready) & ~writeActiveReg;
  wire _haveWriteSel_T = io_xbar_aw_ready_0 & io_xbar_aw_valid;
  wire haveWriteSel = writeActiveReg | _haveWriteSel_T;
  wire curWriteSelClint = writeActiveReg ? writeSelClintReg : awToClint;
  wire _io_top_w_valid_T = io_xbar_w_valid & haveWriteSel;
  wire io_xbar_b_valid_0 = writeSelClintReg ? io_clint_b_valid : io_top_b_valid;
  wire _GEN = io_xbar_ar_ready_0 & io_xbar_ar_valid;
  always @(posedge clock) begin
    if (reset) begin
      readActive <= 1'h0;
      readSelClint <= 1'h0;
      writeActiveReg <= 1'h0;
      writeSelClintReg <= 1'h0;
    end
    else begin
      readActive <= ~(io_xbar_r_valid_0 & io_xbar_r_bits_rlast_0) & (_GEN | readActive);
      if (_GEN)
        readSelClint <= arToClint;
      writeActiveReg <= ~io_xbar_b_valid_0 & (_haveWriteSel_T | writeActiveReg);
      if (_haveWriteSel_T)
        writeSelClintReg <= awToClint;
    end
  end // always @(posedge)
  assign io_xbar_aw_ready = io_xbar_aw_ready_0;
  assign io_xbar_w_ready =
    (curWriteSelClint ? io_clint_w_ready : io_top_w_ready) & haveWriteSel;
  assign io_xbar_b_valid = io_xbar_b_valid_0;
  assign io_xbar_b_bits_bresp = writeSelClintReg ? 2'h0 : io_top_b_bits_bresp;
  assign io_xbar_ar_ready = io_xbar_ar_ready_0;
  assign io_xbar_r_valid = io_xbar_r_valid_0;
  assign io_xbar_r_bits_rresp = readSelClint ? 2'h0 : io_top_r_bits_rresp;
  assign io_xbar_r_bits_rdata =
    readSelClint ? io_clint_r_bits_rdata : io_top_r_bits_rdata;
  assign io_xbar_r_bits_rlast = io_xbar_r_bits_rlast_0;
  assign io_clint_aw_valid = io_xbar_aw_valid & awToClint & ~writeActiveReg;
  assign io_clint_aw_bits_awaddr = io_xbar_aw_bits_awaddr;
  assign io_clint_w_valid = _io_top_w_valid_T & curWriteSelClint;
  assign io_clint_w_bits_wdata = io_xbar_w_bits_wdata;
  assign io_clint_b_ready = writeSelClintReg;
  assign io_clint_ar_valid = io_xbar_ar_valid & arToClint & ~readActive;
  assign io_clint_ar_bits_araddr = io_xbar_ar_bits_araddr;
  assign io_clint_r_ready = readSelClint;
  assign io_top_aw_valid =
    io_xbar_aw_valid & io_xbar_aw_bits_awaddr[31:24] != 8'h2 & ~writeActiveReg;
  assign io_top_aw_bits_awaddr = io_xbar_aw_bits_awaddr;
  assign io_top_aw_bits_awlen = io_xbar_aw_bits_awlen;
  assign io_top_w_valid = _io_top_w_valid_T & ~curWriteSelClint;
  assign io_top_w_bits_wdata = io_xbar_w_bits_wdata;
  assign io_top_w_bits_wstrb = io_xbar_w_bits_wstrb;
  assign io_top_w_bits_wlast = io_xbar_w_bits_wlast;
  assign io_top_b_ready = ~writeSelClintReg;
  assign io_top_ar_valid =
    io_xbar_ar_valid & io_xbar_ar_bits_araddr[31:24] != 8'h2 & ~readActive;
  assign io_top_ar_bits_araddr = io_xbar_ar_bits_araddr;
  assign io_top_ar_bits_arlen = io_xbar_ar_bits_arlen;
  assign io_top_ar_bits_arsize = io_xbar_ar_bits_arsize;
  assign io_top_ar_bits_arburst = io_xbar_ar_bits_arburst;
  assign io_top_ar_bits_arcache = io_xbar_ar_bits_arcache;
  assign io_top_r_ready = ~readSelClint;
endmodule

