// Generated by CIRCT firtool-1.133.0
module dcache_core_tag_ram(
  input         clock,
  input  [6:0]  io_p0_addr,
  output [20:0] io_p0_rdata,
  input  [6:0]  io_p1_addr,
  input  [20:0] io_p1_wdata,
  input         io_p1_wen
);

  dcache_core_tag_ramDev m (
    .clock       (clock),
    .io_p0_addr  (io_p0_addr),
    .io_p0_rdata (io_p0_rdata),
    .io_p1_addr  (io_p1_addr),
    .io_p1_wdata (io_p1_wdata),
    .io_p1_wen   (io_p1_wen)
  );
endmodule

