// Generated by CIRCT firtool-1.133.0
module dcache_mux(
  input         clock,
                reset,
  input  [31:0] io_cpu_req_addr,
                io_cpu_req_dataWr,
  input         io_cpu_req_rd,
  input  [3:0]  io_cpu_req_wr,
  input         io_cpu_req_cacheable,
  output [31:0] io_cpu_resp_dataRd,
  output        io_cpu_resp_ack,
                io_cpu_resp_error,
                io_cpu_accept,
  output [31:0] io_backs_cached_req_addr,
                io_backs_cached_req_dataWr,
  output        io_backs_cached_req_rd,
  output [3:0]  io_backs_cached_req_wr,
  input  [31:0] io_backs_cached_resp_dataRd,
  input         io_backs_cached_resp_ack,
                io_backs_cached_resp_error,
                io_backs_cached_accept,
  output [31:0] io_backs_uncached_req_addr,
                io_backs_uncached_req_dataWr,
  output        io_backs_uncached_req_rd,
  output [3:0]  io_backs_uncached_req_wr,
  input  [31:0] io_backs_uncached_resp_dataRd,
  input         io_backs_uncached_resp_ack,
                io_backs_uncached_resp_error,
                io_backs_uncached_accept,
  output        io_cacheActive
);

  wire       hold_w;
  reg        cache_access_q;
  wire       io_cpu_accept_0 =
    (io_cpu_req_cacheable ? io_backs_cached_accept : io_backs_uncached_accept) & ~hold_w;
  wire       io_cpu_resp_ack_0 =
    cache_access_q ? io_backs_cached_resp_ack : io_backs_uncached_resp_ack;
  reg  [4:0] pending_q;
  assign hold_w = (|pending_q) & cache_access_q != io_cpu_req_cacheable;
  wire       _GEN = io_cpu_req_rd & io_cpu_accept_0;
  always @(posedge clock) begin
    if (reset) begin
      cache_access_q <= 1'h0;
      pending_q <= 5'h0;
    end
    else begin
      if (_GEN)
        cache_access_q <= io_cpu_req_cacheable;
      if (_GEN & ~io_cpu_resp_ack_0)
        pending_q <= pending_q + 5'h1;
      else if (~_GEN & io_cpu_resp_ack_0)
        pending_q <= pending_q - 5'h1;
    end
  end // always @(posedge)
  assign io_cpu_resp_dataRd =
    cache_access_q ? io_backs_cached_resp_dataRd : io_backs_uncached_resp_dataRd;
  assign io_cpu_resp_ack = io_cpu_resp_ack_0;
  assign io_cpu_resp_error =
    cache_access_q ? io_backs_cached_resp_error : io_backs_uncached_resp_error;
  assign io_cpu_accept = io_cpu_accept_0;
  assign io_backs_cached_req_addr = io_cpu_req_addr;
  assign io_backs_cached_req_dataWr = io_cpu_req_dataWr;
  assign io_backs_cached_req_rd = io_cpu_req_cacheable & ~hold_w & io_cpu_req_rd;
  assign io_backs_cached_req_wr = io_cpu_req_cacheable & ~hold_w ? io_cpu_req_wr : 4'h0;
  assign io_backs_uncached_req_addr = io_cpu_req_addr;
  assign io_backs_uncached_req_dataWr = io_cpu_req_dataWr;
  assign io_backs_uncached_req_rd = ~io_cpu_req_cacheable & ~hold_w & io_cpu_req_rd;
  assign io_backs_uncached_req_wr = io_cpu_req_cacheable | hold_w ? 4'h0 : io_cpu_req_wr;
  assign io_cacheActive = (|pending_q) ? cache_access_q : io_cpu_req_cacheable;
endmodule

