// Generated by CIRCT firtool-1.133.0
module dcache_if_pmem(
  input         clock,
                reset,
  input  [31:0] io_cpu_req_addr,
                io_cpu_req_dataWr,
  input         io_cpu_req_rd,
  input  [3:0]  io_cpu_req_wr,
  output [31:0] io_cpu_resp_dataRd,
  output        io_cpu_resp_ack,
                io_cpu_resp_error,
                io_cpu_accept,
  output [3:0]  io_pmem_req_wr,
  output        io_pmem_req_rd,
  output [31:0] io_pmem_req_addr,
                io_pmem_req_writeData,
  input         io_pmem_resp_accept,
                io_pmem_resp_ack,
                io_pmem_resp_error,
  input  [31:0] io_pmem_resp_readData
);

  wire        u_resp_io_pop_i;
  wire        _u_resp_io_accept_o;
  wire [69:0] _u_req_io_out_data;
  wire        _u_req_io_accept_o;
  wire        _u_req_io_valid_o;
  reg         request_pending_q;
  wire        request_in_progress_w = request_pending_q & ~u_resp_io_pop_i;
  wire        req_is_read_w =
    _u_req_io_valid_o & ~request_in_progress_w & _u_req_io_out_data[68];
  wire        req_is_drop_w =
    _u_req_io_valid_o & ~request_in_progress_w & _u_req_io_out_data[69];
  wire [3:0]  io_pmem_req_wr_0 =
    _u_req_io_valid_o & ~request_in_progress_w & ~(_u_req_io_out_data[68])
      ? _u_req_io_out_data[67:64]
      : 4'h0;
  wire        request_complete_w =
    req_is_drop_w | (|{req_is_read_w, io_pmem_req_wr_0}) & io_pmem_resp_accept;
  reg         dropped_q;
  assign u_resp_io_pop_i = dropped_q | io_pmem_resp_ack;
  always @(posedge clock) begin
    if (reset) begin
      request_pending_q <= 1'h0;
      dropped_q <= 1'h0;
    end
    else begin
      request_pending_q <= request_complete_w | ~u_resp_io_pop_i & request_pending_q;
      dropped_q <= req_is_drop_w;
    end
  end // always @(posedge)
  dcache_if_pmem_fifo u_req (
    .clock       (clock),
    .reset       (reset),
    .io_in_data
      ({1'h0, io_cpu_req_wr == 4'h0, io_cpu_req_wr, io_cpu_req_dataWr, io_cpu_req_addr}),
    .io_push_i   (io_cpu_req_rd & _u_resp_io_accept_o),
    .io_pop_i    (request_complete_w),
    .io_out_data (_u_req_io_out_data),
    .io_accept_o (_u_req_io_accept_o),
    .io_valid_o  (_u_req_io_valid_o)
  );
  dcache_if_pmem_fifo_1 u_resp (
    .clock       (clock),
    .reset       (reset),
    .io_push_i   (io_cpu_req_rd & _u_req_io_accept_o),
    .io_pop_i    (u_resp_io_pop_i),
    .io_accept_o (_u_resp_io_accept_o)
  );
  assign io_cpu_resp_dataRd = io_pmem_resp_readData;
  assign io_cpu_resp_ack = u_resp_io_pop_i;
  assign io_cpu_resp_error = io_pmem_resp_error;
  assign io_cpu_accept = _u_req_io_accept_o & _u_resp_io_accept_o;
  assign io_pmem_req_wr = io_pmem_req_wr_0;
  assign io_pmem_req_rd = req_is_read_w;
  assign io_pmem_req_addr = {_u_req_io_out_data[31:2], 2'h0};
  assign io_pmem_req_writeData = _u_req_io_out_data[63:32];
endmodule

