// Generated by CIRCT firtool-1.133.0
module DCacheAxiFifo(
  input         clock,
                reset,
  input  [76:0] io_in_data,
  input         io_push_i,
                io_pop_i,
  output [76:0] io_out_data,
  output        io_accept_o,
                io_valid_o
);

  reg  [76:0] ram_q_0;
  reg  [76:0] ram_q_1;
  reg         rd_ptr_q;
  reg         wr_ptr_q;
  reg  [1:0]  count_q;
  wire        io_accept_o_0 = count_q != 2'h2;
  wire        _GEN = io_push_i & io_accept_o_0;
  wire        _GEN_0 = io_pop_i & (|count_q);
  always @(posedge clock) begin
    if (reset) begin
      ram_q_0 <= 77'h0;
      ram_q_1 <= 77'h0;
      rd_ptr_q <= 1'h0;
      wr_ptr_q <= 1'h0;
      count_q <= 2'h0;
    end
    else begin
      if (_GEN & ~wr_ptr_q)
        ram_q_0 <= io_in_data;
      if (_GEN & wr_ptr_q)
        ram_q_1 <= io_in_data;
      if (_GEN_0)
        rd_ptr_q <= rd_ptr_q - 1'h1;
      if (_GEN)
        wr_ptr_q <= wr_ptr_q - 1'h1;
      if (_GEN & ~_GEN_0)
        count_q <= count_q + 2'h1;
      else if (~_GEN & _GEN_0)
        count_q <= count_q - 2'h1;
    end
  end // always @(posedge)
  assign io_out_data = rd_ptr_q ? ram_q_1 : ram_q_0;
  assign io_accept_o = io_accept_o_0;
  assign io_valid_o = |count_q;
endmodule

