// Generated by CIRCT firtool-1.133.0
module dcache_if_pmem_fifo_1(
  input  clock,
         reset,
         io_push_i,
         io_pop_i,
  output io_accept_o
);

  reg  [1:0] count_q;
  wire       io_accept_o_0 = count_q != 2'h2;
  wire       _GEN = io_push_i & io_accept_o_0;
  always @(posedge clock) begin
    if (reset)
      count_q <= 2'h0;
    else if (_GEN & ~(io_pop_i & (|count_q)))
      count_q <= count_q + 2'h1;
    else if (~_GEN & io_pop_i & (|count_q))
      count_q <= count_q - 2'h1;
  end // always @(posedge)
  assign io_accept_o = io_accept_o_0;
endmodule

