// Generated by CIRCT firtool-1.133.0
module dcache_pmem_mux(
  input         clock,
                reset,
  output [3:0]  io_outport_req_wr,
  output        io_outport_req_rd,
  output [7:0]  io_outport_req_len,
  output [31:0] io_outport_req_addr,
                io_outport_req_writeData,
  input         io_outport_resp_accept,
                io_outport_resp_ack,
                io_outport_resp_error,
  input  [31:0] io_outport_resp_readData,
  input  [3:0]  io_in0port_req_wr,
  input         io_in0port_req_rd,
  input  [31:0] io_in0port_req_addr,
                io_in0port_req_writeData,
  output        io_in0port_resp_accept,
                io_in0port_resp_ack,
                io_in0port_resp_error,
  output [31:0] io_in0port_resp_readData,
  input  [3:0]  io_in1port_req_wr,
  input         io_in1port_req_rd,
  input  [7:0]  io_in1port_req_len,
  input  [31:0] io_in1port_req_addr,
                io_in1port_req_writeData,
  output        io_in1port_resp_accept,
                io_in1port_resp_ack,
                io_in1port_resp_error,
  output [31:0] io_in1port_resp_readData,
  input         io_select_i
);

  reg select_q;
  always @(posedge clock) begin
    if (reset)
      select_q <= 1'h0;
    else
      select_q <= io_select_i;
  end // always @(posedge)
  assign io_outport_req_wr = select_q ? io_in1port_req_wr : io_in0port_req_wr;
  assign io_outport_req_rd = select_q ? io_in1port_req_rd : io_in0port_req_rd;
  assign io_outport_req_len = select_q ? io_in1port_req_len : 8'h0;
  assign io_outport_req_addr = select_q ? io_in1port_req_addr : io_in0port_req_addr;
  assign io_outport_req_writeData =
    select_q ? io_in1port_req_writeData : io_in0port_req_writeData;
  assign io_in0port_resp_accept = ~io_select_i & io_outport_resp_accept;
  assign io_in0port_resp_ack = ~select_q & io_outport_resp_ack;
  assign io_in0port_resp_error = ~select_q & io_outport_resp_error;
  assign io_in0port_resp_readData = io_outport_resp_readData;
  assign io_in1port_resp_accept = io_select_i & io_outport_resp_accept;
  assign io_in1port_resp_ack = select_q & io_outport_resp_ack;
  assign io_in1port_resp_error = select_q & io_outport_resp_error;
  assign io_in1port_resp_readData = io_outport_resp_readData;
endmodule

