// Generated by CIRCT firtool-1.133.0
module dcache_core_data_ram(
  input         clock,
  input  [9:0]  io_p0_addr,
  output [31:0] io_p0_rdata,
  input  [9:0]  io_p1_addr,
  input  [31:0] io_p1_wdata,
  input  [3:0]  io_p1_wstrb
);

  dcache_core_data_ramDev m (
    .clock       (clock),
    .io_p0_addr  (io_p0_addr),
    .io_p0_rdata (io_p0_rdata),
    .io_p1_addr  (io_p1_addr),
    .io_p1_wdata (io_p1_wdata),
    .io_p1_wstrb (io_p1_wstrb)
  );
endmodule

