// Generated by CIRCT firtool-1.133.0
module FetchFIFO(
  input         clock,
                reset,
                io_flush,
  output        io_in_ready,
  input         io_in_valid,
  input  [31:0] io_in_bits_pc,
  input  [63:0] io_in_bits_inst,
  input  [1:0]  io_in_bits_pred,
  input         io_in_bits_fault_fetch,
                io_out_ready,
  output        io_out_valid,
  output [31:0] io_out_bits_0_pc,
                io_out_bits_0_inst,
  output        io_out_bits_0_pred,
                io_out_bits_0_fault_fetch,
  output [31:0] io_out_bits_1_pc,
                io_out_bits_1_inst,
  output        io_out_bits_1_pred,
                io_out_bits_1_fault_fetch
);

  reg  [31:0] entry_vec_0_pc;
  reg  [63:0] entry_vec_0_inst;
  reg  [1:0]  entry_vec_0_pred;
  reg         entry_vec_0_fault_fetch;
  reg  [31:0] entry_vec_1_pc;
  reg  [63:0] entry_vec_1_inst;
  reg  [1:0]  entry_vec_1_pred;
  reg         entry_vec_1_fault_fetch;
  reg         rd_ptr_q;
  reg         wr_ptr_q;
  reg  [1:0]  count_q;
  wire        io_in_ready_0 = count_q != 2'h2;
  wire [31:0] io_out_bits_0_pc_0 = rd_ptr_q ? entry_vec_1_pc : entry_vec_0_pc;
  wire [63:0] _GEN = rd_ptr_q ? entry_vec_1_inst : entry_vec_0_inst;
  wire [1:0]  _GEN_0 = rd_ptr_q ? entry_vec_1_pred : entry_vec_0_pred;
  wire        io_out_bits_1_fault_fetch_0 =
    rd_ptr_q ? entry_vec_1_fault_fetch : entry_vec_0_fault_fetch;
  wire        push = io_in_ready_0 & io_in_valid;
  wire        pop = io_out_ready & (|count_q);
  wire        _GEN_1 = push & ~wr_ptr_q;
  wire        _GEN_2 = push & wr_ptr_q;
  always @(posedge clock) begin
    if (reset) begin
      entry_vec_0_pc <= 32'h0;
      entry_vec_0_inst <= 64'h0;
      entry_vec_0_pred <= 2'h0;
      entry_vec_0_fault_fetch <= 1'h0;
      entry_vec_1_pc <= 32'h0;
      entry_vec_1_inst <= 64'h0;
      entry_vec_1_pred <= 2'h0;
      entry_vec_1_fault_fetch <= 1'h0;
      rd_ptr_q <= 1'h0;
      wr_ptr_q <= 1'h0;
      count_q <= 2'h0;
    end
    else begin
      if (io_flush) begin
        entry_vec_0_pc <= 32'h0;
        entry_vec_0_inst <= 64'h0;
        entry_vec_0_pred <= 2'h0;
        entry_vec_1_pc <= 32'h0;
        entry_vec_1_inst <= 64'h0;
        entry_vec_1_pred <= 2'h0;
        count_q <= 2'h0;
      end
      else begin
        if (_GEN_1) begin
          entry_vec_0_pc <= io_in_bits_pc;
          entry_vec_0_inst <= io_in_bits_inst;
          entry_vec_0_pred <= io_in_bits_pred;
        end
        if (_GEN_2) begin
          entry_vec_1_pc <= io_in_bits_pc;
          entry_vec_1_inst <= io_in_bits_inst;
          entry_vec_1_pred <= io_in_bits_pred;
        end
        if (push & ~pop)
          count_q <= count_q + 2'h1;
        else if (~push & pop)
          count_q <= count_q - 2'h1;
      end
      entry_vec_0_fault_fetch <=
        ~io_flush & (_GEN_1 ? io_in_bits_fault_fetch : entry_vec_0_fault_fetch);
      entry_vec_1_fault_fetch <=
        ~io_flush & (_GEN_2 ? io_in_bits_fault_fetch : entry_vec_1_fault_fetch);
      rd_ptr_q <= ~io_flush & (pop ? rd_ptr_q - 1'h1 : rd_ptr_q);
      wr_ptr_q <= ~io_flush & (push ? wr_ptr_q - 1'h1 : wr_ptr_q);
    end
  end // always @(posedge)
  assign io_in_ready = io_in_ready_0;
  assign io_out_valid = |count_q;
  assign io_out_bits_0_pc = io_out_bits_0_pc_0;
  assign io_out_bits_0_inst = _GEN[31:0];
  assign io_out_bits_0_pred = _GEN_0[0];
  assign io_out_bits_0_fault_fetch = io_out_bits_1_fault_fetch_0;
  assign io_out_bits_1_pc = io_out_bits_0_pc_0 + 32'h4;
  assign io_out_bits_1_inst = _GEN[63:32];
  assign io_out_bits_1_pred = _GEN_0[1];
  assign io_out_bits_1_fault_fetch = io_out_bits_1_fault_fetch_0;
endmodule

