// Generated by CIRCT firtool-1.133.0
module Replacement_1(
  input        clock,
               reset,
  input  [6:0] io_ports_0_setIdx,
  input  [3:0] io_ports_0_invalidWayOH,
  input        io_ports_0_hitValid,
  input  [3:0] io_ports_0_hitWayOH,
  input        io_ports_0_refillValid,
  input  [3:0] io_ports_0_refillWayOH,
  output [3:0] io_ports_0_victimWayOH
);

  ReplPLRUPolicy ReplPLRUPolicy (
    .clock                   (clock),
    .reset                   (reset),
    .io_ports_0_setIdx       (io_ports_0_setIdx),
    .io_ports_0_invalidWayOH (io_ports_0_invalidWayOH),
    .io_ports_0_hitValid     (io_ports_0_hitValid),
    .io_ports_0_hitWayOH     (io_ports_0_hitWayOH),
    .io_ports_0_refillValid  (io_ports_0_refillValid),
    .io_ports_0_refillWayOH  (io_ports_0_refillWayOH),
    .io_ports_0_victimWayOH  (io_ports_0_victimWayOH)
  );
endmodule

