../../thirdparty/serv/rtl/serv_bufreg.v
../../thirdparty/serv/rtl/serv_bufreg2.v
../../thirdparty/serv/rtl/serv_alu.v
../../thirdparty/serv/rtl/serv_csr.v
../../thirdparty/serv/rtl/serv_ctrl.v
../../thirdparty/serv/rtl/serv_decode.v
../../thirdparty/serv/rtl/serv_immdec.v
../../thirdparty/serv/rtl/serv_mem_if.v
../../thirdparty/serv/rtl/serv_rf_if.v
../../thirdparty/serv/rtl/serv_rf_ram_if.v
../../thirdparty/serv/rtl/serv_rf_ram.v
../../thirdparty/serv/rtl/serv_state.v
../../thirdparty/serv/rtl/serv_debug.v
../../thirdparty/serv/rtl/serv_top.v
../../thirdparty/serv/rtl/serv_rf_top.v
../../thirdparty/serv/rtl/serv_aligner.v
../../thirdparty/serv/rtl/serv_compdec.v
ecos_serv_cpu_wrapper.v
../cpu_top_bridge.v
