// Generated by CIRCT firtool-1.133.0
`ifndef layers_CL3Top_Verification_Assume
  `define layers_CL3Top_Verification_Assume
  `include "layers-CL3Top-Verification.sv"
`endif // not def layers_CL3Top_Verification_Assume
