// Generated by CIRCT firtool-1.133.0
module CarrylessMultiplier(
  input         clock,
  input  [1:0]  io_op,
  input  [31:0] io_opa,
                io_opb,
  output [31:0] io_res
);

  reg  [31:0] casez_tmp;
  wire        _opb_true_T = io_op == 2'h2 | (&io_op);
  wire [31:0] _opa_true_T_9 = {16'h0, io_opa[31:16]} | {io_opa[15:0], 16'h0};
  wire [31:0] _opa_true_T_19 =
    {8'h0, _opa_true_T_9[31:8] & 24'hFF00FF} | {_opa_true_T_9[23:0] & 24'hFF00FF, 8'h0};
  wire [31:0] _opa_true_T_29 =
    {4'h0, _opa_true_T_19[31:4] & 28'hF0F0F0F}
    | {_opa_true_T_19[27:0] & 28'hF0F0F0F, 4'h0};
  wire [31:0] _opa_true_T_39 =
    {2'h0, _opa_true_T_29[31:2] & 30'h33333333}
    | {_opa_true_T_29[29:0] & 30'h33333333, 2'h0};
  wire [31:0] opa_true =
    _opb_true_T
      ? {1'h0, _opa_true_T_39[31:1] & 31'h55555555}
        | {_opa_true_T_39[30:0] & 31'h55555555, 1'h0}
      : io_opa;
  wire [31:0] _opb_true_T_9 = {16'h0, io_opb[31:16]} | {io_opb[15:0], 16'h0};
  wire [31:0] _opb_true_T_19 =
    {8'h0, _opb_true_T_9[31:8] & 24'hFF00FF} | {_opb_true_T_9[23:0] & 24'hFF00FF, 8'h0};
  wire [31:0] _opb_true_T_29 =
    {4'h0, _opb_true_T_19[31:4] & 28'hF0F0F0F}
    | {_opb_true_T_19[27:0] & 28'hF0F0F0F, 4'h0};
  wire [31:0] _opb_true_T_39 =
    {2'h0, _opb_true_T_29[31:2] & 30'h33333333}
    | {_opb_true_T_29[29:0] & 30'h33333333, 2'h0};
  wire [31:0] opb_true =
    _opb_true_T
      ? {1'h0, _opb_true_T_39[31:1] & 31'h55555555}
        | {_opb_true_T_39[30:0] & 31'h55555555, 1'h0}
      : io_opb;
  wire [31:0] res_raw =
    (opb_true[0] ? opa_true : 32'h0) ^ (opb_true[1] ? {opa_true[30:0], 1'h0} : 32'h0)
    ^ (opb_true[2] ? {opa_true[29:0], 2'h0} : 32'h0)
    ^ (opb_true[3] ? {opa_true[28:0], 3'h0} : 32'h0)
    ^ (opb_true[4] ? {opa_true[27:0], 4'h0} : 32'h0)
    ^ (opb_true[5] ? {opa_true[26:0], 5'h0} : 32'h0)
    ^ (opb_true[6] ? {opa_true[25:0], 6'h0} : 32'h0)
    ^ (opb_true[7] ? {opa_true[24:0], 7'h0} : 32'h0)
    ^ (opb_true[8] ? {opa_true[23:0], 8'h0} : 32'h0)
    ^ (opb_true[9] ? {opa_true[22:0], 9'h0} : 32'h0)
    ^ (opb_true[10] ? {opa_true[21:0], 10'h0} : 32'h0)
    ^ (opb_true[11] ? {opa_true[20:0], 11'h0} : 32'h0)
    ^ (opb_true[12] ? {opa_true[19:0], 12'h0} : 32'h0)
    ^ (opb_true[13] ? {opa_true[18:0], 13'h0} : 32'h0)
    ^ (opb_true[14] ? {opa_true[17:0], 14'h0} : 32'h0)
    ^ (opb_true[15] ? {opa_true[16:0], 15'h0} : 32'h0)
    ^ (opb_true[16] ? {opa_true[15:0], 16'h0} : 32'h0)
    ^ (opb_true[17] ? {opa_true[14:0], 17'h0} : 32'h0)
    ^ (opb_true[18] ? {opa_true[13:0], 18'h0} : 32'h0)
    ^ (opb_true[19] ? {opa_true[12:0], 19'h0} : 32'h0)
    ^ (opb_true[20] ? {opa_true[11:0], 20'h0} : 32'h0)
    ^ (opb_true[21] ? {opa_true[10:0], 21'h0} : 32'h0)
    ^ (opb_true[22] ? {opa_true[9:0], 22'h0} : 32'h0)
    ^ (opb_true[23] ? {opa_true[8:0], 23'h0} : 32'h0)
    ^ (opb_true[24] ? {opa_true[7:0], 24'h0} : 32'h0)
    ^ (opb_true[25] ? {opa_true[6:0], 25'h0} : 32'h0)
    ^ (opb_true[26] ? {opa_true[5:0], 26'h0} : 32'h0)
    ^ (opb_true[27] ? {opa_true[4:0], 27'h0} : 32'h0)
    ^ (opb_true[28] ? {opa_true[3:0], 28'h0} : 32'h0)
    ^ (opb_true[29] ? {opa_true[2:0], 29'h0} : 32'h0)
    ^ (opb_true[30] ? {opa_true[1:0], 30'h0} : 32'h0)
    ^ (opb_true[31] ? {opa_true[0], 31'h0} : 32'h0);
  wire [31:0] _res_rev_T_8 = {16'h0, res_raw[31:16]} | {res_raw[15:0], 16'h0};
  wire [31:0] _res_rev_T_18 =
    {8'h0, _res_rev_T_8[31:8] & 24'hFF00FF} | {_res_rev_T_8[23:0] & 24'hFF00FF, 8'h0};
  wire [31:0] _res_rev_T_28 =
    {4'h0, _res_rev_T_18[31:4] & 28'hF0F0F0F} | {_res_rev_T_18[27:0] & 28'hF0F0F0F, 4'h0};
  wire [31:0] _res_rev_T_38 =
    {2'h0, _res_rev_T_28[31:2] & 30'h33333333}
    | {_res_rev_T_28[29:0] & 30'h33333333, 2'h0};
  wire [31:0] res_rev =
    {1'h0, _res_rev_T_38[31:1] & 31'h55555555}
    | {_res_rev_T_38[30:0] & 31'h55555555, 1'h0};
  always_comb begin
    casez (io_op)
      2'b00:
        casez_tmp = res_raw;
      2'b01:
        casez_tmp = res_raw;
      2'b10:
        casez_tmp = res_rev;
      default:
        casez_tmp = {1'h0, res_rev[31:1]};
    endcase
  end // always_comb
  reg  [31:0] res_q;
  always @(posedge clock)
    res_q <= casez_tmp;
  assign io_res = res_q;
endmodule

