// Generated by CIRCT firtool-1.133.0
module ICacheTagRamDev(
  input         clock,
  input  [6:0]  io_p0_addr,
  input  [20:0] io_p0_din,
  input         io_p0_wr,
  output [20:0] io_p0_dout,
  input  [6:0]  io_p1_addr,
  input  [20:0] io_p1_din,
  input         io_p1_wr,
  output [20:0] io_p1_dout
);

  wire [20:0] _memBanks_3_ext_R0_data;
  wire [20:0] _memBanks_3_ext_R1_data;
  wire [20:0] _memBanks_2_ext_R0_data;
  wire [20:0] _memBanks_2_ext_R1_data;
  wire [20:0] _memBanks_1_ext_R0_data;
  wire [20:0] _memBanks_1_ext_R1_data;
  wire [20:0] _memBanks_0_ext_R0_data;
  wire [20:0] _memBanks_0_ext_R1_data;
  reg  [1:0]  bank_reg;
  reg  [20:0] casez_tmp;
  always_comb begin
    casez (bank_reg)
      2'b00:
        casez_tmp = _memBanks_0_ext_R1_data;
      2'b01:
        casez_tmp = _memBanks_1_ext_R1_data;
      2'b10:
        casez_tmp = _memBanks_2_ext_R1_data;
      default:
        casez_tmp = _memBanks_3_ext_R1_data;
    endcase
  end // always_comb
  reg  [1:0]  bank_reg_1;
  reg  [20:0] casez_tmp_0;
  always_comb begin
    casez (bank_reg_1)
      2'b00:
        casez_tmp_0 = _memBanks_0_ext_R0_data;
      2'b01:
        casez_tmp_0 = _memBanks_1_ext_R0_data;
      2'b10:
        casez_tmp_0 = _memBanks_2_ext_R0_data;
      default:
        casez_tmp_0 = _memBanks_3_ext_R0_data;
    endcase
  end // always_comb
  always @(posedge clock) begin
    bank_reg <= io_p0_addr[1:0];
    bank_reg_1 <= io_p1_addr[1:0];
  end // always @(posedge)
  memBanks_32x21 memBanks_0_ext (
    .R0_addr (io_p1_addr[6:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_0_ext_R0_data),
    .R1_addr (io_p0_addr[6:2]),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_memBanks_0_ext_R1_data),
    .W0_addr (io_p1_addr[6:2]),
    .W0_en   (io_p1_addr[1:0] == 2'h0 & io_p1_wr),
    .W0_clk  (clock),
    .W0_data (io_p1_din),
    .W1_addr (io_p0_addr[6:2]),
    .W1_en   (io_p0_addr[1:0] == 2'h0 & io_p0_wr),
    .W1_clk  (clock),
    .W1_data (io_p0_din)
  );
  memBanks_32x21 memBanks_1_ext (
    .R0_addr (io_p1_addr[6:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_1_ext_R0_data),
    .R1_addr (io_p0_addr[6:2]),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_memBanks_1_ext_R1_data),
    .W0_addr (io_p1_addr[6:2]),
    .W0_en   (io_p1_addr[1:0] == 2'h1 & io_p1_wr),
    .W0_clk  (clock),
    .W0_data (io_p1_din),
    .W1_addr (io_p0_addr[6:2]),
    .W1_en   (io_p0_addr[1:0] == 2'h1 & io_p0_wr),
    .W1_clk  (clock),
    .W1_data (io_p0_din)
  );
  memBanks_32x21 memBanks_2_ext (
    .R0_addr (io_p1_addr[6:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_2_ext_R0_data),
    .R1_addr (io_p0_addr[6:2]),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_memBanks_2_ext_R1_data),
    .W0_addr (io_p1_addr[6:2]),
    .W0_en   (io_p1_addr[1:0] == 2'h2 & io_p1_wr),
    .W0_clk  (clock),
    .W0_data (io_p1_din),
    .W1_addr (io_p0_addr[6:2]),
    .W1_en   (io_p0_addr[1:0] == 2'h2 & io_p0_wr),
    .W1_clk  (clock),
    .W1_data (io_p0_din)
  );
  memBanks_32x21 memBanks_3_ext (
    .R0_addr (io_p1_addr[6:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_3_ext_R0_data),
    .R1_addr (io_p0_addr[6:2]),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_memBanks_3_ext_R1_data),
    .W0_addr (io_p1_addr[6:2]),
    .W0_en   ((&(io_p1_addr[1:0])) & io_p1_wr),
    .W0_clk  (clock),
    .W0_data (io_p1_din),
    .W1_addr (io_p0_addr[6:2]),
    .W1_en   ((&(io_p0_addr[1:0])) & io_p0_wr),
    .W1_clk  (clock),
    .W1_data (io_p0_din)
  );
  assign io_p0_dout = casez_tmp;
  assign io_p1_dout = casez_tmp_0;
endmodule

