// Generated by CIRCT firtool-1.133.0
module ICache(
  input         clock,
                reset,
                io_cpu_req_rd,
  input  [31:0] io_cpu_req_pc,
  output        io_cpu_resp_accept,
                io_cpu_resp_valid,
                io_cpu_resp_error,
  output [63:0] io_cpu_resp_inst,
  input         io_axi_ar_ready,
  output        io_axi_ar_valid,
  output [31:0] io_axi_ar_bits_addr,
  input         io_axi_r_valid,
  input  [31:0] io_axi_r_bits_data,
  input  [1:0]  io_axi_r_bits_resp,
  input         io_axi_r_bits_last
);

  wire [1:0]  next_state_p1_r;
  wire [19:0] _tag_data_out_p1_w_3_T;
  wire [19:0] _tag_data_out_p1_w_2_T;
  wire [19:0] _tag_data_out_p1_w_1_T;
  wire [19:0] _tag_data_out_p1_w_0_T;
  wire [1:0]  next_state_r;
  wire [19:0] _tag_data_out_w_3_T;
  wire [19:0] _tag_data_out_w_2_T;
  wire [19:0] _tag_data_out_w_1_T;
  wire [19:0] _tag_data_out_w_0_T;
  wire [3:0]  _repl_io_ports_0_victimWayOH;
  wire [3:0]  _repl_io_ports_1_victimWayOH;
  wire [63:0] _u_data_3_io_p0_dout;
  wire [63:0] _u_data_3_io_p1_dout;
  wire [63:0] _u_data_2_io_p0_dout;
  wire [63:0] _u_data_2_io_p1_dout;
  wire [63:0] _u_data_1_io_p0_dout;
  wire [63:0] _u_data_1_io_p1_dout;
  wire [63:0] _u_data_0_io_p0_dout;
  wire [63:0] _u_data_0_io_p1_dout;
  wire        _u_valid_3_io_p0_dout;
  wire        _u_valid_3_io_p1_dout;
  wire        _u_valid_2_io_p0_dout;
  wire        _u_valid_2_io_p1_dout;
  wire        _u_valid_1_io_p0_dout;
  wire        _u_valid_1_io_p1_dout;
  wire        _u_valid_0_io_p0_dout;
  wire        _u_valid_0_io_p1_dout;
  wire [20:0] _u_tag_3_io_p0_dout;
  wire [20:0] _u_tag_3_io_p1_dout;
  wire [20:0] _u_tag_2_io_p0_dout;
  wire [20:0] _u_tag_2_io_p1_dout;
  wire [20:0] _u_tag_1_io_p0_dout;
  wire [20:0] _u_tag_1_io_p1_dout;
  wire [20:0] _u_tag_0_io_p0_dout;
  wire [20:0] _u_tag_0_io_p1_dout;
  reg  [1:0]  state_q;
  reg  [1:0]  state_p1_q;
  reg  [1:0]  replace_way_q;
  reg  [6:0]  flush_addr_q;
  reg         lookup_valid_q;
  reg  [31:0] lookup_addr_q;
  wire        _GEN = state_q == 2'h2;
  wire        _GEN_0 = state_p1_q == 2'h1;
  wire [6:0]  tag_addr_r =
    (|state_q)
      ? (_GEN | (&state_q) | _GEN_0 | next_state_p1_r == 2'h1
           ? lookup_addr_q[11:5]
           : io_cpu_req_pc[11:5])
      : flush_addr_q;
  wire [20:0] tag_data_in_r = (|state_q) & _GEN ? {1'h1, lookup_addr_q[31:12]} : 21'h0;
  wire        tag_hit_w_0 =
    _u_valid_0_io_p0_dout & _tag_data_out_w_0_T == lookup_addr_q[31:12];
  wire        tag_hit_w_1 =
    _u_valid_1_io_p0_dout & _tag_data_out_w_1_T == lookup_addr_q[31:12];
  wire        tag_hit_w_2 =
    _u_valid_2_io_p0_dout & _tag_data_out_w_2_T == lookup_addr_q[31:12];
  wire        tag_hit_w_3 =
    _u_valid_3_io_p0_dout & _tag_data_out_w_3_T == lookup_addr_q[31:12];
  wire        tag_hit_any_w = tag_hit_w_0 | tag_hit_w_1 | tag_hit_w_2 | tag_hit_w_3;
  wire        tag_write_r =
    ~(|state_q) | _GEN & io_axi_r_valid & io_axi_r_bits_last & ~(|replace_way_q);
  assign _tag_data_out_w_0_T = _u_tag_0_io_p0_dout[19:0];
  wire        tag_write_r_1 =
    ~(|state_q) | _GEN & io_axi_r_valid & io_axi_r_bits_last & replace_way_q == 2'h1;
  assign _tag_data_out_w_1_T = _u_tag_1_io_p0_dout[19:0];
  wire        tag_write_r_2 =
    ~(|state_q) | _GEN & io_axi_r_valid & io_axi_r_bits_last & replace_way_q == 2'h2;
  assign _tag_data_out_w_2_T = _u_tag_2_io_p0_dout[19:0];
  wire        tag_write_r_3 =
    ~(|state_q) | _GEN & io_axi_r_valid & io_axi_r_bits_last & (&replace_way_q);
  assign _tag_data_out_w_3_T = _u_tag_3_io_p0_dout[19:0];
  reg  [8:0]  data_write_addr_q;
  reg  [2:0]  refill_word_idx_q;
  reg  [31:0] refill_lower_q;
  wire        _tag_write_r_T_21 = io_axi_r_valid & io_axi_r_bits_last;
  wire        _io_cpu_resp_accept_T = state_q == 2'h1;
  wire        _p0_refill_sel_T = next_state_r == 2'h2;
  wire        _p0_refill_sel_T_1 = state_q == 2'h2;
  wire        _GEN_1 = state_p1_q == 2'h2;
  wire        _GEN_2 = (&state_q) | _GEN_1;
  wire [8:0]  data_addr_r =
    _p0_refill_sel_T_1
      ? data_write_addr_q
      : _GEN_2 ? lookup_addr_q[11:3] : io_cpu_req_pc[11:3];
  wire [63:0] u_data_3_io_p0_din = {io_axi_r_bits_data, refill_lower_q};
  reg         p1_relookup;
  reg         p0_tag_hit_0;
  reg         p0_tag_hit_1;
  reg         p0_tag_hit_2;
  reg         p0_tag_hit_3;
  wire [3:0]  _p0_tag_hit_any_T =
    {p0_tag_hit_3, p0_tag_hit_2, p0_tag_hit_1, p0_tag_hit_0};
  reg  [1:0]  casez_tmp;
  always_comb begin
    casez (state_q)
      2'b00:
        casez_tmp = state_q;
      2'b01:
        casez_tmp =
          lookup_valid_q & ~(p1_relookup ? (|_p0_tag_hit_any_T) : tag_hit_any_w)
            ? 2'h2
            : state_q;
      2'b10:
        casez_tmp = _tag_write_r_T_21 ? 2'h3 : state_q;
      default:
        casez_tmp = 2'h1;
    endcase
  end // always_comb
  assign next_state_r = (|state_q) ? casez_tmp : (&flush_addr_q) ? 2'h1 : state_q;
  reg         unaligned_Reg;
  reg         crossLineReg;
  wire [31:0] _lookup_addr_p1_q_T = io_cpu_req_pc + 32'h4;
  reg         lookup_valid_p1_q;
  reg  [31:0] lookup_addr_p1_q;
  wire        _p1_refill_sel_T_1 = state_p1_q == 2'h1;
  wire [6:0]  tag_addr_p1_r =
    _p1_refill_sel_T_1 | _GEN_1 | (&state_q)
      ? lookup_addr_p1_q[11:5]
      : io_cpu_req_pc[2] ? _lookup_addr_p1_q_T[11:5] : io_cpu_req_pc[11:5];
  wire [20:0] tag_data_in_p1_r =
    _p1_refill_sel_T_1 ? {1'h1, lookup_addr_p1_q[31:12]} : 21'h0;
  wire        tag_hit_p1_w_0 =
    _u_valid_0_io_p1_dout & _tag_data_out_p1_w_0_T == lookup_addr_p1_q[31:12];
  wire        tag_hit_p1_w_1 =
    _u_valid_1_io_p1_dout & _tag_data_out_p1_w_1_T == lookup_addr_p1_q[31:12];
  wire        tag_hit_p1_w_2 =
    _u_valid_2_io_p1_dout & _tag_data_out_p1_w_2_T == lookup_addr_p1_q[31:12];
  wire        tag_hit_p1_w_3 =
    _u_valid_3_io_p1_dout & _tag_data_out_p1_w_3_T == lookup_addr_p1_q[31:12];
  wire        tag_hit_any_p1_w =
    tag_hit_p1_w_0 | tag_hit_p1_w_1 | tag_hit_p1_w_2 | tag_hit_p1_w_3;
  reg  [1:0]  replace_way_p1_q;
  wire        tag_write_r_4 =
    _p1_refill_sel_T_1 & _tag_write_r_T_21 & ~(|replace_way_p1_q);
  assign _tag_data_out_p1_w_0_T = _u_tag_0_io_p1_dout[19:0];
  wire        tag_write_r_5 =
    _p1_refill_sel_T_1 & _tag_write_r_T_21 & replace_way_p1_q == 2'h1;
  assign _tag_data_out_p1_w_1_T = _u_tag_1_io_p1_dout[19:0];
  wire        tag_write_r_6 =
    _p1_refill_sel_T_1 & _tag_write_r_T_21 & replace_way_p1_q == 2'h2;
  assign _tag_data_out_p1_w_2_T = _u_tag_2_io_p1_dout[19:0];
  wire        tag_write_r_7 =
    _p1_refill_sel_T_1 & _tag_write_r_T_21 & (&replace_way_p1_q);
  assign _tag_data_out_p1_w_3_T = _u_tag_3_io_p1_dout[19:0];
  reg  [8:0]  data_write_addr_p1_q;
  reg  [2:0]  refill_word_idx_p1_q;
  reg  [31:0] refill_lower_p1_q;
  wire        _p1_refill_sel_T = next_state_p1_r == 2'h1;
  wire [8:0]  data_addr_p1_r =
    _p1_refill_sel_T_1
      ? data_write_addr_p1_q
      : _GEN_2
          ? lookup_addr_p1_q[11:3]
          : io_cpu_req_pc[2] ? io_cpu_req_pc[11:3] + 9'h1 : io_cpu_req_pc[11:3];
  wire [63:0] u_data_3_io_p1_din = {io_axi_r_bits_data, refill_lower_p1_q};
  wire        _GEN_3 = lookup_valid_p1_q & ~tag_hit_any_p1_w;
  wire [1:0]  _next_state_p1_r_T_1 = {_p0_refill_sel_T, 1'h1};
  reg  [1:0]  casez_tmp_0;
  always_comb begin
    casez (state_p1_q)
      2'b00:
        casez_tmp_0 = state_p1_q;
      2'b01:
        casez_tmp_0 = _p0_refill_sel_T ? 2'h3 : _tag_write_r_T_21 ? 2'h2 : state_p1_q;
      2'b10:
        casez_tmp_0 = 2'h0;
      default:
        casez_tmp_0 = _tag_write_r_T_21 ? (crossLineReg ? 2'h1 : 2'h2) : state_p1_q;
    endcase
  end // always_comb
  assign next_state_p1_r =
    (|state_p1_q) ? casez_tmp_0 : _GEN_3 ? _next_state_p1_r_T_1 : state_p1_q;
  wire        io_cpu_resp_valid_0 =
    lookup_valid_q & _io_cpu_resp_accept_T
    & (p1_relookup ? (|_p0_tag_hit_any_T) : tag_hit_any_w)
    & (lookup_valid_p1_q & ~(|state_p1_q) & tag_hit_any_p1_w | ~unaligned_Reg);
  wire        hitVec_0 = p1_relookup ? p0_tag_hit_0 : tag_hit_w_0;
  wire        hitVec_1 = p1_relookup ? p0_tag_hit_1 : tag_hit_w_1;
  wire        hitVec_2 = p1_relookup ? p0_tag_hit_2 : tag_hit_w_2;
  wire        hitVec_3 = p1_relookup ? p0_tag_hit_3 : tag_hit_w_3;
  wire [63:0] inst_r =
    (|{hitVec_3, hitVec_2, hitVec_1, hitVec_0})
      ? (hitVec_0 ? _u_data_0_io_p0_dout : 64'h0)
        | (hitVec_1 ? _u_data_1_io_p0_dout : 64'h0)
        | (hitVec_2 ? _u_data_2_io_p0_dout : 64'h0)
        | (hitVec_3 ? _u_data_3_io_p0_dout : 64'h0)
      : 64'h0;
  wire        io_cpu_resp_accept_0 =
    _io_cpu_resp_accept_T & next_state_r != 2'h2 & ~(|state_p1_q)
    & next_state_p1_r != 2'h1;
  reg         axi_state;
  reg         axi_error_q;
  wire        io_axi_ar_valid_0 =
    (_p0_refill_sel_T_1 & _p0_refill_sel_T | _p1_refill_sel_T_1 & _p1_refill_sel_T)
    & axi_state;
  wire [31:0] araddr_sel_w =
    _p0_refill_sel_T | _p0_refill_sel_T_1
      ? {lookup_addr_q[31:5], 5'h0}
      : _p1_refill_sel_T | _p1_refill_sel_T_1 ? {lookup_addr_p1_q[31:5], 5'h0} : 32'h0;
  wire        _crossLineReg_T = io_cpu_req_rd & io_cpu_resp_accept_0;
  wire        _GEN_4 = (&state_p1_q) | _GEN_0;
  always @(posedge clock) begin
    if (reset) begin
      state_q <= 2'h0;
      state_p1_q <= 2'h0;
      replace_way_q <= 2'h0;
      flush_addr_q <= 7'h0;
      lookup_valid_q <= 1'h0;
      lookup_addr_q <= 32'h0;
      data_write_addr_q <= 9'h0;
      refill_word_idx_q <= 3'h0;
      refill_lower_q <= 32'h0;
      p1_relookup <= 1'h0;
      p0_tag_hit_0 <= 1'h0;
      p0_tag_hit_1 <= 1'h0;
      p0_tag_hit_2 <= 1'h0;
      p0_tag_hit_3 <= 1'h0;
      unaligned_Reg <= 1'h0;
      crossLineReg <= 1'h0;
      lookup_valid_p1_q <= 1'h0;
      lookup_addr_p1_q <= 32'h0;
      replace_way_p1_q <= 2'h0;
      data_write_addr_p1_q <= 9'h0;
      refill_word_idx_p1_q <= 3'h0;
      refill_lower_p1_q <= 32'h0;
      axi_state <= 1'h1;
      axi_error_q <= 1'h0;
    end
    else begin
      if (|state_q)
        state_q <= casez_tmp;
      else if (&flush_addr_q)
        state_q <= 2'h1;
      if (|state_p1_q)
        state_p1_q <= casez_tmp_0;
      else if (_GEN_3)
        state_p1_q <= _next_state_p1_r_T_1;
      if (_tag_write_r_T_21 & _p0_refill_sel_T_1)
        replace_way_q <=
          {|(_repl_io_ports_0_victimWayOH[3:2]),
           _repl_io_ports_0_victimWayOH[3] | _repl_io_ports_0_victimWayOH[1]};
      flush_addr_q <= (|state_q) ? 7'h0 : flush_addr_q + 7'h1;
      lookup_valid_q <= _crossLineReg_T | ~io_cpu_resp_valid_0 & lookup_valid_q;
      if (_crossLineReg_T) begin
        lookup_addr_q <= io_cpu_req_pc[2] ? {io_cpu_req_pc[31:3], 3'h0} : io_cpu_req_pc;
        unaligned_Reg <= io_cpu_req_pc[2];
        crossLineReg <= &(io_cpu_req_pc[4:2]);
        lookup_addr_p1_q <= io_cpu_req_pc[2] ? _lookup_addr_p1_q_T : io_cpu_req_pc;
      end
      if (_io_cpu_resp_accept_T & _p0_refill_sel_T)
        data_write_addr_q <= araddr_sel_w[11:3];
      else if (_GEN & io_axi_r_valid & refill_word_idx_q[0])
        data_write_addr_q <= data_write_addr_q + 9'h1;
      if (_tag_write_r_T_21) begin
        refill_word_idx_q <= 3'h0;
        replace_way_p1_q <=
          {|(_repl_io_ports_1_victimWayOH[3:2]),
           _repl_io_ports_1_victimWayOH[3] | _repl_io_ports_1_victimWayOH[1]};
        refill_word_idx_p1_q <= 3'h0;
      end
      else if (io_axi_r_valid) begin
        refill_word_idx_q <= refill_word_idx_q + 3'h1;
        refill_word_idx_p1_q <= refill_word_idx_p1_q + 3'h1;
      end
      if (io_axi_r_valid) begin
        refill_lower_q <= io_axi_r_bits_data;
        refill_lower_p1_q <= io_axi_r_bits_data;
      end
      p1_relookup <= (|state_p1_q) & (~_GEN_4 & _GEN_1 | p1_relookup);
      if (~(|state_p1_q) | _GEN_4 | ~_GEN_1) begin
      end
      else begin
        p0_tag_hit_0 <= tag_hit_w_0;
        p0_tag_hit_1 <= tag_hit_w_1;
        p0_tag_hit_2 <= tag_hit_w_2;
        p0_tag_hit_3 <= tag_hit_w_3;
      end
      lookup_valid_p1_q <=
        _crossLineReg_T & io_cpu_req_pc[2] | ~io_cpu_resp_valid_0 & lookup_valid_p1_q;
      if (~(|state_p1_q) & _p1_refill_sel_T)
        data_write_addr_p1_q <= araddr_sel_w[11:3];
      else if ((&state_q) & _p1_refill_sel_T)
        data_write_addr_p1_q <= araddr_sel_w[11:3];
      else if (_p1_refill_sel_T_1 & io_axi_r_valid & refill_word_idx_p1_q[0])
        data_write_addr_p1_q <= data_write_addr_p1_q + 9'h1;
      axi_state <=
        io_axi_r_valid & io_axi_r_bits_last | ~(io_axi_ar_valid_0 & io_axi_ar_ready)
        & axi_state;
      axi_error_q <=
        io_axi_r_valid & (|io_axi_r_bits_resp) | ~io_cpu_resp_valid_0 & axi_error_q;
    end
  end // always @(posedge)
  ICacheTagRam u_tag_0 (
    .clock      (clock),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r),
    .io_p0_wr   (tag_write_r),
    .io_p0_dout (_u_tag_0_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r),
    .io_p1_wr   (tag_write_r_4),
    .io_p1_dout (_u_tag_0_io_p1_dout)
  );
  ICacheTagRam u_tag_1 (
    .clock      (clock),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r),
    .io_p0_wr   (tag_write_r_1),
    .io_p0_dout (_u_tag_1_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r),
    .io_p1_wr   (tag_write_r_5),
    .io_p1_dout (_u_tag_1_io_p1_dout)
  );
  ICacheTagRam u_tag_2 (
    .clock      (clock),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r),
    .io_p0_wr   (tag_write_r_2),
    .io_p0_dout (_u_tag_2_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r),
    .io_p1_wr   (tag_write_r_6),
    .io_p1_dout (_u_tag_2_io_p1_dout)
  );
  ICacheTagRam u_tag_3 (
    .clock      (clock),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r),
    .io_p0_wr   (tag_write_r_3),
    .io_p0_dout (_u_tag_3_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r),
    .io_p1_wr   (tag_write_r_7),
    .io_p1_dout (_u_tag_3_io_p1_dout)
  );
  ICacheValidRam u_valid_0 (
    .clock      (clock),
    .reset      (reset),
    .io_flush   (~(|state_q)),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r[20]),
    .io_p0_wr   (tag_write_r),
    .io_p0_dout (_u_valid_0_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r[20]),
    .io_p1_wr   (tag_write_r_4),
    .io_p1_dout (_u_valid_0_io_p1_dout)
  );
  ICacheValidRam u_valid_1 (
    .clock      (clock),
    .reset      (reset),
    .io_flush   (~(|state_q)),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r[20]),
    .io_p0_wr   (tag_write_r_1),
    .io_p0_dout (_u_valid_1_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r[20]),
    .io_p1_wr   (tag_write_r_5),
    .io_p1_dout (_u_valid_1_io_p1_dout)
  );
  ICacheValidRam u_valid_2 (
    .clock      (clock),
    .reset      (reset),
    .io_flush   (~(|state_q)),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r[20]),
    .io_p0_wr   (tag_write_r_2),
    .io_p0_dout (_u_valid_2_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r[20]),
    .io_p1_wr   (tag_write_r_6),
    .io_p1_dout (_u_valid_2_io_p1_dout)
  );
  ICacheValidRam u_valid_3 (
    .clock      (clock),
    .reset      (reset),
    .io_flush   (~(|state_q)),
    .io_p0_addr (tag_addr_r),
    .io_p0_din  (tag_data_in_r[20]),
    .io_p0_wr   (tag_write_r_3),
    .io_p0_dout (_u_valid_3_io_p0_dout),
    .io_p1_addr (tag_addr_p1_r),
    .io_p1_din  (tag_data_in_p1_r[20]),
    .io_p1_wr   (tag_write_r_7),
    .io_p1_dout (_u_valid_3_io_p1_dout)
  );
  ICacheDataRam u_data_0 (
    .clock      (clock),
    .io_p0_addr (data_addr_r),
    .io_p0_din  (u_data_3_io_p0_din),
    .io_p0_wr   (io_axi_r_valid & ~(|replace_way_q) & _p0_refill_sel_T_1),
    .io_p0_dout (_u_data_0_io_p0_dout),
    .io_p1_addr (data_addr_p1_r),
    .io_p1_din  (u_data_3_io_p1_din),
    .io_p1_wr   (io_axi_r_valid & ~(|replace_way_p1_q) & _p1_refill_sel_T_1),
    .io_p1_dout (_u_data_0_io_p1_dout)
  );
  ICacheDataRam u_data_1 (
    .clock      (clock),
    .io_p0_addr (data_addr_r),
    .io_p0_din  (u_data_3_io_p0_din),
    .io_p0_wr   (io_axi_r_valid & replace_way_q == 2'h1 & _p0_refill_sel_T_1),
    .io_p0_dout (_u_data_1_io_p0_dout),
    .io_p1_addr (data_addr_p1_r),
    .io_p1_din  (u_data_3_io_p1_din),
    .io_p1_wr   (io_axi_r_valid & replace_way_p1_q == 2'h1 & _p1_refill_sel_T_1),
    .io_p1_dout (_u_data_1_io_p1_dout)
  );
  ICacheDataRam u_data_2 (
    .clock      (clock),
    .io_p0_addr (data_addr_r),
    .io_p0_din  (u_data_3_io_p0_din),
    .io_p0_wr   (io_axi_r_valid & replace_way_q == 2'h2 & _p0_refill_sel_T_1),
    .io_p0_dout (_u_data_2_io_p0_dout),
    .io_p1_addr (data_addr_p1_r),
    .io_p1_din  (u_data_3_io_p1_din),
    .io_p1_wr   (io_axi_r_valid & replace_way_p1_q == 2'h2 & _p1_refill_sel_T_1),
    .io_p1_dout (_u_data_2_io_p1_dout)
  );
  ICacheDataRam u_data_3 (
    .clock      (clock),
    .io_p0_addr (data_addr_r),
    .io_p0_din  (u_data_3_io_p0_din),
    .io_p0_wr   (io_axi_r_valid & (&replace_way_q) & _p0_refill_sel_T_1),
    .io_p0_dout (_u_data_3_io_p0_dout),
    .io_p1_addr (data_addr_p1_r),
    .io_p1_din  (u_data_3_io_p1_din),
    .io_p1_wr   (io_axi_r_valid & (&replace_way_p1_q) & _p1_refill_sel_T_1),
    .io_p1_dout (_u_data_3_io_p1_dout)
  );
  Replacement repl (
    .clock                   (clock),
    .reset                   (reset),
    .io_ports_0_invalidWayOH
      (~{_u_valid_3_io_p0_dout,
         _u_valid_2_io_p0_dout,
         _u_valid_1_io_p0_dout,
         _u_valid_0_io_p0_dout}),
    .io_ports_0_victimWayOH  (_repl_io_ports_0_victimWayOH),
    .io_ports_1_invalidWayOH
      (~{_u_valid_3_io_p1_dout,
         _u_valid_2_io_p1_dout,
         _u_valid_1_io_p1_dout,
         _u_valid_0_io_p1_dout}),
    .io_ports_1_victimWayOH  (_repl_io_ports_1_victimWayOH)
  );
  assign io_cpu_resp_accept = io_cpu_resp_accept_0;
  assign io_cpu_resp_valid = io_cpu_resp_valid_0;
  assign io_cpu_resp_error = axi_error_q;
  assign io_cpu_resp_inst =
    unaligned_Reg
      ? {tag_hit_any_p1_w
           ? (tag_hit_p1_w_0 ? _u_data_0_io_p1_dout[31:0] : 32'h0)
             | (tag_hit_p1_w_1 ? _u_data_1_io_p1_dout[31:0] : 32'h0)
             | (tag_hit_p1_w_2 ? _u_data_2_io_p1_dout[31:0] : 32'h0)
             | (tag_hit_p1_w_3 ? _u_data_3_io_p1_dout[31:0] : 32'h0)
           : 32'h0,
         inst_r[63:32]}
      : inst_r;
  assign io_axi_ar_valid = io_axi_ar_valid_0;
  assign io_axi_ar_bits_addr = araddr_sel_w;
endmodule

