// Generated by CIRCT firtool-1.133.0
module ReplPLRUPolicy(
  input        clock,
               reset,
  input  [6:0] io_ports_0_setIdx,
  input  [3:0] io_ports_0_invalidWayOH,
  input        io_ports_0_hitValid,
  input  [3:0] io_ports_0_hitWayOH,
  input        io_ports_0_refillValid,
  input  [3:0] io_ports_0_refillWayOH,
  output [3:0] io_ports_0_victimWayOH
);

  reg  [2:0] meta_0;
  reg  [2:0] meta_1;
  reg  [2:0] meta_2;
  reg  [2:0] meta_3;
  reg  [2:0] meta_4;
  reg  [2:0] meta_5;
  reg  [2:0] meta_6;
  reg  [2:0] meta_7;
  reg  [2:0] meta_8;
  reg  [2:0] meta_9;
  reg  [2:0] meta_10;
  reg  [2:0] meta_11;
  reg  [2:0] meta_12;
  reg  [2:0] meta_13;
  reg  [2:0] meta_14;
  reg  [2:0] meta_15;
  reg  [2:0] meta_16;
  reg  [2:0] meta_17;
  reg  [2:0] meta_18;
  reg  [2:0] meta_19;
  reg  [2:0] meta_20;
  reg  [2:0] meta_21;
  reg  [2:0] meta_22;
  reg  [2:0] meta_23;
  reg  [2:0] meta_24;
  reg  [2:0] meta_25;
  reg  [2:0] meta_26;
  reg  [2:0] meta_27;
  reg  [2:0] meta_28;
  reg  [2:0] meta_29;
  reg  [2:0] meta_30;
  reg  [2:0] meta_31;
  reg  [2:0] meta_32;
  reg  [2:0] meta_33;
  reg  [2:0] meta_34;
  reg  [2:0] meta_35;
  reg  [2:0] meta_36;
  reg  [2:0] meta_37;
  reg  [2:0] meta_38;
  reg  [2:0] meta_39;
  reg  [2:0] meta_40;
  reg  [2:0] meta_41;
  reg  [2:0] meta_42;
  reg  [2:0] meta_43;
  reg  [2:0] meta_44;
  reg  [2:0] meta_45;
  reg  [2:0] meta_46;
  reg  [2:0] meta_47;
  reg  [2:0] meta_48;
  reg  [2:0] meta_49;
  reg  [2:0] meta_50;
  reg  [2:0] meta_51;
  reg  [2:0] meta_52;
  reg  [2:0] meta_53;
  reg  [2:0] meta_54;
  reg  [2:0] meta_55;
  reg  [2:0] meta_56;
  reg  [2:0] meta_57;
  reg  [2:0] meta_58;
  reg  [2:0] meta_59;
  reg  [2:0] meta_60;
  reg  [2:0] meta_61;
  reg  [2:0] meta_62;
  reg  [2:0] meta_63;
  reg  [2:0] meta_64;
  reg  [2:0] meta_65;
  reg  [2:0] meta_66;
  reg  [2:0] meta_67;
  reg  [2:0] meta_68;
  reg  [2:0] meta_69;
  reg  [2:0] meta_70;
  reg  [2:0] meta_71;
  reg  [2:0] meta_72;
  reg  [2:0] meta_73;
  reg  [2:0] meta_74;
  reg  [2:0] meta_75;
  reg  [2:0] meta_76;
  reg  [2:0] meta_77;
  reg  [2:0] meta_78;
  reg  [2:0] meta_79;
  reg  [2:0] meta_80;
  reg  [2:0] meta_81;
  reg  [2:0] meta_82;
  reg  [2:0] meta_83;
  reg  [2:0] meta_84;
  reg  [2:0] meta_85;
  reg  [2:0] meta_86;
  reg  [2:0] meta_87;
  reg  [2:0] meta_88;
  reg  [2:0] meta_89;
  reg  [2:0] meta_90;
  reg  [2:0] meta_91;
  reg  [2:0] meta_92;
  reg  [2:0] meta_93;
  reg  [2:0] meta_94;
  reg  [2:0] meta_95;
  reg  [2:0] meta_96;
  reg  [2:0] meta_97;
  reg  [2:0] meta_98;
  reg  [2:0] meta_99;
  reg  [2:0] meta_100;
  reg  [2:0] meta_101;
  reg  [2:0] meta_102;
  reg  [2:0] meta_103;
  reg  [2:0] meta_104;
  reg  [2:0] meta_105;
  reg  [2:0] meta_106;
  reg  [2:0] meta_107;
  reg  [2:0] meta_108;
  reg  [2:0] meta_109;
  reg  [2:0] meta_110;
  reg  [2:0] meta_111;
  reg  [2:0] meta_112;
  reg  [2:0] meta_113;
  reg  [2:0] meta_114;
  reg  [2:0] meta_115;
  reg  [2:0] meta_116;
  reg  [2:0] meta_117;
  reg  [2:0] meta_118;
  reg  [2:0] meta_119;
  reg  [2:0] meta_120;
  reg  [2:0] meta_121;
  reg  [2:0] meta_122;
  reg  [2:0] meta_123;
  reg  [2:0] meta_124;
  reg  [2:0] meta_125;
  reg  [2:0] meta_126;
  reg  [2:0] meta_127;
  reg  [2:0] casez_tmp;
  always_comb begin
    casez (io_ports_0_setIdx)
      7'b0000000:
        casez_tmp = meta_0;
      7'b0000001:
        casez_tmp = meta_1;
      7'b0000010:
        casez_tmp = meta_2;
      7'b0000011:
        casez_tmp = meta_3;
      7'b0000100:
        casez_tmp = meta_4;
      7'b0000101:
        casez_tmp = meta_5;
      7'b0000110:
        casez_tmp = meta_6;
      7'b0000111:
        casez_tmp = meta_7;
      7'b0001000:
        casez_tmp = meta_8;
      7'b0001001:
        casez_tmp = meta_9;
      7'b0001010:
        casez_tmp = meta_10;
      7'b0001011:
        casez_tmp = meta_11;
      7'b0001100:
        casez_tmp = meta_12;
      7'b0001101:
        casez_tmp = meta_13;
      7'b0001110:
        casez_tmp = meta_14;
      7'b0001111:
        casez_tmp = meta_15;
      7'b0010000:
        casez_tmp = meta_16;
      7'b0010001:
        casez_tmp = meta_17;
      7'b0010010:
        casez_tmp = meta_18;
      7'b0010011:
        casez_tmp = meta_19;
      7'b0010100:
        casez_tmp = meta_20;
      7'b0010101:
        casez_tmp = meta_21;
      7'b0010110:
        casez_tmp = meta_22;
      7'b0010111:
        casez_tmp = meta_23;
      7'b0011000:
        casez_tmp = meta_24;
      7'b0011001:
        casez_tmp = meta_25;
      7'b0011010:
        casez_tmp = meta_26;
      7'b0011011:
        casez_tmp = meta_27;
      7'b0011100:
        casez_tmp = meta_28;
      7'b0011101:
        casez_tmp = meta_29;
      7'b0011110:
        casez_tmp = meta_30;
      7'b0011111:
        casez_tmp = meta_31;
      7'b0100000:
        casez_tmp = meta_32;
      7'b0100001:
        casez_tmp = meta_33;
      7'b0100010:
        casez_tmp = meta_34;
      7'b0100011:
        casez_tmp = meta_35;
      7'b0100100:
        casez_tmp = meta_36;
      7'b0100101:
        casez_tmp = meta_37;
      7'b0100110:
        casez_tmp = meta_38;
      7'b0100111:
        casez_tmp = meta_39;
      7'b0101000:
        casez_tmp = meta_40;
      7'b0101001:
        casez_tmp = meta_41;
      7'b0101010:
        casez_tmp = meta_42;
      7'b0101011:
        casez_tmp = meta_43;
      7'b0101100:
        casez_tmp = meta_44;
      7'b0101101:
        casez_tmp = meta_45;
      7'b0101110:
        casez_tmp = meta_46;
      7'b0101111:
        casez_tmp = meta_47;
      7'b0110000:
        casez_tmp = meta_48;
      7'b0110001:
        casez_tmp = meta_49;
      7'b0110010:
        casez_tmp = meta_50;
      7'b0110011:
        casez_tmp = meta_51;
      7'b0110100:
        casez_tmp = meta_52;
      7'b0110101:
        casez_tmp = meta_53;
      7'b0110110:
        casez_tmp = meta_54;
      7'b0110111:
        casez_tmp = meta_55;
      7'b0111000:
        casez_tmp = meta_56;
      7'b0111001:
        casez_tmp = meta_57;
      7'b0111010:
        casez_tmp = meta_58;
      7'b0111011:
        casez_tmp = meta_59;
      7'b0111100:
        casez_tmp = meta_60;
      7'b0111101:
        casez_tmp = meta_61;
      7'b0111110:
        casez_tmp = meta_62;
      7'b0111111:
        casez_tmp = meta_63;
      7'b1000000:
        casez_tmp = meta_64;
      7'b1000001:
        casez_tmp = meta_65;
      7'b1000010:
        casez_tmp = meta_66;
      7'b1000011:
        casez_tmp = meta_67;
      7'b1000100:
        casez_tmp = meta_68;
      7'b1000101:
        casez_tmp = meta_69;
      7'b1000110:
        casez_tmp = meta_70;
      7'b1000111:
        casez_tmp = meta_71;
      7'b1001000:
        casez_tmp = meta_72;
      7'b1001001:
        casez_tmp = meta_73;
      7'b1001010:
        casez_tmp = meta_74;
      7'b1001011:
        casez_tmp = meta_75;
      7'b1001100:
        casez_tmp = meta_76;
      7'b1001101:
        casez_tmp = meta_77;
      7'b1001110:
        casez_tmp = meta_78;
      7'b1001111:
        casez_tmp = meta_79;
      7'b1010000:
        casez_tmp = meta_80;
      7'b1010001:
        casez_tmp = meta_81;
      7'b1010010:
        casez_tmp = meta_82;
      7'b1010011:
        casez_tmp = meta_83;
      7'b1010100:
        casez_tmp = meta_84;
      7'b1010101:
        casez_tmp = meta_85;
      7'b1010110:
        casez_tmp = meta_86;
      7'b1010111:
        casez_tmp = meta_87;
      7'b1011000:
        casez_tmp = meta_88;
      7'b1011001:
        casez_tmp = meta_89;
      7'b1011010:
        casez_tmp = meta_90;
      7'b1011011:
        casez_tmp = meta_91;
      7'b1011100:
        casez_tmp = meta_92;
      7'b1011101:
        casez_tmp = meta_93;
      7'b1011110:
        casez_tmp = meta_94;
      7'b1011111:
        casez_tmp = meta_95;
      7'b1100000:
        casez_tmp = meta_96;
      7'b1100001:
        casez_tmp = meta_97;
      7'b1100010:
        casez_tmp = meta_98;
      7'b1100011:
        casez_tmp = meta_99;
      7'b1100100:
        casez_tmp = meta_100;
      7'b1100101:
        casez_tmp = meta_101;
      7'b1100110:
        casez_tmp = meta_102;
      7'b1100111:
        casez_tmp = meta_103;
      7'b1101000:
        casez_tmp = meta_104;
      7'b1101001:
        casez_tmp = meta_105;
      7'b1101010:
        casez_tmp = meta_106;
      7'b1101011:
        casez_tmp = meta_107;
      7'b1101100:
        casez_tmp = meta_108;
      7'b1101101:
        casez_tmp = meta_109;
      7'b1101110:
        casez_tmp = meta_110;
      7'b1101111:
        casez_tmp = meta_111;
      7'b1110000:
        casez_tmp = meta_112;
      7'b1110001:
        casez_tmp = meta_113;
      7'b1110010:
        casez_tmp = meta_114;
      7'b1110011:
        casez_tmp = meta_115;
      7'b1110100:
        casez_tmp = meta_116;
      7'b1110101:
        casez_tmp = meta_117;
      7'b1110110:
        casez_tmp = meta_118;
      7'b1110111:
        casez_tmp = meta_119;
      7'b1111000:
        casez_tmp = meta_120;
      7'b1111001:
        casez_tmp = meta_121;
      7'b1111010:
        casez_tmp = meta_122;
      7'b1111011:
        casez_tmp = meta_123;
      7'b1111100:
        casez_tmp = meta_124;
      7'b1111101:
        casez_tmp = meta_125;
      7'b1111110:
        casez_tmp = meta_126;
      default:
        casez_tmp = meta_127;
    endcase
  end // always_comb
  wire [2:0] _victimIdx_dir_T_1 = casez_tmp >> {1'h0, casez_tmp[0]} + 2'h1;
  wire       doUpdate = io_ports_0_hitValid | io_ports_0_refillValid;
  wire [2:0] updWayOH =
    io_ports_0_refillValid ? io_ports_0_refillWayOH[3:1] : io_ports_0_hitWayOH[3:1];
  wire [5:0] metaNext_mask_1 = 6'h1 << {1'h0, |(updWayOH[2:1])} + 2'h1;
  wire [2:0] _metaNext_metaVec_2_T =
    ~(metaNext_mask_1[2:0]) & ({casez_tmp[2:1], 1'h0} | {2'h0, ~(|(updWayOH[2:1]))})
    | (updWayOH[2] | updWayOH[0] ? 3'h0 : metaNext_mask_1[2:0]);
  always @(posedge clock) begin
    if (reset) begin
      meta_0 <= 3'h0;
      meta_1 <= 3'h0;
      meta_2 <= 3'h0;
      meta_3 <= 3'h0;
      meta_4 <= 3'h0;
      meta_5 <= 3'h0;
      meta_6 <= 3'h0;
      meta_7 <= 3'h0;
      meta_8 <= 3'h0;
      meta_9 <= 3'h0;
      meta_10 <= 3'h0;
      meta_11 <= 3'h0;
      meta_12 <= 3'h0;
      meta_13 <= 3'h0;
      meta_14 <= 3'h0;
      meta_15 <= 3'h0;
      meta_16 <= 3'h0;
      meta_17 <= 3'h0;
      meta_18 <= 3'h0;
      meta_19 <= 3'h0;
      meta_20 <= 3'h0;
      meta_21 <= 3'h0;
      meta_22 <= 3'h0;
      meta_23 <= 3'h0;
      meta_24 <= 3'h0;
      meta_25 <= 3'h0;
      meta_26 <= 3'h0;
      meta_27 <= 3'h0;
      meta_28 <= 3'h0;
      meta_29 <= 3'h0;
      meta_30 <= 3'h0;
      meta_31 <= 3'h0;
      meta_32 <= 3'h0;
      meta_33 <= 3'h0;
      meta_34 <= 3'h0;
      meta_35 <= 3'h0;
      meta_36 <= 3'h0;
      meta_37 <= 3'h0;
      meta_38 <= 3'h0;
      meta_39 <= 3'h0;
      meta_40 <= 3'h0;
      meta_41 <= 3'h0;
      meta_42 <= 3'h0;
      meta_43 <= 3'h0;
      meta_44 <= 3'h0;
      meta_45 <= 3'h0;
      meta_46 <= 3'h0;
      meta_47 <= 3'h0;
      meta_48 <= 3'h0;
      meta_49 <= 3'h0;
      meta_50 <= 3'h0;
      meta_51 <= 3'h0;
      meta_52 <= 3'h0;
      meta_53 <= 3'h0;
      meta_54 <= 3'h0;
      meta_55 <= 3'h0;
      meta_56 <= 3'h0;
      meta_57 <= 3'h0;
      meta_58 <= 3'h0;
      meta_59 <= 3'h0;
      meta_60 <= 3'h0;
      meta_61 <= 3'h0;
      meta_62 <= 3'h0;
      meta_63 <= 3'h0;
      meta_64 <= 3'h0;
      meta_65 <= 3'h0;
      meta_66 <= 3'h0;
      meta_67 <= 3'h0;
      meta_68 <= 3'h0;
      meta_69 <= 3'h0;
      meta_70 <= 3'h0;
      meta_71 <= 3'h0;
      meta_72 <= 3'h0;
      meta_73 <= 3'h0;
      meta_74 <= 3'h0;
      meta_75 <= 3'h0;
      meta_76 <= 3'h0;
      meta_77 <= 3'h0;
      meta_78 <= 3'h0;
      meta_79 <= 3'h0;
      meta_80 <= 3'h0;
      meta_81 <= 3'h0;
      meta_82 <= 3'h0;
      meta_83 <= 3'h0;
      meta_84 <= 3'h0;
      meta_85 <= 3'h0;
      meta_86 <= 3'h0;
      meta_87 <= 3'h0;
      meta_88 <= 3'h0;
      meta_89 <= 3'h0;
      meta_90 <= 3'h0;
      meta_91 <= 3'h0;
      meta_92 <= 3'h0;
      meta_93 <= 3'h0;
      meta_94 <= 3'h0;
      meta_95 <= 3'h0;
      meta_96 <= 3'h0;
      meta_97 <= 3'h0;
      meta_98 <= 3'h0;
      meta_99 <= 3'h0;
      meta_100 <= 3'h0;
      meta_101 <= 3'h0;
      meta_102 <= 3'h0;
      meta_103 <= 3'h0;
      meta_104 <= 3'h0;
      meta_105 <= 3'h0;
      meta_106 <= 3'h0;
      meta_107 <= 3'h0;
      meta_108 <= 3'h0;
      meta_109 <= 3'h0;
      meta_110 <= 3'h0;
      meta_111 <= 3'h0;
      meta_112 <= 3'h0;
      meta_113 <= 3'h0;
      meta_114 <= 3'h0;
      meta_115 <= 3'h0;
      meta_116 <= 3'h0;
      meta_117 <= 3'h0;
      meta_118 <= 3'h0;
      meta_119 <= 3'h0;
      meta_120 <= 3'h0;
      meta_121 <= 3'h0;
      meta_122 <= 3'h0;
      meta_123 <= 3'h0;
      meta_124 <= 3'h0;
      meta_125 <= 3'h0;
      meta_126 <= 3'h0;
      meta_127 <= 3'h0;
    end
    else begin
      if (doUpdate & io_ports_0_setIdx == 7'h0)
        meta_0 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1)
        meta_1 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2)
        meta_2 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3)
        meta_3 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4)
        meta_4 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5)
        meta_5 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6)
        meta_6 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h7)
        meta_7 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h8)
        meta_8 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h9)
        meta_9 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'hA)
        meta_10 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'hB)
        meta_11 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'hC)
        meta_12 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'hD)
        meta_13 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'hE)
        meta_14 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'hF)
        meta_15 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h10)
        meta_16 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h11)
        meta_17 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h12)
        meta_18 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h13)
        meta_19 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h14)
        meta_20 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h15)
        meta_21 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h16)
        meta_22 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h17)
        meta_23 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h18)
        meta_24 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h19)
        meta_25 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1A)
        meta_26 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1B)
        meta_27 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1C)
        meta_28 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1D)
        meta_29 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1E)
        meta_30 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h1F)
        meta_31 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h20)
        meta_32 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h21)
        meta_33 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h22)
        meta_34 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h23)
        meta_35 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h24)
        meta_36 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h25)
        meta_37 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h26)
        meta_38 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h27)
        meta_39 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h28)
        meta_40 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h29)
        meta_41 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2A)
        meta_42 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2B)
        meta_43 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2C)
        meta_44 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2D)
        meta_45 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2E)
        meta_46 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h2F)
        meta_47 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h30)
        meta_48 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h31)
        meta_49 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h32)
        meta_50 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h33)
        meta_51 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h34)
        meta_52 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h35)
        meta_53 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h36)
        meta_54 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h37)
        meta_55 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h38)
        meta_56 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h39)
        meta_57 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3A)
        meta_58 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3B)
        meta_59 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3C)
        meta_60 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3D)
        meta_61 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3E)
        meta_62 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h3F)
        meta_63 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h40)
        meta_64 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h41)
        meta_65 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h42)
        meta_66 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h43)
        meta_67 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h44)
        meta_68 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h45)
        meta_69 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h46)
        meta_70 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h47)
        meta_71 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h48)
        meta_72 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h49)
        meta_73 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4A)
        meta_74 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4B)
        meta_75 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4C)
        meta_76 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4D)
        meta_77 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4E)
        meta_78 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h4F)
        meta_79 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h50)
        meta_80 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h51)
        meta_81 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h52)
        meta_82 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h53)
        meta_83 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h54)
        meta_84 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h55)
        meta_85 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h56)
        meta_86 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h57)
        meta_87 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h58)
        meta_88 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h59)
        meta_89 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5A)
        meta_90 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5B)
        meta_91 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5C)
        meta_92 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5D)
        meta_93 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5E)
        meta_94 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h5F)
        meta_95 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h60)
        meta_96 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h61)
        meta_97 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h62)
        meta_98 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h63)
        meta_99 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h64)
        meta_100 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h65)
        meta_101 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h66)
        meta_102 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h67)
        meta_103 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h68)
        meta_104 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h69)
        meta_105 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6A)
        meta_106 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6B)
        meta_107 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6C)
        meta_108 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6D)
        meta_109 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6E)
        meta_110 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h6F)
        meta_111 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h70)
        meta_112 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h71)
        meta_113 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h72)
        meta_114 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h73)
        meta_115 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h74)
        meta_116 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h75)
        meta_117 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h76)
        meta_118 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h77)
        meta_119 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h78)
        meta_120 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h79)
        meta_121 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h7A)
        meta_122 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h7B)
        meta_123 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h7C)
        meta_124 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h7D)
        meta_125 <= _metaNext_metaVec_2_T;
      if (doUpdate & io_ports_0_setIdx == 7'h7E)
        meta_126 <= _metaNext_metaVec_2_T;
      if (doUpdate & (&io_ports_0_setIdx))
        meta_127 <= _metaNext_metaVec_2_T;
    end
  end // always @(posedge)
  assign io_ports_0_victimWayOH =
    (|io_ports_0_invalidWayOH)
      ? (io_ports_0_invalidWayOH[0]
           ? 4'h1
           : io_ports_0_invalidWayOH[1]
               ? 4'h2
               : io_ports_0_invalidWayOH[2] ? 4'h4 : {io_ports_0_invalidWayOH[3], 3'h0})
      : 4'h1 << {2'h0, casez_tmp[0], _victimIdx_dir_T_1[0]};
endmodule

