// Generated by CIRCT firtool-1.133.0
module BoothMultiplier(
  input         clock,
  input  [32:0] io_ra,
                io_rb,
  output [63:0] io_res
);

  wire [65:0] _MulUnit_io_result;
  BoothMul MulUnit (
    .clock     (clock),
    .io_a      (io_ra),
    .io_b      (io_rb),
    .io_result (_MulUnit_io_result)
  );
  assign io_res = _MulUnit_io_result[63:0];
endmodule

