// Generated by CIRCT firtool-1.133.0
module CL3DIV(
  input         clock,
                reset,
                io_in_info_valid,
  input  [31:0] io_in_info_inst,
                io_in_info_rs1,
                io_in_info_rs2,
  output        io_out_wb_valid,
  output [31:0] io_out_wb_result
);

  wire [63:0] _divider_io_res;
  wire        rem = io_in_info_inst[14:12] == 3'h6;
  reg         div_q;
  always @(posedge clock) begin
    if (io_in_info_valid)
      div_q <= rem | (&(io_in_info_inst[14:12]));
  end // always @(posedge)
  RestoringDivider divider (
    .clock     (clock),
    .reset     (reset),
    .io_valid  (io_in_info_valid),
    .io_ra     (io_in_info_rs1),
    .io_rb     (io_in_info_rs2),
    .io_sign   (io_in_info_inst[14:12] == 3'h4 | rem),
    .io_res    (_divider_io_res),
    .io_finish (io_out_wb_valid)
  );
  assign io_out_wb_result = div_q ? _divider_io_res[63:32] : _divider_io_res[31:0];
endmodule

