// Generated by CIRCT firtool-1.133.0
module CL3Top(
  input         clock,
                reset,
                io_extIrq,
                io_timerIrq,
                io_master_aw_ready,
  output        io_master_aw_valid,
  output [31:0] io_master_aw_bits_awaddr,
  output [3:0]  io_master_aw_bits_awid,
  output [7:0]  io_master_aw_bits_awlen,
  output [2:0]  io_master_aw_bits_awsize,
  output [1:0]  io_master_aw_bits_awburst,
  output        io_master_aw_bits_awlock,
  output [3:0]  io_master_aw_bits_awcache,
  output [2:0]  io_master_aw_bits_awprot,
  input         io_master_w_ready,
  output        io_master_w_valid,
  output [31:0] io_master_w_bits_wdata,
  output [3:0]  io_master_w_bits_wstrb,
  output        io_master_w_bits_wlast,
                io_master_b_ready,
  input         io_master_b_valid,
  input  [1:0]  io_master_b_bits_bresp,
  input  [3:0]  io_master_b_bits_bid,
  input         io_master_ar_ready,
  output        io_master_ar_valid,
  output [31:0] io_master_ar_bits_araddr,
  output [3:0]  io_master_ar_bits_arid,
  output [7:0]  io_master_ar_bits_arlen,
  output [2:0]  io_master_ar_bits_arsize,
  output [1:0]  io_master_ar_bits_arburst,
  output        io_master_ar_bits_arlock,
  output [3:0]  io_master_ar_bits_arcache,
  output [2:0]  io_master_ar_bits_arprot,
  output        io_master_r_ready,
  input         io_master_r_valid,
  input  [1:0]  io_master_r_bits_rresp,
  input  [31:0] io_master_r_bits_rdata,
  input         io_master_r_bits_rlast,
  input  [3:0]  io_master_r_bits_rid
);

  wire        _xbar_io_xbar_aw_ready;
  wire        _xbar_io_xbar_w_ready;
  wire        _xbar_io_xbar_b_valid;
  wire [1:0]  _xbar_io_xbar_b_bits_bresp;
  wire        _xbar_io_xbar_ar_ready;
  wire        _xbar_io_xbar_r_valid;
  wire [1:0]  _xbar_io_xbar_r_bits_rresp;
  wire [31:0] _xbar_io_xbar_r_bits_rdata;
  wire        _xbar_io_xbar_r_bits_rlast;
  wire        _xbar_io_clint_aw_valid;
  wire [31:0] _xbar_io_clint_aw_bits_awaddr;
  wire        _xbar_io_clint_w_valid;
  wire [31:0] _xbar_io_clint_w_bits_wdata;
  wire        _xbar_io_clint_b_ready;
  wire        _xbar_io_clint_ar_valid;
  wire [31:0] _xbar_io_clint_ar_bits_araddr;
  wire        _xbar_io_clint_r_ready;
  wire        _clint_io_axi_aw_ready;
  wire        _clint_io_axi_w_ready;
  wire        _clint_io_axi_b_valid;
  wire        _clint_io_axi_ar_ready;
  wire        _clint_io_axi_r_valid;
  wire [31:0] _clint_io_axi_r_bits_rdata;
  wire        _clint_io_irq;
  wire        _u_arbiter_io_icache_axi_ar_ready;
  wire        _u_arbiter_io_icache_axi_r_valid;
  wire [31:0] _u_arbiter_io_icache_axi_r_bits_data;
  wire [1:0]  _u_arbiter_io_icache_axi_r_bits_resp;
  wire        _u_arbiter_io_icache_axi_r_bits_last;
  wire        _u_arbiter_io_dcache_axi_aw_ready;
  wire        _u_arbiter_io_dcache_axi_w_ready;
  wire        _u_arbiter_io_dcache_axi_b_valid;
  wire [1:0]  _u_arbiter_io_dcache_axi_b_bits_resp;
  wire        _u_arbiter_io_dcache_axi_ar_ready;
  wire        _u_arbiter_io_dcache_axi_r_valid;
  wire [31:0] _u_arbiter_io_dcache_axi_r_bits_data;
  wire [1:0]  _u_arbiter_io_dcache_axi_r_bits_resp;
  wire        _u_arbiter_io_dcache_axi_r_bits_last;
  wire        _u_arbiter_io_mem_axi_aw_valid;
  wire [31:0] _u_arbiter_io_mem_axi_aw_bits_addr;
  wire [7:0]  _u_arbiter_io_mem_axi_aw_bits_len;
  wire        _u_arbiter_io_mem_axi_w_valid;
  wire [31:0] _u_arbiter_io_mem_axi_w_bits_data;
  wire [3:0]  _u_arbiter_io_mem_axi_w_bits_strb;
  wire        _u_arbiter_io_mem_axi_w_bits_last;
  wire        _u_arbiter_io_mem_axi_ar_valid;
  wire [31:0] _u_arbiter_io_mem_axi_ar_bits_addr;
  wire [7:0]  _u_arbiter_io_mem_axi_ar_bits_len;
  wire [1:0]  _u_arbiter_io_mem_axi_ar_bits_burst;
  wire [2:0]  _u_arbiter_io_mem_axi_ar_bits_size;
  wire [3:0]  _u_arbiter_io_mem_axi_ar_bits_cache;
  wire [31:0] _dcache_io_cpu_resp_dataRd;
  wire        _dcache_io_cpu_resp_ack;
  wire        _dcache_io_cpu_resp_error;
  wire        _dcache_io_cpu_accept;
  wire        _dcache_io_axi_aw_valid;
  wire [31:0] _dcache_io_axi_aw_bits_addr;
  wire [7:0]  _dcache_io_axi_aw_bits_len;
  wire        _dcache_io_axi_w_valid;
  wire [31:0] _dcache_io_axi_w_bits_data;
  wire [3:0]  _dcache_io_axi_w_bits_strb;
  wire        _dcache_io_axi_w_bits_last;
  wire        _dcache_io_axi_ar_valid;
  wire [31:0] _dcache_io_axi_ar_bits_addr;
  wire [7:0]  _dcache_io_axi_ar_bits_len;
  wire        _icache_io_cpu_resp_accept;
  wire        _icache_io_cpu_resp_valid;
  wire        _icache_io_cpu_resp_error;
  wire [63:0] _icache_io_cpu_resp_inst;
  wire        _icache_io_axi_ar_valid;
  wire [31:0] _icache_io_axi_ar_bits_addr;
  wire        _core_io_imem_req_valid;
  wire [31:0] _core_io_imem_req_bits_addr;
  wire        _core_io_dmem_req_valid;
  wire [31:0] _core_io_dmem_req_bits_addr;
  wire [31:0] _core_io_dmem_req_bits_wdata;
  wire [3:0]  _core_io_dmem_req_bits_mask;
  wire        _core_io_dmem_req_bits_cacheable;
  wire        _core_io_dmem_req_bits_atomic_isAmo;
  wire        _core_io_dmem_req_bits_atomic_isLR;
  wire        _core_io_dmem_req_bits_atomic_isSC;
  wire [3:0]  _core_io_dmem_req_bits_atomic_amoCode;
  CL3Core core (
    .clock                           (clock),
    .reset                           (reset),
    .io_imem_req_ready               (_icache_io_cpu_resp_accept),
    .io_imem_req_valid               (_core_io_imem_req_valid),
    .io_imem_req_bits_addr           (_core_io_imem_req_bits_addr),
    .io_imem_resp_valid              (_icache_io_cpu_resp_valid),
    .io_imem_resp_bits_err           ({3'h0, _icache_io_cpu_resp_error}),
    .io_imem_resp_bits_rdata         (_icache_io_cpu_resp_inst),
    .io_dmem_req_ready               (_dcache_io_cpu_accept),
    .io_dmem_req_valid               (_core_io_dmem_req_valid),
    .io_dmem_req_bits_addr           (_core_io_dmem_req_bits_addr),
    .io_dmem_req_bits_wdata          (_core_io_dmem_req_bits_wdata),
    .io_dmem_req_bits_mask           (_core_io_dmem_req_bits_mask),
    .io_dmem_req_bits_cacheable      (_core_io_dmem_req_bits_cacheable),
    .io_dmem_req_bits_atomic_isAmo   (_core_io_dmem_req_bits_atomic_isAmo),
    .io_dmem_req_bits_atomic_isLR    (_core_io_dmem_req_bits_atomic_isLR),
    .io_dmem_req_bits_atomic_isSC    (_core_io_dmem_req_bits_atomic_isSC),
    .io_dmem_req_bits_atomic_amoCode (_core_io_dmem_req_bits_atomic_amoCode),
    .io_dmem_resp_valid              (_dcache_io_cpu_resp_ack),
    .io_dmem_resp_bits_err           ({3'h0, _dcache_io_cpu_resp_error}),
    .io_dmem_resp_bits_rdata         (_dcache_io_cpu_resp_dataRd),
    .io_timer_irq                    (_clint_io_irq)
  );
  ICache icache (
    .clock               (clock),
    .reset               (reset),
    .io_cpu_req_rd       (_core_io_imem_req_valid),
    .io_cpu_req_pc       (_core_io_imem_req_bits_addr),
    .io_cpu_resp_accept  (_icache_io_cpu_resp_accept),
    .io_cpu_resp_valid   (_icache_io_cpu_resp_valid),
    .io_cpu_resp_error   (_icache_io_cpu_resp_error),
    .io_cpu_resp_inst    (_icache_io_cpu_resp_inst),
    .io_axi_ar_ready     (_u_arbiter_io_icache_axi_ar_ready),
    .io_axi_ar_valid     (_icache_io_axi_ar_valid),
    .io_axi_ar_bits_addr (_icache_io_axi_ar_bits_addr),
    .io_axi_r_valid      (_u_arbiter_io_icache_axi_r_valid),
    .io_axi_r_bits_data  (_u_arbiter_io_icache_axi_r_bits_data),
    .io_axi_r_bits_resp  (_u_arbiter_io_icache_axi_r_bits_resp),
    .io_axi_r_bits_last  (_u_arbiter_io_icache_axi_r_bits_last)
  );
  DCache dcache (
    .clock                (clock),
    .reset                (reset),
    .io_cpu_req_addr      (_core_io_dmem_req_bits_addr),
    .io_cpu_req_dataWr    (_core_io_dmem_req_bits_wdata),
    .io_cpu_req_rd        (_core_io_dmem_req_valid),
    .io_cpu_req_wr        (_core_io_dmem_req_bits_mask),
    .io_cpu_req_cacheable (_core_io_dmem_req_bits_cacheable),
    .io_cpu_resp_dataRd   (_dcache_io_cpu_resp_dataRd),
    .io_cpu_resp_ack      (_dcache_io_cpu_resp_ack),
    .io_cpu_resp_error    (_dcache_io_cpu_resp_error),
    .io_cpu_accept        (_dcache_io_cpu_accept),
    .io_axi_aw_ready      (_u_arbiter_io_dcache_axi_aw_ready),
    .io_axi_aw_valid      (_dcache_io_axi_aw_valid),
    .io_axi_aw_bits_addr  (_dcache_io_axi_aw_bits_addr),
    .io_axi_aw_bits_len   (_dcache_io_axi_aw_bits_len),
    .io_axi_w_ready       (_u_arbiter_io_dcache_axi_w_ready),
    .io_axi_w_valid       (_dcache_io_axi_w_valid),
    .io_axi_w_bits_data   (_dcache_io_axi_w_bits_data),
    .io_axi_w_bits_strb   (_dcache_io_axi_w_bits_strb),
    .io_axi_w_bits_last   (_dcache_io_axi_w_bits_last),
    .io_axi_b_valid       (_u_arbiter_io_dcache_axi_b_valid),
    .io_axi_b_bits_resp   (_u_arbiter_io_dcache_axi_b_bits_resp),
    .io_axi_ar_ready      (_u_arbiter_io_dcache_axi_ar_ready),
    .io_axi_ar_valid      (_dcache_io_axi_ar_valid),
    .io_axi_ar_bits_addr  (_dcache_io_axi_ar_bits_addr),
    .io_axi_ar_bits_len   (_dcache_io_axi_ar_bits_len),
    .io_axi_r_valid       (_u_arbiter_io_dcache_axi_r_valid),
    .io_axi_r_bits_data   (_u_arbiter_io_dcache_axi_r_bits_data),
    .io_axi_r_bits_resp   (_u_arbiter_io_dcache_axi_r_bits_resp),
    .io_axi_r_bits_last   (_u_arbiter_io_dcache_axi_r_bits_last),
    .io_atomic_isAmo      (_core_io_dmem_req_bits_atomic_isAmo),
    .io_atomic_isLR       (_core_io_dmem_req_bits_atomic_isLR),
    .io_atomic_isSC       (_core_io_dmem_req_bits_atomic_isSC),
    .io_atomic_amoCode    (_core_io_dmem_req_bits_atomic_amoCode)
  );
  AxiArbiter u_arbiter (
    .clock                      (clock),
    .reset                      (reset),
    .io_icache_axi_ar_ready     (_u_arbiter_io_icache_axi_ar_ready),
    .io_icache_axi_ar_valid     (_icache_io_axi_ar_valid),
    .io_icache_axi_ar_bits_addr (_icache_io_axi_ar_bits_addr),
    .io_icache_axi_r_valid      (_u_arbiter_io_icache_axi_r_valid),
    .io_icache_axi_r_bits_data  (_u_arbiter_io_icache_axi_r_bits_data),
    .io_icache_axi_r_bits_resp  (_u_arbiter_io_icache_axi_r_bits_resp),
    .io_icache_axi_r_bits_last  (_u_arbiter_io_icache_axi_r_bits_last),
    .io_dcache_axi_aw_ready     (_u_arbiter_io_dcache_axi_aw_ready),
    .io_dcache_axi_aw_valid     (_dcache_io_axi_aw_valid),
    .io_dcache_axi_aw_bits_addr (_dcache_io_axi_aw_bits_addr),
    .io_dcache_axi_aw_bits_len  (_dcache_io_axi_aw_bits_len),
    .io_dcache_axi_w_ready      (_u_arbiter_io_dcache_axi_w_ready),
    .io_dcache_axi_w_valid      (_dcache_io_axi_w_valid),
    .io_dcache_axi_w_bits_data  (_dcache_io_axi_w_bits_data),
    .io_dcache_axi_w_bits_strb  (_dcache_io_axi_w_bits_strb),
    .io_dcache_axi_w_bits_last  (_dcache_io_axi_w_bits_last),
    .io_dcache_axi_b_valid      (_u_arbiter_io_dcache_axi_b_valid),
    .io_dcache_axi_b_bits_resp  (_u_arbiter_io_dcache_axi_b_bits_resp),
    .io_dcache_axi_ar_ready     (_u_arbiter_io_dcache_axi_ar_ready),
    .io_dcache_axi_ar_valid     (_dcache_io_axi_ar_valid),
    .io_dcache_axi_ar_bits_addr (_dcache_io_axi_ar_bits_addr),
    .io_dcache_axi_ar_bits_len  (_dcache_io_axi_ar_bits_len),
    .io_dcache_axi_r_valid      (_u_arbiter_io_dcache_axi_r_valid),
    .io_dcache_axi_r_bits_data  (_u_arbiter_io_dcache_axi_r_bits_data),
    .io_dcache_axi_r_bits_resp  (_u_arbiter_io_dcache_axi_r_bits_resp),
    .io_dcache_axi_r_bits_last  (_u_arbiter_io_dcache_axi_r_bits_last),
    .io_mem_axi_aw_ready        (_xbar_io_xbar_aw_ready),
    .io_mem_axi_aw_valid        (_u_arbiter_io_mem_axi_aw_valid),
    .io_mem_axi_aw_bits_addr    (_u_arbiter_io_mem_axi_aw_bits_addr),
    .io_mem_axi_aw_bits_len     (_u_arbiter_io_mem_axi_aw_bits_len),
    .io_mem_axi_w_ready         (_xbar_io_xbar_w_ready),
    .io_mem_axi_w_valid         (_u_arbiter_io_mem_axi_w_valid),
    .io_mem_axi_w_bits_data     (_u_arbiter_io_mem_axi_w_bits_data),
    .io_mem_axi_w_bits_strb     (_u_arbiter_io_mem_axi_w_bits_strb),
    .io_mem_axi_w_bits_last     (_u_arbiter_io_mem_axi_w_bits_last),
    .io_mem_axi_b_valid         (_xbar_io_xbar_b_valid),
    .io_mem_axi_b_bits_resp     (_xbar_io_xbar_b_bits_bresp),
    .io_mem_axi_ar_ready        (_xbar_io_xbar_ar_ready),
    .io_mem_axi_ar_valid        (_u_arbiter_io_mem_axi_ar_valid),
    .io_mem_axi_ar_bits_addr    (_u_arbiter_io_mem_axi_ar_bits_addr),
    .io_mem_axi_ar_bits_len     (_u_arbiter_io_mem_axi_ar_bits_len),
    .io_mem_axi_ar_bits_burst   (_u_arbiter_io_mem_axi_ar_bits_burst),
    .io_mem_axi_ar_bits_size    (_u_arbiter_io_mem_axi_ar_bits_size),
    .io_mem_axi_ar_bits_cache   (_u_arbiter_io_mem_axi_ar_bits_cache),
    .io_mem_axi_r_valid         (_xbar_io_xbar_r_valid),
    .io_mem_axi_r_bits_data     (_xbar_io_xbar_r_bits_rdata),
    .io_mem_axi_r_bits_resp     (_xbar_io_xbar_r_bits_rresp),
    .io_mem_axi_r_bits_last     (_xbar_io_xbar_r_bits_rlast)
  );
  CL3CLINT clint (
    .clock                 (clock),
    .reset                 (reset),
    .io_axi_aw_ready       (_clint_io_axi_aw_ready),
    .io_axi_aw_valid       (_xbar_io_clint_aw_valid),
    .io_axi_aw_bits_awaddr (_xbar_io_clint_aw_bits_awaddr),
    .io_axi_w_ready        (_clint_io_axi_w_ready),
    .io_axi_w_valid        (_xbar_io_clint_w_valid),
    .io_axi_w_bits_wdata   (_xbar_io_clint_w_bits_wdata),
    .io_axi_b_ready        (_xbar_io_clint_b_ready),
    .io_axi_b_valid        (_clint_io_axi_b_valid),
    .io_axi_ar_ready       (_clint_io_axi_ar_ready),
    .io_axi_ar_valid       (_xbar_io_clint_ar_valid),
    .io_axi_ar_bits_araddr (_xbar_io_clint_ar_bits_araddr),
    .io_axi_r_ready        (_xbar_io_clint_r_ready),
    .io_axi_r_valid        (_clint_io_axi_r_valid),
    .io_axi_r_bits_rdata   (_clint_io_axi_r_bits_rdata),
    .io_irq                (_clint_io_irq)
  );
  CL3Xbar xbar (
    .clock                   (clock),
    .reset                   (reset),
    .io_xbar_aw_ready        (_xbar_io_xbar_aw_ready),
    .io_xbar_aw_valid        (_u_arbiter_io_mem_axi_aw_valid),
    .io_xbar_aw_bits_awaddr  (_u_arbiter_io_mem_axi_aw_bits_addr),
    .io_xbar_aw_bits_awlen   (_u_arbiter_io_mem_axi_aw_bits_len),
    .io_xbar_w_ready         (_xbar_io_xbar_w_ready),
    .io_xbar_w_valid         (_u_arbiter_io_mem_axi_w_valid),
    .io_xbar_w_bits_wdata    (_u_arbiter_io_mem_axi_w_bits_data),
    .io_xbar_w_bits_wstrb    (_u_arbiter_io_mem_axi_w_bits_strb),
    .io_xbar_w_bits_wlast    (_u_arbiter_io_mem_axi_w_bits_last),
    .io_xbar_b_valid         (_xbar_io_xbar_b_valid),
    .io_xbar_b_bits_bresp    (_xbar_io_xbar_b_bits_bresp),
    .io_xbar_ar_ready        (_xbar_io_xbar_ar_ready),
    .io_xbar_ar_valid        (_u_arbiter_io_mem_axi_ar_valid),
    .io_xbar_ar_bits_araddr  (_u_arbiter_io_mem_axi_ar_bits_addr),
    .io_xbar_ar_bits_arlen   (_u_arbiter_io_mem_axi_ar_bits_len),
    .io_xbar_ar_bits_arsize  (_u_arbiter_io_mem_axi_ar_bits_size),
    .io_xbar_ar_bits_arburst (_u_arbiter_io_mem_axi_ar_bits_burst),
    .io_xbar_ar_bits_arcache (_u_arbiter_io_mem_axi_ar_bits_cache),
    .io_xbar_r_valid         (_xbar_io_xbar_r_valid),
    .io_xbar_r_bits_rresp    (_xbar_io_xbar_r_bits_rresp),
    .io_xbar_r_bits_rdata    (_xbar_io_xbar_r_bits_rdata),
    .io_xbar_r_bits_rlast    (_xbar_io_xbar_r_bits_rlast),
    .io_clint_aw_ready       (_clint_io_axi_aw_ready),
    .io_clint_aw_valid       (_xbar_io_clint_aw_valid),
    .io_clint_aw_bits_awaddr (_xbar_io_clint_aw_bits_awaddr),
    .io_clint_w_ready        (_clint_io_axi_w_ready),
    .io_clint_w_valid        (_xbar_io_clint_w_valid),
    .io_clint_w_bits_wdata   (_xbar_io_clint_w_bits_wdata),
    .io_clint_b_ready        (_xbar_io_clint_b_ready),
    .io_clint_b_valid        (_clint_io_axi_b_valid),
    .io_clint_ar_ready       (_clint_io_axi_ar_ready),
    .io_clint_ar_valid       (_xbar_io_clint_ar_valid),
    .io_clint_ar_bits_araddr (_xbar_io_clint_ar_bits_araddr),
    .io_clint_r_ready        (_xbar_io_clint_r_ready),
    .io_clint_r_valid        (_clint_io_axi_r_valid),
    .io_clint_r_bits_rdata   (_clint_io_axi_r_bits_rdata),
    .io_top_aw_ready         (io_master_aw_ready),
    .io_top_aw_valid         (io_master_aw_valid),
    .io_top_aw_bits_awaddr   (io_master_aw_bits_awaddr),
    .io_top_aw_bits_awlen    (io_master_aw_bits_awlen),
    .io_top_w_ready          (io_master_w_ready),
    .io_top_w_valid          (io_master_w_valid),
    .io_top_w_bits_wdata     (io_master_w_bits_wdata),
    .io_top_w_bits_wstrb     (io_master_w_bits_wstrb),
    .io_top_w_bits_wlast     (io_master_w_bits_wlast),
    .io_top_b_ready          (io_master_b_ready),
    .io_top_b_valid          (io_master_b_valid),
    .io_top_b_bits_bresp     (io_master_b_bits_bresp),
    .io_top_ar_ready         (io_master_ar_ready),
    .io_top_ar_valid         (io_master_ar_valid),
    .io_top_ar_bits_araddr   (io_master_ar_bits_araddr),
    .io_top_ar_bits_arlen    (io_master_ar_bits_arlen),
    .io_top_ar_bits_arsize   (io_master_ar_bits_arsize),
    .io_top_ar_bits_arburst  (io_master_ar_bits_arburst),
    .io_top_ar_bits_arcache  (io_master_ar_bits_arcache),
    .io_top_r_ready          (io_master_r_ready),
    .io_top_r_valid          (io_master_r_valid),
    .io_top_r_bits_rresp     (io_master_r_bits_rresp),
    .io_top_r_bits_rdata     (io_master_r_bits_rdata),
    .io_top_r_bits_rlast     (io_master_r_bits_rlast)
  );
  assign io_master_aw_bits_awid = 4'h0;
  assign io_master_aw_bits_awsize = 3'h2;
  assign io_master_aw_bits_awburst = 2'h1;
  assign io_master_aw_bits_awlock = 1'h0;
  assign io_master_aw_bits_awcache = 4'h0;
  assign io_master_aw_bits_awprot = 3'h0;
  assign io_master_ar_bits_arid = 4'h0;
  assign io_master_ar_bits_arlock = 1'h0;
  assign io_master_ar_bits_arprot = 3'h0;
endmodule

