// Generated by CIRCT firtool-1.133.0
module dcache_core_tag_ramDev(
  input         clock,
  input  [6:0]  io_p0_addr,
  output [20:0] io_p0_rdata,
  input  [6:0]  io_p1_addr,
  input  [20:0] io_p1_wdata,
  input         io_p1_wen
);

  mem_128x21 mem_ext (
    .R0_addr (io_p0_addr),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (io_p0_rdata),
    .W0_addr (io_p1_addr),
    .W0_en   (io_p1_wen),
    .W0_clk  (clock),
    .W0_data (io_p1_wdata)
  );
endmodule

