// Generated by CIRCT firtool-1.133.0
module dcache_core_data_ramDev(
  input         clock,
  input  [9:0]  io_p0_addr,
  output [31:0] io_p0_rdata,
  input  [9:0]  io_p1_addr,
  input  [31:0] io_p1_wdata,
  input  [3:0]  io_p1_wstrb
);

  wire [31:0] _memBanks_3_ext_R0_data;
  wire [31:0] _memBanks_2_ext_R0_data;
  wire [31:0] _memBanks_1_ext_R0_data;
  wire [31:0] _memBanks_0_ext_R0_data;
  reg  [1:0]  p0_bank_reg;
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (p0_bank_reg)
      2'b00:
        casez_tmp = _memBanks_0_ext_R0_data;
      2'b01:
        casez_tmp = _memBanks_1_ext_R0_data;
      2'b10:
        casez_tmp = _memBanks_2_ext_R0_data;
      default:
        casez_tmp = _memBanks_3_ext_R0_data;
    endcase
  end // always_comb
  always @(posedge clock)
    p0_bank_reg <= io_p0_addr[1:0];
  memBanks_256x32 memBanks_0_ext (
    .R0_addr (io_p0_addr[9:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_0_ext_R0_data),
    .W0_addr (io_p1_addr[9:2]),
    .W0_en   ((|io_p1_wstrb) & io_p1_addr[1:0] == 2'h0),
    .W0_clk  (clock),
    .W0_data (io_p1_wdata),
    .W0_mask (io_p1_wstrb)
  );
  memBanks_256x32 memBanks_1_ext (
    .R0_addr (io_p0_addr[9:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_1_ext_R0_data),
    .W0_addr (io_p1_addr[9:2]),
    .W0_en   ((|io_p1_wstrb) & io_p1_addr[1:0] == 2'h1),
    .W0_clk  (clock),
    .W0_data (io_p1_wdata),
    .W0_mask (io_p1_wstrb)
  );
  memBanks_256x32 memBanks_2_ext (
    .R0_addr (io_p0_addr[9:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_2_ext_R0_data),
    .W0_addr (io_p1_addr[9:2]),
    .W0_en   ((|io_p1_wstrb) & io_p1_addr[1:0] == 2'h2),
    .W0_clk  (clock),
    .W0_data (io_p1_wdata),
    .W0_mask (io_p1_wstrb)
  );
  memBanks_256x32 memBanks_3_ext (
    .R0_addr (io_p0_addr[9:2]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_memBanks_3_ext_R0_data),
    .W0_addr (io_p1_addr[9:2]),
    .W0_en   ((|io_p1_wstrb) & (&(io_p1_addr[1:0]))),
    .W0_clk  (clock),
    .W0_data (io_p1_wdata),
    .W0_mask (io_p1_wstrb)
  );
  assign io_p0_rdata = casez_tmp;
endmodule

