// Generated by CIRCT firtool-1.133.0
module ReplRandomPolicy(
  input        clock,
               reset,
  input  [3:0] io_ports_0_invalidWayOH,
  output [3:0] io_ports_0_victimWayOH,
  input  [3:0] io_ports_1_invalidWayOH,
  output [3:0] io_ports_1_victimWayOH
);

  wire       _lfsr_prng_io_out_0;
  wire       _lfsr_prng_io_out_1;
  wire [3:0] policyVictimOH = 4'h1 << {2'h0, _lfsr_prng_io_out_1, _lfsr_prng_io_out_0};
  MaxPeriodFibonacciLFSR lfsr_prng (
    .clock     (clock),
    .reset     (reset),
    .io_out_0  (_lfsr_prng_io_out_0),
    .io_out_1  (_lfsr_prng_io_out_1),
    .io_out_2  (/* unused */),
    .io_out_3  (/* unused */),
    .io_out_4  (/* unused */),
    .io_out_5  (/* unused */),
    .io_out_6  (/* unused */),
    .io_out_7  (/* unused */),
    .io_out_8  (/* unused */),
    .io_out_9  (/* unused */),
    .io_out_10 (/* unused */),
    .io_out_11 (/* unused */),
    .io_out_12 (/* unused */),
    .io_out_13 (/* unused */),
    .io_out_14 (/* unused */),
    .io_out_15 (/* unused */)
  );
  assign io_ports_0_victimWayOH =
    (|io_ports_0_invalidWayOH)
      ? (io_ports_0_invalidWayOH[0]
           ? 4'h1
           : io_ports_0_invalidWayOH[1]
               ? 4'h2
               : io_ports_0_invalidWayOH[2] ? 4'h4 : {io_ports_0_invalidWayOH[3], 3'h0})
      : policyVictimOH;
  assign io_ports_1_victimWayOH =
    (|io_ports_1_invalidWayOH)
      ? (io_ports_1_invalidWayOH[0]
           ? 4'h1
           : io_ports_1_invalidWayOH[1]
               ? 4'h2
               : io_ports_1_invalidWayOH[2] ? 4'h4 : {io_ports_1_invalidWayOH[3], 3'h0})
      : policyVictimOH;
endmodule

